{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-coroutine-test/1.9.0-change-badges-SNAPSHOT/util-coroutine-test-1.9.0-change-badges-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-coroutine-test",
    "version": "1.9.0-change-badges-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "d4h7o7s3cngfnjje4vazyi3c64"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-coroutine-test-jvm-1.9.0-change-badges-SNAPSHOT.jar",
          "url": "util-coroutine-test-jvm-1.9.0-change-badges-SNAPSHOT.jar",
          "size": 5989,
          "sha512": "4e3cefb028fc6de6fa97dcc883a8f1077842983a4ce3b12864d240cb23be5565093bde6d7b4b8112748954e8286802057956e45ca94501645329d3445966ccd7",
          "sha256": "04b1606852f56d10f837b74b1b0f47c8af7502d17005899bdc5dba590f332483",
          "sha1": "e026811e90fbf59e077f45faa9fefc5771c12729",
          "md5": "1808b7e75ff2f1914f0376c08259cdc7"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "util-coroutine-test-jvm-1.9.0-change-badges-SNAPSHOT.jar",
          "url": "util-coroutine-test-jvm-1.9.0-change-badges-SNAPSHOT.jar",
          "size": 5989,
          "sha512": "4e3cefb028fc6de6fa97dcc883a8f1077842983a4ce3b12864d240cb23be5565093bde6d7b4b8112748954e8286802057956e45ca94501645329d3445966ccd7",
          "sha256": "04b1606852f56d10f837b74b1b0f47c8af7502d17005899bdc5dba590f332483",
          "sha1": "e026811e90fbf59e077f45faa9fefc5771c12729",
          "md5": "1808b7e75ff2f1914f0376c08259cdc7"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-coroutine-test-metadata/1.9.0-change-badges-SNAPSHOT/util-coroutine-test-metadata-1.9.0-change-badges-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-coroutine-test-metadata",
        "version": "1.9.0-change-badges-SNAPSHOT"
      }
    }
  ]
}
