{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.13.2-add-coverage-android-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "k5kad7j2vvbujarxl2b3myp7na"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.13.2-add-coverage-android-SNAPSHOT.jar",
          "url": "auth-common-1.13.2-add-coverage-android-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "3a1acf206819462025996b01f5b5de522288ed129cf7e2f0b489ee57c1eabdb6cb296bd84369df2a1c5b36f43786ed7bf3123cde683fb9bd31519436758507ce",
          "sha256": "f4e91913438c2010760b96def0c0c67b9a3053ab369d17fc5097a7d53c2cf5ca",
          "sha1": "8e1d049dd03d1952ed22616ce31c217ed6ba012a",
          "md5": "7346c9f5e56c88d0b22602ca104dd4c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.2-add-coverage-android-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.13.2-add-coverage-android-SNAPSHOT.jar",
          "url": "auth-common-1.13.2-add-coverage-android-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "3a1acf206819462025996b01f5b5de522288ed129cf7e2f0b489ee57c1eabdb6cb296bd84369df2a1c5b36f43786ed7bf3123cde683fb9bd31519436758507ce",
          "sha256": "f4e91913438c2010760b96def0c0c67b9a3053ab369d17fc5097a7d53c2cf5ca",
          "sha1": "8e1d049dd03d1952ed22616ce31c217ed6ba012a",
          "md5": "7346c9f5e56c88d0b22602ca104dd4c0"
        }
      ]
    }
  ]
}
