{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.13.2-add-coverage-android-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "gt2wd4re55esrdojmnzl5e7zdm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.13.2-add-coverage-android-SNAPSHOT.jar",
          "url": "auth-common-1.13.2-add-coverage-android-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "002f3a8830ef065e8aa635ce1910f3bd179a7861d5e2c84b293db0e1a0535ce162beae6f8fb87f09362b41bdf9efebeb1cfeea75a3250b28f7121c0824720dd9",
          "sha256": "cfda1feb972db18f3767b016c2ef534789492d34afdf9fde02ece4f560dfd778",
          "sha1": "729d5ca49472c4fca36a5636761c2eafd0798b35",
          "md5": "b8dbc99db218bf612b527861c3360797"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.2-add-coverage-android-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.13.2-add-coverage-android-SNAPSHOT.jar",
          "url": "auth-common-1.13.2-add-coverage-android-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "002f3a8830ef065e8aa635ce1910f3bd179a7861d5e2c84b293db0e1a0535ce162beae6f8fb87f09362b41bdf9efebeb1cfeea75a3250b28f7121c0824720dd9",
          "sha256": "cfda1feb972db18f3767b016c2ef534789492d34afdf9fde02ece4f560dfd778",
          "sha1": "729d5ca49472c4fca36a5636761c2eafd0798b35",
          "md5": "b8dbc99db218bf612b527861c3360797"
        }
      ]
    }
  ]
}
