{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir/0.2.0-bump-updates-SNAPSHOT/fhir-0.2.0-bump-updates-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir",
    "version": "0.2.0-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir.klib",
          "url": "fhir-iosx64-0.2.0-bump-updates-SNAPSHOT.klib",
          "size": 9786809,
          "sha512": "efc8bb5dc56aa2160eadc9bbdc24fb2036ca1fdf7ee3ab8b7efeb11fa531277c075bbe3466d6fcafb99088ad696f1bd7ee2c40e965fb1203f460a8e3f46ba474",
          "sha256": "971661d15143062fd7149fe41c985e7495e083f0c64a34abc81ad13050268c6a",
          "sha1": "0b82b247859a296490bab7e57c5c37af2fc5ef80",
          "md5": "1e8c393228dd902854bd041f29d61f01"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-iosx64-0.2.0-bump-updates-SNAPSHOT-metadata.jar",
          "url": "fhir-iosx64-0.2.0-bump-updates-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "e84dbce738dadd911d778d9252733208a53027fe6347dfd4b75604541d6c35e044b4ad6e06702abfdf10d06aa83f6e16fdb00e6557e6327f13caaec3ab8ef145",
          "sha256": "3bcf70010dd2f01881f4a50e6877588bb983f6dbf73167bb0905e88f1078bd17",
          "sha1": "0d2a5c3b233921c531d95e818e0cdebe8a7759b0",
          "md5": "ee4919309a7fea6535fa7de5b4ec9301"
        }
      ]
    }
  ]
}
