{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coroutine-util/0.1.0-bump-updates-SNAPSHOT/coroutine-util-0.1.0-bump-updates-SNAPSHOT.module",
    "group": "care.data4life.hc-coroutine-util-sdk-kmp",
    "module": "coroutine-util",
    "version": "0.1.0-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1-native-mt"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "coroutine-util.klib",
          "url": "coroutine-util-iosx64-0.1.0-bump-updates-SNAPSHOT.klib",
          "size": 6985,
          "sha512": "c469c2ba133b07fb382f9ef9e4f0a4a316dff7ad77b38a18f8fb8c7552aee12777152d43d77efe14ebccf4ac27fb0b3cfb5ad1406d1fe06b73cf081ad752f8e5",
          "sha256": "a7a97c27df6e951b8f1f56c6531fa64e2f0119ac44cd33b919d2d6ffc4d45c04",
          "sha1": "845b9c9c056acb52827187e92faa7a09950ac853",
          "md5": "e6287f2f0f04e6c3ea365842e8b25d07"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1-native-mt"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "coroutine-util-iosx64-0.1.0-bump-updates-SNAPSHOT-metadata.jar",
          "url": "coroutine-util-iosx64-0.1.0-bump-updates-SNAPSHOT-metadata.jar",
          "size": 5693,
          "sha512": "b6bc75a6c3204ecd4a976ede94baea7dc566228c4c25274775d7831c1c64114f297895a81c570585b556727f3350bee59b3ae298591c68a5ddee27a27b50e4d0",
          "sha256": "bae3e6a04b8bea1549af3d7d76a2740a3277bb8c146f699742e9003924ce4440",
          "sha1": "e7f952ad25a2e521dc8b39684a27c6c0a7dc05f5",
          "md5": "10338ef753e86684c4f26e5d1896bf53"
        }
      ]
    }
  ]
}
