{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-jvm",
    "version": "1.13.1-change-attachment-service-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "d3won7mtbbgopomqomu27sdq6q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.13.1-change-attachment-service-tests-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.13.1-change-attachment-service-tests-SNAPSHOT.jar",
          "url": "sdk-jvm-1.13.1-change-attachment-service-tests-SNAPSHOT.jar",
          "size": 11645,
          "sha512": "c092750c975a0baf67811f1ffcba9dc15411bdf0f665e7060b7a7cd5b401efd9f9a18b21ba6d15188ee4edfd37d569575477db147ae659992700dfcf76abc4c9",
          "sha256": "4cd82cbb52944299b44b59485ee7f32f8dd791d4ade85575c4ab11714a7765a3",
          "sha1": "98696019ccc6a7bb0e7e19b2536d6ac5ee25cd91",
          "md5": "aa98ba8fdfd0f27bb84239d7b2587570"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.13.1-change-attachment-service-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.13.1-change-attachment-service-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.13.1-change-attachment-service-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.13.1-change-attachment-service-tests-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.13.1-change-attachment-service-tests-SNAPSHOT.jar",
          "url": "sdk-jvm-1.13.1-change-attachment-service-tests-SNAPSHOT.jar",
          "size": 11645,
          "sha512": "c092750c975a0baf67811f1ffcba9dc15411bdf0f665e7060b7a7cd5b401efd9f9a18b21ba6d15188ee4edfd37d569575477db147ae659992700dfcf76abc4c9",
          "sha256": "4cd82cbb52944299b44b59485ee7f32f8dd791d4ade85575c4ab11714a7765a3",
          "sha1": "98696019ccc6a7bb0e7e19b2536d6ac5ee25cd91",
          "md5": "aa98ba8fdfd0f27bb84239d7b2587570"
        }
      ]
    }
  ]
}
