{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.11.0-bump-okhttp-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "wbwnp32vdvbofcdpbagdxxp6tu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-bump-okhttp-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.11.0-bump-okhttp-SNAPSHOT.jar",
          "url": "crypto-jvm-1.11.0-bump-okhttp-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "ee22f5257e123fb90605d3fddd547f36a7e3105e81f7c699b1f39b56fe568af82e419fe8287a9fe2bfa84df365ca00623c50a47a63ab39ed6640c8ff885c2d80",
          "sha256": "104e32807bba7e23d6d58feff5faf0c896c6569d05356ca97182b372f0e703a6",
          "sha1": "0420b1112e28e5eefb5d1b24b2e63bb2be0fb95a",
          "md5": "7542c1370cb564cf8fb63c7cd412fdb7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-bump-okhttp-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.11.0-bump-okhttp-SNAPSHOT.jar",
          "url": "crypto-jvm-1.11.0-bump-okhttp-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "ee22f5257e123fb90605d3fddd547f36a7e3105e81f7c699b1f39b56fe568af82e419fe8287a9fe2bfa84df365ca00623c50a47a63ab39ed6640c8ff885c2d80",
          "sha256": "104e32807bba7e23d6d58feff5faf0c896c6569d05356ca97182b372f0e703a6",
          "sha1": "0420b1112e28e5eefb5d1b24b2e63bb2be0fb95a",
          "md5": "7542c1370cb564cf8fb63c7cd412fdb7"
        }
      ]
    }
  ]
}
