{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.11.0-bump-okhttp-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "gpnkc7p7ebeeffqavho5h7k5ju"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-bump-okhttp-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.11.0-bump-okhttp-SNAPSHOT.jar",
          "url": "crypto-jvm-1.11.0-bump-okhttp-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "3f4c5d3fa649e3b40d71ce30c655d7871ca38483567906b19a74ee1b476ba787b59055a0e66ff51b6bb848c2c6dafd30fa4788103bb108511a38402729a71984",
          "sha256": "a068357eb0c084300098fab26be727a5cb7a23227e6bbea77cbbb01c3bd48597",
          "sha1": "88666be39f4f247827d8c4b139a3d3ff998a6478",
          "md5": "caaf4e8c445a5f05705c5313b107a2b5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-bump-okhttp-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.11.0-bump-okhttp-SNAPSHOT.jar",
          "url": "crypto-jvm-1.11.0-bump-okhttp-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "3f4c5d3fa649e3b40d71ce30c655d7871ca38483567906b19a74ee1b476ba787b59055a0e66ff51b6bb848c2c6dafd30fa4788103bb108511a38402729a71984",
          "sha256": "a068357eb0c084300098fab26be727a5cb7a23227e6bbea77cbbb01c3bd48597",
          "sha1": "88666be39f4f247827d8c4b139a3d3ff998a6478",
          "md5": "caaf4e8c445a5f05705c5313b107a2b5"
        }
      ]
    }
  ]
}
