{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.0-change-consent-document-model-SNAPSHOT/data-donation-sdk-iosx64-0.1.0-change-consent-document-model-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.0-change-consent-document-model-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "xwiaf3bbhjegdhmdvtrv3ese6m"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.0-change-consent-document-model-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.0-change-consent-document-model-SNAPSHOT.jar",
          "size": 40175,
          "sha512": "134b44b305e672baae4115647bd079c96b0e13fc1311d7ede3d86526d202b57404dd3c8a54873f0c9aa9f2e68930715deb5ef7bb193af58033fa3859602486c9",
          "sha256": "886780948081d9b8523edc0009bcbfecc13b17fb336c76cceea5bebe4786c4c3",
          "sha1": "c4fb6269ccb61a8567c9aa266dbed923bb56167e",
          "md5": "cfa8e19439c110a04cdcb44f12a5815d"
        }
      ]
    }
  ]
}
