{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.12.0-change-resource-crypto-service-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "u75audiu3jaf7geury3s4ijsp4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.12.0-change-resource-crypto-service-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.12.0-change-resource-crypto-service-SNAPSHOT.jar",
          "url": "crypto-jvm-1.12.0-change-resource-crypto-service-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "feffbb5c20df7df358d1a878813c2e1af8537192d1a7c38d4ac992933123b84f85aa1d9df7f68638ad6806e452a621792a6f5d1ec969545940dba6e9a94c3c04",
          "sha256": "c6e0aecf5639ca3c935560e68ebb0c2cc960063ca3839695f6a3a9adc0b0de35",
          "sha1": "36690eafabd75d09ef1088f80c3ea27c7556b0ca",
          "md5": "08bd10095742d649d22dc627c09afd98"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.12.0-change-resource-crypto-service-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.12.0-change-resource-crypto-service-SNAPSHOT.jar",
          "url": "crypto-jvm-1.12.0-change-resource-crypto-service-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "feffbb5c20df7df358d1a878813c2e1af8537192d1a7c38d4ac992933123b84f85aa1d9df7f68638ad6806e452a621792a6f5d1ec969545940dba6e9a94c3c04",
          "sha256": "c6e0aecf5639ca3c935560e68ebb0c2cc960063ca3839695f6a3a9adc0b0de35",
          "sha1": "36690eafabd75d09ef1088f80c3ea27c7556b0ca",
          "md5": "08bd10095742d649d22dc627c09afd98"
        }
      ]
    }
  ]
}
