{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk",
    "version": "0.0.3-change-create-and-revoke-consent-for-custom-key-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "zwram2jmcff7lkpqckuvgxknva"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.3-change-create-and-revoke-consent-for-custom-key-SNAPSHOT.jar",
          "url": "data-donation-sdk-0.0.3-change-create-and-revoke-consent-for-custom-key-SNAPSHOT.jar",
          "size": 73681,
          "sha512": "0b3ac68e17ee9dfed8b527ffef0ed490b1d8b70421dcc497ab4d43a5e473a22439c453a82945eb1572672e74a31682764966f8ee3014c3e0fc7292c17a1c8b5e",
          "sha256": "6bb59919b439ef691a5daad26d3313e5f3ec0b99f7911274f942848c583e8fc8",
          "sha1": "81a9b3d278bd759dabc38469a454a74435678fef",
          "md5": "a92ec07f279bb32ab816addde716fd6a"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android-debug/0.0.3-change-create-and-revoke-consent-for-custom-key-SNAPSHOT/data-donation-sdk-android-debug-0.0.3-change-create-and-revoke-consent-for-custom-key-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android-debug",
        "version": "0.0.3-change-create-and-revoke-consent-for-custom-key-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android-debug/0.0.3-change-create-and-revoke-consent-for-custom-key-SNAPSHOT/data-donation-sdk-android-debug-0.0.3-change-create-and-revoke-consent-for-custom-key-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android-debug",
        "version": "0.0.3-change-create-and-revoke-consent-for-custom-key-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android/0.0.3-change-create-and-revoke-consent-for-custom-key-SNAPSHOT/data-donation-sdk-android-0.0.3-change-create-and-revoke-consent-for-custom-key-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android",
        "version": "0.0.3-change-create-and-revoke-consent-for-custom-key-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android/0.0.3-change-create-and-revoke-consent-for-custom-key-SNAPSHOT/data-donation-sdk-android-0.0.3-change-create-and-revoke-consent-for-custom-key-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android",
        "version": "0.0.3-change-create-and-revoke-consent-for-custom-key-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../data-donation-sdk-iosarm64/0.0.3-change-create-and-revoke-consent-for-custom-key-SNAPSHOT/data-donation-sdk-iosarm64-0.0.3-change-create-and-revoke-consent-for-custom-key-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-iosarm64",
        "version": "0.0.3-change-create-and-revoke-consent-for-custom-key-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../data-donation-sdk-iosx64/0.0.3-change-create-and-revoke-consent-for-custom-key-SNAPSHOT/data-donation-sdk-iosx64-0.0.3-change-create-and-revoke-consent-for-custom-key-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-iosx64",
        "version": "0.0.3-change-create-and-revoke-consent-for-custom-key-SNAPSHOT"
      }
    }
  ]
}
