{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk/0.0.4-add-consent-serive-error-propagation-SNAPSHOT/data-donation-sdk-0.0.4-add-consent-serive-error-propagation-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk",
    "version": "0.0.4-add-consent-serive-error-propagation-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "b2rxd27mvnexfpsfem2lql2y5q"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-kmp",
          "module": "fhir",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.4.3-native-mt",
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-ios",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "data-donation-sdk.klib",
          "url": "data-donation-sdk-iosarm64-0.0.4-add-consent-serive-error-propagation-SNAPSHOT.klib",
          "size": 229781,
          "sha512": "5a4baf7eeee41b45da8e89184683a139f1f89dae65d5efafbcbd7870ba67e16d11707013fcc6f59c9c417797211774eed4c4fec7885877101b47e88bde6c45cb",
          "sha256": "903288d5bb8684ea2f96bcb8e2ae806d6ed608ac4b4d45eb45164c3464abb623",
          "sha1": "ff4ee7ca8c52321c9b8a414317e692db89185dd5",
          "md5": "f24b847c89ac5f263f14cacfcf1a2336"
        },
        {
          "name": "data-donation-sdk-cinterop-iOSCryptoDD.klib",
          "url": "data-donation-sdk-iosarm64-0.0.4-add-consent-serive-error-propagation-SNAPSHOT-cinterop-iOSCryptoDD.klib",
          "size": 4269848,
          "sha512": "85605abf6252c5b4cdd1608e963a01ec343d38260e1765bc1c0e57e1c48d6e8df26fd7e504ee5333aba14c2142e121e6bd6e97c1ab64998ca5c6eaff5d984697",
          "sha256": "2235116e34f9003aecedb2804845d49fd82af4e57c314d982e5d8c2560d7e8db",
          "sha1": "e75dfed9da9f7420a46661a0ccff086c2d3e3936",
          "md5": "910a0144820fc7d06a39766a0228df73"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../data-donation-sdk-metadata/0.0.4-add-consent-serive-error-propagation-SNAPSHOT/data-donation-sdk-metadata-0.0.4-add-consent-serive-error-propagation-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-metadata",
        "version": "0.0.4-add-consent-serive-error-propagation-SNAPSHOT"
      }
    }
  ]
}
