{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.13.1-remove-pinning-s4h-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "v7wkef75mjg2dpkqtpmk6iikge"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.13.1-remove-pinning-s4h-SNAPSHOT.jar",
          "url": "securestore-common-1.13.1-remove-pinning-s4h-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "d425702734b5f1bf86eb846a6028cbad9d1bb2348f369cc5ebb34ec4be1df832c18adbe920fc8d8d65857001dabec2c81e08e8e20f9b3eabc1466ef4d1500fe6",
          "sha256": "76b30b881fd1b4027262618a86358911876b4bf8f09ea427da8a18e7cfa88794",
          "sha1": "d7bec85e70ff6d2c1e6ece8d45fa4be4b8f6314e",
          "md5": "79181c477cf07f480f36214615b370d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.13.1-remove-pinning-s4h-SNAPSHOT.jar",
          "url": "securestore-common-1.13.1-remove-pinning-s4h-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "d425702734b5f1bf86eb846a6028cbad9d1bb2348f369cc5ebb34ec4be1df832c18adbe920fc8d8d65857001dabec2c81e08e8e20f9b3eabc1466ef4d1500fe6",
          "sha256": "76b30b881fd1b4027262618a86358911876b4bf8f09ea427da8a18e7cfa88794",
          "sha1": "d7bec85e70ff6d2c1e6ece8d45fa4be4b8f6314e",
          "md5": "79181c477cf07f480f36214615b370d6"
        }
      ]
    }
  ]
}
