{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk/0.2.1-add-defintion-module-SNAPSHOT/data-donation-sdk-0.2.1-add-defintion-module-SNAPSHOT.module",
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk",
    "version": "0.2.1-add-defintion-module-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "f3vilcc5vfbvhlh4xcstptsbi4"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-data-donation-sdk-kmp",
          "module": "data-donation-sdk-api",
          "version": {
            "requires": "0.2.1-add-defintion-module-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "data-donation-sdk-debug.aar",
          "url": "data-donation-sdk-android-debug-0.2.1-add-defintion-module-SNAPSHOT.aar",
          "size": 351274,
          "sha512": "aceff9521e28dd1d2748d48fd59e76efb0e0370099f2bc29b506491daaed76f985cb4ad8085a09c9d1e9a7c060486bc8d592e39ce5bdd08377602f0f22e45146",
          "sha256": "b13b044efe6337f7494766e8b2e8ad7e8d8e52fa8e43bae02bc1c3d4d33db1a9",
          "sha1": "d549a731ba3436968a1a1754612bc1a40902e250",
          "md5": "c01a532ab29aa12145ab6a3568a11896"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-data-donation-sdk-kmp",
          "module": "data-donation-sdk-api",
          "version": {
            "requires": "0.2.1-add-defintion-module-SNAPSHOT"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-nop",
          "version": {
            "requires": "1.7.31"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.31"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.6"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.1.6-a1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "1.1.6"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-kmp",
          "module": "fhir",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "care.data4life.hc-result-sdk-kmp",
          "module": "flow",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "care.data4life.hc-result-sdk-kmp",
          "module": "error",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "care.data4life.hc-coroutine-util-sdk-kmp",
          "module": "coroutine-util",
          "version": {
            "requires": "0.1.0"
          },
          "excludes": [
            {
              "group": "co.touchlab:stately-concurrency",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "data-donation-sdk-debug.aar",
          "url": "data-donation-sdk-android-debug-0.2.1-add-defintion-module-SNAPSHOT.aar",
          "size": 351274,
          "sha512": "aceff9521e28dd1d2748d48fd59e76efb0e0370099f2bc29b506491daaed76f985cb4ad8085a09c9d1e9a7c060486bc8d592e39ce5bdd08377602f0f22e45146",
          "sha256": "b13b044efe6337f7494766e8b2e8ad7e8d8e52fa8e43bae02bc1c3d4d33db1a9",
          "sha1": "d549a731ba3436968a1a1754612bc1a40902e250",
          "md5": "c01a532ab29aa12145ab6a3568a11896"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../data-donation-sdk-metadata/0.2.1-add-defintion-module-SNAPSHOT/data-donation-sdk-metadata-0.2.1-add-defintion-module-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-metadata",
        "version": "0.2.1-add-defintion-module-SNAPSHOT"
      }
    }
  ]
}
