{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coroutine-util/9facc07/coroutine-util-9facc07.module",
    "group": "care.data4life.hc-coroutine-util-sdk-kmp",
    "module": "coroutine-util",
    "version": "9facc07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "ald7uvirhfhm3niuaw2jvuus2e"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "coroutine-util-jvm-9facc07.jar",
          "url": "coroutine-util-jvm-9facc07.jar",
          "size": 2767,
          "sha512": "b287346db5129b41dd06126be0642ef545ddecf31786bfc89e7cfadf13f2dd3726a1cc72c3009ec299b9e0622d2a03bfe3cf985c5d4dbc413802a46620fb9cd5",
          "sha256": "6e9bdd173553c377df54ff8d1d1265bd350e2d7b94f95d557c2aea0ee6d9353f",
          "sha1": "389589812d840dd0700fee560e5aeba33067089d",
          "md5": "f8a3df7f737ae682262d51401cfd884d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "coroutine-util-jvm-9facc07.jar",
          "url": "coroutine-util-jvm-9facc07.jar",
          "size": 2767,
          "sha512": "b287346db5129b41dd06126be0642ef545ddecf31786bfc89e7cfadf13f2dd3726a1cc72c3009ec299b9e0622d2a03bfe3cf985c5d4dbc413802a46620fb9cd5",
          "sha256": "6e9bdd173553c377df54ff8d1d1265bd350e2d7b94f95d557c2aea0ee6d9353f",
          "sha1": "389589812d840dd0700fee560e5aeba33067089d",
          "md5": "f8a3df7f737ae682262d51401cfd884d"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../coroutine-util-metadata/9facc07/coroutine-util-metadata-9facc07.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util-metadata",
        "version": "9facc07"
      }
    }
  ]
}
