{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "tpm3ssju65agdisfmybmps4usa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.11.0-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "98421cd74a7e104db73e2d519f3dd4313056b8b8a0528ebf7a8d16a414a9b1461f48f7a7f59943c4b73e489b7c2df19cb7b1f851efba5ba5e41371f3202279b6",
          "sha256": "ed0814b678066d2141c9b7ef7afd0ce03789f3eb6664f8b170b23717fbeefc40",
          "sha1": "bb3977e0f56889015696d1f16ca296a02fe01f2b",
          "md5": "cbd900b0d6945051546fdda58b9e15b6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.11.0-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "98421cd74a7e104db73e2d519f3dd4313056b8b8a0528ebf7a8d16a414a9b1461f48f7a7f59943c4b73e489b7c2df19cb7b1f851efba5ba5e41371f3202279b6",
          "sha256": "ed0814b678066d2141c9b7ef7afd0ce03789f3eb6664f8b170b23717fbeefc40",
          "sha1": "bb3977e0f56889015696d1f16ca296a02fe01f2b",
          "md5": "cbd900b0d6945051546fdda58b9e15b6"
        }
      ]
    }
  ]
}
