{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "vr7whqxv4bgjbf5nzgcldqzf3a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.11.0-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "3696fdd15bc69965b1163a1e3dce16359ffc3fd3662ca1a9141b2923ec4a698382a9ff54a488071f56bc901c0dde1abf781cce359e27ac83fda7d0fa933df2f7",
          "sha256": "9ffa1feef42e652ac648fcb2d1a25ecfd515a00743b33ab1b3e462fbc8187ac5",
          "sha1": "01ca800457f94949c2fe9faa76b95f3326e2a1d7",
          "md5": "974982934358f73a035f3edafed07170"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.11.0-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "3696fdd15bc69965b1163a1e3dce16359ffc3fd3662ca1a9141b2923ec4a698382a9ff54a488071f56bc901c0dde1abf781cce359e27ac83fda7d0fa933df2f7",
          "sha256": "9ffa1feef42e652ac648fcb2d1a25ecfd515a00743b33ab1b3e462fbc8187ac5",
          "sha1": "01ca800457f94949c2fe9faa76b95f3326e2a1d7",
          "md5": "974982934358f73a035f3edafed07170"
        }
      ]
    }
  ]
}
