{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.0.5-change-model-contract-SNAPSHOT/data-donation-sdk-iosx64-0.0.5-change-model-contract-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.0.5-change-model-contract-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ust2qlrarvbihkiafynvuefpfm"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.5-change-model-contract-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.0.5-change-model-contract-SNAPSHOT.jar",
          "size": 45013,
          "sha512": "ed7473c71a464c3a144bc8ad20a830732efc92230e070bcdad8eacc7af5a3d1e968768d3cdc139f6d13c3fb69dbb4a654aa81c32816ddf6942dd7a1b65f4292c",
          "sha256": "70bc14b7dc6ac4032e2314fca6affe439bcc4b12820c0e762d4a459fbb67ab29",
          "sha1": "b61b9732cfbc80ea64bf9f9c162c930d6447aba4",
          "md5": "d23722abdab5e7a398b3b18d11a41652"
        }
      ]
    }
  ]
}
