{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.11.0-add-certificate-pinner-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "pcpk4mrtkjhhpp376j656fu4l4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-add-certificate-pinner-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.11.0-add-certificate-pinner-SNAPSHOT.jar",
          "url": "securestore-jvm-1.11.0-add-certificate-pinner-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "9f2ebc58b93af4c57ca59942cc1ba449be8045d179cb38d451d56f5be442977aadc53548616a78646491be498ac7453f1f5136332d4ad364b4c89efc494fb853",
          "sha256": "7b142f890a6b7399329a5dbbab484ee597a637629b9d16dca79382547780442f",
          "sha1": "cea01115bf8f5226d955f7be8ef20ccc3059bb86",
          "md5": "7611f2884b6acf1725411b5069cb9980"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-add-certificate-pinner-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.11.0-add-certificate-pinner-SNAPSHOT.jar",
          "url": "securestore-jvm-1.11.0-add-certificate-pinner-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "9f2ebc58b93af4c57ca59942cc1ba449be8045d179cb38d451d56f5be442977aadc53548616a78646491be498ac7453f1f5136332d4ad364b4c89efc494fb853",
          "sha256": "7b142f890a6b7399329a5dbbab484ee597a637629b9d16dca79382547780442f",
          "sha1": "cea01115bf8f5226d955f7be8ef20ccc3059bb86",
          "md5": "7611f2884b6acf1725411b5069cb9980"
        }
      ]
    }
  ]
}
