{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.13.0-add-sdk-config-to-gitignore-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "m2l3lbf5xng3vfhujms3gnt24y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.0-add-sdk-config-to-gitignore-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.13.0-add-sdk-config-to-gitignore-SNAPSHOT.jar",
          "url": "securestore-jvm-1.13.0-add-sdk-config-to-gitignore-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "3a739c1e6d37402ca132cb408ee0604b7e6ef478f4fae418153e4e59df102886094fe1999d3c7e7923537f7794e62743536bc803d721dd30d1e85a7dbfa324eb",
          "sha256": "82456e4a93c30cf6abef9ab9ff0ecf0c4f7ea81d7d3b477cb5bcc826099284a1",
          "sha1": "bb35bca4afee8a7e6b2ac29dd7bdeb351ad27536",
          "md5": "972013acb57f4f9bd8cdf136cbe89181"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.0-add-sdk-config-to-gitignore-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.13.0-add-sdk-config-to-gitignore-SNAPSHOT.jar",
          "url": "securestore-jvm-1.13.0-add-sdk-config-to-gitignore-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "3a739c1e6d37402ca132cb408ee0604b7e6ef478f4fae418153e4e59df102886094fe1999d3c7e7923537f7794e62743536bc803d721dd30d1e85a7dbfa324eb",
          "sha256": "82456e4a93c30cf6abef9ab9ff0ecf0c4f7ea81d7d3b477cb5bcc826099284a1",
          "sha1": "bb35bca4afee8a7e6b2ac29dd7bdeb351ad27536",
          "md5": "972013acb57f4f9bd8cdf136cbe89181"
        }
      ]
    }
  ]
}
