{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.3-add-crypto-service-android-SNAPSHOT/data-donation-sdk-iosx64-0.1.3-add-crypto-service-android-SNAPSHOT.module",
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.3-add-crypto-service-android-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "s24wkkzkxzglbmmrgxeufqupcu"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.3-add-crypto-service-android-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.3-add-crypto-service-android-SNAPSHOT.jar",
          "size": 60014,
          "sha512": "7f7a97fe253feb9e0cc9000d3935f506d324e3465713bccf66bc1d7a096068f3d1d01e1573705fa73346c72177548a2c83d14e2f1c5236eddd33d077f5099594",
          "sha256": "4e7eb723df20190ef37d11248d1c7a8220b4bbff36ef5f98cc5c229f779202d7",
          "sha1": "27270771579472f4439a16a96758a7320df27a8d",
          "md5": "cc32c704298b32f641dcdfba5c50235e"
        }
      ]
    }
  ]
}
