{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.11.0-add-error-SNAPSHOT/util-1.11.0-add-error-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.11.0-add-error-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "util.klib",
          "url": "util-iosx64-1.11.0-add-error-SNAPSHOT.klib",
          "size": 25769,
          "sha512": "41694487c662f68d2ed6a1d05af4973f225a3d1bf191ef4e78fcb71323d56bfd819fca2b0e78dde008b351ea4e7f5419a11ef550556fa4d202de72727f9e050b",
          "sha256": "cf81e7166b7e7d242eab202bc8b943e2d2b1a975df14932a76afeaf5fe33ebdc",
          "sha1": "5b18856e53efe56b9d849ae0b14e6a85acd91a0e",
          "md5": "be5e0e80abd1e6eab87535cb6e14d8e9"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "util-iosx64-1.11.0-add-error-SNAPSHOT-metadata.jar",
          "url": "util-iosx64-1.11.0-add-error-SNAPSHOT-metadata.jar",
          "size": 6109,
          "sha512": "7f8369d10e8b10a45c0ea928798d05a97a84ca9df39bb24b8fcbc979cb3c92bf8ebdfc6973dae9a4107ab88679e92da7aa394d6bc97f6eae61ef017b10c22854",
          "sha256": "6063d78a62775210f38e1152db71785cf7b59f00ebb5889eedc5e3a337f5b455",
          "sha1": "bc29d7c9f1d5d5d4e6d7160f602109d3dab06713",
          "md5": "089e7d36118a309d5b4540b56fc0e296"
        }
      ]
    }
  ]
}
