{
  "formatVersion": "1.1",
  "component": {
    "url": "../../error/1.11.0-bump-updates-SNAPSHOT/error-1.11.0-bump-updates-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "error",
    "version": "1.11.0-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "error.klib",
          "url": "error-iosx64-1.11.0-bump-updates-SNAPSHOT.klib",
          "size": 7076,
          "sha512": "b546aeca485ff79ce297f8e21621b9d09644d6d03f025d0fd2ffd3bfb8ebd100640cfa9104bb8c7ae9b90c53e89df9903151cd4d28dc94f0421ce830dbf4a716",
          "sha256": "fdc476c2d0f47659e23961b5303cd98e82b2f29d89ab5c73d1d5a2038aff2d14",
          "sha1": "1bdf29866dac1f9dee9c75b7f83382f529c920e6",
          "md5": "b9cb2fa35514ac6503837ab344fc834f"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "error-iosx64-1.11.0-bump-updates-SNAPSHOT-metadata.jar",
          "url": "error-iosx64-1.11.0-bump-updates-SNAPSHOT-metadata.jar",
          "size": 5050,
          "sha512": "6a0d7922352de3499cae197de036a7656a4bac69989b9589a437a695d24d994666f3b634e3c001a085f2bebeebeaf0467231774ceeb1f3502cdf44c91ea02fa6",
          "sha256": "fc6f2a6d8c96d8abaf2f8380066ff2dec03cd0149bb39bdd1424223a4fedfe5e",
          "sha1": "e72e75573f5020daf7805f9212c2512baa763a18",
          "md5": "c1871582f93189dc2768e957cb15ae6a"
        }
      ]
    }
  ]
}
