{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-jvm",
    "version": "1.11.0-add-envrioment-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "igtt4bl2cbcxhhi2d52ubt2rry"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.11.0-add-envrioment-tests-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.11.0-add-envrioment-tests-SNAPSHOT.jar",
          "url": "sdk-jvm-1.11.0-add-envrioment-tests-SNAPSHOT.jar",
          "size": 11509,
          "sha512": "57aa29b3df8c0f45c66246b563cd8f36a3c45a876a776eebcb669701547413eeee70f9e1592ba3f827e35566f66f4de8e4e574931e66f8f4e9a3a140a82c29b3",
          "sha256": "70cee6e938ecf0c9ce1ed5bbbd5c590eb65a3979d9744a893555bbdc1e4f5eaf",
          "sha1": "68f5dbd448d7aae1774488779cdf26b85392161f",
          "md5": "f9fb862e33ae92d1414cd47a4c5dbb43"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.11.0-add-envrioment-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.11.0-add-envrioment-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.11.0-add-envrioment-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.11.0-add-envrioment-tests-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.11.0-add-envrioment-tests-SNAPSHOT.jar",
          "url": "sdk-jvm-1.11.0-add-envrioment-tests-SNAPSHOT.jar",
          "size": 11509,
          "sha512": "57aa29b3df8c0f45c66246b563cd8f36a3c45a876a776eebcb669701547413eeee70f9e1592ba3f827e35566f66f4de8e4e574931e66f8f4e9a3a140a82c29b3",
          "sha256": "70cee6e938ecf0c9ce1ed5bbbd5c590eb65a3979d9744a893555bbdc1e4f5eaf",
          "sha1": "68f5dbd448d7aae1774488779cdf26b85392161f",
          "md5": "f9fb862e33ae92d1414cd47a4c5dbb43"
        }
      ]
    }
  ]
}
