{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir",
    "version": "0.1.0-change-setup-for-multiple-fhir-versions-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "y7pg5uxemnddrfgncioniae5a4"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "fhir-metadata-0.1.0-change-setup-for-multiple-fhir-versions-SNAPSHOT.jar",
          "url": "fhir-0.1.0-change-setup-for-multiple-fhir-versions-SNAPSHOT.jar",
          "size": 522470,
          "sha512": "ecf5ae88a605416e736610cacd4a2f6e202bc2bbe4ee7b5aa0920954f08fa70470e5181ca297b61c9729f433227eff6f88c54faf3bd5cfb92947de38ceb492ce",
          "sha256": "6976f6f16764370c7ae23a0d9d58ea2f185eacda94df742506d1ec49d4fe6119",
          "sha1": "f08d50e593c2ad930d7ad7cb4add8c43cae80e01",
          "md5": "a9fc4aa2f9394cfa9ba3867594ae0841"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-android/0.1.0-change-setup-for-multiple-fhir-versions-SNAPSHOT/fhir-android-0.1.0-change-setup-for-multiple-fhir-versions-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-android",
        "version": "0.1.0-change-setup-for-multiple-fhir-versions-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-android/0.1.0-change-setup-for-multiple-fhir-versions-SNAPSHOT/fhir-android-0.1.0-change-setup-for-multiple-fhir-versions-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-android",
        "version": "0.1.0-change-setup-for-multiple-fhir-versions-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fhir-iosarm64/0.1.0-change-setup-for-multiple-fhir-versions-SNAPSHOT/fhir-iosarm64-0.1.0-change-setup-for-multiple-fhir-versions-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-iosarm64",
        "version": "0.1.0-change-setup-for-multiple-fhir-versions-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fhir-iosx64/0.1.0-change-setup-for-multiple-fhir-versions-SNAPSHOT/fhir-iosx64-0.1.0-change-setup-for-multiple-fhir-versions-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-iosx64",
        "version": "0.1.0-change-setup-for-multiple-fhir-versions-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../fhir-jvm/0.1.0-change-setup-for-multiple-fhir-versions-SNAPSHOT/fhir-jvm-0.1.0-change-setup-for-multiple-fhir-versions-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-jvm",
        "version": "0.1.0-change-setup-for-multiple-fhir-versions-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../fhir-jvm/0.1.0-change-setup-for-multiple-fhir-versions-SNAPSHOT/fhir-jvm-0.1.0-change-setup-for-multiple-fhir-versions-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-jvm",
        "version": "0.1.0-change-setup-for-multiple-fhir-versions-SNAPSHOT"
      }
    }
  ]
}
