{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.3-add-asym-key-creation-SNAPSHOT/data-donation-sdk-iosx64-0.1.3-add-asym-key-creation-SNAPSHOT.module",
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.3-add-asym-key-creation-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "uqr3jceehjbrzbjkekroqwvkmm"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.3-add-asym-key-creation-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.3-add-asym-key-creation-SNAPSHOT.jar",
          "size": 58853,
          "sha512": "6c128ec30392940e7a9d00637dfb305437b8f828740d8289a06d2cc246facfcc5776ec98954e03c69876637e2d3b1f63d9e12c8873b3f8fe1df6bcb6f341c5a6",
          "sha256": "6771263796e74548254bedf656f1f776da266c24913f0ca9085c1cce92e8b31c",
          "sha1": "045dd50243c76e657df61ee4819892b6939c7448",
          "md5": "c5e7770ac525972c6e0b2117d5f650c5"
        }
      ]
    }
  ]
}
