{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.13.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "3kvhtq43pvh4pmf7mejuxeljsq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.13.2-SNAPSHOT.jar",
          "url": "crypto-common-1.13.2-SNAPSHOT.jar",
          "size": 11957,
          "sha512": "5e3c35627b46515a7129d488799252d71e1db82f43f6b85deab779d97a0c44cace13b7bc9ad21894d32bdfed62032ab5e4f5b858f69d8e60652e31ceb394dc02",
          "sha256": "258a67804e0113da825a6852f1416a48ed2359c5278c41c37ac49188e4d388c9",
          "sha1": "7d610037858e7908bc48d9751132c5f39f0acec6",
          "md5": "35102953c929fb36d9d940d18ffefb33"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.13.2-SNAPSHOT.jar",
          "url": "crypto-common-1.13.2-SNAPSHOT.jar",
          "size": 11957,
          "sha512": "5e3c35627b46515a7129d488799252d71e1db82f43f6b85deab779d97a0c44cace13b7bc9ad21894d32bdfed62032ab5e4f5b858f69d8e60652e31ceb394dc02",
          "sha256": "258a67804e0113da825a6852f1416a48ed2359c5278c41c37ac49188e4d388c9",
          "sha1": "7d610037858e7908bc48d9751132c5f39f0acec6",
          "md5": "35102953c929fb36d9d940d18ffefb33"
        }
      ]
    }
  ]
}
