{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.2.1-change-provider-paradigm-SNAPSHOT/data-donation-sdk-iosx64-0.2.1-change-provider-paradigm-SNAPSHOT.module",
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.2.1-change-provider-paradigm-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "47nbtkphs5cxjm3uhblh2mvsp4"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.2.1-change-provider-paradigm-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.2.1-change-provider-paradigm-SNAPSHOT.jar",
          "size": 60014,
          "sha512": "fb8eb4e43e80afab583f61b3077f7d70c6fbe6760b194ab0b97160d603e52677a05c631fef254b2cc80e53e15fec3531fa8baaeb959e272db9b9a46efc64e06e",
          "sha256": "ab8e793523b2a388b3166c66dd0730bc118e9809da303895e71c835ed353587c",
          "sha1": "af1296ab5895f977db4bed90d37659c1342e4516",
          "md5": "ddd0b1e509029c892cb58601bd808d71"
        }
      ]
    }
  ]
}
