{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.2.1-change-provider-paradigm-SNAPSHOT/data-donation-sdk-iosx64-0.2.1-change-provider-paradigm-SNAPSHOT.module",
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.2.1-change-provider-paradigm-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "pbxu2quxkvgdrlkij3374igvya"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.2.1-change-provider-paradigm-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.2.1-change-provider-paradigm-SNAPSHOT.jar",
          "size": 58985,
          "sha512": "3c889c796eead84b169c38f8f3b2080c5047285195e46eef166f71d69f69f411690834c3cf728d4686abe9606cb8c17f508b64f9bfb5afe4c15e980729e66416",
          "sha256": "47bf3036635de9f1d998942758da6cfedf5b382f0bf984645db4912d27c31657",
          "sha1": "9694b4abf4b8835f2705f8dfc647097a3b4c034a",
          "md5": "be5c338ce1dc9c7e396412359162e52f"
        }
      ]
    }
  ]
}
