{
  "formatVersion": "1.1",
  "component": {
    "url": "../../example-kmp-library-jvm/0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT/example-kmp-library-jvm-0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT.module",
    "group": "care.data4life.hc-gradle-scripts",
    "module": "example-kmp-library-jvm",
    "version": "0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "xrqgx4ezjfhgpl3ygw5tinwg6e"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "example-kmp-library-metadata-0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT.jar",
          "url": "example-kmp-library-metadata-0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT.jar",
          "size": 6554,
          "sha512": "65be84887b936d3fc010eba31b582480e777691344c7eefca55bc9e854f289bdd0e37d9b8cc9374ba6767e17888fc19fe8492b6d33a25f44f987cec82b64b59d",
          "sha256": "05da1cdde52b71ba53beac588f007c23c49c96064b757676ece6abc1e69b7ca6",
          "sha1": "da1d6d2f3c9a392db23c228894a6dcab889cbbe7",
          "md5": "cd74beadf37f8dcd93ccabc26075afea"
        }
      ]
    }
  ]
}
