{
  "formatVersion": "1.1",
  "component": {
    "url": "../../example-kmp-library-jvm/0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT/example-kmp-library-jvm-0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT.module",
    "group": "care.data4life.hc-gradle-scripts",
    "module": "example-kmp-library-jvm",
    "version": "0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "myzzcbkzmjfvhnpmfbt4zanugm"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "example-kmp-library-metadata-0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT.jar",
          "url": "example-kmp-library-metadata-0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT.jar",
          "size": 6554,
          "sha512": "47455f2aa2c986c9df074376cdf7d113e643a4dc941098d4dcc0c456a79523c41c81745c9dd1bdbfef7a2acbbb242ff5b12034f1f3a7e203dc3711c090214063",
          "sha256": "0bab39144eb3ea639e08fad0997718fa94ea7ab22d3cfed652547d24c2b99c80",
          "sha1": "b8e8714079a1b697cc852e94c2bc075548583949",
          "md5": "6a7812a19c21ee3ab34a8b20d20b1134"
        }
      ]
    }
  ]
}
