{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir-stu3",
    "version": "0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-kmp",
          "module": "fhir",
          "version": {
            "requires": "0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-stu3-metadata-0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT-all.jar",
          "url": "fhir-stu3-0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT-all.jar",
          "size": 342891,
          "sha512": "7302eb260a05cacd72018ce9afea7cd31cf3eae426968e473793487c73061f02b8a633665c3d90993796ff8c65033dbe046c3da19547418313a6d4794ff1a240",
          "sha256": "20f5f9d89b300b9a5cd6435054346ab37ffb70d655c66f24fc3ae8c92979c287",
          "sha1": "ee9d3a3789defc954ac9596a31701d20d5823079",
          "md5": "1d77306fccfe32494d65d450024f64e8"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-kmp",
          "module": "fhir",
          "version": {
            "requires": "0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-stu3-0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT.jar",
          "url": "fhir-stu3-0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT.jar",
          "size": 1279568,
          "sha512": "b0c77612e5d57421706197a6b64d7f5429118a593703b6f413092fb6237dc301c4935d36ca3ccc36fe4007c9759bec1f2d5aaf31c60a6c2ca6d31815a84a620a",
          "sha256": "76e56b74204161cbd37221111d5578c0e3d825e8ded4ef4b8b68cde99c63c215",
          "sha1": "5de9af016cadbc6111efbd26240421392d98265c",
          "md5": "1a69fc0334b4c4323f11ea7907244dfa"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-stu3-android-debug/0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT/fhir-stu3-android-debug-0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-stu3-android-debug",
        "version": "0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-stu3-android-debug/0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT/fhir-stu3-android-debug-0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-stu3-android-debug",
        "version": "0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-stu3-android/0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT/fhir-stu3-android-0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-stu3-android",
        "version": "0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-stu3-android/0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT/fhir-stu3-android-0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-stu3-android",
        "version": "0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fhir-stu3-iosarm64/0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT/fhir-stu3-iosarm64-0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-stu3-iosarm64",
        "version": "0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fhir-stu3-iosarm64/0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT/fhir-stu3-iosarm64-0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-stu3-iosarm64",
        "version": "0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fhir-stu3-iosx64/0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT/fhir-stu3-iosx64-0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-stu3-iosx64",
        "version": "0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fhir-stu3-iosx64/0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT/fhir-stu3-iosx64-0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-stu3-iosx64",
        "version": "0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../fhir-stu3-jvm/0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT/fhir-stu3-jvm-0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-stu3-jvm",
        "version": "0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../fhir-stu3-jvm/0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT/fhir-stu3-jvm-0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-stu3-jvm",
        "version": "0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT"
      }
    }
  ]
}
