{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir-helper/1.8.0-SNAPSHOT/fhir-helper-1.8.0-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-helper-sdk-kmp",
    "module": "fhir-helper",
    "version": "1.8.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-helper-jvm-1.8.0-SNAPSHOT.jar",
          "url": "fhir-helper-jvm-1.8.0-SNAPSHOT.jar",
          "size": 114498,
          "sha512": "e5d00194c2c0c4e27e4917c15c5fd4b4c0ee8df071db2c9478e329253e3254dc272c098d60edd5cb4dfcac0fbe72932fd359fb7280cfc595be44a1109d47894f",
          "sha256": "9ba6f12b0ebd172fcc5604cb619fbb4d757d048afffeaab3619d80f36f385ffd",
          "sha1": "1e301ab638cad6c26cc5ba35f59f59fb47b40791",
          "md5": "3a3a3f2cb5b9bc424a74f8556e2b6eda"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "error",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-helper-jvm-1.8.0-SNAPSHOT.jar",
          "url": "fhir-helper-jvm-1.8.0-SNAPSHOT.jar",
          "size": 114498,
          "sha512": "e5d00194c2c0c4e27e4917c15c5fd4b4c0ee8df071db2c9478e329253e3254dc272c098d60edd5cb4dfcac0fbe72932fd359fb7280cfc595be44a1109d47894f",
          "sha256": "9ba6f12b0ebd172fcc5604cb619fbb4d757d048afffeaab3619d80f36f385ffd",
          "sha1": "1e301ab638cad6c26cc5ba35f59f59fb47b40791",
          "md5": "3a3a3f2cb5b9bc424a74f8556e2b6eda"
        }
      ]
    }
  ]
}
