{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-jvm",
    "version": "1.13.0-bump-mockk-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "smcsphdrhvgqfcfnppicezsyjy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.13.0-bump-mockk-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.13.0-bump-mockk-SNAPSHOT.jar",
          "url": "sdk-jvm-1.13.0-bump-mockk-SNAPSHOT.jar",
          "size": 11643,
          "sha512": "50bee1c645f5e4c1807b032149b0ac88c92ce48764f3d40117fa7b0791cb5b6d2829eca489de689da09b490d8165421a01b47dc4863b6975460d99a86b7c8d1d",
          "sha256": "d7e7d0106662488b6c4b2acfd0d73f4d07ad2554a53a88c0f738f334ef138f61",
          "sha1": "5b54c599c6c1f155448b5c605a54b555d74fcf83",
          "md5": "7ef272abf85c44d5cae27d0f116f4a29"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.13.0-bump-mockk-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.13.0-bump-mockk-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.13.0-bump-mockk-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.13.0-bump-mockk-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.13.0-bump-mockk-SNAPSHOT.jar",
          "url": "sdk-jvm-1.13.0-bump-mockk-SNAPSHOT.jar",
          "size": 11643,
          "sha512": "50bee1c645f5e4c1807b032149b0ac88c92ce48764f3d40117fa7b0791cb5b6d2829eca489de689da09b490d8165421a01b47dc4863b6975460d99a86b7c8d1d",
          "sha256": "d7e7d0106662488b6c4b2acfd0d73f4d07ad2554a53a88c0f738f334ef138f61",
          "sha1": "5b54c599c6c1f155448b5c605a54b555d74fcf83",
          "md5": "7ef272abf85c44d5cae27d0f116f4a29"
        }
      ]
    }
  ]
}
