{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.3-add-crypto-service-ios-SNAPSHOT/data-donation-sdk-iosx64-0.1.3-add-crypto-service-ios-SNAPSHOT.module",
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.3-add-crypto-service-ios-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "k7fsq3bcdzdsfleyvnqtm7ljzm"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.3-add-crypto-service-ios-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.3-add-crypto-service-ios-SNAPSHOT.jar",
          "size": 77406,
          "sha512": "2ef75cbd3b88e484c208f7cb3eabf671e6472de025b1f44c9bc36c7768145cf69cc1963e5274691955542c1e6ad169f71bebc2affd7687028a6cfb6d1815cfed",
          "sha256": "51eb9870958fac18bd2ea4fde17ee586a8445c871ece07ba8939e3a3904473e8",
          "sha1": "ae01718daff5636a58d457e4d107872f7354c260",
          "md5": "73f41f832b064f8b578046319ab4f605"
        }
      ]
    }
  ]
}
