{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.3-add-crypto-service-ios-SNAPSHOT/data-donation-sdk-iosx64-0.1.3-add-crypto-service-ios-SNAPSHOT.module",
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.3-add-crypto-service-ios-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "slbzxm3nevgzrdldve4zpslcdm"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.3-add-crypto-service-ios-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.3-add-crypto-service-ios-SNAPSHOT.jar",
          "size": 87691,
          "sha512": "e1f654ba60d020ecbece62f52fdeae41f6104e5c9f5aa71cb6a8df397fe8beb6f80d568587e4384725109154f603edf0c5433a2f70732b0cf654bc518c4522ef",
          "sha256": "47d822de7163778f819a9e41647b9ae2a71ce29e882102a2acda6169c6a73c02",
          "sha1": "90e21ea7fc7af3838fedc5d4ff2bb6e158a83aac",
          "md5": "370bdf770f53053126fcd6c85d28f10a"
        }
      ]
    }
  ]
}
