{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.11.0-add-certificate-pinner-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "exsjfgsemfgk7fawrxnhqaokqm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.11.0-add-certificate-pinner-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-add-certificate-pinner-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "f09e152fa34a0c6620988dd18cb54b864c0cc60b2fd0ed81948dac8d539ec5484f0e7a55d00eace2e0b354dc18393982dfe5ebe71c2685e9418d0ee2c8952aa3",
          "sha256": "721af15339d4738dbbe0e068e52b34e4326a8474b4e691bc6cc1f9421e792fa3",
          "sha1": "df89b233a6f44fe56b149fc26aed9c01ebcf0702",
          "md5": "f5172be51cb7b5c0d8df5ede64e1d9f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.11.0-add-certificate-pinner-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-add-certificate-pinner-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "f09e152fa34a0c6620988dd18cb54b864c0cc60b2fd0ed81948dac8d539ec5484f0e7a55d00eace2e0b354dc18393982dfe5ebe71c2685e9418d0ee2c8952aa3",
          "sha256": "721af15339d4738dbbe0e068e52b34e4326a8474b4e691bc6cc1f9421e792fa3",
          "sha1": "df89b233a6f44fe56b149fc26aed9c01ebcf0702",
          "md5": "f5172be51cb7b5c0d8df5ede64e1d9f6"
        }
      ]
    }
  ]
}
