{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-auth-sdk-kmp",
    "module": "auth",
    "version": "1.14.0-change-to-latest-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "7lz3ebewkvcq7hs6gr6fqrsgze"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "auth-metadata-1.14.0-change-to-latest-setup-SNAPSHOT.jar",
          "url": "auth-1.14.0-change-to-latest-setup-SNAPSHOT.jar",
          "size": 3764,
          "sha512": "4123c9bf05b109e4410b7d94fd2eee9659bf05c9586b8c4dd5551e1d16c1db73ddace9dedf2dc6a75144189cc35fcd057437253f9d3a08ce18e7d5ca9914e1e9",
          "sha256": "36f60fe1eb3ed8757bad386a8fc5797d5d62fab7113e0df5d4dabc8c0c525c43",
          "sha1": "e63fb73413922e66ef82c45048a29387018758a8",
          "md5": "ce4de4d45dd7f7ecb9557a62dbd92b79"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../auth-android-debug/1.14.0-change-to-latest-setup-SNAPSHOT/auth-android-debug-1.14.0-change-to-latest-setup-SNAPSHOT.module",
        "group": "care.data4life.hc-auth-sdk-kmp",
        "module": "auth-android-debug",
        "version": "1.14.0-change-to-latest-setup-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../auth-android-debug/1.14.0-change-to-latest-setup-SNAPSHOT/auth-android-debug-1.14.0-change-to-latest-setup-SNAPSHOT.module",
        "group": "care.data4life.hc-auth-sdk-kmp",
        "module": "auth-android-debug",
        "version": "1.14.0-change-to-latest-setup-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../auth-android/1.14.0-change-to-latest-setup-SNAPSHOT/auth-android-1.14.0-change-to-latest-setup-SNAPSHOT.module",
        "group": "care.data4life.hc-auth-sdk-kmp",
        "module": "auth-android",
        "version": "1.14.0-change-to-latest-setup-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../auth-android/1.14.0-change-to-latest-setup-SNAPSHOT/auth-android-1.14.0-change-to-latest-setup-SNAPSHOT.module",
        "group": "care.data4life.hc-auth-sdk-kmp",
        "module": "auth-android",
        "version": "1.14.0-change-to-latest-setup-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../auth-jvm/1.14.0-change-to-latest-setup-SNAPSHOT/auth-jvm-1.14.0-change-to-latest-setup-SNAPSHOT.module",
        "group": "care.data4life.hc-auth-sdk-kmp",
        "module": "auth-jvm",
        "version": "1.14.0-change-to-latest-setup-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../auth-jvm/1.14.0-change-to-latest-setup-SNAPSHOT/auth-jvm-1.14.0-change-to-latest-setup-SNAPSHOT.module",
        "group": "care.data4life.hc-auth-sdk-kmp",
        "module": "auth-jvm",
        "version": "1.14.0-change-to-latest-setup-SNAPSHOT"
      }
    }
  ]
}
