{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-coroutine/0.2.0-change-codeowners-SNAPSHOT/test-util-coroutine-0.2.0-change-codeowners-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-coroutine",
    "version": "0.2.0-change-codeowners-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "yzcokp3r7rasllbwsswwrjiez4"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-util-coroutine-jvm-0.2.0-change-codeowners-SNAPSHOT.jar",
          "url": "test-util-coroutine-jvm-0.2.0-change-codeowners-SNAPSHOT.jar",
          "size": 5987,
          "sha512": "829fa75ec0c8757748088612b137e97a34268376cf2389b85e7d0d11ec1b38a598cf8492f77d5f75f408a3bbc0890be78ebc175e3a95ef1c0a1b1c0730ed206c",
          "sha256": "003a520345a55ec7ee77c747f011e57021e13988f363ed8305d8828270c24d61",
          "sha1": "95724a4e0515d4aa24ca2353f75b604aad424626",
          "md5": "6d4843410794ed308cf1266d7b849f3c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-coroutine-jvm-0.2.0-change-codeowners-SNAPSHOT.jar",
          "url": "test-util-coroutine-jvm-0.2.0-change-codeowners-SNAPSHOT.jar",
          "size": 5987,
          "sha512": "829fa75ec0c8757748088612b137e97a34268376cf2389b85e7d0d11ec1b38a598cf8492f77d5f75f408a3bbc0890be78ebc175e3a95ef1c0a1b1c0730ed206c",
          "sha256": "003a520345a55ec7ee77c747f011e57021e13988f363ed8305d8828270c24d61",
          "sha1": "95724a4e0515d4aa24ca2353f75b604aad424626",
          "md5": "6d4843410794ed308cf1266d7b849f3c"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../test-util-coroutine-metadata/0.2.0-change-codeowners-SNAPSHOT/test-util-coroutine-metadata-0.2.0-change-codeowners-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-metadata",
        "version": "0.2.0-change-codeowners-SNAPSHOT"
      }
    }
  ]
}
