{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-jvm/1.7.0-SNAPSHOT/util-jvm-1.7.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-jvm",
    "version": "1.7.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "hlyqhg2uzreznieledogjqgl6q"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-metadata-1.7.0-SNAPSHOT.jar",
          "url": "util-metadata-1.7.0-SNAPSHOT.jar",
          "size": 6309,
          "sha512": "ff18241bafaadd60820929b95ad0c685d7d8513230c62da10b6b17fdfc86edb201aeb8765eb124f11da90e5340cbe1473c91232bb011a3958d0ce6a4f7fadfb9",
          "sha256": "b8df13547a1802b1553d87ce108d7e782097611467889ab91b47190e1c9d31c1",
          "sha1": "ad6f5cd356f57929cb8f206f4adaaedf8924ae15",
          "md5": "a68bae3c001b14d2e2f6f55f19ef4029"
        }
      ]
    }
  ]
}
