{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-core",
    "version": "1.12.0-add-count-for-arbitrary-data-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ibostorcrvhz7chnnu3popfprm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.12.0-add-count-for-arbitrary-data-SNAPSHOT.jar",
          "url": "sdk-core-1.12.0-add-count-for-arbitrary-data-SNAPSHOT.jar",
          "size": 575975,
          "sha512": "dd58a48468bba2bdd7300c42b7e9b8728caf5ebdbc9253bbed3f753bf14d7494b015a1ec7f777f904b2f506bc6ad5fe4d95d1bdfba9804ea1c68b3f30c224cad",
          "sha256": "a1cca8b58ff2f8708292979633202a8385b23f0413bf9a0480d891c8f009ed8f",
          "sha1": "c75356bbc5fefad9dc06fee69b301d33e28c8f7f",
          "md5": "c53c734d2f259913c4d4e35eb06610b5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.12.0-add-count-for-arbitrary-data-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.12.0-add-count-for-arbitrary-data-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.12.0-add-count-for-arbitrary-data-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.12.0-add-count-for-arbitrary-data-SNAPSHOT.jar",
          "url": "sdk-core-1.12.0-add-count-for-arbitrary-data-SNAPSHOT.jar",
          "size": 575975,
          "sha512": "dd58a48468bba2bdd7300c42b7e9b8728caf5ebdbc9253bbed3f753bf14d7494b015a1ec7f777f904b2f506bc6ad5fe4d95d1bdfba9804ea1c68b3f30c224cad",
          "sha256": "a1cca8b58ff2f8708292979633202a8385b23f0413bf9a0480d891c8f009ed8f",
          "sha1": "c75356bbc5fefad9dc06fee69b301d33e28c8f7f",
          "md5": "c53c734d2f259913c4d4e35eb06610b5"
        }
      ]
    }
  ]
}
