{
  "formatVersion": "1.1",
  "component": {
    "url": "../../objc-util/0.1.0-SNAPSHOT/objc-util-0.1.0-SNAPSHOT.module",
    "group": "care.data4life.hc-objc-util-sdk-kmp",
    "module": "objc-util",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "objc-util.klib",
          "url": "objc-util-iosarm64-0.1.0-SNAPSHOT.klib",
          "size": 8900,
          "sha512": "a378cc690f4a70147cc2fba88d320ae78ddef5a52fc052df495ec2e4e4a4af7dc5248a1da44abfd501841864055003addf0ccaede62ac84131638b462fb94c81",
          "sha256": "632d6a5b32ac7072e3768c3694f4c36cad46bed506a02c2a0652c77cd2a62637",
          "sha1": "57ad6b32232eff5e9d970ce592cb41c91e314d23",
          "md5": "6e049c86649ee63b9999f919da94af76"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "objc-util-iosarm64-0.1.0-SNAPSHOT-metadata.jar",
          "url": "objc-util-iosarm64-0.1.0-SNAPSHOT-metadata.jar",
          "size": 5763,
          "sha512": "a7224cd8e1291cf1d77abd0a5a57b22851e0228c71f9e6a00fa62105e227a9a0f12e42ccf99bed367081d4f9fe4b9372851a2b0a842da5f641dffd40abc3687f",
          "sha256": "6962370f8dbda351af7e8f61f5e56c44e110195f7964d1c0de9eac0541bb55aa",
          "sha1": "ad20494c45b829080daacd6d8eea037beef98818",
          "md5": "802bcc5b5edad2027e9c22cf048606d8"
        }
      ]
    }
  ]
}
