{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.11.0-change-api-service-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "of7vey2p2nh4xherzhghmjsrey"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-change-api-service-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.11.0-change-api-service-SNAPSHOT.jar",
          "url": "securestore-jvm-1.11.0-change-api-service-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "f2a629e67da8f08732cd2830eb01df095c77521958e2232a5e144b2d00abb0a5b91e3aefab28e8105d9faeb7e86799c5c787eb365bedaa43891cf4490e3f6152",
          "sha256": "e0cebdd1b5e281d4784e6d3166307b96d3cc8dedde342a0e8c4f9d600088e16c",
          "sha1": "586f65ff0acb07e78ded0acbd0a8cacc8d7f3109",
          "md5": "930b053a4f7cbd91d840562586ba9f2a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-change-api-service-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.11.0-change-api-service-SNAPSHOT.jar",
          "url": "securestore-jvm-1.11.0-change-api-service-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "f2a629e67da8f08732cd2830eb01df095c77521958e2232a5e144b2d00abb0a5b91e3aefab28e8105d9faeb7e86799c5c787eb365bedaa43891cf4490e3f6152",
          "sha256": "e0cebdd1b5e281d4784e6d3166307b96d3cc8dedde342a0e8c4f9d600088e16c",
          "sha1": "586f65ff0acb07e78ded0acbd0a8cacc8d7f3109",
          "md5": "930b053a4f7cbd91d840562586ba9f2a"
        }
      ]
    }
  ]
}
