{
  "formatVersion": "1.1",
  "component": {
    "url": "../../example-kmp-library/0.0.1-add-coverage-scripts-SNAPSHOT/example-kmp-library-0.0.1-add-coverage-scripts-SNAPSHOT.module",
    "group": "care.data4life.hc-gradle-scripts",
    "module": "example-kmp-library",
    "version": "0.0.1-add-coverage-scripts-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "nuz5hbtpyrfdxbzcbcsvbz7vkq"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "example-kmp-library.klib",
          "url": "example-kmp-library-iosarm64-0.0.1-add-coverage-scripts-SNAPSHOT.klib",
          "size": 15327,
          "sha512": "e1fcac234e1f11a76337da2f4ed5803900b88725224eee40e5a434d15f5c3a9f2102b6811e28b3992cb34ce247a2fda1b3265a38c14374a4202dfa357430567b",
          "sha256": "78c50aa489ca1fb6db516301dacaa22c6862f1801a5957d93aad5af537f1d824",
          "sha1": "58d6233facd2a36ef1937388ad3dbbbfbebda5aa",
          "md5": "b7597cc61422326f96ee0ecf01620d0d"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../example-kmp-library-metadata/0.0.1-add-coverage-scripts-SNAPSHOT/example-kmp-library-metadata-0.0.1-add-coverage-scripts-SNAPSHOT.module",
        "group": "care.data4life.hc-gradle-scripts",
        "module": "example-kmp-library-metadata",
        "version": "0.0.1-add-coverage-scripts-SNAPSHOT"
      }
    }
  ]
}
