{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.7.0-add-ios-branch-SNAPSHOT/util-1.7.0-add-ios-branch-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.7.0-add-ios-branch-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "l62zg4elmnfzpkuuhyftlofzuq"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "util.klib",
          "url": "util-iosarm64-1.7.0-add-ios-branch-SNAPSHOT.klib",
          "size": 24411,
          "sha512": "5758d975648f979e085416d067c31e9b95cc664526775d31bdb2a1d5af7914c10ec5acf8c7619653e62ff82824e58f49b211e7635e71abf1d9f5e21365b9fa9f",
          "sha256": "89ee9afb645ffadf0f8bf9868018fb70c2e8094c4804abb13d6a95505fdfb73e",
          "sha1": "3df80d6090c039283a3ef44d8291ef3cb8103e5b",
          "md5": "8582090c91b7b5d1c4a69a09a9fed81a"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-metadata/1.7.0-add-ios-branch-SNAPSHOT/util-metadata-1.7.0-add-ios-branch-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-metadata",
        "version": "1.7.0-add-ios-branch-SNAPSHOT"
      }
    }
  ]
}
