{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-test-jvm/1.8.1-add-coroutine-util-SNAPSHOT/util-test-jvm-1.8.1-add-coroutine-util-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-test-jvm",
    "version": "1.8.1-add-coroutine-util-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "3byk2twyijgtrh4bkxch45v7t4"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-test-metadata-1.8.1-add-coroutine-util-SNAPSHOT.jar",
          "url": "util-test-metadata-1.8.1-add-coroutine-util-SNAPSHOT.jar",
          "size": 4877,
          "sha512": "59ed5b70a6ce8671c18d214246198d0e9027b071459172634ef9947e0c0141029aa9b795be1e8fa1b034f9a3ead26af2e519f717905625a73b7699611bef0c3d",
          "sha256": "d4bd869588a03399df2ccb60788ca0b40f373cf013a2700f048b670afd345705",
          "sha1": "c5f90dbe86e9e29f10787027a00071aa6444f890",
          "md5": "e52b35c25dc0d3b28f7a8e1fcf103df3"
        }
      ]
    }
  ]
}
