{
  "formatVersion": "1.1",
  "component": {
    "url": "../../securestore/1.13.2-bump-updates-SNAPSHOT/securestore-1.13.2-bump-updates-SNAPSHOT.module",
    "group": "care.data4life.hc-securestore-sdk-kmp",
    "module": "securestore",
    "version": "1.13.2-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "securestore-jvm-1.13.2-bump-updates-SNAPSHOT.jar",
          "url": "securestore-jvm-1.13.2-bump-updates-SNAPSHOT.jar",
          "size": 16659,
          "sha512": "ded5e56ae8898ffe20d46ad4253b85cde04f606269aceee1078a1ced30084802f20e14fe72045c0b4f7ac804c8ad2ee1acca452c9d774b9fd6c08dc1beed9f1a",
          "sha256": "73a28edf498e1c8e61864c6e9f6610bba6396ded6e6aaee7e45eb98c5488eb6b",
          "sha1": "796208fbdbfa7604687d7c2bed55110dc9147ec1",
          "md5": "205b042a4d882f7900121540d6fcf314"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.13.2-bump-updates-SNAPSHOT.jar",
          "url": "securestore-jvm-1.13.2-bump-updates-SNAPSHOT.jar",
          "size": 16659,
          "sha512": "ded5e56ae8898ffe20d46ad4253b85cde04f606269aceee1078a1ced30084802f20e14fe72045c0b4f7ac804c8ad2ee1acca452c9d774b9fd6c08dc1beed9f1a",
          "sha256": "73a28edf498e1c8e61864c6e9f6610bba6396ded6e6aaee7e45eb98c5488eb6b",
          "sha1": "796208fbdbfa7604687d7c2bed55110dc9147ec1",
          "md5": "205b042a4d882f7900121540d6fcf314"
        }
      ]
    }
  ]
}
