{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-gradle-scripts",
    "module": "example-kmp-library",
    "version": "0.0.1-add-android-example-app-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "eqmjegv6h5byza6ybagpb4tvvu"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "example-kmp-library-metadata-0.0.1-add-android-example-app-SNAPSHOT.jar",
          "url": "example-kmp-library-0.0.1-add-android-example-app-SNAPSHOT.jar",
          "size": 6554,
          "sha512": "7b596d8bdf0801d9fd079f1c3399769ca4ac0cfe914bdcd621c0d0cb43d930620c8ad7f88b80156088e5a5bddb7573f8be1fb02d6337d5253be68cc45098cb79",
          "sha256": "7cae8146c8d757cac5609b732484f664bd9235e4e8b947691ddc3ed58f2c86ef",
          "sha1": "8f0c20b3994c55950904533576fa01ad34ceb26a",
          "md5": "b8f353ff37475c81c68a56b3fd9aa548"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../example-kmp-library-android/0.0.1-add-android-example-app-SNAPSHOT/example-kmp-library-android-0.0.1-add-android-example-app-SNAPSHOT.module",
        "group": "care.data4life",
        "module": "example-kmp-library-android",
        "version": "0.0.1-add-android-example-app-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../example-kmp-library-android/0.0.1-add-android-example-app-SNAPSHOT/example-kmp-library-android-0.0.1-add-android-example-app-SNAPSHOT.module",
        "group": "care.data4life",
        "module": "example-kmp-library-android",
        "version": "0.0.1-add-android-example-app-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../example-kmp-library-android/0.0.1-add-android-example-app-SNAPSHOT/example-kmp-library-android-0.0.1-add-android-example-app-SNAPSHOT.module",
        "group": "care.data4life.hc-gradle-scripts",
        "module": "example-kmp-library-android",
        "version": "0.0.1-add-android-example-app-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../example-kmp-library-android/0.0.1-add-android-example-app-SNAPSHOT/example-kmp-library-android-0.0.1-add-android-example-app-SNAPSHOT.module",
        "group": "care.data4life.hc-gradle-scripts",
        "module": "example-kmp-library-android",
        "version": "0.0.1-add-android-example-app-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../example-kmp-library-iosarm64/0.0.1-add-android-example-app-SNAPSHOT/example-kmp-library-iosarm64-0.0.1-add-android-example-app-SNAPSHOT.module",
        "group": "care.data4life",
        "module": "example-kmp-library-iosarm64",
        "version": "0.0.1-add-android-example-app-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../example-kmp-library-iosx64/0.0.1-add-android-example-app-SNAPSHOT/example-kmp-library-iosx64-0.0.1-add-android-example-app-SNAPSHOT.module",
        "group": "care.data4life",
        "module": "example-kmp-library-iosx64",
        "version": "0.0.1-add-android-example-app-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../example-kmp-library-jvm/0.0.1-add-android-example-app-SNAPSHOT/example-kmp-library-jvm-0.0.1-add-android-example-app-SNAPSHOT.module",
        "group": "care.data4life.hc-gradle-scripts",
        "module": "example-kmp-library-jvm",
        "version": "0.0.1-add-android-example-app-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../example-kmp-library-jvm/0.0.1-add-android-example-app-SNAPSHOT/example-kmp-library-jvm-0.0.1-add-android-example-app-SNAPSHOT.module",
        "group": "care.data4life.hc-gradle-scripts",
        "module": "example-kmp-library-jvm",
        "version": "0.0.1-add-android-example-app-SNAPSHOT"
      }
    }
  ]
}
