{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-test/1.8.1-change-util-test-SNAPSHOT/util-test-1.8.1-change-util-test-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-test",
    "version": "1.8.1-change-util-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "awtcvvijqnbcfgckt6ndkt2e5u"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "util-test-release.aar",
          "url": "util-test-android-1.8.1-change-util-test-SNAPSHOT.aar",
          "size": 11870,
          "sha512": "5dc26db740e82076948ecf124e8a232a5d9ecdd009d854f7b037041e9314a3c61ea550ac10f10123139e2bfc5b02af98505fd03555953f5e586dc6287f34f0ae",
          "sha256": "b31e8a762dda767ab91354d25928f9b0e07ae43967d20eb9f63ab72ffa6ed1c6",
          "sha1": "6129045e413b3cdd54f978e6e06423eff7984f20",
          "md5": "37f19517aaa57b5c0f8c5bfb1c3605dd"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "util-test-release.aar",
          "url": "util-test-android-1.8.1-change-util-test-SNAPSHOT.aar",
          "size": 11870,
          "sha512": "5dc26db740e82076948ecf124e8a232a5d9ecdd009d854f7b037041e9314a3c61ea550ac10f10123139e2bfc5b02af98505fd03555953f5e586dc6287f34f0ae",
          "sha256": "b31e8a762dda767ab91354d25928f9b0e07ae43967d20eb9f63ab72ffa6ed1c6",
          "sha1": "6129045e413b3cdd54f978e6e06423eff7984f20",
          "md5": "37f19517aaa57b5c0f8c5bfb1c3605dd"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-test-metadata/1.8.1-change-util-test-SNAPSHOT/util-test-metadata-1.8.1-change-util-test-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-test-metadata",
        "version": "1.8.1-change-util-test-SNAPSHOT"
      }
    }
  ]
}
