{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.13.0-bump-mockk-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "g4icepa36je35mn2qhw5aq7co4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.13.0-bump-mockk-SNAPSHOT.jar",
          "url": "crypto-common-1.13.0-bump-mockk-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "7f0de63a7a28ce27795288f827ccddc25434cce1d7925f7a86f22623744790f2afe631662b018211acef752cd368fbc15948d07518c350cc1c5a7a1fd9914cf5",
          "sha256": "9ea54c7699ab84fd830b849f6bffe194f726458707ddd0c3c0fc809f5e6c9a29",
          "sha1": "4a4512d6bc51066e29cf155aa05d1580b79b484e",
          "md5": "5d5eb254a06eede6a35a02534c4c0039"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.13.0-bump-mockk-SNAPSHOT.jar",
          "url": "crypto-common-1.13.0-bump-mockk-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "7f0de63a7a28ce27795288f827ccddc25434cce1d7925f7a86f22623744790f2afe631662b018211acef752cd368fbc15948d07518c350cc1c5a7a1fd9914cf5",
          "sha256": "9ea54c7699ab84fd830b849f6bffe194f726458707ddd0c3c0fc809f5e6c9a29",
          "sha1": "4a4512d6bc51066e29cf155aa05d1580b79b484e",
          "md5": "5d5eb254a06eede6a35a02534c4c0039"
        }
      ]
    }
  ]
}
