{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.10.0-change-securestore-to-external-dependency-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "oy2w2fmtvvf2pc7s4lcgbnq2i4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-change-securestore-to-external-dependency-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.10.0-change-securestore-to-external-dependency-SNAPSHOT.jar",
          "url": "auth-jvm-1.10.0-change-securestore-to-external-dependency-SNAPSHOT.jar",
          "size": 34319,
          "sha512": "9d1ab4392a99b5c8f783ba9e5d4da6dd65bdc0abecff988697a5c97236eaaaf9d11252689a3eb277db620ed4c495590fd1d2b645782cf70eadf59d757a047d8a",
          "sha256": "69964de015472fb0e6c08cef841edb49dac2bc15f04ae5126ac49c3ed170889b",
          "sha1": "66768c5b8b8902714204f7699375159c5552c9b1",
          "md5": "05c38b5cc7c9eda99f3532c11aaffb0b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-securestore-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "0.0.1-add-securestore-implementation-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-change-securestore-to-external-dependency-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.10.0-change-securestore-to-external-dependency-SNAPSHOT.jar",
          "url": "auth-jvm-1.10.0-change-securestore-to-external-dependency-SNAPSHOT.jar",
          "size": 34319,
          "sha512": "9d1ab4392a99b5c8f783ba9e5d4da6dd65bdc0abecff988697a5c97236eaaaf9d11252689a3eb277db620ed4c495590fd1d2b645782cf70eadf59d757a047d8a",
          "sha256": "69964de015472fb0e6c08cef841edb49dac2bc15f04ae5126ac49c3ed170889b",
          "sha1": "66768c5b8b8902714204f7699375159c5552c9b1",
          "md5": "05c38b5cc7c9eda99f3532c11aaffb0b"
        }
      ]
    }
  ]
}
