{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.13.1-change-attachment-service-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "d3won7mtbbgopomqomu27sdq6q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.13.1-change-attachment-service-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.13.1-change-attachment-service-tests-SNAPSHOT.jar",
          "url": "auth-jvm-1.13.1-change-attachment-service-tests-SNAPSHOT.jar",
          "size": 34319,
          "sha512": "93f2ea6f8fecc0b4e4dc6ce0e1f6fae0d6e786c8ffd483b0a641967ff6b6f492b6601e8ea87ef0f306628b66b307312bb934cc56b8be5ffdb5eb3b529d22f9a9",
          "sha256": "1a1bcbcf92f5d723f6ac0024eaa6926708af701f71aa3bfa0f5e78726d787569",
          "sha1": "0493879a7a386cfbc38270f744dba4e4a86dd4e0",
          "md5": "840d061df800f35651deb18ea6a6f1b6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.13.1-change-attachment-service-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.13.1-change-attachment-service-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.13.1-change-attachment-service-tests-SNAPSHOT.jar",
          "url": "auth-jvm-1.13.1-change-attachment-service-tests-SNAPSHOT.jar",
          "size": 34319,
          "sha512": "93f2ea6f8fecc0b4e4dc6ce0e1f6fae0d6e786c8ffd483b0a641967ff6b6f492b6601e8ea87ef0f306628b66b307312bb934cc56b8be5ffdb5eb3b529d22f9a9",
          "sha256": "1a1bcbcf92f5d723f6ac0024eaa6926708af701f71aa3bfa0f5e78726d787569",
          "sha1": "0493879a7a386cfbc38270f744dba4e4a86dd4e0",
          "md5": "840d061df800f35651deb18ea6a6f1b6"
        }
      ]
    }
  ]
}
