{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-crypto-sdk-kmp",
    "module": "crypto",
    "version": "1.13.2-change-to-latest-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "gp75bvaecbgszh4u5j3gwgfhcm"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "crypto-metadata-1.13.2-change-to-latest-setup-SNAPSHOT.jar",
          "url": "crypto-1.13.2-change-to-latest-setup-SNAPSHOT.jar",
          "size": 12471,
          "sha512": "312e5a1c1fd295bc2ac8103e83269199034babb31db591d98837a24967f0191e92c8b7c4508ca6e760db0275f98ba93462bd98eafff8ebd4acd61cc36f8e8a6c",
          "sha256": "3d5008638123595daf0a2288a6a8861f2761e547cf833aeb8469034b199d38f0",
          "sha1": "46e1e27a37383d17747837da4ac8cd492f89e146",
          "md5": "008c0f72bb9ccd254a444376c944c961"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../crypto-android-debug/1.13.2-change-to-latest-setup-SNAPSHOT/crypto-android-debug-1.13.2-change-to-latest-setup-SNAPSHOT.module",
        "group": "care.data4life.hc-crypto-sdk-kmp",
        "module": "crypto-android-debug",
        "version": "1.13.2-change-to-latest-setup-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../crypto-android-debug/1.13.2-change-to-latest-setup-SNAPSHOT/crypto-android-debug-1.13.2-change-to-latest-setup-SNAPSHOT.module",
        "group": "care.data4life.hc-crypto-sdk-kmp",
        "module": "crypto-android-debug",
        "version": "1.13.2-change-to-latest-setup-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../crypto-android/1.13.2-change-to-latest-setup-SNAPSHOT/crypto-android-1.13.2-change-to-latest-setup-SNAPSHOT.module",
        "group": "care.data4life.hc-crypto-sdk-kmp",
        "module": "crypto-android",
        "version": "1.13.2-change-to-latest-setup-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../crypto-android/1.13.2-change-to-latest-setup-SNAPSHOT/crypto-android-1.13.2-change-to-latest-setup-SNAPSHOT.module",
        "group": "care.data4life.hc-crypto-sdk-kmp",
        "module": "crypto-android",
        "version": "1.13.2-change-to-latest-setup-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../crypto-jvm/1.13.2-change-to-latest-setup-SNAPSHOT/crypto-jvm-1.13.2-change-to-latest-setup-SNAPSHOT.module",
        "group": "care.data4life.hc-crypto-sdk-kmp",
        "module": "crypto-jvm",
        "version": "1.13.2-change-to-latest-setup-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../crypto-jvm/1.13.2-change-to-latest-setup-SNAPSHOT/crypto-jvm-1.13.2-change-to-latest-setup-SNAPSHOT.module",
        "group": "care.data4life.hc-crypto-sdk-kmp",
        "module": "crypto-jvm",
        "version": "1.13.2-change-to-latest-setup-SNAPSHOT"
      }
    }
  ]
}
