{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir-stu3/0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT/fhir-stu3-0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir-stu3",
    "version": "0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-kmp",
          "module": "fhir",
          "version": {
            "requires": "0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-stu3-jvm-0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT.jar",
          "url": "fhir-stu3-jvm-0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT.jar",
          "size": 6595112,
          "sha512": "6114f425f973bc55cf3a02d0609acc40e2b7b2b4177dabc62b88d1467624032b4dfcc1efa8ab50f3019bd8df51b9772c3e9ecf9c84798615c8b3218221e31746",
          "sha256": "f09409f95767a7c44093f804296e785c6d2c9087d8d04413abeea3fc35c37730",
          "sha1": "1e47ca31f0268a7574765b6f2a142aeac4273fd6",
          "md5": "123cac6c04396e44e23a9cba79f0015a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-kmp",
          "module": "fhir",
          "version": {
            "requires": "0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-stu3-jvm-0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT.jar",
          "url": "fhir-stu3-jvm-0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT.jar",
          "size": 6595112,
          "sha512": "6114f425f973bc55cf3a02d0609acc40e2b7b2b4177dabc62b88d1467624032b4dfcc1efa8ab50f3019bd8df51b9772c3e9ecf9c84798615c8b3218221e31746",
          "sha256": "f09409f95767a7c44093f804296e785c6d2c9087d8d04413abeea3fc35c37730",
          "sha1": "1e47ca31f0268a7574765b6f2a142aeac4273fd6",
          "md5": "123cac6c04396e44e23a9cba79f0015a"
        }
      ]
    }
  ]
}
