{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-jvm",
    "version": "1.12.0-change-merge-fhir-and-data-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "db2gmtahhrenrjyvqwkzusgqje"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.12.0-change-merge-fhir-and-data-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.12.0-change-merge-fhir-and-data-SNAPSHOT.jar",
          "url": "sdk-jvm-1.12.0-change-merge-fhir-and-data-SNAPSHOT.jar",
          "size": 11648,
          "sha512": "842c81b2d2b5945092dde591d6467f76d427f908a1eb8aece998e73e2d60c96c9ca09d590d14c8afe24016bcf40159830e5ad832d560e63e8d672c744b802ab0",
          "sha256": "26dc365d54624a7fe706072845b06839a3ad2ce967a6cc70abf5b876e74de6e5",
          "sha1": "d950f35861555a068d486e29db8fab3cbcddb403",
          "md5": "24dfbe758fcce7801b2a759dba384b62"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.12.0-change-merge-fhir-and-data-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.12.0-change-merge-fhir-and-data-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.12.0-change-merge-fhir-and-data-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.12.0-change-merge-fhir-and-data-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.12.0-change-merge-fhir-and-data-SNAPSHOT.jar",
          "url": "sdk-jvm-1.12.0-change-merge-fhir-and-data-SNAPSHOT.jar",
          "size": 11648,
          "sha512": "842c81b2d2b5945092dde591d6467f76d427f908a1eb8aece998e73e2d60c96c9ca09d590d14c8afe24016bcf40159830e5ad832d560e63e8d672c744b802ab0",
          "sha256": "26dc365d54624a7fe706072845b06839a3ad2ce967a6cc70abf5b876e74de6e5",
          "sha1": "d950f35861555a068d486e29db8fab3cbcddb403",
          "md5": "24dfbe758fcce7801b2a759dba384b62"
        }
      ]
    }
  ]
}
