{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util/0.2.0-bump-updates-SNAPSHOT/test-util-0.2.0-bump-updates-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util",
    "version": "0.2.0-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-util-jvm-0.2.0-bump-updates-SNAPSHOT.jar",
          "url": "test-util-jvm-0.2.0-bump-updates-SNAPSHOT.jar",
          "size": 12792,
          "sha512": "e5834551b072bec32864a8154dd2f21331fa84e67670541c3051cbb4a4c1e9a6ea91db41060c272bef5122623f26de1dfccb9187e07cf3acc7873323f2ccf4c5",
          "sha256": "11e388d697a47f1d8ff461e0b8ac1166101cad0626a33a24d4f4ebbfbea73644",
          "sha1": "b856f58ae6c30822bc53155946bd74924e3a1024",
          "md5": "0a90a2f2820cec2e707d04a9b2e5b867"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-jvm-0.2.0-bump-updates-SNAPSHOT.jar",
          "url": "test-util-jvm-0.2.0-bump-updates-SNAPSHOT.jar",
          "size": 12792,
          "sha512": "e5834551b072bec32864a8154dd2f21331fa84e67670541c3051cbb4a4c1e9a6ea91db41060c272bef5122623f26de1dfccb9187e07cf3acc7873323f2ccf4c5",
          "sha256": "11e388d697a47f1d8ff461e0b8ac1166101cad0626a33a24d4f4ebbfbea73644",
          "sha1": "b856f58ae6c30822bc53155946bd74924e3a1024",
          "md5": "0a90a2f2820cec2e707d04a9b2e5b867"
        }
      ]
    }
  ]
}
