{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-android",
    "version": "1.11.0-bump-okhttp-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "gpnkc7p7ebeeffqavho5h7k5ju"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-bump-okhttp-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.11.0-bump-okhttp-SNAPSHOT.aar",
          "url": "crypto-android-1.11.0-bump-okhttp-SNAPSHOT.aar",
          "size": 61898,
          "sha512": "66bed7bd58e08e235f89c2fbe5df553ebbbad195b9b788f06a014b63d9c844fcfe737010912f4f615883b79ff9f175f009243f5687203d83f738fbc4de34e42e",
          "sha256": "256064018e2543df7940cbc1feeb80cf21529cf70b1b97872abb7151ed4265bc",
          "sha1": "1cb1041fbed4412ebbf220f5924706f51200e194",
          "md5": "a8ca90c6b5477849a290c4106ccb4d04"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-bump-okhttp-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.11.0-bump-okhttp-SNAPSHOT.aar",
          "url": "crypto-android-1.11.0-bump-okhttp-SNAPSHOT.aar",
          "size": 61898,
          "sha512": "66bed7bd58e08e235f89c2fbe5df553ebbbad195b9b788f06a014b63d9c844fcfe737010912f4f615883b79ff9f175f009243f5687203d83f738fbc4de34e42e",
          "sha256": "256064018e2543df7940cbc1feeb80cf21529cf70b1b97872abb7151ed4265bc",
          "sha1": "1cb1041fbed4412ebbf220f5924706f51200e194",
          "md5": "a8ca90c6b5477849a290c4106ccb4d04"
        }
      ]
    }
  ]
}
