{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.11.0-add-client-factory-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ktklzn34pbfwdeknp3gip6zgia"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-add-client-factory-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.11.0-add-client-factory-SNAPSHOT.jar",
          "url": "crypto-jvm-1.11.0-add-client-factory-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "8cf33184aec6e4a06cd76bdde5d72f8ecad49698483330d598df2999f6d8597d1b17708485c8536f0906b1c3788cae21cc558a69d65fe2b80d4e5ac80a27e1b1",
          "sha256": "4b031e3665e99407a89e736b88095ae71fa67e1772ad5e112b8a641057ed363a",
          "sha1": "acf090d95addaeed560f7ea697ceee7e653d7b4e",
          "md5": "2159be7c19b267e7832ec4f31d8e4ec3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-add-client-factory-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.11.0-add-client-factory-SNAPSHOT.jar",
          "url": "crypto-jvm-1.11.0-add-client-factory-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "8cf33184aec6e4a06cd76bdde5d72f8ecad49698483330d598df2999f6d8597d1b17708485c8536f0906b1c3788cae21cc558a69d65fe2b80d4e5ac80a27e1b1",
          "sha256": "4b031e3665e99407a89e736b88095ae71fa67e1772ad5e112b8a641057ed363a",
          "sha1": "acf090d95addaeed560f7ea697ceee7e653d7b4e",
          "md5": "2159be7c19b267e7832ec4f31d8e4ec3"
        }
      ]
    }
  ]
}
