{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-core",
    "version": "1.14.0-change-readme-badges-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "4ddlzw6aovhffaigdkgrto6qfa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.14.0-change-readme-badges-SNAPSHOT.jar",
          "url": "sdk-core-1.14.0-change-readme-badges-SNAPSHOT.jar",
          "size": 576091,
          "sha512": "a322b4e74b4f3730010d0d9537548ce676745bfdfafa55700b354419dc8b4fce32ab2b14ef99b92240575db11fcc6516e00485eca4198375973b5f780e1927ea",
          "sha256": "c32f08b517ba53f86cc4575d4aeaaa06d27b971372675e002332d6a592cf0812",
          "sha1": "18418a5be6f2b9a7f4f2493404e05ffd41fb44ba",
          "md5": "6d96e8b809b96210213e17d7c78eb9fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.14.0-change-readme-badges-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.14.0-change-readme-badges-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.14.0-change-readme-badges-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.14.0-change-readme-badges-SNAPSHOT.jar",
          "url": "sdk-core-1.14.0-change-readme-badges-SNAPSHOT.jar",
          "size": 576091,
          "sha512": "a322b4e74b4f3730010d0d9537548ce676745bfdfafa55700b354419dc8b4fce32ab2b14ef99b92240575db11fcc6516e00485eca4198375973b5f780e1927ea",
          "sha256": "c32f08b517ba53f86cc4575d4aeaaa06d27b971372675e002332d6a592cf0812",
          "sha1": "18418a5be6f2b9a7f4f2493404e05ffd41fb44ba",
          "md5": "6d96e8b809b96210213e17d7c78eb9fc"
        }
      ]
    }
  ]
}
