{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk",
    "version": "0.1.3-add-resource-validator-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "guiswlu3fvfmji3v63f3gjykqy"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.3-add-resource-validator-SNAPSHOT.jar",
          "url": "data-donation-sdk-0.1.3-add-resource-validator-SNAPSHOT.jar",
          "size": 77019,
          "sha512": "e3a5c5ef99a44d5070634cb83a3e714c877f09498ce292705f0c507c005d3a72115d4b77554dceacba12ca75070510854b9bd57140a5c87e1152e0097370ad98",
          "sha256": "80da8fcf13ed76b80fb6ec421bd478bcef493ae6862e7c623f4f49f2f9653e86",
          "sha1": "b23867e6eb7edadf247d5fc7a2ec43d2289ba26f",
          "md5": "d1a7ef3dc6b5c3d395bfa42700b5a854"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android-debug/0.1.3-add-resource-validator-SNAPSHOT/data-donation-sdk-android-debug-0.1.3-add-resource-validator-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android-debug",
        "version": "0.1.3-add-resource-validator-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android-debug/0.1.3-add-resource-validator-SNAPSHOT/data-donation-sdk-android-debug-0.1.3-add-resource-validator-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android-debug",
        "version": "0.1.3-add-resource-validator-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android/0.1.3-add-resource-validator-SNAPSHOT/data-donation-sdk-android-0.1.3-add-resource-validator-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android",
        "version": "0.1.3-add-resource-validator-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android/0.1.3-add-resource-validator-SNAPSHOT/data-donation-sdk-android-0.1.3-add-resource-validator-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android",
        "version": "0.1.3-add-resource-validator-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../data-donation-sdk-iosarm64/0.1.3-add-resource-validator-SNAPSHOT/data-donation-sdk-iosarm64-0.1.3-add-resource-validator-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-iosarm64",
        "version": "0.1.3-add-resource-validator-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../data-donation-sdk-iosx64/0.1.3-add-resource-validator-SNAPSHOT/data-donation-sdk-iosx64-0.1.3-add-resource-validator-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-iosx64",
        "version": "0.1.3-add-resource-validator-SNAPSHOT"
      }
    }
  ]
}
