{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.12.0-add-auth-client-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "mcix2dz25bdtvpnb4jljkshbqq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.12.0-add-auth-client-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.12.0-add-auth-client-tests-SNAPSHOT.jar",
          "url": "securestore-jvm-1.12.0-add-auth-client-tests-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "751d942631a1a37cf4a4ca0f8f6000d2ae95d1efbc9aab5fb710ee0bcab6b6d0527d37edd1a8a3c3b9ed5019e13280e4d97673d420b0c9c340761e20ca24afa0",
          "sha256": "b4e510f64264fdc3bb92f07f2ca6f2238520250e5b77103881fb607c42071cae",
          "sha1": "2c07f736072b47cadeed083c7ca388a8cb584452",
          "md5": "60f9593100ca3c3c8ce1f2d5caf4c428"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.12.0-add-auth-client-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.12.0-add-auth-client-tests-SNAPSHOT.jar",
          "url": "securestore-jvm-1.12.0-add-auth-client-tests-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "751d942631a1a37cf4a4ca0f8f6000d2ae95d1efbc9aab5fb710ee0bcab6b6d0527d37edd1a8a3c3b9ed5019e13280e4d97673d420b0c9c340761e20ca24afa0",
          "sha256": "b4e510f64264fdc3bb92f07f2ca6f2238520250e5b77103881fb607c42071cae",
          "sha1": "2c07f736072b47cadeed083c7ca388a8cb584452",
          "md5": "60f9593100ca3c3c8ce1f2d5caf4c428"
        }
      ]
    }
  ]
}
