{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.0.3-change-root-module-SNAPSHOT/data-donation-sdk-iosx64-0.0.3-change-root-module-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.0.3-change-root-module-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "5qvgxlw6inghjn5hcehiyoxhum"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.3-change-root-module-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.0.3-change-root-module-SNAPSHOT.jar",
          "size": 70015,
          "sha512": "7b950df026f77bc076468934e4f3002e35ce6a5b9f9ed4a48241d44ede11571e3a61df1c9b33b18cd1c980b9f4459ce762f9159f922a41813420b8ff226a2692",
          "sha256": "c5880787932b306f93aa457639419c37170eca847981f2bd00e5fd380ea888ad",
          "sha1": "0ae7522b2f617d6d3292338f467ea411946f7289",
          "md5": "014758f0deed2a8923f23125e325c650"
        }
      ]
    }
  ]
}
