{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.11.0-change-compatibility-service-unblocking-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "qkq54fvcifdwtbpx4m4vjkcnm4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.11.0-change-compatibility-service-unblocking-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-change-compatibility-service-unblocking-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "f3f0ddefb7ac95074e842e415b4456c13fd7094648b4a2397b1df9f26fa6d394347ebd3da6492c553341a77b10bc4f52b989a14fb84a690efabcd46ec8876549",
          "sha256": "5158d8a0f667aca0b0b102792d2f8b435d18a54d56a0e3d89043b369c7e8ffbd",
          "sha1": "86700e41a04e8bf0bbb4bba212097539dd3ebecb",
          "md5": "e5b8a4fa25dbc7f2981f05ec576b35f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.11.0-change-compatibility-service-unblocking-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-change-compatibility-service-unblocking-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "f3f0ddefb7ac95074e842e415b4456c13fd7094648b4a2397b1df9f26fa6d394347ebd3da6492c553341a77b10bc4f52b989a14fb84a690efabcd46ec8876549",
          "sha256": "5158d8a0f667aca0b0b102792d2f8b435d18a54d56a0e3d89043b369c7e8ffbd",
          "sha1": "86700e41a04e8bf0bbb4bba212097539dd3ebecb",
          "md5": "e5b8a4fa25dbc7f2981f05ec576b35f2"
        }
      ]
    }
  ]
}
