{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.0.4-add-payload-tests-SNAPSHOT/data-donation-sdk-iosx64-0.0.4-add-payload-tests-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.0.4-add-payload-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "6avcvlhj2rcgdhye2inhqdn6a4"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.4-add-payload-tests-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.0.4-add-payload-tests-SNAPSHOT.jar",
          "size": 73678,
          "sha512": "8fb772a6c2cd049a604716b5f76bb8730cd03ca139132f9c7e02e9caf52db2213cee9bfa29b9b0c84b0145f07c32f179d7cb97973fcfa2934fb997087ac52f73",
          "sha256": "6f7b15627db8d5ca55ec06e838ae436f3b4c772bb3ee8d2c00d8a905436d2ad2",
          "sha1": "57025a30dfab5c6fb454539b621078e61af99f3e",
          "md5": "b2ba3c9c24afef5010a0b7f895244fde"
        }
      ]
    }
  ]
}
