{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.12.0-bump-fhir-java-sdk-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "mva6kdav5zc2hl2l4n3zguil34"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.12.0-bump-fhir-java-sdk-SNAPSHOT.jar",
          "url": "crypto-common-1.12.0-bump-fhir-java-sdk-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "8fe189146cc5883bcafd9d39e806453e7e4d076fcf184de4009d858c792142157db5753a556d897790022a985b00d6bb120cb6571e630fe73c04c837380b26df",
          "sha256": "7e3165b1a540f778ef0954f6bf358ad65a8216067be5e7a1ce362193481e0430",
          "sha1": "6155831dc666f11f36464d9c93359fda3429c785",
          "md5": "0dfb229891c96d1783955398033c7925"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.12.0-bump-fhir-java-sdk-SNAPSHOT.jar",
          "url": "crypto-common-1.12.0-bump-fhir-java-sdk-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "8fe189146cc5883bcafd9d39e806453e7e4d076fcf184de4009d858c792142157db5753a556d897790022a985b00d6bb120cb6571e630fe73c04c837380b26df",
          "sha256": "7e3165b1a540f778ef0954f6bf358ad65a8216067be5e7a1ce362193481e0430",
          "sha1": "6155831dc666f11f36464d9c93359fda3429c785",
          "md5": "0dfb229891c96d1783955398033c7925"
        }
      ]
    }
  ]
}
