{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-test/1.7.0-add-coroutine-test-util-SNAPSHOT/util-test-1.7.0-add-coroutine-test-util-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-test",
    "version": "1.7.0-add-coroutine-test-util-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "uncqhpeobnfu5bdk7mtmijsk7m"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.4.3-native-mt",
            "requires": "1.4.3-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "util-test.klib",
          "url": "util-test-iosx64-1.7.0-add-coroutine-test-util-SNAPSHOT.klib",
          "size": 6603,
          "sha512": "ee2fa5b011e0d3d81b0b0098a2a980e2ac0ecb1210c29911d759aa17109ff805445ffa806848408002ab8f8265ade6e453cf42375937ac3c3c87cc812c7385b4",
          "sha256": "db1843e2a95795b809bb3a7b67b3a9cbd0262a4a5bcd602e41f62009458b63e6",
          "sha1": "2af55cdd6682fe21f68ef1b8c908556a0af11158",
          "md5": "91785f180f22e005ecd8503a5a66a4f3"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-test-metadata/1.7.0-add-coroutine-test-util-SNAPSHOT/util-test-metadata-1.7.0-add-coroutine-test-util-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-test-metadata",
        "version": "1.7.0-add-coroutine-test-util-SNAPSHOT"
      }
    }
  ]
}
