{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk",
    "version": "0.1.3-add-time-bluring-questionaireresponse-authored-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "uvrsfy4byfgrzgdfrvp3gyqirq"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.3-add-time-bluring-questionaireresponse-authored-SNAPSHOT.jar",
          "url": "data-donation-sdk-0.1.3-add-time-bluring-questionaireresponse-authored-SNAPSHOT.jar",
          "size": 63597,
          "sha512": "1ad0bf8a56ac6955425df3675cb12c4d6ba8c3d0f991cced75ef3f5ff7c657dd71a93d9cd8f1cc3eec3d2d0380de3f7be4bfa1a53dac83af71c991a2df8dac05",
          "sha256": "3bd9548b71822ef05463426dea7b7620896cc584afd4a273e89cc3c005c51206",
          "sha1": "f5c26fd55a94bcdc1fabb2278e2843e5f57633bc",
          "md5": "205fea64cab83a20698490500d9f6ac8"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android-debug/0.1.3-add-time-bluring-questionaireresponse-authored-SNAPSHOT/data-donation-sdk-android-debug-0.1.3-add-time-bluring-questionaireresponse-authored-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android-debug",
        "version": "0.1.3-add-time-bluring-questionaireresponse-authored-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android-debug/0.1.3-add-time-bluring-questionaireresponse-authored-SNAPSHOT/data-donation-sdk-android-debug-0.1.3-add-time-bluring-questionaireresponse-authored-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android-debug",
        "version": "0.1.3-add-time-bluring-questionaireresponse-authored-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android/0.1.3-add-time-bluring-questionaireresponse-authored-SNAPSHOT/data-donation-sdk-android-0.1.3-add-time-bluring-questionaireresponse-authored-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android",
        "version": "0.1.3-add-time-bluring-questionaireresponse-authored-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android/0.1.3-add-time-bluring-questionaireresponse-authored-SNAPSHOT/data-donation-sdk-android-0.1.3-add-time-bluring-questionaireresponse-authored-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android",
        "version": "0.1.3-add-time-bluring-questionaireresponse-authored-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../data-donation-sdk-iosarm64/0.1.3-add-time-bluring-questionaireresponse-authored-SNAPSHOT/data-donation-sdk-iosarm64-0.1.3-add-time-bluring-questionaireresponse-authored-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-iosarm64",
        "version": "0.1.3-add-time-bluring-questionaireresponse-authored-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../data-donation-sdk-iosx64/0.1.3-add-time-bluring-questionaireresponse-authored-SNAPSHOT/data-donation-sdk-iosx64-0.1.3-add-time-bluring-questionaireresponse-authored-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-iosx64",
        "version": "0.1.3-add-time-bluring-questionaireresponse-authored-SNAPSHOT"
      }
    }
  ]
}
