{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk",
    "version": "0.1.3-add-time-bluring-research-subject-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "umteaxdqknfatio4zbuwe557yq"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.3-add-time-bluring-research-subject-SNAPSHOT.jar",
          "url": "data-donation-sdk-0.1.3-add-time-bluring-research-subject-SNAPSHOT.jar",
          "size": 55746,
          "sha512": "9a4fb1bb30ee3aab32786e5ca9f00ed96a89d5428a83c3e43ead990822c82f81cbf64b8389bd8e82424912a5281d44c6870771deb983a105d8cdaf2e70230df1",
          "sha256": "95f75886f3236bd13a2938e8fdc81553ae4e254551509c932933e7e91871608d",
          "sha1": "2066a85f653b9e3e2234eb93a5619292f734700f",
          "md5": "cce9a9dc2b04e91cada185d2d6fa1035"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android-debug/0.1.3-add-time-bluring-research-subject-SNAPSHOT/data-donation-sdk-android-debug-0.1.3-add-time-bluring-research-subject-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android-debug",
        "version": "0.1.3-add-time-bluring-research-subject-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android-debug/0.1.3-add-time-bluring-research-subject-SNAPSHOT/data-donation-sdk-android-debug-0.1.3-add-time-bluring-research-subject-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android-debug",
        "version": "0.1.3-add-time-bluring-research-subject-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android/0.1.3-add-time-bluring-research-subject-SNAPSHOT/data-donation-sdk-android-0.1.3-add-time-bluring-research-subject-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android",
        "version": "0.1.3-add-time-bluring-research-subject-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android/0.1.3-add-time-bluring-research-subject-SNAPSHOT/data-donation-sdk-android-0.1.3-add-time-bluring-research-subject-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android",
        "version": "0.1.3-add-time-bluring-research-subject-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../data-donation-sdk-iosarm64/0.1.3-add-time-bluring-research-subject-SNAPSHOT/data-donation-sdk-iosarm64-0.1.3-add-time-bluring-research-subject-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-iosarm64",
        "version": "0.1.3-add-time-bluring-research-subject-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../data-donation-sdk-iosx64/0.1.3-add-time-bluring-research-subject-SNAPSHOT/data-donation-sdk-iosx64-0.1.3-add-time-bluring-research-subject-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-iosx64",
        "version": "0.1.3-add-time-bluring-research-subject-SNAPSHOT"
      }
    }
  ]
}
