{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-coroutine-test",
    "version": "1.9.0-add-default-scope-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "2xarvvrfhrgnbbv6sjw2f2mcti"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-coroutine-test-metadata-1.9.0-add-default-scope-SNAPSHOT.jar",
          "url": "util-coroutine-test-1.9.0-add-default-scope-SNAPSHOT.jar",
          "size": 1777,
          "sha512": "61c3eab5eb3d19703c1fdd37f30a0cd6e03c65e66ffe493e30b223e20a501ae5e86ad5606874bf862727c6c126200f3c504db3d4e425379f1632f689bdbe4d34",
          "sha256": "95771cb9d463e745a69c37b121bff754c14e7a94f344de7f2f8a472bbca649d5",
          "sha1": "de2412f45d0436045cf816c8f2dda5b46baa6a2f",
          "md5": "e2cfd2f902b7f283bc42b2d74dc9b181"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../util-coroutine-test-android-debug/1.9.0-add-default-scope-SNAPSHOT/util-coroutine-test-android-debug-1.9.0-add-default-scope-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-coroutine-test-android-debug",
        "version": "1.9.0-add-default-scope-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../util-coroutine-test-android-debug/1.9.0-add-default-scope-SNAPSHOT/util-coroutine-test-android-debug-1.9.0-add-default-scope-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-coroutine-test-android-debug",
        "version": "1.9.0-add-default-scope-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../util-coroutine-test-android/1.9.0-add-default-scope-SNAPSHOT/util-coroutine-test-android-1.9.0-add-default-scope-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-coroutine-test-android",
        "version": "1.9.0-add-default-scope-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../util-coroutine-test-android/1.9.0-add-default-scope-SNAPSHOT/util-coroutine-test-android-1.9.0-add-default-scope-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-coroutine-test-android",
        "version": "1.9.0-add-default-scope-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../util-coroutine-test-iosarm64/1.9.0-add-default-scope-SNAPSHOT/util-coroutine-test-iosarm64-1.9.0-add-default-scope-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-coroutine-test-iosarm64",
        "version": "1.9.0-add-default-scope-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../util-coroutine-test-iosx64/1.9.0-add-default-scope-SNAPSHOT/util-coroutine-test-iosx64-1.9.0-add-default-scope-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-coroutine-test-iosx64",
        "version": "1.9.0-add-default-scope-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../util-coroutine-test-jvm/1.9.0-add-default-scope-SNAPSHOT/util-coroutine-test-jvm-1.9.0-add-default-scope-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-coroutine-test-jvm",
        "version": "1.9.0-add-default-scope-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../util-coroutine-test-jvm/1.9.0-add-default-scope-SNAPSHOT/util-coroutine-test-jvm-1.9.0-add-default-scope-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-coroutine-test-jvm",
        "version": "1.9.0-add-default-scope-SNAPSHOT"
      }
    }
  ]
}
