{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.12.0-change-user-service-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "mu5b7nen4zafxg3f7dh2ahj6be"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.12.0-change-user-service-tests-SNAPSHOT.jar",
          "url": "securestore-common-1.12.0-change-user-service-tests-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "ee4c265e9a13599a1a5ed69a21f807fc104fc72623300855e20736c741abe26e818f57c679c98f01783895bc534e8d88392ea00b5fe1e0fc1a50872d979dba70",
          "sha256": "7425a6fe6d61b9e93eb9177845abbfd481d44c12a41c7dda4338ed5574180f30",
          "sha1": "bbeed2b6b9b4f97c8fb417d9ccbf5313988711a7",
          "md5": "6991169dc8f7b88cbb5537f5aac26a12"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.12.0-change-user-service-tests-SNAPSHOT.jar",
          "url": "securestore-common-1.12.0-change-user-service-tests-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "ee4c265e9a13599a1a5ed69a21f807fc104fc72623300855e20736c741abe26e818f57c679c98f01783895bc534e8d88392ea00b5fe1e0fc1a50872d979dba70",
          "sha256": "7425a6fe6d61b9e93eb9177845abbfd481d44c12a41c7dda4338ed5574180f30",
          "sha1": "bbeed2b6b9b4f97c8fb417d9ccbf5313988711a7",
          "md5": "6991169dc8f7b88cbb5537f5aac26a12"
        }
      ]
    }
  ]
}
