{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk/0.0.4-remove-local-env-SNAPSHOT/data-donation-sdk-0.0.4-remove-local-env-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk",
    "version": "0.0.4-remove-local-env-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "6tsh2nkg25gavfg4qgwpf4fnby"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-kmp",
          "module": "fhir",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.4.3-native-mt",
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-ios",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "data-donation-sdk.klib",
          "url": "data-donation-sdk-iosarm64-0.0.4-remove-local-env-SNAPSHOT.klib",
          "size": 216374,
          "sha512": "3444cbde6370a16176c0f582b2522bd1da05551dcd244b5ce4aca74de964742efd7fdb17d54518eac179c01e12dfbab3546e978483eff44609da9be3ac2111de",
          "sha256": "010e252d58f9b1aab61250d2a7be93792be575e94cc62f43cc128b50e691f260",
          "sha1": "9f4e212df981a038389742eb1b037b17d7e608c9",
          "md5": "fdf9b6ae0eef183e96245a49fe78be9e"
        },
        {
          "name": "data-donation-sdk-cinterop-iOSCryptoDD.klib",
          "url": "data-donation-sdk-iosarm64-0.0.4-remove-local-env-SNAPSHOT-cinterop-iOSCryptoDD.klib",
          "size": 4269780,
          "sha512": "2f4ce087f4bf3709a7eb689f631ac8c6b36a87987f981cf8b70d478f1382176d4e0c3ac4c02c0b7db3f6fa499177badbabca6a9d01187bf94b11475be9c770be",
          "sha256": "0c6dafd5eb2fb017c94f79c17f855186314b386d00a27546f153367d8bb4d3f1",
          "sha1": "8e6e48d5534d64b65831539a44d834ab15fce0c1",
          "md5": "f29177b1d5cdaa03b78ce5253a3e8a73"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../data-donation-sdk-metadata/0.0.4-remove-local-env-SNAPSHOT/data-donation-sdk-metadata-0.0.4-remove-local-env-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-metadata",
        "version": "0.0.4-remove-local-env-SNAPSHOT"
      }
    }
  ]
}
