{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.10.0-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "util-metadata-1.10.0-bump-updates-SNAPSHOT-all.jar",
          "url": "util-1.10.0-bump-updates-SNAPSHOT-all.jar",
          "size": 6369,
          "sha512": "ea71b27a66dd72df95836cb8ae65cbf625c44a1d7fb8a3030b9ef9a3464f4b0de832efe6ac56253ebce90ec1ba549f81629ca6ac360ef3093fdb92eddf48d7e9",
          "sha256": "9263aa827ec5209106e34c3099f274dba22f8a850663af5035a1678ac256a76b",
          "sha1": "3841a72e7dd17d6f4745dfe17ae61f3f905faa07",
          "md5": "8cae36cb03fc70186490dad61c33c50e"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-1.10.0-bump-updates-SNAPSHOT.jar",
          "url": "util-1.10.0-bump-updates-SNAPSHOT.jar",
          "size": 4932,
          "sha512": "57238a3a36673a58f70a62b01d940c81fb1dd63c343a59618b93c17e8927b0692a8bc2a6daa4e3bec0df7c7311b8a6d58c1debff1570a1807314c3d6373e9801",
          "sha256": "b06a14a010671c2f176fddbbfdd4e845b34656a4e0d9a5f5d2979307b6ec8d6c",
          "sha1": "4ef938bc971e29cba66b9358844b021d69334dcb",
          "md5": "4fc5cc725e6c19593d2ca30b37b7bc60"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../util-android-debug/1.10.0-bump-updates-SNAPSHOT/util-android-debug-1.10.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-android-debug",
        "version": "1.10.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../util-android-debug/1.10.0-bump-updates-SNAPSHOT/util-android-debug-1.10.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-android-debug",
        "version": "1.10.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../util-android/1.10.0-bump-updates-SNAPSHOT/util-android-1.10.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-android",
        "version": "1.10.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../util-android/1.10.0-bump-updates-SNAPSHOT/util-android-1.10.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-android",
        "version": "1.10.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../util-iosarm64/1.10.0-bump-updates-SNAPSHOT/util-iosarm64-1.10.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-iosarm64",
        "version": "1.10.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../util-iosarm64/1.10.0-bump-updates-SNAPSHOT/util-iosarm64-1.10.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-iosarm64",
        "version": "1.10.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../util-iosx64/1.10.0-bump-updates-SNAPSHOT/util-iosx64-1.10.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-iosx64",
        "version": "1.10.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../util-iosx64/1.10.0-bump-updates-SNAPSHOT/util-iosx64-1.10.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-iosx64",
        "version": "1.10.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../util-jvm/1.10.0-bump-updates-SNAPSHOT/util-jvm-1.10.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-jvm",
        "version": "1.10.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../util-jvm/1.10.0-bump-updates-SNAPSHOT/util-jvm-1.10.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-jvm",
        "version": "1.10.0-bump-updates-SNAPSHOT"
      }
    }
  ]
}
