{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.3-add-donor-key-storage-SNAPSHOT/data-donation-sdk-iosx64-0.1.3-add-donor-key-storage-SNAPSHOT.module",
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.3-add-donor-key-storage-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "ugwvggejszdxbnhi6t3xuchy4u"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.3-add-donor-key-storage-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.3-add-donor-key-storage-SNAPSHOT.jar",
          "size": 65338,
          "sha512": "5b1c5926e91ecbd3ac737036f2651f11dbbe366a3afa34534ca5598b10059f9445c336e60bd8735628e0137c6525dd6a42ebe21b6ee87e392e289b98dbcb659f",
          "sha256": "96c2fbfe77b581ef8cdec09f05911b14b0f6c6daa28961a6d3f0b9ac8396f6f5",
          "sha1": "b1cc95491b27d59810d5530c4dc48d2893fdfbee",
          "md5": "6a5e29145c2330cafffd652ed3973107"
        }
      ]
    }
  ]
}
