{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-coroutine",
    "version": "0.2.0-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.1-native-mt",
            "requires": "1.5.1-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-coroutine-metadata-0.2.0-bump-updates-SNAPSHOT-all.jar",
          "url": "test-util-coroutine-0.2.0-bump-updates-SNAPSHOT-all.jar",
          "size": 5018,
          "sha512": "1fe2efbdd257cda8f4aec8757a191a5303ec83f675b58b7afbc88e92bfd59364fe3f124ce26e088b20e82616cd29053cf2cc2dc8f23cbe8419fb40edfd3eea12",
          "sha256": "29213d820aae3748ae84ca0bb43e6b8a30fee23fe4c03bbeea8e8e45db62a6b7",
          "sha1": "041f1be807909881cd011f3b33cf08d1c466d5d8",
          "md5": "d1015e62f72395b1c43ac850d4b47a3d"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-util-coroutine-0.2.0-bump-updates-SNAPSHOT.jar",
          "url": "test-util-coroutine-0.2.0-bump-updates-SNAPSHOT.jar",
          "size": 1774,
          "sha512": "53a94a6bd71f979055bd4814380b59f925ac2a4f3bd434e618a90250d5f18d56f3a06707f9fe72d84ab30fc3a6b9a7d22036a04ed47b2421b0924c4a4af06774",
          "sha256": "e93b579ccbee72af474a62160fe4d04f96de771942e7e9b5e8a5d36680eed7a6",
          "sha1": "809ca98458643aeb5d4d7cbac5c86bb18a7be47d",
          "md5": "11aecd64af35a23bf6868111f6c3cabe"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-util-coroutine-android-debug/0.2.0-bump-updates-SNAPSHOT/test-util-coroutine-android-debug-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-android-debug",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-util-coroutine-android-debug/0.2.0-bump-updates-SNAPSHOT/test-util-coroutine-android-debug-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-android-debug",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-util-coroutine-android/0.2.0-bump-updates-SNAPSHOT/test-util-coroutine-android-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-android",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-util-coroutine-android/0.2.0-bump-updates-SNAPSHOT/test-util-coroutine-android-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-android",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-util-coroutine-iosarm64/0.2.0-bump-updates-SNAPSHOT/test-util-coroutine-iosarm64-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-iosarm64",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-util-coroutine-iosarm64/0.2.0-bump-updates-SNAPSHOT/test-util-coroutine-iosarm64-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-iosarm64",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-util-coroutine-iosx64/0.2.0-bump-updates-SNAPSHOT/test-util-coroutine-iosx64-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-iosx64",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-util-coroutine-iosx64/0.2.0-bump-updates-SNAPSHOT/test-util-coroutine-iosx64-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-iosx64",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-util-coroutine-jvm/0.2.0-bump-updates-SNAPSHOT/test-util-coroutine-jvm-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-jvm",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-util-coroutine-jvm/0.2.0-bump-updates-SNAPSHOT/test-util-coroutine-jvm-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-jvm",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    }
  ]
}
