{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-coroutine",
    "version": "0.2.0-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.1-native-mt",
            "requires": "1.5.1-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-coroutine-metadata-0.2.0-bump-updates-SNAPSHOT-all.jar",
          "url": "test-util-coroutine-0.2.0-bump-updates-SNAPSHOT-all.jar",
          "size": 5018,
          "sha512": "0adc3b1e03a17dabb695d7a9ae5c3420560da8cdca66e1485bb8d53aa25e221e42ab5c934809f95346eac1fe5de479b0b665f2ca067d9a937e015b39e4cb5ff4",
          "sha256": "be9d472b98417c7fa5d3da2e2d72a64d0b0b56384c035fd3e55fed82a9ebef82",
          "sha1": "e3ebd8041d7d36cb2ca1472c1ed12f17171a3191",
          "md5": "43d8459b378f4ca5ae5303eebd06d740"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-util-coroutine-0.2.0-bump-updates-SNAPSHOT.jar",
          "url": "test-util-coroutine-0.2.0-bump-updates-SNAPSHOT.jar",
          "size": 1774,
          "sha512": "e985e3d6c3eb54f573b56b7c022a3f22ce7daf63200b8de9e4918df4d1d299192fe06d180b7e81b45083401d8686ecfae0b5773d36a6bd7a52e2b7acdd95dd39",
          "sha256": "2a068a0c60340053bdf2e3483507e2e63449599dd330a6a0ef09bf4eead2a137",
          "sha1": "c0b8187818110af36b35f43193a17a928a3d60d3",
          "md5": "0ff7c97c42847fd5527c327bbba9f8e9"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-util-coroutine-android-debug/0.2.0-bump-updates-SNAPSHOT/test-util-coroutine-android-debug-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-android-debug",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-util-coroutine-android-debug/0.2.0-bump-updates-SNAPSHOT/test-util-coroutine-android-debug-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-android-debug",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-util-coroutine-android/0.2.0-bump-updates-SNAPSHOT/test-util-coroutine-android-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-android",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-util-coroutine-android/0.2.0-bump-updates-SNAPSHOT/test-util-coroutine-android-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-android",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-util-coroutine-iosarm64/0.2.0-bump-updates-SNAPSHOT/test-util-coroutine-iosarm64-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-iosarm64",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-util-coroutine-iosarm64/0.2.0-bump-updates-SNAPSHOT/test-util-coroutine-iosarm64-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-iosarm64",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-util-coroutine-iosx64/0.2.0-bump-updates-SNAPSHOT/test-util-coroutine-iosx64-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-iosx64",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-util-coroutine-iosx64/0.2.0-bump-updates-SNAPSHOT/test-util-coroutine-iosx64-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-iosx64",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-util-coroutine-jvm/0.2.0-bump-updates-SNAPSHOT/test-util-coroutine-jvm-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-jvm",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-util-coroutine-jvm/0.2.0-bump-updates-SNAPSHOT/test-util-coroutine-jvm-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-jvm",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    }
  ]
}
