{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.11.0-fix-updateRecord-checks-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "uqypsdpftrervn3osaqkitvtmm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-fix-updateRecord-checks-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.11.0-fix-updateRecord-checks-SNAPSHOT.jar",
          "url": "auth-jvm-1.11.0-fix-updateRecord-checks-SNAPSHOT.jar",
          "size": 34318,
          "sha512": "0c516b28c304b5e3760646a1f8c994e5fd5637596f0e5ba5f4e9f607b84432d08cde99ffc89ee41bc882ebaa91cdff97592bc0d0ca129398a7e6b343ac1e0061",
          "sha256": "8c70612ff297cd07e202e5dc74b3cb89ad902d1efcfe80fe606d122ceb58bfb7",
          "sha1": "892e86fa5c20d162d0c0861b0608d4d5436330c6",
          "md5": "008a046606d9061966d60ecd38945cf8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.11.0-fix-updateRecord-checks-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-fix-updateRecord-checks-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.11.0-fix-updateRecord-checks-SNAPSHOT.jar",
          "url": "auth-jvm-1.11.0-fix-updateRecord-checks-SNAPSHOT.jar",
          "size": 34318,
          "sha512": "0c516b28c304b5e3760646a1f8c994e5fd5637596f0e5ba5f4e9f607b84432d08cde99ffc89ee41bc882ebaa91cdff97592bc0d0ca129398a7e6b343ac1e0061",
          "sha256": "8c70612ff297cd07e202e5dc74b3cb89ad902d1efcfe80fe606d122ceb58bfb7",
          "sha1": "892e86fa5c20d162d0c0861b0608d4d5436330c6",
          "md5": "008a046606d9061966d60ecd38945cf8"
        }
      ]
    }
  ]
}
