{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.11.0-change-client-version-header-dynamic-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "p3ldgez2tjaxzjaeu37pmwakju"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-change-client-version-header-dynamic-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.11.0-change-client-version-header-dynamic-SNAPSHOT.jar",
          "url": "auth-jvm-1.11.0-change-client-version-header-dynamic-SNAPSHOT.jar",
          "size": 34318,
          "sha512": "4bf6355a1bc83c1e54794f6d8ca1abd1f6e03f1090686ab3ed7d928b46041c29a35d628910d63f97294b2101c6b7965f5329943f64df92eaa39684ccf7cbb561",
          "sha256": "37cd9f1fe2bcd4c35b87f57e29d1581edc42dcab1d8081976878ec2f366a0c03",
          "sha1": "fbbf3a1b87a3434579887d1581879c318c0f10ad",
          "md5": "d65f080fa9af871addd884a9992fa0bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.11.0-change-client-version-header-dynamic-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-change-client-version-header-dynamic-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.11.0-change-client-version-header-dynamic-SNAPSHOT.jar",
          "url": "auth-jvm-1.11.0-change-client-version-header-dynamic-SNAPSHOT.jar",
          "size": 34318,
          "sha512": "4bf6355a1bc83c1e54794f6d8ca1abd1f6e03f1090686ab3ed7d928b46041c29a35d628910d63f97294b2101c6b7965f5329943f64df92eaa39684ccf7cbb561",
          "sha256": "37cd9f1fe2bcd4c35b87f57e29d1581edc42dcab1d8081976878ec2f366a0c03",
          "sha1": "fbbf3a1b87a3434579887d1581879c318c0f10ad",
          "md5": "d65f080fa9af871addd884a9992fa0bf"
        }
      ]
    }
  ]
}
