{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-coroutine-test/1.9.0-change-setup-SNAPSHOT/util-coroutine-test-1.9.0-change-setup-SNAPSHOT.module",
    "group": "care.data4life.hc-coroutine-util-sdk-kmp",
    "module": "util-coroutine-test",
    "version": "1.9.0-change-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "yorverysjbczhdukaj2axvo7um"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-coroutine-test-jvm-1.9.0-change-setup-SNAPSHOT.jar",
          "url": "util-coroutine-test-jvm-1.9.0-change-setup-SNAPSHOT.jar",
          "size": 5989,
          "sha512": "7185207efe180753a416c1d16d0d23b5e2f56e438e991a13b93a87d5f276b8adc3464ea4164e3a088880b19f92e3ca9bcc05f00ec6282c0ac8881e1fcfd0bdd9",
          "sha256": "f481752b243452ac6e8b4c4875c7d980666dfb532427eae364fba5f72f31614e",
          "sha1": "57ac0ce41da438efab8b09898eed9932dd728164",
          "md5": "8acddd6ab0d9abc457d0f64b35478571"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "util-coroutine-test-jvm-1.9.0-change-setup-SNAPSHOT.jar",
          "url": "util-coroutine-test-jvm-1.9.0-change-setup-SNAPSHOT.jar",
          "size": 5989,
          "sha512": "7185207efe180753a416c1d16d0d23b5e2f56e438e991a13b93a87d5f276b8adc3464ea4164e3a088880b19f92e3ca9bcc05f00ec6282c0ac8881e1fcfd0bdd9",
          "sha256": "f481752b243452ac6e8b4c4875c7d980666dfb532427eae364fba5f72f31614e",
          "sha1": "57ac0ce41da438efab8b09898eed9932dd728164",
          "md5": "8acddd6ab0d9abc457d0f64b35478571"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-coroutine-test-metadata/1.9.0-change-setup-SNAPSHOT/util-coroutine-test-metadata-1.9.0-change-setup-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "util-coroutine-test-metadata",
        "version": "1.9.0-change-setup-SNAPSHOT"
      }
    }
  ]
}
