{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.3-add-donation-service-model-SNAPSHOT/data-donation-sdk-iosx64-0.1.3-add-donation-service-model-SNAPSHOT.module",
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.3-add-donation-service-model-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "zvdv5d3fzjanfktxzjafyqkcg4"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.3-add-donation-service-model-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.3-add-donation-service-model-SNAPSHOT.jar",
          "size": 69526,
          "sha512": "fc10ca919cdf0c0f0c23fd0a662daff72a839c8673d23197d46ba1fb9bcf24930458fc3b89ab21772717fe8df02c17e35f3e8592010e1de87ce97ca949005ed3",
          "sha256": "493b1f564240ffa78bb6ac6b595cd9f63af933d2507c675fcc60456b4c3ad759",
          "sha1": "e118c85714a2dd5993e2547de4425e5dac235a0c",
          "md5": "30d7c9d738148818af4b962d46ed71de"
        }
      ]
    }
  ]
}
