{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.11.0-change-update-data-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "tiozloarwrf45fq3tp77gskryy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.11.0-change-update-data-SNAPSHOT.jar",
          "url": "securestore-common-1.11.0-change-update-data-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "a712826047ccd2838b905f130f6abe439cde9d514f64401403075ad4620b7537aa2fb51c7b188215c2ce7c49a1d93ab6ab4632f2cd63f62d29f356c8fbb6d214",
          "sha256": "818a60c20b14fbd5c6c3225a9b5b1ed736d4948ad40b81b0f1e7af1502143a35",
          "sha1": "1aaa6dd9bff79d003f46145738720e1353cff8b6",
          "md5": "a24fc1d0abdf7cf0a2185497305f089a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.11.0-change-update-data-SNAPSHOT.jar",
          "url": "securestore-common-1.11.0-change-update-data-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "a712826047ccd2838b905f130f6abe439cde9d514f64401403075ad4620b7537aa2fb51c7b188215c2ce7c49a1d93ab6ab4632f2cd63f62d29f356c8fbb6d214",
          "sha256": "818a60c20b14fbd5c6c3225a9b5b1ed736d4948ad40b81b0f1e7af1502143a35",
          "sha1": "1aaa6dd9bff79d003f46145738720e1353cff8b6",
          "md5": "a24fc1d0abdf7cf0a2185497305f089a"
        }
      ]
    }
  ]
}
