{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.11.0-change-client-version-header-dynamic-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "p3ldgez2tjaxzjaeu37pmwakju"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-change-client-version-header-dynamic-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.11.0-change-client-version-header-dynamic-SNAPSHOT.jar",
          "url": "crypto-jvm-1.11.0-change-client-version-header-dynamic-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "13e2030ada09b19aff0e0738a9373d0f0c3ed8c4436ea4ea0b93adf346aa316b0e40ec4d2a8644690341b6fc0c048257135179609d576d11253d26208cfe33ea",
          "sha256": "1a53bcaa1faf32fabe29eb457136d8c1a01eb5a4fa7322e83d3200913b0db410",
          "sha1": "7ba394af47579fab90908953de14da881a080c0f",
          "md5": "b621a7aae41998a538f66c757d5b857c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-change-client-version-header-dynamic-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.11.0-change-client-version-header-dynamic-SNAPSHOT.jar",
          "url": "crypto-jvm-1.11.0-change-client-version-header-dynamic-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "13e2030ada09b19aff0e0738a9373d0f0c3ed8c4436ea4ea0b93adf346aa316b0e40ec4d2a8644690341b6fc0c048257135179609d576d11253d26208cfe33ea",
          "sha256": "1a53bcaa1faf32fabe29eb457136d8c1a01eb5a4fa7322e83d3200913b0db410",
          "sha1": "7ba394af47579fab90908953de14da881a080c0f",
          "md5": "b621a7aae41998a538f66c757d5b857c"
        }
      ]
    }
  ]
}
