{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-coroutine/0.1.0-bump-robolectric-SNAPSHOT/test-util-coroutine-0.1.0-bump-robolectric-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-coroutine",
    "version": "0.1.0-bump-robolectric-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "zwzryyjrszf5vhynbmmehnrtpe"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-util-coroutine-jvm-0.1.0-bump-robolectric-SNAPSHOT.jar",
          "url": "test-util-coroutine-jvm-0.1.0-bump-robolectric-SNAPSHOT.jar",
          "size": 5987,
          "sha512": "a99797bcd183d4e19c03ed2fdbf5792d35584fb3a2285ae9301852a100bf1d72782c527de3e50485a0612b79c551d83f0ae1f53e9bbfbced7d94f006b806d807",
          "sha256": "9adb2e9a0867536ddbda86c1dd25613a71510670bc77092257b8892d98817512",
          "sha1": "6f92a721d6eb9e854d97e2b12c789d71ca43d100",
          "md5": "5081481368e337627445037bae77ed50"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-coroutine-jvm-0.1.0-bump-robolectric-SNAPSHOT.jar",
          "url": "test-util-coroutine-jvm-0.1.0-bump-robolectric-SNAPSHOT.jar",
          "size": 5987,
          "sha512": "a99797bcd183d4e19c03ed2fdbf5792d35584fb3a2285ae9301852a100bf1d72782c527de3e50485a0612b79c551d83f0ae1f53e9bbfbced7d94f006b806d807",
          "sha256": "9adb2e9a0867536ddbda86c1dd25613a71510670bc77092257b8892d98817512",
          "sha1": "6f92a721d6eb9e854d97e2b12c789d71ca43d100",
          "md5": "5081481368e337627445037bae77ed50"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../test-util-coroutine-metadata/0.1.0-bump-robolectric-SNAPSHOT/test-util-coroutine-metadata-0.1.0-bump-robolectric-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-metadata",
        "version": "0.1.0-bump-robolectric-SNAPSHOT"
      }
    }
  ]
}
