{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-coroutine-jvm/1.8.1-SNAPSHOT/util-coroutine-jvm-1.8.1-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-coroutine-jvm",
    "version": "1.8.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "k26a5ou77rhs7a53ykbajtys34"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-coroutine-metadata-1.8.1-SNAPSHOT.jar",
          "url": "util-coroutine-metadata-1.8.1-SNAPSHOT.jar",
          "size": 2237,
          "sha512": "b2d5f8ddc60e981dc5e94666bc4f4eb57a2031f480d959846288fadbc44f4be9e124d57d0ff4f8901fba8b861a0cb03618c85c9153e2b9ba7aa6ca0b9dc6ea2b",
          "sha256": "d9e90e0e9079d368bd981db33bb0e60736ac72905ccbc4b612b7801d18bb6fa6",
          "sha1": "803ee71b5f683271caeccd6113f7e72348d3472b",
          "md5": "df13d721185d798c6c0c7ecb8ee3565a"
        }
      ]
    }
  ]
}
