{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coroutine-util/0.1.0-change-setup-to-latest-SNAPSHOT/coroutine-util-0.1.0-change-setup-to-latest-SNAPSHOT.module",
    "group": "care.data4life.hc-coroutine-util-sdk-kmp",
    "module": "coroutine-util",
    "version": "0.1.0-change-setup-to-latest-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "z7v3ek7uxrcjdbyyyvyzsrctvm"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "coroutine-util.klib",
          "url": "coroutine-util-iosarm64-0.1.0-change-setup-to-latest-SNAPSHOT.klib",
          "size": 8745,
          "sha512": "2c236ee4dbc89f32668fcc194990fb55883764e4da4069396b740bf8dfe783ba569b4359c39fde99727e6de2f1e14be1416cbfbf8dbf005c6ced0035fad706fa",
          "sha256": "dc9102d2d832f6db88c87dab74aff1387fa9aec2dfca344a0afe3f56577fca66",
          "sha1": "b45f24d3aebb27cfd7d057ac676b7deb1273ecb3",
          "md5": "4e9aba5410410a037b02578fd3058744"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "coroutine-util-iosarm64-0.1.0-change-setup-to-latest-SNAPSHOT-metadata.jar",
          "url": "coroutine-util-iosarm64-0.1.0-change-setup-to-latest-SNAPSHOT-metadata.jar",
          "size": 5787,
          "sha512": "681f8628438ec79df7787d61e77f2fe02d7f84f5a776fb0a5080ac5e9f4f61780d008dacca34900950bb0536eff5ade2c91f03792177c8f644c10e47a61fc36b",
          "sha256": "4cb3614903726cce5de80d5f9b2ab90fe63f2d4f417c493a3b35686441309843",
          "sha1": "5c7fc0f29169300a551a0fb72206f3f6e3f625d0",
          "md5": "af678b6f1a25491620f22a673449c676"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../coroutine-util/0.1.0-change-setup-to-latest-SNAPSHOT/coroutine-util-0.1.0-change-setup-to-latest-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util",
        "version": "0.1.0-change-setup-to-latest-SNAPSHOT"
      }
    },
    {
      "name": "commonMainMetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../coroutine-util/0.1.0-change-setup-to-latest-SNAPSHOT/coroutine-util-0.1.0-change-setup-to-latest-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util",
        "version": "0.1.0-change-setup-to-latest-SNAPSHOT"
      }
    }
  ]
}
