{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coroutine-util/0.1.0-change-setup-to-latest-SNAPSHOT/coroutine-util-0.1.0-change-setup-to-latest-SNAPSHOT.module",
    "group": "care.data4life.hc-coroutine-util-sdk-kmp",
    "module": "coroutine-util",
    "version": "0.1.0-change-setup-to-latest-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "xzzmcqyyzffyfovu7xkepcyp3a"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "coroutine-util.klib",
          "url": "coroutine-util-iosarm64-0.1.0-change-setup-to-latest-SNAPSHOT.klib",
          "size": 6771,
          "sha512": "89d1eec22431167a0c3072273ced741d701c02d98fc78e2d52a1335f1f39f2c6a23527c35294ad47abbc1bc0ce9899b6ef8e4e8ccb96e2cb811995c4baccc882",
          "sha256": "0bf474caf4c99d6633d1c0518cfe15743c5adbbcaa54c4a305956e589c60c20e",
          "sha1": "5c85561cf640ff6bfb4a1ced0b4d51ecfc932f6c",
          "md5": "1075c1dd41eac499155a835acc81a770"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "coroutine-util-iosarm64-0.1.0-change-setup-to-latest-SNAPSHOT-metadata.jar",
          "url": "coroutine-util-iosarm64-0.1.0-change-setup-to-latest-SNAPSHOT-metadata.jar",
          "size": 5677,
          "sha512": "3bd43738007b41b5b0a85aa79226c6463e6e235331135b5a15f1610d130ec60a6c12d7d6e7368b95329c3f63d20fbeec675eb7f6296dabb0cd129abf12b08e83",
          "sha256": "779193abbf2acc0c323a03fc42f4f7d988a2336373bdf9b0e18ac262e4030dab",
          "sha1": "1dbc8486764b7dfbcf62cdb57fe69ad999104f3b",
          "md5": "72c9673af2423a349440b1c21a453b1e"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../coroutine-util/0.1.0-change-setup-to-latest-SNAPSHOT/coroutine-util-0.1.0-change-setup-to-latest-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util",
        "version": "0.1.0-change-setup-to-latest-SNAPSHOT"
      }
    },
    {
      "name": "commonMainMetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../coroutine-util/0.1.0-change-setup-to-latest-SNAPSHOT/coroutine-util-0.1.0-change-setup-to-latest-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util",
        "version": "0.1.0-change-setup-to-latest-SNAPSHOT"
      }
    }
  ]
}
