{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir-jvm/0.1.0-add-fhir4-date-primitives-SNAPSHOT/fhir-jvm-0.1.0-add-fhir4-date-primitives-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir-jvm",
    "version": "0.1.0-add-fhir4-date-primitives-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "tdlwhmwjk5de5caqogn2kp5aya"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "fhir-metadata-0.1.0-add-fhir4-date-primitives-SNAPSHOT.jar",
          "url": "fhir-metadata-0.1.0-add-fhir4-date-primitives-SNAPSHOT.jar",
          "size": 998099,
          "sha512": "94144c5a76b24dd54d54ba66e7ac41a6f6eeaf03041ad75adb0138bc58ea2eaca4ed9021f4b2bddb1500414ecbc420335d9b19138e4509b37150a8dcbbc8ded4",
          "sha256": "3ca1d79d779294c1c6ae1a425361e07d79268c5f9c818f1a0a2c7db6e6dbd62b",
          "sha1": "55b76b6dd0492707dca58a0077fb0cbc424fdc6b",
          "md5": "c6cfaac02617fbcac1e2c07bedf3c7cf"
        }
      ]
    }
  ]
}
