{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.11.0-change-ihc-service-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "zakliq67cnabnibqsbgpkai6tm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-change-ihc-service-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.11.0-change-ihc-service-SNAPSHOT.jar",
          "url": "auth-jvm-1.11.0-change-ihc-service-SNAPSHOT.jar",
          "size": 34318,
          "sha512": "3e98826fd85a534314d611034c38f5a8783f630a29c7001535c5dfc95e96128315a3869d5c890edf85ea319a11d1a124fec6362010b2fd58673f11e217ba8aae",
          "sha256": "213c9737f943f01c1d00df4cf1e04fd55a6000864178407edc70127839f2f271",
          "sha1": "ba137c28d021a8a960cd199abd7342b1ac359e98",
          "md5": "15a359e105d1bd63435aee61df063f4c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.11.0-change-ihc-service-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-change-ihc-service-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.11.0-change-ihc-service-SNAPSHOT.jar",
          "url": "auth-jvm-1.11.0-change-ihc-service-SNAPSHOT.jar",
          "size": 34318,
          "sha512": "3e98826fd85a534314d611034c38f5a8783f630a29c7001535c5dfc95e96128315a3869d5c890edf85ea319a11d1a124fec6362010b2fd58673f11e217ba8aae",
          "sha256": "213c9737f943f01c1d00df4cf1e04fd55a6000864178407edc70127839f2f271",
          "sha1": "ba137c28d021a8a960cd199abd7342b1ac359e98",
          "md5": "15a359e105d1bd63435aee61df063f4c"
        }
      ]
    }
  ]
}
