{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.3-add-program-SNAPSHOT/data-donation-sdk-iosx64-0.1.3-add-program-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.3-add-program-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ue4rvcd3nrecnfr2lutygkqcxm"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.3-add-program-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.3-add-program-SNAPSHOT.jar",
          "size": 48107,
          "sha512": "c542b99f8c33e7eb5426a0931be1aa1a91cb2a20d6610afb62ca721ff08c8b640d41bee250a9c5e1d27562f9425702a05e2d5fd21742a74e25b0192a143798a5",
          "sha256": "6e9201ccd89bf364c2dfaf652961c9999a3885aba991ddd793428874eee6871d",
          "sha1": "458af007db6b7326a42b2562972bfc04f0ef3a9c",
          "md5": "68ae705b7ee64f3aeb65148a3a1cf71f"
        }
      ]
    }
  ]
}
