{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.3-add-program-SNAPSHOT/data-donation-sdk-iosx64-0.1.3-add-program-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.3-add-program-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "fyv6fuaa3bb3tjgayoh545jrju"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.3-add-program-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.3-add-program-SNAPSHOT.jar",
          "size": 47637,
          "sha512": "cf67e935d8bc70438ce1e71b8fc86c770169a3f87885972ef87a2a5762a68e29e07ed4e018f246e1ff4562109fe370f17a16f476d2ca99297260b37ee15dbdc7",
          "sha256": "4c2895a06d6c09836eb4af90acdbecc5f271c2e7ce144661153475b23ce17af2",
          "sha1": "540cefab7e7ab91a55cbc78e4288e39b6e5a2ea1",
          "md5": "8b11b7e7af8b2a7237b64c8d571db194"
        }
      ]
    }
  ]
}
