{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.3-add-program-SNAPSHOT/data-donation-sdk-iosx64-0.1.3-add-program-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.3-add-program-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "rgp2fpnnsnc6fgoz3ifpvx7gla"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.3-add-program-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.3-add-program-SNAPSHOT.jar",
          "size": 47559,
          "sha512": "72aaa0a3154ac3f1ac59b038301daafb173b34bb975008a8c732e642769c0a6fff06de3fe391ab287d0965c11294de80953697c86c768b825b0d52817e670f85",
          "sha256": "67fc8b5db5040a4796f10690c1a8163442a7fd4009104a3be55075e3ef294890",
          "sha1": "5f28b937999cf2a3351d8795e1f68a01f389cf36",
          "md5": "51a15003556cb99d0dabcbda0f2bc3ed"
        }
      ]
    }
  ]
}
