{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.3-add-program-SNAPSHOT/data-donation-sdk-iosx64-0.1.3-add-program-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.3-add-program-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "qw6tbeato5awzfjorzpb2hqd7e"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.3-add-program-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.3-add-program-SNAPSHOT.jar",
          "size": 47501,
          "sha512": "334865546882fbd62ae7017320da787f47359997fcfa84884860f0207915c4d82f26c71e1453d5abe952a45a8fbda36ec1eea8578bd809e710bcf4eb66d38466",
          "sha256": "de10d9f06c4f90c5c3186699443419d589dbdfff022391b6215e31112f8ca66e",
          "sha1": "fba7ee57f8b49a4fe90a9d13ef5a7a1072f62bbc",
          "md5": "2b77b83aa22d7e5cc1f49f704bce879b"
        }
      ]
    }
  ]
}
