{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.11.0-change-client-version-header-dynamic-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ltm5y33dkbba5jvupfrdkbs24y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-change-client-version-header-dynamic-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-change-client-version-header-dynamic-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "db1bc57e4ad65b6c11594f8e37faf8645c216652a13032f1cc8b87d265db378988698658c2c8022792748fe00982404b690ac61eff4084308fb6079c72dc8dd6",
          "sha256": "49221151c92ff09e8d3b2704cee950ff9ca32de54efc01751884db40bfe3544e",
          "sha1": "eccfdd0efcac660d3186accddb428ed40614cbac",
          "md5": "6b7bc40a401313927ddd9ac9ce898e9b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-change-client-version-header-dynamic-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-change-client-version-header-dynamic-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-change-client-version-header-dynamic-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "db1bc57e4ad65b6c11594f8e37faf8645c216652a13032f1cc8b87d265db378988698658c2c8022792748fe00982404b690ac61eff4084308fb6079c72dc8dd6",
          "sha256": "49221151c92ff09e8d3b2704cee950ff9ca32de54efc01751884db40bfe3544e",
          "sha1": "eccfdd0efcac660d3186accddb428ed40614cbac",
          "md5": "6b7bc40a401313927ddd9ac9ce898e9b"
        }
      ]
    }
  ]
}
