{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-coroutine/0.2.0-bump-updates-SNAPSHOT/test-util-coroutine-0.2.0-bump-updates-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-coroutine",
    "version": "0.2.0-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.1-native-mt",
            "requires": "1.5.1-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-coroutine.klib",
          "url": "test-util-coroutine-iosx64-0.2.0-bump-updates-SNAPSHOT.klib",
          "size": 7833,
          "sha512": "5d452210f798bc7962914a7b4842372c09ae05aebca3b2542f80455fb2dd5c29d6f4361a670775f1edc64d4427a9460dff6c3a601c5b90fc2aae1baeb43fe9a4",
          "sha256": "bcfaac01ec3c920ae9bc592fe493a3eeeaa81e869f1239b6a6e279649b7ae333",
          "sha1": "563d97f1b93737bbad96f76c8bec4d3387167730",
          "md5": "77313596725723eb75007be3770520b1"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.1-native-mt",
            "requires": "1.5.1-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-coroutine-iosx64-0.2.0-bump-updates-SNAPSHOT-metadata.jar",
          "url": "test-util-coroutine-iosx64-0.2.0-bump-updates-SNAPSHOT-metadata.jar",
          "size": 6284,
          "sha512": "3c58f5b39e902f3ad5f4ca07727e67765a3ff4fa7e5de5f29181e375a0e4591d9a0ab1438ff9c873429dd178ddcc55f22897ff924f7ec67d916f58d15e6da2a6",
          "sha256": "cd687d0926f29e620c9e7c7b92c670f209f18cdff92341491cd8722a62c170bc",
          "sha1": "61c6bd9ebd56bae631cc9bc4cfea52cf6d4ab97d",
          "md5": "94f745e3020322c1ca9b57b08a2a55fd"
        }
      ]
    }
  ]
}
