{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir",
    "version": "0.1.0-fix-docs-dependencies-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "fhir-metadata-0.1.0-fix-docs-dependencies-SNAPSHOT.jar",
          "url": "fhir-0.1.0-fix-docs-dependencies-SNAPSHOT.jar",
          "size": 3216152,
          "sha512": "b171be9ebc44efec971b3b24d8f76f218624b09a351db2fc1c0ed9f375161d15620a7fd9dec53b87f8aa52ed839585d1dc00e8c0bce924d3d590d5d24c323425",
          "sha256": "cd86a689a58862ff7446af4e16eb23568640f9c719596fe55ba4675565543f40",
          "sha1": "848edd47fe606954789fecf0272adf27693ccfff",
          "md5": "9cb61ca6ef138369ae5533e08e9aea3d"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-android/0.1.0-fix-docs-dependencies-SNAPSHOT/fhir-android-0.1.0-fix-docs-dependencies-SNAPSHOT.module",
        "group": "care.data4life",
        "module": "fhir-android",
        "version": "0.1.0-fix-docs-dependencies-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-android/0.1.0-fix-docs-dependencies-SNAPSHOT/fhir-android-0.1.0-fix-docs-dependencies-SNAPSHOT.module",
        "group": "care.data4life",
        "module": "fhir-android",
        "version": "0.1.0-fix-docs-dependencies-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-android/0.1.0-fix-docs-dependencies-SNAPSHOT/fhir-android-0.1.0-fix-docs-dependencies-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-android",
        "version": "0.1.0-fix-docs-dependencies-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-android/0.1.0-fix-docs-dependencies-SNAPSHOT/fhir-android-0.1.0-fix-docs-dependencies-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-android",
        "version": "0.1.0-fix-docs-dependencies-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fhir-iosarm64/0.1.0-fix-docs-dependencies-SNAPSHOT/fhir-iosarm64-0.1.0-fix-docs-dependencies-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-iosarm64",
        "version": "0.1.0-fix-docs-dependencies-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fhir-iosx64/0.1.0-fix-docs-dependencies-SNAPSHOT/fhir-iosx64-0.1.0-fix-docs-dependencies-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-iosx64",
        "version": "0.1.0-fix-docs-dependencies-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../fhir-jvm/0.1.0-fix-docs-dependencies-SNAPSHOT/fhir-jvm-0.1.0-fix-docs-dependencies-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-jvm",
        "version": "0.1.0-fix-docs-dependencies-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../fhir-jvm/0.1.0-fix-docs-dependencies-SNAPSHOT/fhir-jvm-0.1.0-fix-docs-dependencies-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-jvm",
        "version": "0.1.0-fix-docs-dependencies-SNAPSHOT"
      }
    }
  ]
}
