{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-android",
    "version": "1.11.0-add-interceptors-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "4wnhsisxrbhzhnyfitrygvw7xe"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-add-interceptors-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.11.0-add-interceptors-SNAPSHOT.aar",
          "url": "auth-android-1.11.0-add-interceptors-SNAPSHOT.aar",
          "size": 45008,
          "sha512": "0e3e78b642bbbea221ff0771d4b1d8a602325014387b1a765a5769f165261b4877cf94f767547732a1aa77b43497a8be9a4ceecc864037472829daf93998ce25",
          "sha256": "f4a4c01013e4a0fb249c3a0aca668aa589921f99c7ffd02d174fbeb9a331f060",
          "sha1": "6881f8bc3f966acbc63f444e9d23a541a3d20715",
          "md5": "bc57d1ceb3315d048bf1b0d66ec9d701"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-add-interceptors-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-android",
          "version": {
            "requires": "1.11.0-add-interceptors-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.gesundheitscloud",
          "module": "AppAuth-Android",
          "version": {
            "requires": "9e3cc033ff"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.11.0-add-interceptors-SNAPSHOT.aar",
          "url": "auth-android-1.11.0-add-interceptors-SNAPSHOT.aar",
          "size": 45008,
          "sha512": "0e3e78b642bbbea221ff0771d4b1d8a602325014387b1a765a5769f165261b4877cf94f767547732a1aa77b43497a8be9a4ceecc864037472829daf93998ce25",
          "sha256": "f4a4c01013e4a0fb249c3a0aca668aa589921f99c7ffd02d174fbeb9a331f060",
          "sha1": "6881f8bc3f966acbc63f444e9d23a541a3d20715",
          "md5": "bc57d1ceb3315d048bf1b0d66ec9d701"
        }
      ]
    }
  ]
}
