{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir-stu3/0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT/fhir-stu3-0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir-stu3",
    "version": "0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-kmp",
          "module": "fhir",
          "version": {
            "requires": "0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-stu3.klib",
          "url": "fhir-stu3-iosx64-0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT.klib",
          "size": 3983030,
          "sha512": "27d70beb73d96d7ca0506469d73ac90e9795cd1a782525e2c94394280a44e6e262c53dd29aa6cecda9f74077e1dd08704652d041759631b9df8687de4c94c3fc",
          "sha256": "24b7c5cae850668691afe94e8d517b03c48d06a90bbbdae780167d4f6d0d5597",
          "sha1": "91c9f3d6bc914bf47adb34ca059c0c9a51a6146e",
          "md5": "f7fed3adefb803ba21009f86643c9bda"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-kmp",
          "module": "fhir",
          "version": {
            "requires": "0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-stu3-iosx64-0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT-metadata.jar",
          "url": "fhir-stu3-iosx64-0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "b3c0b990b8a2e1c3be83b703c0e0aeb43ef267280bcb25847a24659b38de31dd047c50b6421a6b718a0b2ab4a1544523b3b9058e1a8267f4420d53119f5f5e2b",
          "sha256": "d92fc742729af680becf81bcf666bb24390e52e4ce34a401f2d178d32811d3e9",
          "sha1": "498d885dad0724c8dbbda2e38e9ff62f20fb639a",
          "md5": "416c409f89684f5c44d4cc9be987dc48"
        }
      ]
    }
  ]
}
