{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk/0.0.5-bump-update-SNAPSHOT/data-donation-sdk-0.0.5-bump-update-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk",
    "version": "0.0.5-bump-update-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "xpfsyoenx5ec3m3onytpettfhe"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-kmp",
          "module": "fhir",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.4.3-native-mt",
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-ios",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "data-donation-sdk.klib",
          "url": "data-donation-sdk-iosx64-0.0.5-bump-update-SNAPSHOT.klib",
          "size": 216875,
          "sha512": "5425fe6e82aa45f88f38d38d0b55611fb4327f4446bdb40c098f57fd82698a8fddb42d0c83c8468813cdd071932002daa39e771fe421c9882e17604859ae392c",
          "sha256": "9ee779b292f5c2604f2f6024d04406e59f83a76d8292fc0624d74090df3fc0ef",
          "sha1": "9c26965e1eef83e145a8c947fa28c42dc3107eb8",
          "md5": "12ed61205279c4eb4a655543e0d542db"
        },
        {
          "name": "data-donation-sdk-cinterop-iOSCryptoDD.klib",
          "url": "data-donation-sdk-iosx64-0.0.5-bump-update-SNAPSHOT-cinterop-iOSCryptoDD.klib",
          "size": 650752,
          "sha512": "91443d5a580f20e444222266857cb22dc5730115d64a851f3ec85e66a8549489c3941367d7b4f7145fc8e8112f3c3974d2eb62bde1f8b5c5f269f5d8de62c2f8",
          "sha256": "4b3deabc9ddd63720c2c356ef4b15da3629b80ccb5713e6e4e687b6009da2cd5",
          "sha1": "05e432120549e446e97f7744a469bc79df6fe3a6",
          "md5": "2297a949e652c54a5956769b09d3c4b3"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../data-donation-sdk-metadata/0.0.5-bump-update-SNAPSHOT/data-donation-sdk-metadata-0.0.5-bump-update-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-metadata",
        "version": "0.0.5-bump-update-SNAPSHOT"
      }
    }
  ]
}
