{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.14.0-change-logging-login-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "dmwxw2tqtvh6veenwto3vh3gdm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.14.0-change-logging-login-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.14.0-change-logging-login-SNAPSHOT.jar",
          "url": "securestore-jvm-1.14.0-change-logging-login-SNAPSHOT.jar",
          "size": 16455,
          "sha512": "11ce2aa0ef2a8463f8681bb6f0849b0702d6fe344132ea1e6df85f02da41317956c9e707cefa0efe7bcc68fc496da91edfdffac410afe4b0c1dd3afa56c3bf7f",
          "sha256": "c60ddcb47352912bb90dd8aadf767764457d884c24e07075f02b4957dc06696d",
          "sha1": "8da8d6c3012480fda257793080fcba43a749f645",
          "md5": "551e21e522508060f50f7a257b803942"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.14.0-change-logging-login-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.14.0-change-logging-login-SNAPSHOT.jar",
          "url": "securestore-jvm-1.14.0-change-logging-login-SNAPSHOT.jar",
          "size": 16455,
          "sha512": "11ce2aa0ef2a8463f8681bb6f0849b0702d6fe344132ea1e6df85f02da41317956c9e707cefa0efe7bcc68fc496da91edfdffac410afe4b0c1dd3afa56c3bf7f",
          "sha256": "c60ddcb47352912bb90dd8aadf767764457d884c24e07075f02b4957dc06696d",
          "sha1": "8da8d6c3012480fda257793080fcba43a749f645",
          "md5": "551e21e522508060f50f7a257b803942"
        }
      ]
    }
  ]
}
