{
  "formatVersion": "1.1",
  "component": {
    "url": "../../objc-util/0.1.0-SNAPSHOT/objc-util-0.1.0-SNAPSHOT.module",
    "group": "care.data4life.hc-objc-util-sdk-kmp",
    "module": "objc-util",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "objc-util.klib",
          "url": "objc-util-iosx64-0.1.0-SNAPSHOT.klib",
          "size": 8882,
          "sha512": "ba9439706673c7bce71692adf48cb14c1056a107c7dacdf696d227e7f40d7b0bd875d6b5d13e711b81f0f836760266c51296208a666c69a2f691dd8a7710f7a0",
          "sha256": "1be2bdcfb0c3bdf00528903465345ccf5e0f9b5cffcbe284688ad14080fff55a",
          "sha1": "3927b4af7a5de28dee43fbdde2074d611f9ce2fe",
          "md5": "6680587c64d67f1afb31799b872d2972"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "objc-util-iosx64-0.1.0-SNAPSHOT-metadata.jar",
          "url": "objc-util-iosx64-0.1.0-SNAPSHOT-metadata.jar",
          "size": 5763,
          "sha512": "a7224cd8e1291cf1d77abd0a5a57b22851e0228c71f9e6a00fa62105e227a9a0f12e42ccf99bed367081d4f9fe4b9372851a2b0a842da5f641dffd40abc3687f",
          "sha256": "6962370f8dbda351af7e8f61f5e56c44e110195f7964d1c0de9eac0541bb55aa",
          "sha1": "ad20494c45b829080daacd6d8eea037beef98818",
          "md5": "802bcc5b5edad2027e9c22cf048606d8"
        }
      ]
    }
  ]
}
