{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.13.2-bump-util-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "kpdxsq5mqraltl54gn4horbpye"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.8.1-bump-android-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.13.2-bump-util-SNAPSHOT.jar",
          "url": "auth-common-1.13.2-bump-util-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "88de0776a7590a90bcd13686120aa359d8f8be6ea3017e20562d591242dec256fcb2a1667f372ecda29da1bb1e573de3862d87c13980fbc3bac143f4483491a2",
          "sha256": "213df026990c954a5738e57091eec401bb23bbbe5d08327b8fb00285d306ffa8",
          "sha1": "7f8242455a3ab7ac27dbdfd75371058b85e27f4e",
          "md5": "3b3e4fe5cdbd8c8291c5ff2625a1a100"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.2-bump-util-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.8.1-bump-android-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.13.2-bump-util-SNAPSHOT.jar",
          "url": "auth-common-1.13.2-bump-util-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "88de0776a7590a90bcd13686120aa359d8f8be6ea3017e20562d591242dec256fcb2a1667f372ecda29da1bb1e573de3862d87c13980fbc3bac143f4483491a2",
          "sha256": "213df026990c954a5738e57091eec401bb23bbbe5d08327b8fb00285d306ffa8",
          "sha1": "7f8242455a3ab7ac27dbdfd75371058b85e27f4e",
          "md5": "3b3e4fe5cdbd8c8291c5ff2625a1a100"
        }
      ]
    }
  ]
}
