{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.12.0-change-merge-fhir-and-data-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "db2gmtahhrenrjyvqwkzusgqje"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.12.0-change-merge-fhir-and-data-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.12.0-change-merge-fhir-and-data-SNAPSHOT.jar",
          "url": "securestore-jvm-1.12.0-change-merge-fhir-and-data-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "ff2494bcf3aba1914b24e92233face2fe8f318aad9ab15016e6c2c444e728e9801a731217866cac00534ca1d8ee5fba74e6577be02bd8784574947b3fec76154",
          "sha256": "aeb4275a1a10977029a3674a72c0fa4032d80eec0f4baafc77e8447e8490f01d",
          "sha1": "da3e4c7a668be66498f5295f6775b09a72e1ff41",
          "md5": "84c88fb086c258c253783952ee841d65"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.12.0-change-merge-fhir-and-data-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.12.0-change-merge-fhir-and-data-SNAPSHOT.jar",
          "url": "securestore-jvm-1.12.0-change-merge-fhir-and-data-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "ff2494bcf3aba1914b24e92233face2fe8f318aad9ab15016e6c2c444e728e9801a731217866cac00534ca1d8ee5fba74e6577be02bd8784574947b3fec76154",
          "sha256": "aeb4275a1a10977029a3674a72c0fa4032d80eec0f4baafc77e8447e8490f01d",
          "sha1": "da3e4c7a668be66498f5295f6775b09a72e1ff41",
          "md5": "84c88fb086c258c253783952ee841d65"
        }
      ]
    }
  ]
}
