{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.11.0-bump-android-gradle-plugin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "qyna35etyjfxzck5l2ppswauw4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.11.0-bump-android-gradle-plugin-SNAPSHOT.jar",
          "url": "securestore-common-1.11.0-bump-android-gradle-plugin-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "44958ebe3511a9c1c8425171e48b1fd30f01eefe240175716fb2095579cdfaf891d6e4bdd254f873d1e2637e29ff39f9b2ffe881e39faec883caa063f312a086",
          "sha256": "3f1f5064f60ead25b805c8cb7cc36080dc4809c21203df56cc18ba5ecc9a5828",
          "sha1": "b0f067058bbcdd9cc81f23ce5a6670d1dc75480e",
          "md5": "1be2d5b53ab4db351fb917f7af1d95a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.11.0-bump-android-gradle-plugin-SNAPSHOT.jar",
          "url": "securestore-common-1.11.0-bump-android-gradle-plugin-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "44958ebe3511a9c1c8425171e48b1fd30f01eefe240175716fb2095579cdfaf891d6e4bdd254f873d1e2637e29ff39f9b2ffe881e39faec883caa063f312a086",
          "sha256": "3f1f5064f60ead25b805c8cb7cc36080dc4809c21203df56cc18ba5ecc9a5828",
          "sha1": "b0f067058bbcdd9cc81f23ce5a6670d1dc75480e",
          "md5": "1be2d5b53ab4db351fb917f7af1d95a2"
        }
      ]
    }
  ]
}
