{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-jvm/1.8.1-add-coroutine-util-SNAPSHOT/util-jvm-1.8.1-add-coroutine-util-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-jvm",
    "version": "1.8.1-add-coroutine-util-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "iz5ttph76nfalgh5ax2bsukur4"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-metadata-1.8.1-add-coroutine-util-SNAPSHOT.jar",
          "url": "util-metadata-1.8.1-add-coroutine-util-SNAPSHOT.jar",
          "size": 6309,
          "sha512": "62a515443a8267e648ad3b23673a2f3bd117fdf79f5b6cbebafa51751d252405193d598595ad5e4aede7179b97b02de6cabdcfe87c83305ea08ff6e9ecfb59d2",
          "sha256": "daa238d15697ac447c7b71b0f211dcbf8c1e4a5975d049aa4a3465311d27a28a",
          "sha1": "319dd993a17c6bf9cdf731c0e92622044996d879",
          "md5": "e36a59241c1242e50c091657628bc340"
        }
      ]
    }
  ]
}
