{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-jvm/1.8.1-add-coroutine-util-SNAPSHOT/util-jvm-1.8.1-add-coroutine-util-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-jvm",
    "version": "1.8.1-add-coroutine-util-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "3gxapi3hobc3za3qtxn6bz6taa"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-metadata-1.8.1-add-coroutine-util-SNAPSHOT.jar",
          "url": "util-metadata-1.8.1-add-coroutine-util-SNAPSHOT.jar",
          "size": 6309,
          "sha512": "9de91acce728482bb5926f7427ddc5ce9f06a14b7c0cb16a4efc80b057106393fab665ac8d073e68cce48046b8b06a21a9b8d7594413cb57d03615ff6355635e",
          "sha256": "574ac34da3ea00fd96446c4613ef1210d9b0310c5d09e90a989e04a5d45067e6",
          "sha1": "935456742830cf9502afa152411c8e7847f32c2a",
          "md5": "eb043dad8df7bb793f219193e4e661f0"
        }
      ]
    }
  ]
}
