{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.0-change-token-service-SNAPSHOT/data-donation-sdk-iosx64-0.1.0-change-token-service-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.0-change-token-service-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "uk6autkjzjgo3l4jwvwialrqbi"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.0-change-token-service-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.0-change-token-service-SNAPSHOT.jar",
          "size": 39787,
          "sha512": "25060a4cb834c19975e689a06b05c8cbdfde7be676889dc116e700bbee6124be21236e60f2614ee15ac29b7b70b9af234de76e8c91bc099fb5c7f4f8ca481e59",
          "sha256": "40437eda3b4eab93790cd529cd521770eb945d56b3f5330416c20dba5c7b7580",
          "sha1": "02835f9a8c4767db955898104ff5874a1e5facb0",
          "md5": "cd9da905cbde25a13cff6d83360a5e69"
        }
      ]
    }
  ]
}
