{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.0-change-token-service-SNAPSHOT/data-donation-sdk-iosx64-0.1.0-change-token-service-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.0-change-token-service-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ajbheuob5fai5inwum5r473zki"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.0-change-token-service-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.0-change-token-service-SNAPSHOT.jar",
          "size": 40358,
          "sha512": "c484dd00b3f05fdbf6ab67bce1659ba8c0c21d3f8b4fbf1c3e1bff4c9f2d24642ae0c0230a5e366c30508e1d36c2927e3c12496b71a540fc7047149b8fbc6003",
          "sha256": "1af6e88e655e1e84299556d8a22e207c39caec4fda374395f9bd06c6e10ad07d",
          "sha1": "70ef2af0e94136e34f2c145330a291809a875506",
          "md5": "3aed0d91fff1ce785dcf2d2fec1362f7"
        }
      ]
    }
  ]
}
