{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.0.4-change-exceptions-SNAPSHOT/data-donation-sdk-iosx64-0.0.4-change-exceptions-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.0.4-change-exceptions-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "flgej7znlfgetnnswsxhilczn4"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.4-change-exceptions-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.0.4-change-exceptions-SNAPSHOT.jar",
          "size": 70106,
          "sha512": "b4faa6fcb41c3febaa4cc5f42c9f1bfe51d6eda2dc1fd3783571c931ec8f5d064d3a966e84823b318f22fbe74d1e128bc8552a01bbf3260c2d8bb050a530ab0e",
          "sha256": "37959d3da7df013d4e186274ac55442cb89f5d4724679bab442e9a806bc1d3f1",
          "sha1": "7e03d52fd6cad1e7b95a7118dee534652b8da635",
          "md5": "2abe09464035a2d97a7645aefa1bbe6c"
        }
      ]
    }
  ]
}
