{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.0.4-change-exceptions-SNAPSHOT/data-donation-sdk-iosx64-0.0.4-change-exceptions-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.0.4-change-exceptions-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "cf5y6psuwzhwtoxctwpo7hsseu"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.4-change-exceptions-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.0.4-change-exceptions-SNAPSHOT.jar",
          "size": 69397,
          "sha512": "adc6c0d16deb40fc0304e038a8ec14bea6cd7b6274ac15c45dda59c9fd2ef83f477e93d00ace328e1d21a6473955c7cd625ffdba8fefbe1158cb7d826ad925ae",
          "sha256": "652d21c4b5097ed7ab7d2425d90e6c610d851422fd1a67c5a0798f512bd1907a",
          "sha1": "748d81ab4f354d189591f0b717ca31b61306e022",
          "md5": "c26e919653baeee8235af2d3cb843f8b"
        }
      ]
    }
  ]
}
