{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.13.1-change-attachment-service-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "zaek2pfilvcjla4x434qhxwmei"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.13.1-change-attachment-service-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.13.1-change-attachment-service-SNAPSHOT.jar",
          "url": "crypto-jvm-1.13.1-change-attachment-service-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "3200e96d901d9015a54276dfce2d1aa4995706b17df8d14499e92ccdf45874494278869a4c027869f9da45469fea7dd5ab88c1e16e807f416e2215680c828a53",
          "sha256": "389aac8f155c97a9c5b2c8a0b65a796f6453024f0446ebcc52001d5db4dec273",
          "sha1": "fc760591eb52c6794304103342d279f757c431e2",
          "md5": "8b6af82f41c23eca773a5ff076e5c90b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.13.1-change-attachment-service-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.13.1-change-attachment-service-SNAPSHOT.jar",
          "url": "crypto-jvm-1.13.1-change-attachment-service-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "3200e96d901d9015a54276dfce2d1aa4995706b17df8d14499e92ccdf45874494278869a4c027869f9da45469fea7dd5ab88c1e16e807f416e2215680c828a53",
          "sha256": "389aac8f155c97a9c5b2c8a0b65a796f6453024f0446ebcc52001d5db4dec273",
          "sha1": "fc760591eb52c6794304103342d279f757c431e2",
          "md5": "8b6af82f41c23eca773a5ff076e5c90b"
        }
      ]
    }
  ]
}
