{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.2.0-SNAPSHOT/data-donation-sdk-iosx64-0.2.0-SNAPSHOT.module",
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "pueuwsuweneuznxkbdhhh3uwou"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.2.0-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.2.0-SNAPSHOT.jar",
          "size": 58960,
          "sha512": "9a994746db222c17eaf634331ab0e66e47db8a6a0edfccf51dc66a542c039ae5d6ad1830c1dba6e87a22a79745bf0fe9db33ef7d7e553c8b96e27dd4d9fa5609",
          "sha256": "e03375981fc2e6a92a4d2a81aef122ecf6243ab80151ed94eacb0f291d6d051a",
          "sha1": "57ff1604959bd6523eb8e591a3ff3192cad04bf9",
          "md5": "c43942d7de41395dd616c5884acab8cf"
        }
      ]
    }
  ]
}
