{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.12.0-change-merge-fhir-and-data-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "3nw3hslqt5b5hfszqqqikkelpy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.12.0-change-merge-fhir-and-data-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.12.0-change-merge-fhir-and-data-SNAPSHOT.jar",
          "url": "crypto-jvm-1.12.0-change-merge-fhir-and-data-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "82295405bdbb19dd819d747c35509ee3bccb8219d40bfab1b1948a905626e86f92ed53c4bcc2dad02e6d82faff7d862a0f2f9603d473da574dad3ec3155742a6",
          "sha256": "f1fa120464bde445301929fe5d06857de20216c8fe0b375d3ec1b01d9471797a",
          "sha1": "1d01064acc9ca74b1ebc8ea1fe3b9d2272dbc2ba",
          "md5": "727d760844a8af896a4da8133e7a077f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.12.0-change-merge-fhir-and-data-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.12.0-change-merge-fhir-and-data-SNAPSHOT.jar",
          "url": "crypto-jvm-1.12.0-change-merge-fhir-and-data-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "82295405bdbb19dd819d747c35509ee3bccb8219d40bfab1b1948a905626e86f92ed53c4bcc2dad02e6d82faff7d862a0f2f9603d473da574dad3ec3155742a6",
          "sha256": "f1fa120464bde445301929fe5d06857de20216c8fe0b375d3ec1b01d9471797a",
          "sha1": "1d01064acc9ca74b1ebc8ea1fe3b9d2272dbc2ba",
          "md5": "727d760844a8af896a4da8133e7a077f"
        }
      ]
    }
  ]
}
