{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.0.5-bump-update-SNAPSHOT/data-donation-sdk-iosx64-0.0.5-bump-update-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.0.5-bump-update-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "3dqehtuspvgnjmxix3p6syxl4u"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.5-bump-update-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.0.5-bump-update-SNAPSHOT.jar",
          "size": 73678,
          "sha512": "e54ae0b8b3659e11db95b46420b78c6465f2b53152fa04fbd9eee11585835dca363922b84f77083ab85e8cbb4cfa96abf3641607553c02e03c523303f35dace1",
          "sha256": "2deadc26e84b073a71de3912f15752200ed57b48505ad0a830e89c3c36c4e590",
          "sha1": "f08f73f3e5821c830f5b439bcafa39104ebf2a50",
          "md5": "d176c67f76a3b47ab0e6417b4326544d"
        }
      ]
    }
  ]
}
