{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util/0.2.0-bump-updates-SNAPSHOT/test-util-0.2.0-bump-updates-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util",
    "version": "0.2.0-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "care.data4life.hc-objc-util-sdk-kmp",
          "module": "objc-util",
          "version": {
            "requires": "0.1.0-bump-kotlin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "test-util.klib",
          "url": "test-util-iosarm64-0.2.0-bump-updates-SNAPSHOT.klib",
          "size": 14751,
          "sha512": "2e710d1d5dd7d75b9d633aa2235b18971715cc58e7579f8051faa3773e6e2465f74f7970356a3480a6e7640aeaeaf6428853ec2571e3550b99abcc2e22901886",
          "sha256": "39f37a3c817980d7117c4b83335c8820b07d4025bd362496bdcfb4e4706ee67d",
          "sha1": "502a48dff35089563af7748d96f32d8153dce802",
          "md5": "7e0406dbc4e43382ec55f7e8b20ff268"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "care.data4life.hc-objc-util-sdk-kmp",
          "module": "objc-util",
          "version": {
            "requires": "0.1.0-bump-kotlin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-iosarm64-0.2.0-bump-updates-SNAPSHOT-metadata.jar",
          "url": "test-util-iosarm64-0.2.0-bump-updates-SNAPSHOT-metadata.jar",
          "size": 6886,
          "sha512": "4af9dd2d332f4afa986b1b1ecd73164f0d1964c2c2ff531c0538b9331a296437a81ab6618d043adc7bc7ae100593fcc4f2f5c24824a4a935e0246a69574d7c97",
          "sha256": "67509ee33b84cc877befc7196f77bcd78955756017364cbb421f7b5534cd91ca",
          "sha1": "988eb8f548c18b6a769d32217f4df1273934c32c",
          "md5": "e58386f7e952656224002f4fd78bcbbd"
        }
      ]
    }
  ]
}
