{
  "formatVersion": "1.1",
  "component": {
    "url": "../../example-kmp-library-jvm/0.0.1-change-coverage-for-coverage-plugin-SNAPSHOT/example-kmp-library-jvm-0.0.1-change-coverage-for-coverage-plugin-SNAPSHOT.module",
    "group": "care.data4life.hc-gradle-scripts",
    "module": "example-kmp-library-jvm",
    "version": "0.0.1-change-coverage-for-coverage-plugin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "jmbqyrhkvfflbktbjfqa5vtb5a"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "example-kmp-library-metadata-0.0.1-change-coverage-for-coverage-plugin-SNAPSHOT.jar",
          "url": "example-kmp-library-metadata-0.0.1-change-coverage-for-coverage-plugin-SNAPSHOT.jar",
          "size": 6554,
          "sha512": "295229e693b339a502b2fbd4104a02e3411163d1274bcccb28441422406abd19cdbb747d6c510e92340b7d65926bb9b6fbb9f5914b7bd10bea1461b5ea671f66",
          "sha256": "1d10ec739021a91a11268d9befa2411e2469d69789936f56b59eaaa05294a046",
          "sha1": "195d1768e1488509260474bc6814e1b24510624c",
          "md5": "7d49aa49ce68ffb94ed94b305151275b"
        }
      ]
    }
  ]
}
