{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.7.0-add-ios-branch-SNAPSHOT/util-1.7.0-add-ios-branch-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.7.0-add-ios-branch-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "klnhbnll7rfp7p5g4zaiqurmfq"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-jvm-1.7.0-add-ios-branch-SNAPSHOT.jar",
          "url": "util-jvm-1.7.0-add-ios-branch-SNAPSHOT.jar",
          "size": 19627,
          "sha512": "eb38fa4a16e73501e4719f5b1d4fc0f1443cca08522c945e986b8baacbbcd8c7b946d1b57ae86d5cf3cd4c0b42235a989349b4166ace36127f52186a5fd5d3cb",
          "sha256": "9953ceb35308a4a9d383d8f540dbfc43774a8bb12cc39517f846e3edb92a1653",
          "sha1": "cccb29017be1ac64ec4243b7114234c36e6e3522",
          "md5": "eec6757f952e5f8b89a014d35fc5b9ad"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "util-jvm-1.7.0-add-ios-branch-SNAPSHOT.jar",
          "url": "util-jvm-1.7.0-add-ios-branch-SNAPSHOT.jar",
          "size": 19627,
          "sha512": "eb38fa4a16e73501e4719f5b1d4fc0f1443cca08522c945e986b8baacbbcd8c7b946d1b57ae86d5cf3cd4c0b42235a989349b4166ace36127f52186a5fd5d3cb",
          "sha256": "9953ceb35308a4a9d383d8f540dbfc43774a8bb12cc39517f846e3edb92a1653",
          "sha1": "cccb29017be1ac64ec4243b7114234c36e6e3522",
          "md5": "eec6757f952e5f8b89a014d35fc5b9ad"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-metadata/1.7.0-add-ios-branch-SNAPSHOT/util-metadata-1.7.0-add-ios-branch-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-metadata",
        "version": "1.7.0-add-ios-branch-SNAPSHOT"
      }
    }
  ]
}
