{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.7.0-add-ios-branch-SNAPSHOT/util-1.7.0-add-ios-branch-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.7.0-add-ios-branch-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "l62zg4elmnfzpkuuhyftlofzuq"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-jvm-1.7.0-add-ios-branch-SNAPSHOT.jar",
          "url": "util-jvm-1.7.0-add-ios-branch-SNAPSHOT.jar",
          "size": 19627,
          "sha512": "9c91d736be2cc7e58ed63956f6f6382bb7afad7abdf107a96ff3d5a275947626002d41a6deb1868f809f0bf3388c50bcf2c5ea3b9c0b4fa56f6516c001d5d4aa",
          "sha256": "fc4acebb93376e9acbe115fe8b4bcd3200dccd25b63be48f10711ec747a6be0f",
          "sha1": "12261ba99e05034bae9e98e1084b4bdef37ae084",
          "md5": "44bf52ebe5346618c6e5c33da72c42a1"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "util-jvm-1.7.0-add-ios-branch-SNAPSHOT.jar",
          "url": "util-jvm-1.7.0-add-ios-branch-SNAPSHOT.jar",
          "size": 19627,
          "sha512": "9c91d736be2cc7e58ed63956f6f6382bb7afad7abdf107a96ff3d5a275947626002d41a6deb1868f809f0bf3388c50bcf2c5ea3b9c0b4fa56f6516c001d5d4aa",
          "sha256": "fc4acebb93376e9acbe115fe8b4bcd3200dccd25b63be48f10711ec747a6be0f",
          "sha1": "12261ba99e05034bae9e98e1084b4bdef37ae084",
          "md5": "44bf52ebe5346618c6e5c33da72c42a1"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-metadata/1.7.0-add-ios-branch-SNAPSHOT/util-metadata-1.7.0-add-ios-branch-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-metadata",
        "version": "1.7.0-add-ios-branch-SNAPSHOT"
      }
    }
  ]
}
