{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.11.0-fix-update-record-data-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "tnz6vgochzftdj2lib4llqdosm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.11.0-fix-update-record-data-SNAPSHOT.jar",
          "url": "securestore-common-1.11.0-fix-update-record-data-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "7155cf8e95141c3341c08ddc86ba1e4ecfafc59b21287853a7d766623d682b47a9bd06d49f413aa56114106e88d832d60700279a5c3bda05cd7fcf759f3f348f",
          "sha256": "be44981691f3007ef0f6afd16ead7e9212da9fe0630e7bd8062220e2d17905af",
          "sha1": "b7ebe4524d81744ec9f6eaef98dbcb96d9bdd548",
          "md5": "d9a38046250aef1d4a11e14aa6d14c82"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.11.0-fix-update-record-data-SNAPSHOT.jar",
          "url": "securestore-common-1.11.0-fix-update-record-data-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "7155cf8e95141c3341c08ddc86ba1e4ecfafc59b21287853a7d766623d682b47a9bd06d49f413aa56114106e88d832d60700279a5c3bda05cd7fcf759f3f348f",
          "sha256": "be44981691f3007ef0f6afd16ead7e9212da9fe0630e7bd8062220e2d17905af",
          "sha1": "b7ebe4524d81744ec9f6eaef98dbcb96d9bdd548",
          "md5": "d9a38046250aef1d4a11e14aa6d14c82"
        }
      ]
    }
  ]
}
