{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.3-change-setup-SNAPSHOT/data-donation-sdk-iosx64-0.1.3-change-setup-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.3-change-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "eshiyd3ao5ddjhn4tmsd523iz4"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.3-change-setup-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.3-change-setup-SNAPSHOT.jar",
          "size": 33909,
          "sha512": "6fbbc4c535beacd3cac3efdf4708229703512e53d263ca61a92b2a292823cdf4bd554315707469699351b485ab2267192ca3c87abe97654ee7d31439b48608e2",
          "sha256": "432e62a3c82aafe35e36fc3ee2fa54e04d60bbd496fed13479bcf89a75793e4a",
          "sha1": "7e8095e331a07e0232897bd1fdecc33cec78855e",
          "md5": "fed8b8d31725ee2122644a20396d3ac8"
        }
      ]
    }
  ]
}
