{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.12.0-change-resource-crypto-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "kk377b7zf5a5jnzbkhdj7iv3pe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.12.0-change-resource-crypto-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.12.0-change-resource-crypto-tests-SNAPSHOT.jar",
          "url": "auth-jvm-1.12.0-change-resource-crypto-tests-SNAPSHOT.jar",
          "size": 34318,
          "sha512": "ba254e00ea8021d6fc53cec76ac26c5d59198a456a9fd0a551bde539809ccf8ef9abb32897334c3f05fcff5da00c838132323a8077dbe7dd803e1e3f3e323231",
          "sha256": "d3e2b5f5a85f300dcfc428d4310c9037b39ae6e3180fb5a981afeea87fd6dbc3",
          "sha1": "c2e00dd6295953eacc6e66f0557f526eb912cdf1",
          "md5": "bc68cd0ffffb02d573d817b022406ea3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.12.0-change-resource-crypto-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.12.0-change-resource-crypto-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.12.0-change-resource-crypto-tests-SNAPSHOT.jar",
          "url": "auth-jvm-1.12.0-change-resource-crypto-tests-SNAPSHOT.jar",
          "size": 34318,
          "sha512": "ba254e00ea8021d6fc53cec76ac26c5d59198a456a9fd0a551bde539809ccf8ef9abb32897334c3f05fcff5da00c838132323a8077dbe7dd803e1e3f3e323231",
          "sha256": "d3e2b5f5a85f300dcfc428d4310c9037b39ae6e3180fb5a981afeea87fd6dbc3",
          "sha1": "c2e00dd6295953eacc6e66f0557f526eb912cdf1",
          "md5": "bc68cd0ffffb02d573d817b022406ea3"
        }
      ]
    }
  ]
}
