{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.0.4-remove-storage-layer-SNAPSHOT/data-donation-sdk-iosx64-0.0.4-remove-storage-layer-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.0.4-remove-storage-layer-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "jwvaytfd4rdyzgqqu6vmce5jsu"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.4-remove-storage-layer-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.0.4-remove-storage-layer-SNAPSHOT.jar",
          "size": 70926,
          "sha512": "999fff96c20f131c0f69a9bee40c7c8558f83cc776b4828019ac74db667b76925ca5346735f2406cc2d4be242345386154155d547967910bc7fb293dba6159ff",
          "sha256": "8070b0d9ea3a06483615775d144230a63963f717a3f8b25eef446ab0ca8b1684",
          "sha1": "22714fcb6d0e45181830da55874dda0a557565fb",
          "md5": "1bc1ca3f7f214e60efdfc009b7c9d7b1"
        }
      ]
    }
  ]
}
