{
  "formatVersion": "1.1",
  "component": {
    "url": "../../example-kmp-library-jvm/0.0.1-change-repo-ownership-SNAPSHOT/example-kmp-library-jvm-0.0.1-change-repo-ownership-SNAPSHOT.module",
    "group": "care.data4life.hc-gradle-scripts",
    "module": "example-kmp-library-jvm",
    "version": "0.0.1-change-repo-ownership-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "qedglqtu3feoplpsr6a2lg4klu"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "example-kmp-library-metadata-0.0.1-change-repo-ownership-SNAPSHOT.jar",
          "url": "example-kmp-library-metadata-0.0.1-change-repo-ownership-SNAPSHOT.jar",
          "size": 6554,
          "sha512": "ce3223830ea5ef2784e7e3a66631c7c48d444b90a77e25cedbbbd7d0a1a1e75e50a8e8df7aa3b1b436c485dc06a897a0e53f34628319652eb973eb6228a1ccde",
          "sha256": "a85ee7693f4169cc46ec341184a11615e14de53a1beffda45d03dcd87a962c5b",
          "sha1": "9aa241bb08a0dd7242ce96ee58bf663b52a50ccb",
          "md5": "451a71908ff39057dad3e77ef5370213"
        }
      ]
    }
  ]
}
