{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-test/1.8.1-change-util-test-SNAPSHOT/util-test-1.8.1-change-util-test-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-test",
    "version": "1.8.1-change-util-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "awtcvvijqnbcfgckt6ndkt2e5u"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-test-jvm-1.8.1-change-util-test-SNAPSHOT.jar",
          "url": "util-test-jvm-1.8.1-change-util-test-SNAPSHOT.jar",
          "size": 12812,
          "sha512": "4dc8421ec3b349d33ff50ec7f60d9a641c862898a2952acd8ab4267af88eb6a999c4f7e9b44e012bb04e6da561c1d12b4becacdd1f6937de4fd3c2bd7203babd",
          "sha256": "1786a76fc16a80f1b20cafdaa2e3de052dfaf8d55a8a2c297e1001f60dd7a84a",
          "sha1": "64a27c7b9bd11e4f8dd1f95232e980e00a2f9e0c",
          "md5": "8e4a21884cc025c48bfd0d700618383d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "util-test-jvm-1.8.1-change-util-test-SNAPSHOT.jar",
          "url": "util-test-jvm-1.8.1-change-util-test-SNAPSHOT.jar",
          "size": 12812,
          "sha512": "4dc8421ec3b349d33ff50ec7f60d9a641c862898a2952acd8ab4267af88eb6a999c4f7e9b44e012bb04e6da561c1d12b4becacdd1f6937de4fd3c2bd7203babd",
          "sha256": "1786a76fc16a80f1b20cafdaa2e3de052dfaf8d55a8a2c297e1001f60dd7a84a",
          "sha1": "64a27c7b9bd11e4f8dd1f95232e980e00a2f9e0c",
          "md5": "8e4a21884cc025c48bfd0d700618383d"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-test-metadata/1.8.1-change-util-test-SNAPSHOT/util-test-metadata-1.8.1-change-util-test-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-test-metadata",
        "version": "1.8.1-change-util-test-SNAPSHOT"
      }
    }
  ]
}
