{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-auth-sdk-kmp",
    "module": "auth",
    "version": "1.13.2-bump-app-auth-dependency-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "rq3yzetckvc2vd7bvwaddoj6oy"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "auth-metadata-1.13.2-bump-app-auth-dependency-SNAPSHOT.jar",
          "url": "auth-1.13.2-bump-app-auth-dependency-SNAPSHOT.jar",
          "size": 3764,
          "sha512": "285ba7e450d6853de6d75f09b7956aada30ceeecf03f40d041e433044ed0772efd56524c67d49a251e03f0f86d6a30f59eb91ae17630c1ee93dad33045f9b54a",
          "sha256": "43b7181966d17dceb42defa7f5fe0f357b858d8c3e844de6b650743e49e7f55a",
          "sha1": "5f582591728a3225e327a90cf4114cc1f2660237",
          "md5": "f5fa18ac82ee1c60f3977482f1a0466c"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../auth-android-debug/1.13.2-bump-app-auth-dependency-SNAPSHOT/auth-android-debug-1.13.2-bump-app-auth-dependency-SNAPSHOT.module",
        "group": "care.data4life.hc-auth-sdk-kmp",
        "module": "auth-android-debug",
        "version": "1.13.2-bump-app-auth-dependency-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../auth-android-debug/1.13.2-bump-app-auth-dependency-SNAPSHOT/auth-android-debug-1.13.2-bump-app-auth-dependency-SNAPSHOT.module",
        "group": "care.data4life.hc-auth-sdk-kmp",
        "module": "auth-android-debug",
        "version": "1.13.2-bump-app-auth-dependency-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../auth-android/1.13.2-bump-app-auth-dependency-SNAPSHOT/auth-android-1.13.2-bump-app-auth-dependency-SNAPSHOT.module",
        "group": "care.data4life.hc-auth-sdk-kmp",
        "module": "auth-android",
        "version": "1.13.2-bump-app-auth-dependency-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../auth-android/1.13.2-bump-app-auth-dependency-SNAPSHOT/auth-android-1.13.2-bump-app-auth-dependency-SNAPSHOT.module",
        "group": "care.data4life.hc-auth-sdk-kmp",
        "module": "auth-android",
        "version": "1.13.2-bump-app-auth-dependency-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../auth-jvm/1.13.2-bump-app-auth-dependency-SNAPSHOT/auth-jvm-1.13.2-bump-app-auth-dependency-SNAPSHOT.module",
        "group": "care.data4life.hc-auth-sdk-kmp",
        "module": "auth-jvm",
        "version": "1.13.2-bump-app-auth-dependency-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../auth-jvm/1.13.2-bump-app-auth-dependency-SNAPSHOT/auth-jvm-1.13.2-bump-app-auth-dependency-SNAPSHOT.module",
        "group": "care.data4life.hc-auth-sdk-kmp",
        "module": "auth-jvm",
        "version": "1.13.2-bump-app-auth-dependency-SNAPSHOT"
      }
    }
  ]
}
