{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-jvm",
    "version": "1.14.0-change-crypto-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "qtiqf7cs75cuxdusatwhwpa5gm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.14.0-change-crypto-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util"
            },
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.14.0-change-crypto-SNAPSHOT.jar",
          "url": "sdk-jvm-1.14.0-change-crypto-SNAPSHOT.jar",
          "size": 11637,
          "sha512": "6aa957d949b3ba45a212cae387896a84459f0fa751e68fd9070dfc40de0c6d5c3c02dab72d5c767dc101f151e4510ab74533cb0c853732000d3e3cc67200c6ad",
          "sha256": "b8f055523c48dd36a8b47ada3b870466f070c90eb984b14ec5068cfa80820686",
          "sha1": "cb1bd6f1066367bd5b4f1fd372dfca33c781cb75",
          "md5": "c472ffc0b93af2f07cb92e2ee4437e90"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.14.0-change-crypto-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.14.0-change-crypto-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.14.0-change-crypto-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.14.0-change-crypto-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util"
            },
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.14.0-change-crypto-SNAPSHOT.jar",
          "url": "sdk-jvm-1.14.0-change-crypto-SNAPSHOT.jar",
          "size": 11637,
          "sha512": "6aa957d949b3ba45a212cae387896a84459f0fa751e68fd9070dfc40de0c6d5c3c02dab72d5c767dc101f151e4510ab74533cb0c853732000d3e3cc67200c6ad",
          "sha256": "b8f055523c48dd36a8b47ada3b870466f070c90eb984b14ec5068cfa80820686",
          "sha1": "cb1bd6f1066367bd5b4f1fd372dfca33c781cb75",
          "md5": "c472ffc0b93af2f07cb92e2ee4437e90"
        }
      ]
    }
  ]
}
