{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-test/1.8.1-change-util-test-SNAPSHOT/util-test-1.8.1-change-util-test-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-test",
    "version": "1.8.1-change-util-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "awtcvvijqnbcfgckt6ndkt2e5u"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "util-test-debug.aar",
          "url": "util-test-android-debug-1.8.1-change-util-test-SNAPSHOT.aar",
          "size": 12284,
          "sha512": "85ca71267b089c489bec6339e7c603854fbf57e8fe9ffffb136f9da4d8080e0b2bfbf694712ec50f5c756fd955ca0c956f2a2a90ef4b251d456e754ae1ce924e",
          "sha256": "0e1aee98adde12916fa89cfe85f02ebb2b5f09ad50e080f73833aa54cc61deb4",
          "sha1": "825d500919c5f95271b0f259653164cde4c8f6dc",
          "md5": "105fbb10ac4207b0b78c5558d43396de"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "util-test-debug.aar",
          "url": "util-test-android-debug-1.8.1-change-util-test-SNAPSHOT.aar",
          "size": 12284,
          "sha512": "85ca71267b089c489bec6339e7c603854fbf57e8fe9ffffb136f9da4d8080e0b2bfbf694712ec50f5c756fd955ca0c956f2a2a90ef4b251d456e754ae1ce924e",
          "sha256": "0e1aee98adde12916fa89cfe85f02ebb2b5f09ad50e080f73833aa54cc61deb4",
          "sha1": "825d500919c5f95271b0f259653164cde4c8f6dc",
          "md5": "105fbb10ac4207b0b78c5558d43396de"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-test-metadata/1.8.1-change-util-test-SNAPSHOT/util-test-metadata-1.8.1-change-util-test-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-test-metadata",
        "version": "1.8.1-change-util-test-SNAPSHOT"
      }
    }
  ]
}
