{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.11.0-add-certificate-pinner-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "pcpk4mrtkjhhpp376j656fu4l4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-add-certificate-pinner-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-add-certificate-pinner-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "124296aa56b0c81c8f2bc43814c7f416b0f60a559e80fb0028e4a2fb661ace19105b1591002aaa825643baf0f53a9b900fc5bf88ed97e010b8ff5fa0e4df9284",
          "sha256": "36b04ad3aedbaaf80d81d03439f1fc7ac0f2d64072c1345e0c21e5fb5906eb8a",
          "sha1": "4c4d6e75c5d560cb66c003755b2927f7a3143bf9",
          "md5": "89c47697caeb18bef6a5abaeeb17fa54"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-add-certificate-pinner-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-add-certificate-pinner-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-add-certificate-pinner-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "124296aa56b0c81c8f2bc43814c7f416b0f60a559e80fb0028e4a2fb661ace19105b1591002aaa825643baf0f53a9b900fc5bf88ed97e010b8ff5fa0e4df9284",
          "sha256": "36b04ad3aedbaaf80d81d03439f1fc7ac0f2d64072c1345e0c21e5fb5906eb8a",
          "sha1": "4c4d6e75c5d560cb66c003755b2927f7a3143bf9",
          "md5": "89c47697caeb18bef6a5abaeeb17fa54"
        }
      ]
    }
  ]
}
