{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.2-change-revoke-errors-SNAPSHOT/data-donation-sdk-iosx64-0.1.2-change-revoke-errors-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.2-change-revoke-errors-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "pi3yuh33tnejtewduiamesxjpu"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.2-change-revoke-errors-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.2-change-revoke-errors-SNAPSHOT.jar",
          "size": 39139,
          "sha512": "c72e085bd6f17c853afad19894d53331ceb742139daf2f2ac3e8a1f05e525ae42a6e93fdb6e4f7cb1148e2f1ba191343b67a5d6c13f904b96b932b0f5b86ab35",
          "sha256": "738e8dba0933a0cff6a87be63002a25d3d11feefcb1c05f3f20c0a508d18a2b1",
          "sha1": "26e338fc25fd769f9f182d740c4514be886fe573",
          "md5": "eed59f42ca4e469b3d4a3e8fbdb4de93"
        }
      ]
    }
  ]
}
