{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-ktor-test/1.9.0-add-default-scope-SNAPSHOT/util-ktor-test-1.9.0-add-default-scope-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-ktor-test",
    "version": "1.9.0-add-default-scope-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "lywpjsvcsfhm7mjwnl7aytkyki"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-ktor-test-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "url": "util-ktor-test-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "size": 28641,
          "sha512": "89d4d65475f018e58dde63b04e782e5dd0a585b9c1b492c28546fb7e6cf2da3e51bd52ee7e3f3e6cf96afdefe03f4cbf729ec3857ce307dc57351801fe136a78",
          "sha256": "8f4ed366f36a890314d87fb6597e0f0e46858a191a9a5b81e465873a7b6207cc",
          "sha1": "be924dcf03a80db19208d27c122203c2222bd04d",
          "md5": "60eed47cf9ad8a1070167f4e95968545"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "util-ktor-test-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "url": "util-ktor-test-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "size": 28641,
          "sha512": "89d4d65475f018e58dde63b04e782e5dd0a585b9c1b492c28546fb7e6cf2da3e51bd52ee7e3f3e6cf96afdefe03f4cbf729ec3857ce307dc57351801fe136a78",
          "sha256": "8f4ed366f36a890314d87fb6597e0f0e46858a191a9a5b81e465873a7b6207cc",
          "sha1": "be924dcf03a80db19208d27c122203c2222bd04d",
          "md5": "60eed47cf9ad8a1070167f4e95968545"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-ktor-test-metadata/1.9.0-add-default-scope-SNAPSHOT/util-ktor-test-metadata-1.9.0-add-default-scope-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-ktor-test-metadata",
        "version": "1.9.0-add-default-scope-SNAPSHOT"
      }
    }
  ]
}
