{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-ktor-test/1.9.0-add-default-scope-SNAPSHOT/util-ktor-test-1.9.0-add-default-scope-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-ktor-test",
    "version": "1.9.0-add-default-scope-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "2xarvvrfhrgnbbv6sjw2f2mcti"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-ktor-test-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "url": "util-ktor-test-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "size": 28641,
          "sha512": "ad24dec97bbdb6702c5e0555d6c88f61f1db644483a552ea17c925219fa169654db1358f7308037f2ff1c58d3da674ab6a4e44feff6535b706e16cef85082ebb",
          "sha256": "14a5038d1a62d8b3286d51428eeca72bfbf8bbbe98c383a6db5f636563906f88",
          "sha1": "9bcfdc697575f7d78457247be6146eda46d3ec8b",
          "md5": "fc775b9f17af694f5e84faced16cc3c5"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "util-ktor-test-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "url": "util-ktor-test-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "size": 28641,
          "sha512": "ad24dec97bbdb6702c5e0555d6c88f61f1db644483a552ea17c925219fa169654db1358f7308037f2ff1c58d3da674ab6a4e44feff6535b706e16cef85082ebb",
          "sha256": "14a5038d1a62d8b3286d51428eeca72bfbf8bbbe98c383a6db5f636563906f88",
          "sha1": "9bcfdc697575f7d78457247be6146eda46d3ec8b",
          "md5": "fc775b9f17af694f5e84faced16cc3c5"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-ktor-test-metadata/1.9.0-add-default-scope-SNAPSHOT/util-ktor-test-metadata-1.9.0-add-default-scope-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-ktor-test-metadata",
        "version": "1.9.0-add-default-scope-SNAPSHOT"
      }
    }
  ]
}
