{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-ktor-test/1.9.0-add-default-scope-SNAPSHOT/util-ktor-test-1.9.0-add-default-scope-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-ktor-test",
    "version": "1.9.0-add-default-scope-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "xenom24cxna5hikpnifc4jf6lu"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-ktor-test-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "url": "util-ktor-test-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "size": 28641,
          "sha512": "a6c6fc728ae22f08f07d3a2cacff6c234ec3a4dfdc848d368c699209bf9242fa9d8c271b2fc78a9431f2bc3ca37603a1be91ffd194accf6eaf934846d2c28217",
          "sha256": "26d908167642dfdfc4c64041805a9ffcc404fb450681c2f5a91f9142a0361051",
          "sha1": "cde9566bf2af89d0d691777510f78afee06f11a8",
          "md5": "dc0b7f26672348b71a34919fd3ab2ccb"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "util-ktor-test-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "url": "util-ktor-test-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "size": 28641,
          "sha512": "a6c6fc728ae22f08f07d3a2cacff6c234ec3a4dfdc848d368c699209bf9242fa9d8c271b2fc78a9431f2bc3ca37603a1be91ffd194accf6eaf934846d2c28217",
          "sha256": "26d908167642dfdfc4c64041805a9ffcc404fb450681c2f5a91f9142a0361051",
          "sha1": "cde9566bf2af89d0d691777510f78afee06f11a8",
          "md5": "dc0b7f26672348b71a34919fd3ab2ccb"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-ktor-test-metadata/1.9.0-add-default-scope-SNAPSHOT/util-ktor-test-metadata-1.9.0-add-default-scope-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-ktor-test-metadata",
        "version": "1.9.0-add-default-scope-SNAPSHOT"
      }
    }
  ]
}
