{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-ktor-test/1.9.0-add-default-scope-SNAPSHOT/util-ktor-test-1.9.0-add-default-scope-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-ktor-test",
    "version": "1.9.0-add-default-scope-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "fncgrx3r7jc7zf3yari5cu3qpm"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-ktor-test-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "url": "util-ktor-test-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "size": 28641,
          "sha512": "404dca8e793814ce65e98f32f4c9e18d1f932f3d904e502acb6cbe0dac6a1d20ff937fd7b465505e147e68cf33025e3ea7d2a076584d748cbff9d317f4dcaa73",
          "sha256": "a1715791bef5d180f6c50d53e08d3a13840d5bbaa83a0e2baf7cfcd8d5d6f159",
          "sha1": "2755f6af31e67498af816a3ce5bf3fbbe3cca2ba",
          "md5": "eab8860aa0ad3123293b5b91ba624dd3"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "util-ktor-test-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "url": "util-ktor-test-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "size": 28641,
          "sha512": "404dca8e793814ce65e98f32f4c9e18d1f932f3d904e502acb6cbe0dac6a1d20ff937fd7b465505e147e68cf33025e3ea7d2a076584d748cbff9d317f4dcaa73",
          "sha256": "a1715791bef5d180f6c50d53e08d3a13840d5bbaa83a0e2baf7cfcd8d5d6f159",
          "sha1": "2755f6af31e67498af816a3ce5bf3fbbe3cca2ba",
          "md5": "eab8860aa0ad3123293b5b91ba624dd3"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-ktor-test-metadata/1.9.0-add-default-scope-SNAPSHOT/util-ktor-test-metadata-1.9.0-add-default-scope-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-ktor-test-metadata",
        "version": "1.9.0-add-default-scope-SNAPSHOT"
      }
    }
  ]
}
