{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-ktor-test/1.9.0-add-default-scope-SNAPSHOT/util-ktor-test-1.9.0-add-default-scope-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-ktor-test",
    "version": "1.9.0-add-default-scope-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ub7iyfeu25gibj6q2xbe5zn4x4"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-ktor-test-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "url": "util-ktor-test-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "size": 28641,
          "sha512": "a2f82e8320b1ceac73d1f09c9a0886dd83293ce1b24cf6834e77a4deb41cf6d722c9e95882e10254086f6632278c9836bbe3c9d943ced8052f84301aead4f4a5",
          "sha256": "9d77ff0f10d97ebffcaf7452e212f2d161e4d6f2c930541096680718aa4dd382",
          "sha1": "a7866295d43c387ab3ea5edba286c1ae87fbb0a0",
          "md5": "f03f851cb62f893b7560d345bd3d8bdb"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "util-ktor-test-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "url": "util-ktor-test-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "size": 28641,
          "sha512": "a2f82e8320b1ceac73d1f09c9a0886dd83293ce1b24cf6834e77a4deb41cf6d722c9e95882e10254086f6632278c9836bbe3c9d943ced8052f84301aead4f4a5",
          "sha256": "9d77ff0f10d97ebffcaf7452e212f2d161e4d6f2c930541096680718aa4dd382",
          "sha1": "a7866295d43c387ab3ea5edba286c1ae87fbb0a0",
          "md5": "f03f851cb62f893b7560d345bd3d8bdb"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-ktor-test-metadata/1.9.0-add-default-scope-SNAPSHOT/util-ktor-test-metadata-1.9.0-add-default-scope-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-ktor-test-metadata",
        "version": "1.9.0-add-default-scope-SNAPSHOT"
      }
    }
  ]
}
