{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk/0.0.3-create-and-revoke-consent-supporting-custom-key-SNAPSHOT/data-donation-sdk-0.0.3-create-and-revoke-consent-supporting-custom-key-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk",
    "version": "0.0.3-create-and-revoke-consent-supporting-custom-key-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "btp54uqyqrddxmgsnb77k3h2hm"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "data-donation-sdk-debug.aar",
          "url": "data-donation-sdk-android-debug-0.0.3-create-and-revoke-consent-supporting-custom-key-SNAPSHOT.aar",
          "size": 411309,
          "sha512": "51e95f54a59a568ad38d8e8b7dc943f3499458bd9c5e3a0e42b9f7dd73b88ae72fffb56c702679d38d69ffd663d25250477e822b9dc8ca89d8be62d7cccf6b00",
          "sha256": "be485c05b5ae9ba5b4958cea9da95c30f2c955f267262f2fd2899fca9eb6a96f",
          "sha1": "ee37fa65adba35d19083579f6ea477b9af947059",
          "md5": "1fb1fdca33bf52ffffd931c319bf56db"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.2-native-mt"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.jakewharton.threetenabp",
          "module": "threetenabp",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization-jvm",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core-jvm",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2-native-mt"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-kmp",
          "module": "fhir",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "data-donation-sdk-debug.aar",
          "url": "data-donation-sdk-android-debug-0.0.3-create-and-revoke-consent-supporting-custom-key-SNAPSHOT.aar",
          "size": 411309,
          "sha512": "51e95f54a59a568ad38d8e8b7dc943f3499458bd9c5e3a0e42b9f7dd73b88ae72fffb56c702679d38d69ffd663d25250477e822b9dc8ca89d8be62d7cccf6b00",
          "sha256": "be485c05b5ae9ba5b4958cea9da95c30f2c955f267262f2fd2899fca9eb6a96f",
          "sha1": "ee37fa65adba35d19083579f6ea477b9af947059",
          "md5": "1fb1fdca33bf52ffffd931c319bf56db"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../data-donation-sdk-metadata/0.0.3-create-and-revoke-consent-supporting-custom-key-SNAPSHOT/data-donation-sdk-metadata-0.0.3-create-and-revoke-consent-supporting-custom-key-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-metadata",
        "version": "0.0.3-create-and-revoke-consent-supporting-custom-key-SNAPSHOT"
      }
    }
  ]
}
