{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk",
    "version": "0.2.1-change-project-setup-to-latest-iteration-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "xgxsdrwo4bef5c65then5vktgq"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.2.1-change-project-setup-to-latest-iteration-SNAPSHOT.jar",
          "url": "data-donation-sdk-0.2.1-change-project-setup-to-latest-iteration-SNAPSHOT.jar",
          "size": 60014,
          "sha512": "e48d1ce803bfdea66a14c603df98f4188f54b957a18181b8c871f8d468c048b8489c490e6049a5d436117e26970c60ecf215f296802efafe8eb136a051d9b10e",
          "sha256": "541da59c593df846ff6f04bc09aeadfb9bbe3c26eaf570e59959c6f9b57c7a81",
          "sha1": "c3d41d53e54cd553172286d544992bd463bb9e1a",
          "md5": "f2e8e15e3feaaf9d83cfca77386cd597"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android-debug/0.2.1-change-project-setup-to-latest-iteration-SNAPSHOT/data-donation-sdk-android-debug-0.2.1-change-project-setup-to-latest-iteration-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android-debug",
        "version": "0.2.1-change-project-setup-to-latest-iteration-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android-debug/0.2.1-change-project-setup-to-latest-iteration-SNAPSHOT/data-donation-sdk-android-debug-0.2.1-change-project-setup-to-latest-iteration-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android-debug",
        "version": "0.2.1-change-project-setup-to-latest-iteration-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android/0.2.1-change-project-setup-to-latest-iteration-SNAPSHOT/data-donation-sdk-android-0.2.1-change-project-setup-to-latest-iteration-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android",
        "version": "0.2.1-change-project-setup-to-latest-iteration-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android/0.2.1-change-project-setup-to-latest-iteration-SNAPSHOT/data-donation-sdk-android-0.2.1-change-project-setup-to-latest-iteration-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android",
        "version": "0.2.1-change-project-setup-to-latest-iteration-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../data-donation-sdk-iosarm64/0.2.1-change-project-setup-to-latest-iteration-SNAPSHOT/data-donation-sdk-iosarm64-0.2.1-change-project-setup-to-latest-iteration-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-iosarm64",
        "version": "0.2.1-change-project-setup-to-latest-iteration-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../data-donation-sdk-iosx64/0.2.1-change-project-setup-to-latest-iteration-SNAPSHOT/data-donation-sdk-iosx64-0.2.1-change-project-setup-to-latest-iteration-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-iosx64",
        "version": "0.2.1-change-project-setup-to-latest-iteration-SNAPSHOT"
      }
    }
  ]
}
