{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk/0.0.4-remove-donation-methods-SNAPSHOT/data-donation-sdk-0.0.4-remove-donation-methods-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk",
    "version": "0.0.4-remove-donation-methods-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "3bbeggvt6ze2ngufl7nyekqu6e"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-kmp",
          "module": "fhir",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.4.3-native-mt",
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-ios",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "data-donation-sdk.klib",
          "url": "data-donation-sdk-iosarm64-0.0.4-remove-donation-methods-SNAPSHOT.klib",
          "size": 224354,
          "sha512": "bfa7e2cc7a12bb94044825a88fa6d5ae5bb0cfe5e35bc11147c50ffcbf316b3098fc38f55097decb71f451272b875e6307929ec45050888a1c8c28c629e92d11",
          "sha256": "f7dde6705df48d4c879ea60d6d88c83a5e4e57c5ce7a99eeb51ad179bc00775e",
          "sha1": "c5d20e7b717669c0608ef1883e09b21efc07fd09",
          "md5": "009d2f344cf300287206150902a8c885"
        },
        {
          "name": "data-donation-sdk-cinterop-iOSCryptoDD.klib",
          "url": "data-donation-sdk-iosarm64-0.0.4-remove-donation-methods-SNAPSHOT-cinterop-iOSCryptoDD.klib",
          "size": 4269780,
          "sha512": "aa1d7654ec4a92532bd1282e4f06ac2096df12ddfd688357f75ce141e313d8518b2dedd849ffdc9c1e957010c5a4631032d7419cfd400d4cce7d87e8cd0456b6",
          "sha256": "c7a4108a8ad8c331386e67ad66dce951e559dc24709d7a5eda6b990bb66a3fdb",
          "sha1": "7a04ca433710a23c60865b32bac5c15120cd165d",
          "md5": "862f36ba187e6bee7372505d0831ab44"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../data-donation-sdk-metadata/0.0.4-remove-donation-methods-SNAPSHOT/data-donation-sdk-metadata-0.0.4-remove-donation-methods-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-metadata",
        "version": "0.0.4-remove-donation-methods-SNAPSHOT"
      }
    }
  ]
}
