{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.0.3-add-call-builder-SNAPSHOT/data-donation-sdk-iosx64-0.0.3-add-call-builder-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.0.3-add-call-builder-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "5vlqteyy4vbgtotxonst3xdgbe"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.3-add-call-builder-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.0.3-add-call-builder-SNAPSHOT.jar",
          "size": 72894,
          "sha512": "e4b9d607e5820563787ce873f2589005983dfdb907d63799c0aef48412aefcc75e84ac9cafb00c59b7df9a0745be0728fe6b451ec1e4d33053cea20076387165",
          "sha256": "f5527cf52a7627579d38f2c778334c3236a6880278788caae4be0e494dde2d4e",
          "sha1": "38c46aae9a95b3dda66f7f2df495722853ff4011",
          "md5": "8e4e880030f8c4ae5525477b4e0aeeb0"
        }
      ]
    }
  ]
}
