{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk",
    "version": "0.0.2-add-debug-release-2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "cfmoxei3jfechiubpwwow6moz4"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.2-add-debug-release-2-SNAPSHOT.jar",
          "url": "data-donation-sdk-0.0.2-add-debug-release-2-SNAPSHOT.jar",
          "size": 63040,
          "sha512": "4256507ec08e00ab543e743a850edf6a731bc7de1715b5883e77587c488fef24f70338820c40959d405cd17987747540c2e87a21803e2e62fe12880e44a15ac9",
          "sha256": "047ca77cfef50bb4a2639b4ffcb0d60ef2f9f27286e5e600fad0d22a5be8511c",
          "sha1": "52c0a1d572c39cddbaadfee8db55ffd54a4f77d9",
          "md5": "85f50679898865ce7984df0b660160ad"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android/0.0.2-add-debug-release-2-SNAPSHOT/data-donation-sdk-android-0.0.2-add-debug-release-2-SNAPSHOT.module",
        "group": "care.data4life",
        "module": "data-donation-sdk-android",
        "version": "0.0.2-add-debug-release-2-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android/0.0.2-add-debug-release-2-SNAPSHOT/data-donation-sdk-android-0.0.2-add-debug-release-2-SNAPSHOT.module",
        "group": "care.data4life",
        "module": "data-donation-sdk-android",
        "version": "0.0.2-add-debug-release-2-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android/0.0.2-add-debug-release-2-SNAPSHOT/data-donation-sdk-android-0.0.2-add-debug-release-2-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android",
        "version": "0.0.2-add-debug-release-2-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android/0.0.2-add-debug-release-2-SNAPSHOT/data-donation-sdk-android-0.0.2-add-debug-release-2-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android",
        "version": "0.0.2-add-debug-release-2-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../data-donation-sdk-iosarm64/0.0.2-add-debug-release-2-SNAPSHOT/data-donation-sdk-iosarm64-0.0.2-add-debug-release-2-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-iosarm64",
        "version": "0.0.2-add-debug-release-2-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../data-donation-sdk-iosx64/0.0.2-add-debug-release-2-SNAPSHOT/data-donation-sdk-iosx64-0.0.2-add-debug-release-2-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-iosx64",
        "version": "0.0.2-add-debug-release-2-SNAPSHOT"
      }
    }
  ]
}
