{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "c34zg3yi5bay5gf7r4uecrpjhq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.11.0-SNAPSHOT.jar",
          "url": "securestore-common-1.11.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "626febcbfe1f77c72a2803187cb41ce20e9ba4c713a6397c689df59bfb6bc40a24981b2a35a9552103fdb258fb431c44fd05cedfd2bc2797e614422984db4687",
          "sha256": "080b2c747038976fae2ea31b266d3a4890582af6fc73b558f08afd7131f635e4",
          "sha1": "bd72487296fef01fc06ab940b832961e199ee94f",
          "md5": "188cb91992dd40a7c65a939d2b1124b0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.11.0-SNAPSHOT.jar",
          "url": "securestore-common-1.11.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "626febcbfe1f77c72a2803187cb41ce20e9ba4c713a6397c689df59bfb6bc40a24981b2a35a9552103fdb258fb431c44fd05cedfd2bc2797e614422984db4687",
          "sha256": "080b2c747038976fae2ea31b266d3a4890582af6fc73b558f08afd7131f635e4",
          "sha1": "bd72487296fef01fc06ab940b832961e199ee94f",
          "md5": "188cb91992dd40a7c65a939d2b1124b0"
        }
      ]
    }
  ]
}
