{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.11.0-bump-desugar-SNAPSHOT/util-1.11.0-bump-desugar-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.11.0-bump-desugar-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "util.klib",
          "url": "util-iosarm64-1.11.0-bump-desugar-SNAPSHOT.klib",
          "size": 24862,
          "sha512": "dc0d82d16ae5d91e1b0dafeee6caa7744b6b0627f372288b5e5fcd4b99268493be29975883a860a08d52c7a0b249994f3717a798d0153d77c8ed3d013aef7c35",
          "sha256": "e2c4115a3e4c3b923d160fc6f59dd6d128fa19bb3bdda462b54542792ea04fc5",
          "sha1": "98c855243c966ad0276f52e0c3571577395728b2",
          "md5": "ca35cd0e7e4b827efa61e261d1c4e954"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "util-iosarm64-1.11.0-bump-desugar-SNAPSHOT-metadata.jar",
          "url": "util-iosarm64-1.11.0-bump-desugar-SNAPSHOT-metadata.jar",
          "size": 6110,
          "sha512": "3a04abafd8596d2427040327490d6bb85166e3b8ac3403ad3bafa43e34aa36bf0fa0bf9b3d2e81af4253e3d0839a8bb1c8243e76c21af4e2ef25dfb0d66c1be5",
          "sha256": "e4ec4d8af0da748cd486b7bbdc0be2aa52754f4ef8a8eb50c42465aa1a447fa3",
          "sha1": "c392c7293200d5ee653ab3b73db0ee0179d9e063",
          "md5": "c2bf23878b1a1f71b3b3268ddfebad8d"
        }
      ]
    }
  ]
}
