{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.11.0-bump-desugar-SNAPSHOT/util-1.11.0-bump-desugar-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.11.0-bump-desugar-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "util.klib",
          "url": "util-iosarm64-1.11.0-bump-desugar-SNAPSHOT.klib",
          "size": 24862,
          "sha512": "dc0d82d16ae5d91e1b0dafeee6caa7744b6b0627f372288b5e5fcd4b99268493be29975883a860a08d52c7a0b249994f3717a798d0153d77c8ed3d013aef7c35",
          "sha256": "e2c4115a3e4c3b923d160fc6f59dd6d128fa19bb3bdda462b54542792ea04fc5",
          "sha1": "98c855243c966ad0276f52e0c3571577395728b2",
          "md5": "ca35cd0e7e4b827efa61e261d1c4e954"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "util-iosarm64-1.11.0-bump-desugar-SNAPSHOT-metadata.jar",
          "url": "util-iosarm64-1.11.0-bump-desugar-SNAPSHOT-metadata.jar",
          "size": 6110,
          "sha512": "3519e9d6bac289c106bbb1204a49c75a407439b4fdb799b39edad5072e6ed4f3a7bdcf51c7e0e283938d84604a031cf41f230341541f716cb5d320c9dbf6f674",
          "sha256": "208fdec905e3b029a054617470ac40167e12845a5c34f73875d943ac632db0a0",
          "sha1": "be5bf5a492cb5c12828bedd60387330ab34bbcfe",
          "md5": "be009fabbc8579537187f75681627359"
        }
      ]
    }
  ]
}
