{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.0.3-fix-ios-test-setup-SNAPSHOT/data-donation-sdk-iosx64-0.0.3-fix-ios-test-setup-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.0.3-fix-ios-test-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "chvclxdjiram5ae7osyfdnym7i"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.3-fix-ios-test-setup-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.0.3-fix-ios-test-setup-SNAPSHOT.jar",
          "size": 63773,
          "sha512": "98dbefd3244521ef53a61d70b4d9cc0718633539fc87e905df32042e3c6a8ca02b0f74f303053c8cd5c558c84e8d6ba61ad74cf16a22314448c691335a33d047",
          "sha256": "d15457a2b5271d3140913e130c811f653a0e40eb15a95d4df70a7aed3cdce15a",
          "sha1": "8314931dae37178e4f30072b059b90f2c86c3d71",
          "md5": "bde4763e75783729ed9a509e81d0c095"
        }
      ]
    }
  ]
}
