{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-jvm",
    "version": "1.13.2-add-coverage-android-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "y3j7a5h4nfdddcw7tuhxprx55e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.13.2-add-coverage-android-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.13.2-add-coverage-android-SNAPSHOT.jar",
          "url": "sdk-jvm-1.13.2-add-coverage-android-SNAPSHOT.jar",
          "size": 11645,
          "sha512": "993bcf640b99be65e84b9c722b34f7a98cc6af833229ec9981059f558a7dbe62a30e7757f1a1f66b57b3ee8d4eef076eb30ee865d276080fc3987b81920afa45",
          "sha256": "21d0acd5308a22f14f8998d380dd0472f69089d7b1360658a134e7496759127a",
          "sha1": "b10526c9f25f3a9028e69e39785480ce8f93f0be",
          "md5": "e7762250875cb64058e6638d657ee1d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.13.2-add-coverage-android-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.13.2-add-coverage-android-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.13.2-add-coverage-android-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.13.2-add-coverage-android-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.13.2-add-coverage-android-SNAPSHOT.jar",
          "url": "sdk-jvm-1.13.2-add-coverage-android-SNAPSHOT.jar",
          "size": 11645,
          "sha512": "993bcf640b99be65e84b9c722b34f7a98cc6af833229ec9981059f558a7dbe62a30e7757f1a1f66b57b3ee8d4eef076eb30ee865d276080fc3987b81920afa45",
          "sha256": "21d0acd5308a22f14f8998d380dd0472f69089d7b1360658a134e7496759127a",
          "sha1": "b10526c9f25f3a9028e69e39785480ce8f93f0be",
          "md5": "e7762250875cb64058e6638d657ee1d4"
        }
      ]
    }
  ]
}
