{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk",
    "version": "0.1.3-add-objc-crypto-wrapper-lib-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "damznvfgnjhcfg5n557j3hje4m"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.3-add-objc-crypto-wrapper-lib-SNAPSHOT.jar",
          "url": "data-donation-sdk-0.1.3-add-objc-crypto-wrapper-lib-SNAPSHOT.jar",
          "size": 33909,
          "sha512": "06b11d5412158ea5d195f8867e53919a371c7746230ed0c5f73ddcc80e6b7736f1d34604c16dd7552aa0938e517e24a67a4697ab728137a20b580e04ec7d6cc5",
          "sha256": "7514737555af59b1a7891830643b03e4a3e3f98946b69732316429acdc4c8b96",
          "sha1": "403d18f37a3fd9237111be14b3d1f6c8fb80fbf3",
          "md5": "ab985786fd58fc0511382a5d86c6dbce"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android-debug/0.1.3-add-objc-crypto-wrapper-lib-SNAPSHOT/data-donation-sdk-android-debug-0.1.3-add-objc-crypto-wrapper-lib-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android-debug",
        "version": "0.1.3-add-objc-crypto-wrapper-lib-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android-debug/0.1.3-add-objc-crypto-wrapper-lib-SNAPSHOT/data-donation-sdk-android-debug-0.1.3-add-objc-crypto-wrapper-lib-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android-debug",
        "version": "0.1.3-add-objc-crypto-wrapper-lib-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android/0.1.3-add-objc-crypto-wrapper-lib-SNAPSHOT/data-donation-sdk-android-0.1.3-add-objc-crypto-wrapper-lib-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android",
        "version": "0.1.3-add-objc-crypto-wrapper-lib-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android/0.1.3-add-objc-crypto-wrapper-lib-SNAPSHOT/data-donation-sdk-android-0.1.3-add-objc-crypto-wrapper-lib-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android",
        "version": "0.1.3-add-objc-crypto-wrapper-lib-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../data-donation-sdk-iosarm64/0.1.3-add-objc-crypto-wrapper-lib-SNAPSHOT/data-donation-sdk-iosarm64-0.1.3-add-objc-crypto-wrapper-lib-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-iosarm64",
        "version": "0.1.3-add-objc-crypto-wrapper-lib-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../data-donation-sdk-iosx64/0.1.3-add-objc-crypto-wrapper-lib-SNAPSHOT/data-donation-sdk-iosx64-0.1.3-add-objc-crypto-wrapper-lib-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-iosx64",
        "version": "0.1.3-add-objc-crypto-wrapper-lib-SNAPSHOT"
      }
    }
  ]
}
