{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.3-add-objc-crypto-wrapper-lib-SNAPSHOT/data-donation-sdk-iosx64-0.1.3-add-objc-crypto-wrapper-lib-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.3-add-objc-crypto-wrapper-lib-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "kq6l27ovl5bjnfarneka6ujqju"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.3-add-objc-crypto-wrapper-lib-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.3-add-objc-crypto-wrapper-lib-SNAPSHOT.jar",
          "size": 33955,
          "sha512": "63711e15e0d6a969338223b8297e20d4ab578ee67c572b58bb34c5f32cf3428a3d1478a1f7cc5a78086c778420b6118fcb9104fd570ed36107a5c929141f507f",
          "sha256": "ba8441e1af30312dd06a290ec2a34289a71240a3d7058fcbadc7946beb792416",
          "sha1": "8a5822daf3a5808281ff3150c721101beca470f1",
          "md5": "03b975fdc4709bd35f989bce79864c33"
        }
      ]
    }
  ]
}
