{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.11.0-change-update-data-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "tiozloarwrf45fq3tp77gskryy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-change-update-data-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.11.0-change-update-data-SNAPSHOT.jar",
          "url": "auth-jvm-1.11.0-change-update-data-SNAPSHOT.jar",
          "size": 34283,
          "sha512": "11fa08ca164b896faf8e90d25536e7b024b0075741e8c5b09fbea91323ed5b985d09e34ca112bb7198623ca0a61a20069981eb75fd1e83f7492e7731fbf141c8",
          "sha256": "8f11ba7e654d7e98ae64c2a31acdc22f514a193cadf8f03b247ca3fc8c40aa91",
          "sha1": "d902ffcfbafe981791dc6b110d07a45ad6b4f08d",
          "md5": "73504251dbb272d2213e3143cd020905"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.11.0-change-update-data-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-change-update-data-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.11.0-change-update-data-SNAPSHOT.jar",
          "url": "auth-jvm-1.11.0-change-update-data-SNAPSHOT.jar",
          "size": 34283,
          "sha512": "11fa08ca164b896faf8e90d25536e7b024b0075741e8c5b09fbea91323ed5b985d09e34ca112bb7198623ca0a61a20069981eb75fd1e83f7492e7731fbf141c8",
          "sha256": "8f11ba7e654d7e98ae64c2a31acdc22f514a193cadf8f03b247ca3fc8c40aa91",
          "sha1": "d902ffcfbafe981791dc6b110d07a45ad6b4f08d",
          "md5": "73504251dbb272d2213e3143cd020905"
        }
      ]
    }
  ]
}
