{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.8.1-change-util-test-SNAPSHOT/util-1.8.1-change-util-test-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.8.1-change-util-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "awtcvvijqnbcfgckt6ndkt2e5u"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-jvm-1.8.1-change-util-test-SNAPSHOT.jar",
          "url": "util-jvm-1.8.1-change-util-test-SNAPSHOT.jar",
          "size": 19627,
          "sha512": "e0bdb7c9544c217f8c5ccab2147b87b0688d66f728580bbf2af131593cdaff380f5ef40954d221a3fe679456b9b41fa9b459763b94e767f68121ddec80a63b5b",
          "sha256": "0cddd0a69be3d7e9b5ec38699cf7f91775397027c792159fbcc71eddf778cf27",
          "sha1": "3e5cc860c2618715d88764b75d92f9bff8d843cd",
          "md5": "bf3985025a66b770a16b846c796f8b85"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "util-jvm-1.8.1-change-util-test-SNAPSHOT.jar",
          "url": "util-jvm-1.8.1-change-util-test-SNAPSHOT.jar",
          "size": 19627,
          "sha512": "e0bdb7c9544c217f8c5ccab2147b87b0688d66f728580bbf2af131593cdaff380f5ef40954d221a3fe679456b9b41fa9b459763b94e767f68121ddec80a63b5b",
          "sha256": "0cddd0a69be3d7e9b5ec38699cf7f91775397027c792159fbcc71eddf778cf27",
          "sha1": "3e5cc860c2618715d88764b75d92f9bff8d843cd",
          "md5": "bf3985025a66b770a16b846c796f8b85"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-metadata/1.8.1-change-util-test-SNAPSHOT/util-metadata-1.8.1-change-util-test-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-metadata",
        "version": "1.8.1-change-util-test-SNAPSHOT"
      }
    }
  ]
}
