{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir/0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT/fhir-0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir",
    "version": "0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir.klib",
          "url": "fhir-iosarm64-0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT.klib",
          "size": 46575,
          "sha512": "fb9b7a3a2695a30f01acf208f76ddd039b746d64a776918e69d7660792a7354f1af77c6f2a97d0bc61a302e0f91b4e631fb58f9a306ee3b62463b6ca6ed50acc",
          "sha256": "6ce7be1b0e92daea05740e67546928bf757d666911d44c1eaa6e4d55b4887bb9",
          "sha1": "af47e18db0bbad69497025c6d9f353ca8318135c",
          "md5": "099e2a1af6ff295a577252e8002f9fa2"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-iosarm64-0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT-metadata.jar",
          "url": "fhir-iosarm64-0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "de705e038c8a53ece4f96a2d050b64e783b79bf671a6d7fb0aee81b4611672b31d7edd5bc464498b7c82b3b9aaf778931585fc5f76c0e20daed6d6d8776bea33",
          "sha256": "7260b37144bd90341ce17a366a26f6534918b1038ac1088d4af64b111f0afede",
          "sha1": "77cc377c1c93f79656bdf4581ba956b8bcb81b8e",
          "md5": "1f8353d0fe335add7d12c5ded84025eb"
        }
      ]
    }
  ]
}
