{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.10.0-add-secure-store-and-crypto-service-kotlin-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "vpbm6lmtdvcl7gezbc5xya2ioe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-add-secure-store-and-crypto-service-kotlin-tests-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-add-secure-store-and-crypto-service-kotlin-tests-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "60b89144eaf0383dc001809a5b05726165b30d12dd43e891f09912f4fe4276c355c4c05031ce58511571801c18449fd8cb1cce0f697a40e9af9c898f2160f755",
          "sha256": "cbaefe2cd120a843769c235be5d7ec5806ba46504f233d865bc8fe44840dbb46",
          "sha1": "1e685dba78d41afd5d49b3eb84415e125d71b098",
          "md5": "8966865a278fc3d028910bb31b0ca311"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-add-secure-store-and-crypto-service-kotlin-tests-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-add-secure-store-and-crypto-service-kotlin-tests-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-add-secure-store-and-crypto-service-kotlin-tests-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "60b89144eaf0383dc001809a5b05726165b30d12dd43e891f09912f4fe4276c355c4c05031ce58511571801c18449fd8cb1cce0f697a40e9af9c898f2160f755",
          "sha256": "cbaefe2cd120a843769c235be5d7ec5806ba46504f233d865bc8fe44840dbb46",
          "sha1": "1e685dba78d41afd5d49b3eb84415e125d71b098",
          "md5": "8966865a278fc3d028910bb31b0ca311"
        }
      ]
    }
  ]
}
