{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.11.0-bump-updates-SNAPSHOT/util-1.11.0-bump-updates-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.11.0-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "util.klib",
          "url": "util-iosarm64-1.11.0-bump-updates-SNAPSHOT.klib",
          "size": 25786,
          "sha512": "0f56bce6a007735cb525e5ac8ee6e6775c85af3fba8004e2aac486ecbd1121d60be655c073f0bd4cc085ab4d105fc20705cfe9e0fa7657b595257a0aeec91293",
          "sha256": "6af17d22f5c4ca48e5a34db42b7259e7fdf0735626cc3cd38c93e37e4b27bc35",
          "sha1": "44dfd1995190e6b5ebcf74fa52007ab0fea1fded",
          "md5": "83e401a6d6b5ac26fe80907ad569c4ce"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "util-iosarm64-1.11.0-bump-updates-SNAPSHOT-metadata.jar",
          "url": "util-iosarm64-1.11.0-bump-updates-SNAPSHOT-metadata.jar",
          "size": 6109,
          "sha512": "ae8440df85320a8cfab23b2ce48ee3360095cb31e525dc8e3042673b6944510fc5211aa52ad7ca234f93a882884fb990fca07108ea9537e7967815093dd8a61c",
          "sha256": "ceca3de271cfa4f8524aa5fc9000f192a6eff45a3b68d537239947a6c5889637",
          "sha1": "2a9f72ff7a9acebef7b05cd42b2b6ca8eb55ff9b",
          "md5": "a0d7fc3d9f65b0df527e3ee583eea899"
        }
      ]
    }
  ]
}
