{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.11.0-bump-updates-SNAPSHOT/util-1.11.0-bump-updates-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.11.0-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "util.klib",
          "url": "util-iosarm64-1.11.0-bump-updates-SNAPSHOT.klib",
          "size": 25794,
          "sha512": "6ac58d5a9bea013c82f76e95424752bc3eeb2624c3ff220e805665c0788a49cb7b9e4faa3f556f61699401cc9e6b487f4ecdf712d1d299ad6403440e85855401",
          "sha256": "796531085200bcb6577a78ebb4e1336c2ded111d8901bab0f9c28a0aeec36577",
          "sha1": "6d4d0cdff904288483d5bd1df72a2bec7d098b66",
          "md5": "28fd600ecbb451fb4bc45e5b42e61b50"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "util-iosarm64-1.11.0-bump-updates-SNAPSHOT-metadata.jar",
          "url": "util-iosarm64-1.11.0-bump-updates-SNAPSHOT-metadata.jar",
          "size": 6142,
          "sha512": "168b2e20f474bec0fee0313288d2f33c997bbcb8475ee9761267dc6da05d1b155fef191152e9e17e973d5fc205bedf74096c0088103391907269fd83f393bc6d",
          "sha256": "4c880dbd474ba591b7bfc181b0555f9b440ebf29ee07daa19146cd579db4c679",
          "sha1": "561d7a9dc7e945d7bc7c0852d111b6cc0a27a9ce",
          "md5": "4fb903fc6dedcf96e42fbb71c4f49f05"
        }
      ]
    }
  ]
}
