{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-coroutine/0.4.0-SNAPSHOT/test-util-coroutine-0.4.0-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-coroutine",
    "version": "0.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.6.0-native-mt",
            "requires": "1.6.0-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-coroutine.klib",
          "url": "test-util-coroutine-iosx64-0.4.0-SNAPSHOT.klib",
          "size": 8255,
          "sha512": "f231a1f9d018cded691e9bc8fe2521645760430f5aa993d9207391980986637f28adab29c89d8da5afb78377792340be6fa9d28449b29506be13a41779c68d51",
          "sha256": "14a68739caebb5636199d693141b4d0050742a0023c54578d28356560ccaada2",
          "sha1": "1a7a1215637d716351a81897a5ca3671a5100035",
          "md5": "e99f25ac6e60ef2276590ac6a573bc0c"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.6.0-native-mt",
            "requires": "1.6.0-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-coroutine-iosx64-0.4.0-SNAPSHOT-metadata.jar",
          "url": "test-util-coroutine-iosx64-0.4.0-SNAPSHOT-metadata.jar",
          "size": 6287,
          "sha512": "2dbf66a22e202151ffa8a5092759391db206a0371953423b2b9e91850f02c9ced647f5e960c772b36129bdd482ba3b14be7be91438074ee9f0213c215c885917",
          "sha256": "1a418a6359aeb705474a4a74e1e0b26224b0e3593365a0ac262a3e7c320a6204",
          "sha1": "f9d1d878f410b264bdbd67b572903e013d9f61d2",
          "md5": "1e181e3bf6ed5643c454be373bb8fe25"
        }
      ]
    }
  ]
}
