{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.0.3-fix-missing-native-resources-test-SNAPSHOT/data-donation-sdk-iosx64-0.0.3-fix-missing-native-resources-test-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.0.3-fix-missing-native-resources-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "leysguqt5valzed7ey23tgcn2m"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.3-fix-missing-native-resources-test-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.0.3-fix-missing-native-resources-test-SNAPSHOT.jar",
          "size": 64163,
          "sha512": "7fc7253b8717422d4dc25292351e9edd9739499115ecf259e98e3891f1dc7849481e96465b1a22588fe139395e298439912e6b0460a6bd87031019e5e8fdd7bc",
          "sha256": "738140d4783c8e22f29a38acbafdbce1e410e3cb4434f1e6a1a9fc77c8066efd",
          "sha1": "371678ab2967bfa358f24bfae5040ee835fdaa21",
          "md5": "42b0edf46fcd441de6ea84346aca5824"
        }
      ]
    }
  ]
}
