{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-objc-util-sdk-kmp",
    "module": "objc-util",
    "version": "0.1.0-bump-kotlin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "objc-util-metadata-0.1.0-bump-kotlin-SNAPSHOT-all.jar",
          "url": "objc-util-0.1.0-bump-kotlin-SNAPSHOT-all.jar",
          "size": 706,
          "sha512": "1e589014cc81361bb7d8af454d3a4a3809f756cff7a95a45d07c2085ea965c387ab03412ae35661e77b98212f3d9f00b5f62ec30c9de835832e604a6a209bdc5",
          "sha256": "4582b31593dfd98220c3e9422bb3c84ceffb6b69b7232843f2de2e408a412539",
          "sha1": "e1d1b7ae08afedf07ef7c3c88ccc1bb65a0f55ee",
          "md5": "b042ad531879b88d19a5ee3f939ae357"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "objc-util-0.1.0-bump-kotlin-SNAPSHOT.jar",
          "url": "objc-util-0.1.0-bump-kotlin-SNAPSHOT.jar",
          "size": 261,
          "sha512": "67be516c01e8deee5a689bf6068274374bce4ab31a19ff3bb3e9fc0c83b3614d01c655738a3074ed18a0a872e9ea07b04de5fd23009092bd641009869a571cef",
          "sha256": "6878b143ddc9e1fbddaad6965b2293260a90d7fa251dda21c6036f0d2bb19298",
          "sha1": "0182b3a7414fba9676864c4a0cd9d53ed764879a",
          "md5": "34762e33bd3a51d6a956544a4505f2ba"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../objc-util-iosarm64/0.1.0-bump-kotlin-SNAPSHOT/objc-util-iosarm64-0.1.0-bump-kotlin-SNAPSHOT.module",
        "group": "care.data4life.hc-objc-util-sdk-kmp",
        "module": "objc-util-iosarm64",
        "version": "0.1.0-bump-kotlin-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../objc-util-iosarm64/0.1.0-bump-kotlin-SNAPSHOT/objc-util-iosarm64-0.1.0-bump-kotlin-SNAPSHOT.module",
        "group": "care.data4life.hc-objc-util-sdk-kmp",
        "module": "objc-util-iosarm64",
        "version": "0.1.0-bump-kotlin-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../objc-util-iosx64/0.1.0-bump-kotlin-SNAPSHOT/objc-util-iosx64-0.1.0-bump-kotlin-SNAPSHOT.module",
        "group": "care.data4life.hc-objc-util-sdk-kmp",
        "module": "objc-util-iosx64",
        "version": "0.1.0-bump-kotlin-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../objc-util-iosx64/0.1.0-bump-kotlin-SNAPSHOT/objc-util-iosx64-0.1.0-bump-kotlin-SNAPSHOT.module",
        "group": "care.data4life.hc-objc-util-sdk-kmp",
        "module": "objc-util-iosx64",
        "version": "0.1.0-bump-kotlin-SNAPSHOT"
      }
    }
  ]
}
