{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk",
    "version": "0.0.3-change-root-module-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "2x6fhvstbjbdnetohvwdahuzim"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.3-change-root-module-SNAPSHOT.jar",
          "url": "data-donation-sdk-0.0.3-change-root-module-SNAPSHOT.jar",
          "size": 69554,
          "sha512": "bbde3815779ce71452003762555ae5b0add433a6a76bbc5306f8416d5d1cd020f237247677d613ff6daefcec516be5b6e3f00ce517eb1340dba9bc7640e6f7a0",
          "sha256": "ed5d0dae9a5ac0dc0979e47c6c9082f73d0e50929d68630bed95d2534ffe04f4",
          "sha1": "e85870627178883e242ad8535c1140255310d66e",
          "md5": "2abc98a3761dc425f1cf0b1032a85bc6"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android-debug/0.0.3-change-root-module-SNAPSHOT/data-donation-sdk-android-debug-0.0.3-change-root-module-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android-debug",
        "version": "0.0.3-change-root-module-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android-debug/0.0.3-change-root-module-SNAPSHOT/data-donation-sdk-android-debug-0.0.3-change-root-module-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android-debug",
        "version": "0.0.3-change-root-module-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android/0.0.3-change-root-module-SNAPSHOT/data-donation-sdk-android-0.0.3-change-root-module-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android",
        "version": "0.0.3-change-root-module-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android/0.0.3-change-root-module-SNAPSHOT/data-donation-sdk-android-0.0.3-change-root-module-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android",
        "version": "0.0.3-change-root-module-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../data-donation-sdk-iosarm64/0.0.3-change-root-module-SNAPSHOT/data-donation-sdk-iosarm64-0.0.3-change-root-module-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-iosarm64",
        "version": "0.0.3-change-root-module-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../data-donation-sdk-iosx64/0.0.3-change-root-module-SNAPSHOT/data-donation-sdk-iosx64-0.0.3-change-root-module-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-iosx64",
        "version": "0.0.3-change-root-module-SNAPSHOT"
      }
    }
  ]
}
