{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.0.4-remove-local-env-SNAPSHOT/data-donation-sdk-iosx64-0.0.4-remove-local-env-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.0.4-remove-local-env-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "kffvjyrlwbhlhi2bm5ynnvplfm"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.4-remove-local-env-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.0.4-remove-local-env-SNAPSHOT.jar",
          "size": 73363,
          "sha512": "d1a64e4a3dd3db3f68968706e4b686b61adc71b5122401e576a79be7e8831f4da1a70ee9cd0833ea6ad35edcd284296b572634164d4016d105b90b872b3872ff",
          "sha256": "2343e44f9ee4b6825d39dd5dc249d9791d5861be8a4ea2be338c56a783305350",
          "sha1": "287e81bd9fc5bf93655db03d02d37bc5b6ce9ba7",
          "md5": "c68cfa65c21696d71c9f083f53eb1bc3"
        }
      ]
    }
  ]
}
