{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.11.0-change-ihc-service-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "zakliq67cnabnibqsbgpkai6tm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.11.0-change-ihc-service-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-change-ihc-service-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "dc3a0ee794d3980a3934480dbe130986c717a920c6ab9b057dd8e2b8eb41fb51b4a4aafa34e8263f5268f8a71bed1f9da2bec5ef2e8fd894c8cd78b701a2f94a",
          "sha256": "fa3fb5937517ac6563bfa4084e87413048952c5a53ba8b1381aa4817eda64e6b",
          "sha1": "67fb93fe496dc02ba60c911965ec2700dca23cc0",
          "md5": "76b5e6b2dc92f9c15f44f43faae8ba95"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.11.0-change-ihc-service-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-change-ihc-service-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "dc3a0ee794d3980a3934480dbe130986c717a920c6ab9b057dd8e2b8eb41fb51b4a4aafa34e8263f5268f8a71bed1f9da2bec5ef2e8fd894c8cd78b701a2f94a",
          "sha256": "fa3fb5937517ac6563bfa4084e87413048952c5a53ba8b1381aa4817eda64e6b",
          "sha1": "67fb93fe496dc02ba60c911965ec2700dca23cc0",
          "md5": "76b5e6b2dc92f9c15f44f43faae8ba95"
        }
      ]
    }
  ]
}
