{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.12.0-change-resource-crypto-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "kk377b7zf5a5jnzbkhdj7iv3pe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.12.0-change-resource-crypto-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.12.0-change-resource-crypto-tests-SNAPSHOT.jar",
          "url": "securestore-jvm-1.12.0-change-resource-crypto-tests-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "ea234e0ba1643d838bfed5deb1f860e742508265274afa0287c6ef369f5508c5aa9f59fa3b0094ac40f74f98e61cc2eabec9f93566b3e2d8575dd770f075beef",
          "sha256": "69da66dc8563e9b41a4c1decdd8242319eacb6b4d834160de01a30e01c00e61d",
          "sha1": "8d7e8c90f4fec692b7994232487f77e806252b84",
          "md5": "3b8f0e4072384d02495fe18eca8e95ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.12.0-change-resource-crypto-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.12.0-change-resource-crypto-tests-SNAPSHOT.jar",
          "url": "securestore-jvm-1.12.0-change-resource-crypto-tests-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "ea234e0ba1643d838bfed5deb1f860e742508265274afa0287c6ef369f5508c5aa9f59fa3b0094ac40f74f98e61cc2eabec9f93566b3e2d8575dd770f075beef",
          "sha256": "69da66dc8563e9b41a4c1decdd8242319eacb6b4d834160de01a30e01c00e61d",
          "sha1": "8d7e8c90f4fec692b7994232487f77e806252b84",
          "md5": "3b8f0e4072384d02495fe18eca8e95ab"
        }
      ]
    }
  ]
}
