{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk/0.0.3-change-revoke-consent-usecase-SNAPSHOT/data-donation-sdk-0.0.3-change-revoke-consent-usecase-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk",
    "version": "0.0.3-change-revoke-consent-usecase-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "rvxcpeyfnbg2thfba6hntfssua"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-kmp",
          "module": "fhir",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.4.3-native-mt",
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-ios",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "data-donation-sdk.klib",
          "url": "data-donation-sdk-iosx64-0.0.3-change-revoke-consent-usecase-SNAPSHOT.klib",
          "size": 7277307,
          "sha512": "0feb100f0af1726494ac0ff5239283b6e7e71cb3fc3f1678853111b387e9499917b4c4bce002f5b6bd0f56ea2c954b65bdc200b6995a63461a764dcd5c9af3e0",
          "sha256": "ac847f52a90a8519ed427d2b7bc345553196bf7493260a24e44ca22872adfa1d",
          "sha1": "4af33991de77e3155b73053c4fd740a747c729ef",
          "md5": "f86b19d6668350c446d7834cf92b3bf9"
        },
        {
          "name": "data-donation-sdk-cinterop-iOSDCryptoDD.klib",
          "url": "data-donation-sdk-iosx64-0.0.3-change-revoke-consent-usecase-SNAPSHOT-cinterop-iOSDCryptoDD.klib",
          "size": 5944,
          "sha512": "67305e7a2981e2a2026e815aae23e30ca7ac95c580d46f64450f1d60a40c3d422a7b0a5acd1c8cc49e8d38c23875be1115b417d7ec3aff353dfaf52d7fd93da4",
          "sha256": "5d4c059cd03836dd9bd9b11e5934bf4c6d783b21d70bae1f11367b4c31e9afa9",
          "sha1": "422c224f6c1c63d6481c8b60050933333ce97e38",
          "md5": "6b48e8242d94d68e2e1bc0ed437208f6"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../data-donation-sdk-metadata/0.0.3-change-revoke-consent-usecase-SNAPSHOT/data-donation-sdk-metadata-0.0.3-change-revoke-consent-usecase-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-metadata",
        "version": "0.0.3-change-revoke-consent-usecase-SNAPSHOT"
      }
    }
  ]
}
