{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.12.0-change-contracts-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "svkgmuepi5gfhcclxjteos6ngu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.12.0-change-contracts-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.12.0-change-contracts-SNAPSHOT.jar",
          "url": "auth-jvm-1.12.0-change-contracts-SNAPSHOT.jar",
          "size": 34319,
          "sha512": "cb5e0c26f39e81767013fff85a6fff58a64a35bd4c3f4e62f81cd92dd4d161221db43a6f1890bc544d15a9c76f6cf8c4c5b52cba500854e0694b9e2451949857",
          "sha256": "c9c7eb82d5a401e4d48ef7e9fb72773d7c533dcd29b5caacfa27737255088f7b",
          "sha1": "eb1e3622a7256bdd9797f8f51e3f05a43b4456e6",
          "md5": "a2afdff7293705be4fa1ba91baaf85d0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.12.0-change-contracts-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.12.0-change-contracts-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.12.0-change-contracts-SNAPSHOT.jar",
          "url": "auth-jvm-1.12.0-change-contracts-SNAPSHOT.jar",
          "size": 34319,
          "sha512": "cb5e0c26f39e81767013fff85a6fff58a64a35bd4c3f4e62f81cd92dd4d161221db43a6f1890bc544d15a9c76f6cf8c4c5b52cba500854e0694b9e2451949857",
          "sha256": "c9c7eb82d5a401e4d48ef7e9fb72773d7c533dcd29b5caacfa27737255088f7b",
          "sha1": "eb1e3622a7256bdd9797f8f51e3f05a43b4456e6",
          "md5": "a2afdff7293705be4fa1ba91baaf85d0"
        }
      ]
    }
  ]
}
