{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.12.0-change-contracts-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ixnyxrk4prfxrp7b4vitsfm52a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.12.0-change-contracts-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.12.0-change-contracts-SNAPSHOT.jar",
          "url": "auth-jvm-1.12.0-change-contracts-SNAPSHOT.jar",
          "size": 34318,
          "sha512": "96b3313db2b553b6212c6fe33848b8aae86f527dae25529307249987b04fa83bed4f7e7810d952744999fd273419ec8aae9f5d9ca75f88b45fb9c258edebf8d5",
          "sha256": "a92599e48c2fc4389087b0a374f6255cd10badcea27ba3c86b4d2b2f15b06967",
          "sha1": "364ba43de0e8a4591c757142d3f11ecb88795d23",
          "md5": "dfda057aa3e5eada17a373aac4eb680d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.12.0-change-contracts-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.12.0-change-contracts-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.12.0-change-contracts-SNAPSHOT.jar",
          "url": "auth-jvm-1.12.0-change-contracts-SNAPSHOT.jar",
          "size": 34318,
          "sha512": "96b3313db2b553b6212c6fe33848b8aae86f527dae25529307249987b04fa83bed4f7e7810d952744999fd273419ec8aae9f5d9ca75f88b45fb9c258edebf8d5",
          "sha256": "a92599e48c2fc4389087b0a374f6255cd10badcea27ba3c86b4d2b2f15b06967",
          "sha1": "364ba43de0e8a4591c757142d3f11ecb88795d23",
          "md5": "dfda057aa3e5eada17a373aac4eb680d"
        }
      ]
    }
  ]
}
