{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.0.5-fix-call-builder-SNAPSHOT/data-donation-sdk-iosx64-0.0.5-fix-call-builder-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.0.5-fix-call-builder-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "i3i3zakgmze2jmwn3b7kcsw7yu"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.5-fix-call-builder-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.0.5-fix-call-builder-SNAPSHOT.jar",
          "size": 73724,
          "sha512": "4a95c7a26dc81d7cbe00c5b58e8d977fa8518c744cd44a5f14fda267e907d2544b413ab6ecf82d926c42bf532585ee74ce049600d089c683506b9e0ae5da4c6b",
          "sha256": "eaac3c36c19302281a8d0224c61405334eccf32e86c7ca944d5833d70963d18d",
          "sha1": "eb208254a98e49428e4b9714b7a13048c9b13ce1",
          "md5": "71d876c783d5d82d8f9753c30c7d4612"
        }
      ]
    }
  ]
}
