{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk/0.0.2-enable-data-donation-sdk-SNAPSHOT/data-donation-sdk-0.0.2-enable-data-donation-sdk-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk",
    "version": "0.0.2-enable-data-donation-sdk-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "w4uaz3rx6fgg7a2aczr5cjelki"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "data-donation-sdk-release.aar",
          "url": "data-donation-sdk-android-0.0.2-enable-data-donation-sdk-SNAPSHOT.aar",
          "size": 386170,
          "sha512": "be9a9c1633a8f44029ec1c0269f4a9ec429a89258fa3c3eb861a1b4146f6a1cf47d3f22e246cd8f459e2e2ac0a8d3086c851403cc9a12d422b961515f8d2ffc5",
          "sha256": "2e5e8ab9fecf1eabe4510df4918615f1d94cd4bede1e35a0952abdd152b26a06",
          "sha1": "d3f808fbbf1869e68153e598c08639e77154172a",
          "md5": "19887a87522561fc4f7617deb6dbe4e3"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.2-native-mt"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.jakewharton.threetenabp",
          "module": "threetenabp",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization-jvm",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core-jvm",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2-native-mt"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-kmp",
          "module": "fhir",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "data-donation-sdk-release.aar",
          "url": "data-donation-sdk-android-0.0.2-enable-data-donation-sdk-SNAPSHOT.aar",
          "size": 386170,
          "sha512": "be9a9c1633a8f44029ec1c0269f4a9ec429a89258fa3c3eb861a1b4146f6a1cf47d3f22e246cd8f459e2e2ac0a8d3086c851403cc9a12d422b961515f8d2ffc5",
          "sha256": "2e5e8ab9fecf1eabe4510df4918615f1d94cd4bede1e35a0952abdd152b26a06",
          "sha1": "d3f808fbbf1869e68153e598c08639e77154172a",
          "md5": "19887a87522561fc4f7617deb6dbe4e3"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../data-donation-sdk-metadata/0.0.2-enable-data-donation-sdk-SNAPSHOT/data-donation-sdk-metadata-0.0.2-enable-data-donation-sdk-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-metadata",
        "version": "0.0.2-enable-data-donation-sdk-SNAPSHOT"
      }
    }
  ]
}
