{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-jvm/0.2.0-change-setup-to-latest-SNAPSHOT/test-util-jvm-0.2.0-change-setup-to-latest-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-jvm",
    "version": "0.2.0-change-setup-to-latest-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "bnrxbdssnrgyzp7falhrufum44"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-util-metadata-0.2.0-change-setup-to-latest-SNAPSHOT.jar",
          "url": "test-util-metadata-0.2.0-change-setup-to-latest-SNAPSHOT.jar",
          "size": 6262,
          "sha512": "b2285534f54610946af16cabc4ba7f78ccc783fd486d44c7ca92ebe91b0b7edfcfbd505006874acaa9d90c759e7cf83b1321b243b5106f5db42c08b3e545c7e8",
          "sha256": "436c748b68535b43680773665fb88ab33952998c9815edc42e91215c91a6a4ce",
          "sha1": "ca24fe6431d076e6624baaeada9f4465d8b31ede",
          "md5": "8ace256212702657834854ae4b0921de"
        }
      ]
    }
  ]
}
