{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk",
    "version": "0.0.4-change-usecase-pattern-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "q3rlbfcbwbfsfjxm5axrfpfus4"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.4-change-usecase-pattern-SNAPSHOT.jar",
          "url": "data-donation-sdk-0.0.4-change-usecase-pattern-SNAPSHOT.jar",
          "size": 73545,
          "sha512": "82126b0c590ae85987b35ebe9fb01130c51b4571be710ae683458108b1d09751f3e222bd6bf3d66c49127d6a61557f15e7ff3e3cf2b76fec95cec3cd42d232cd",
          "sha256": "6802f2c84893e9f25251a18fca4841ad5b9ef21c345110ede925eece78abb37e",
          "sha1": "122ded32ea4cdc3c9c5a4286a7c9431a76bde887",
          "md5": "5c051c36b466fba66aa435bf0d5df7f6"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android-debug/0.0.4-change-usecase-pattern-SNAPSHOT/data-donation-sdk-android-debug-0.0.4-change-usecase-pattern-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android-debug",
        "version": "0.0.4-change-usecase-pattern-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android-debug/0.0.4-change-usecase-pattern-SNAPSHOT/data-donation-sdk-android-debug-0.0.4-change-usecase-pattern-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android-debug",
        "version": "0.0.4-change-usecase-pattern-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android/0.0.4-change-usecase-pattern-SNAPSHOT/data-donation-sdk-android-0.0.4-change-usecase-pattern-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android",
        "version": "0.0.4-change-usecase-pattern-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android/0.0.4-change-usecase-pattern-SNAPSHOT/data-donation-sdk-android-0.0.4-change-usecase-pattern-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android",
        "version": "0.0.4-change-usecase-pattern-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../data-donation-sdk-iosarm64/0.0.4-change-usecase-pattern-SNAPSHOT/data-donation-sdk-iosarm64-0.0.4-change-usecase-pattern-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-iosarm64",
        "version": "0.0.4-change-usecase-pattern-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../data-donation-sdk-iosx64/0.0.4-change-usecase-pattern-SNAPSHOT/data-donation-sdk-iosx64-0.0.4-change-usecase-pattern-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-iosx64",
        "version": "0.0.4-change-usecase-pattern-SNAPSHOT"
      }
    }
  ]
}
