{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-coroutine/0.3.0-bump-desugar-SNAPSHOT/test-util-coroutine-0.3.0-bump-desugar-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-coroutine",
    "version": "0.3.0-bump-desugar-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.1-native-mt",
            "requires": "1.5.1-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-coroutine.klib",
          "url": "test-util-coroutine-iosx64-0.3.0-bump-desugar-SNAPSHOT.klib",
          "size": 7833,
          "sha512": "5d452210f798bc7962914a7b4842372c09ae05aebca3b2542f80455fb2dd5c29d6f4361a670775f1edc64d4427a9460dff6c3a601c5b90fc2aae1baeb43fe9a4",
          "sha256": "bcfaac01ec3c920ae9bc592fe493a3eeeaa81e869f1239b6a6e279649b7ae333",
          "sha1": "563d97f1b93737bbad96f76c8bec4d3387167730",
          "md5": "77313596725723eb75007be3770520b1"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.1-native-mt",
            "requires": "1.5.1-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-coroutine-iosx64-0.3.0-bump-desugar-SNAPSHOT-metadata.jar",
          "url": "test-util-coroutine-iosx64-0.3.0-bump-desugar-SNAPSHOT-metadata.jar",
          "size": 6284,
          "sha512": "166c4aca437c86f18ca6222cb23adc71fe1dae552dee460f32ef3da66ece52810faba97d79efc3bd108702ef475a65bccf05e37f49c9f023c892d213ee9016f2",
          "sha256": "60e4e1ec0dc1c23b9c4b0c301862615e9587200edd3003ea882ea8d66c3ae901",
          "sha1": "7bda4b679b8debd4d28b7eaaf68ecf33d9f7a1d5",
          "md5": "aa679fae4bd7fbfcdcee4aaced1048ad"
        }
      ]
    }
  ]
}
