{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.11.0-add-api-service-unit-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "flzedwdnbncnrbojy6oup7j2ra"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.11.0-add-api-service-unit-tests-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-add-api-service-unit-tests-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "2d3159019e6e093159b91b1a344f3ffebaf17dc0f086bb508c74ebcfcccf85427a42a6805e198294d47427557dffdde3655df271ebfb977d816878aec81d3823",
          "sha256": "0590f0e3354f21a52375a268d311b8294504b7fc71f09a684833a014882ee150",
          "sha1": "013f3e12942d7a50e3a0d75b9c6112c3d6f4fd52",
          "md5": "c77528d73cdb265fba1e539d67efcb01"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.11.0-add-api-service-unit-tests-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-add-api-service-unit-tests-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "2d3159019e6e093159b91b1a344f3ffebaf17dc0f086bb508c74ebcfcccf85427a42a6805e198294d47427557dffdde3655df271ebfb977d816878aec81d3823",
          "sha256": "0590f0e3354f21a52375a268d311b8294504b7fc71f09a684833a014882ee150",
          "sha1": "013f3e12942d7a50e3a0d75b9c6112c3d6f4fd52",
          "md5": "c77528d73cdb265fba1e539d67efcb01"
        }
      ]
    }
  ]
}
