{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-android",
    "version": "1.11.0-fix-updateRecord-checks-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "uqypsdpftrervn3osaqkitvtmm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-fix-updateRecord-checks-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.11.0-fix-updateRecord-checks-SNAPSHOT.aar",
          "url": "crypto-android-1.11.0-fix-updateRecord-checks-SNAPSHOT.aar",
          "size": 61908,
          "sha512": "2399e6ad951ffd7f26762e2c6b1285161e35bcfe0411829b42bd2e42ab36e82b5622d8fde0316408ff8f5ee42e9a2c0ec61000a8ce9abf3e5785d525a2353846",
          "sha256": "5e49241156614ec1d33f34b41556348a300acf38ff8a3a7a525429fc0a5081ff",
          "sha1": "607860f9b6d5f85b77a9e287a6932693c0b2a6f7",
          "md5": "6f6baa433e91ee321b014f3d4b41b83f"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-fix-updateRecord-checks-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.11.0-fix-updateRecord-checks-SNAPSHOT.aar",
          "url": "crypto-android-1.11.0-fix-updateRecord-checks-SNAPSHOT.aar",
          "size": 61908,
          "sha512": "2399e6ad951ffd7f26762e2c6b1285161e35bcfe0411829b42bd2e42ab36e82b5622d8fde0316408ff8f5ee42e9a2c0ec61000a8ce9abf3e5785d525a2353846",
          "sha256": "5e49241156614ec1d33f34b41556348a300acf38ff8a3a7a525429fc0a5081ff",
          "sha1": "607860f9b6d5f85b77a9e287a6932693c0b2a6f7",
          "md5": "6f6baa433e91ee321b014f3d4b41b83f"
        }
      ]
    }
  ]
}
