{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.0-fix-danger-rules-SNAPSHOT/data-donation-sdk-iosx64-0.1.0-fix-danger-rules-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.0-fix-danger-rules-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "4qreigsh2bhpneqezvlly2tily"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.0-fix-danger-rules-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.0-fix-danger-rules-SNAPSHOT.jar",
          "size": 39250,
          "sha512": "3b911fede7e05bcf67182b86d26a95e462944bfd008034439d2b5c2350737614c01300a4e4010d6405aedce3b11255b8e043683a745f86efec40b178bcc216bb",
          "sha256": "3b73655c19ea59ec038abbf9680e71a9a3eefed79980498091f6d4b22b1fab67",
          "sha1": "939075435a1c7df6ae141b18529a2f5deec5dd39",
          "md5": "f448b3c5e8cf1546437457ccb3910c4a"
        }
      ]
    }
  ]
}
