{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-android",
    "version": "1.10.0-add-secure-store-and-crypto-service-kotlin-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "wesjnyfvq5c75ovkbhahlvw3ae"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.10.0-add-secure-store-and-crypto-service-kotlin-tests-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "auth-jvm"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            },
            {
              "group": "*",
              "module": "securestore-jvm"
            },
            {
              "group": "*",
              "module": "crypto-jvm"
            },
            {
              "group": "org.threeten",
              "module": "threetenbp"
            }
          ]
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-1.10.0-add-secure-store-and-crypto-service-kotlin-tests-SNAPSHOT.aar",
          "url": "sdk-android-1.10.0-add-secure-store-and-crypto-service-kotlin-tests-SNAPSHOT.aar",
          "size": 28281,
          "sha512": "241fd50d514f273c4d88126713271cb06b569dabf7e45329eefb7af9975f5b8c386f061b82ea6496a65c227adc6c81111c92b3760134ba4b0468a91fc0c1bc16",
          "sha256": "3a17a8689713adb08a0fa3b0812d6d5459f2873f0e61bf70b2b530283e63fd80",
          "sha1": "fa727aae9018e3ee959eac6911a7dba22d33061d",
          "md5": "189c836876f402cda2ba71380356280c"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.10.0-add-secure-store-and-crypto-service-kotlin-tests-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "auth-jvm"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            },
            {
              "group": "*",
              "module": "securestore-jvm"
            },
            {
              "group": "*",
              "module": "crypto-jvm"
            },
            {
              "group": "org.threeten",
              "module": "threetenbp"
            }
          ]
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-android",
          "version": {
            "requires": "1.10.0-add-secure-store-and-crypto-service-kotlin-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-android",
          "version": {
            "requires": "1.10.0-add-secure-store-and-crypto-service-kotlin-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-android",
          "version": {
            "requires": "1.10.0-add-secure-store-and-crypto-service-kotlin-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton.threetenabp",
          "module": "threetenabp",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.github.gesundheitscloud",
          "module": "AppAuth-Android",
          "version": {
            "requires": "9e3cc033ff"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-1.10.0-add-secure-store-and-crypto-service-kotlin-tests-SNAPSHOT.aar",
          "url": "sdk-android-1.10.0-add-secure-store-and-crypto-service-kotlin-tests-SNAPSHOT.aar",
          "size": 28281,
          "sha512": "241fd50d514f273c4d88126713271cb06b569dabf7e45329eefb7af9975f5b8c386f061b82ea6496a65c227adc6c81111c92b3760134ba4b0468a91fc0c1bc16",
          "sha256": "3a17a8689713adb08a0fa3b0812d6d5459f2873f0e61bf70b2b530283e63fd80",
          "sha1": "fa727aae9018e3ee959eac6911a7dba22d33061d",
          "md5": "189c836876f402cda2ba71380356280c"
        }
      ]
    }
  ]
}
