{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT/data-donation-sdk-iosx64-0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "zpybg667vjbhdnpsy5kassro6a"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT.jar",
          "size": 40175,
          "sha512": "d73fe7c189b7bfa7e75d4c1fead08ef958eebd70e032d634930b04708344a989ce7154ae1e4e6c1c5c8a6344ee9a064c7d6d485a47f91a7688648674b0dc1d23",
          "sha256": "c9e4eed74ec0e3bcdf0b3aa665e47e3dcca9f9e3b89d0605bb6ebc1a4da75756",
          "sha1": "6e711cc543c4f54c3b69987d4dc00ad71ef2c40d",
          "md5": "55b73200b57e8479f5d201aea7a564f6"
        }
      ]
    }
  ]
}
