{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT/data-donation-sdk-iosx64-0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "7sgk453mvbchrp24giipc4gesy"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT.jar",
          "size": 40175,
          "sha512": "39de5731c3c8d56b44944dc5d468401dc6bcda63850f8c10ea0cf599935a89a3a86257b87dcb87d345caa07a123374ef45c4ac7b3844ac18cb4f892a2669401f",
          "sha256": "7a4d9e77779ba7fbfe43573bc2302b83d3785e0efd824878ab6748f505e4e8ec",
          "sha1": "4012f1527b0c6f26e5a9bdad9958c870973a4cd2",
          "md5": "4d7aa2f38cdc4728b291519fefd1282d"
        }
      ]
    }
  ]
}
