{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT/data-donation-sdk-iosx64-0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "lmivgpeaqzevlanutd3kqmrgri"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT.jar",
          "size": 40175,
          "sha512": "3b48f3b29019ee6fff5176e8ebfb7dadd7b1c1f7d39f0e7621024f82d11bcf5eee17e6fb4b557e098d6ba3f8d716cfa26f6624a548fadbe869a0373e092c175a",
          "sha256": "c2f002e6dbaeee935f10d29d9b86917928cce060393d2b799ba91ed044529a0d",
          "sha1": "70aa75c604aaab96a8f8c25878a604fee85dd4e4",
          "md5": "efac8cf7880e6b73c2881f026fd46c39"
        }
      ]
    }
  ]
}
