{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.12.0-add-auth-client-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "jfappqw7pncurlg45vldq5mioy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.12.0-add-auth-client-tests-SNAPSHOT.jar",
          "url": "auth-common-1.12.0-add-auth-client-tests-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "f31061fc3fc1f81ff657e73132605133262c8c28e17b3e090330c90f82a166460f08c0cce0753ada07509658c956bbda6257d14d31f0f0472d83fd83e22cdd03",
          "sha256": "dfe6d650da3379baae341b4f184548c93d81f21756e9ad4addf6f75df1390766",
          "sha1": "73ef84c0bfdc0c249135c0308def083121424806",
          "md5": "598a6adefc6bffb436663af186b58b5c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.12.0-add-auth-client-tests-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.12.0-add-auth-client-tests-SNAPSHOT.jar",
          "url": "auth-common-1.12.0-add-auth-client-tests-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "f31061fc3fc1f81ff657e73132605133262c8c28e17b3e090330c90f82a166460f08c0cce0753ada07509658c956bbda6257d14d31f0f0472d83fd83e22cdd03",
          "sha256": "dfe6d650da3379baae341b4f184548c93d81f21756e9ad4addf6f75df1390766",
          "sha1": "73ef84c0bfdc0c249135c0308def083121424806",
          "md5": "598a6adefc6bffb436663af186b58b5c"
        }
      ]
    }
  ]
}
