{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp.hc-sdk-kmp",
    "module": "sdk-jvm",
    "version": "1.15.1-bump-update-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.15.1-bump-update-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            },
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.15.1-bump-update-SNAPSHOT.jar",
          "url": "sdk-jvm-1.15.1-bump-update-SNAPSHOT.jar",
          "size": 11608,
          "sha512": "b2022956a89d9597e9c2cac1c5b0764f1972a702a5a4ecdfa6febfb87ce2b6bad24360dff8c50140b795fd542b7b5e2b4e5bf9843b4ba176ed8ae8ae9a5d5f93",
          "sha256": "6fedec444860deeca6411f99fe04a8a1e39e883b1a24123903bd5014e35aceec",
          "sha1": "c7086b990552651e5295db0d43a143de275a13e9",
          "md5": "fb96e4e0fe06aafc7ac950a81d038d3a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-auth-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.15.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "care.data4life.hc-crypto-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.15.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "care.data4life.hc-securestore-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.15.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.13.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.13.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "care.data4life.hc-sdk-kmp.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.15.1-bump-update-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            },
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.15.1-bump-update-SNAPSHOT.jar",
          "url": "sdk-jvm-1.15.1-bump-update-SNAPSHOT.jar",
          "size": 11608,
          "sha512": "b2022956a89d9597e9c2cac1c5b0764f1972a702a5a4ecdfa6febfb87ce2b6bad24360dff8c50140b795fd542b7b5e2b4e5bf9843b4ba176ed8ae8ae9a5d5f93",
          "sha256": "6fedec444860deeca6411f99fe04a8a1e39e883b1a24123903bd5014e35aceec",
          "sha1": "c7086b990552651e5295db0d43a143de275a13e9",
          "md5": "fb96e4e0fe06aafc7ac950a81d038d3a"
        }
      ]
    }
  ]
}
