{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-fhir-helper-sdk-kmp",
    "module": "fhir-helper",
    "version": "1.8.0-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "fhir-helper-metadata-1.8.0-bump-updates-SNAPSHOT.jar",
          "url": "fhir-helper-1.8.0-bump-updates-SNAPSHOT.jar",
          "size": 1510,
          "sha512": "6399da33010427ad2e45c59d1ba601cc11c44d20fa4825a47d8886bbc51f2be00166d6a248e86fe7d0a790ea0c4544d0d81d87f2832487d1b6a4f031e29e3623",
          "sha256": "6329641e4164dc19a8fda702c9f793430cb99ecfa49120a22c586842cd2f5e61",
          "sha1": "3b1425dc3d12c375ce49c881e1ba8684cdf5cc6e",
          "md5": "6c6251cea2202d8cc51db257124db7da"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-helper-android-debug/1.8.0-bump-updates-SNAPSHOT/fhir-helper-android-debug-1.8.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-helper-sdk-kmp",
        "module": "fhir-helper-android-debug",
        "version": "1.8.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-helper-android-debug/1.8.0-bump-updates-SNAPSHOT/fhir-helper-android-debug-1.8.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-helper-sdk-kmp",
        "module": "fhir-helper-android-debug",
        "version": "1.8.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-helper-android/1.8.0-bump-updates-SNAPSHOT/fhir-helper-android-1.8.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-helper-sdk-kmp",
        "module": "fhir-helper-android",
        "version": "1.8.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-helper-android/1.8.0-bump-updates-SNAPSHOT/fhir-helper-android-1.8.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-helper-sdk-kmp",
        "module": "fhir-helper-android",
        "version": "1.8.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../fhir-helper-jvm/1.8.0-bump-updates-SNAPSHOT/fhir-helper-jvm-1.8.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-helper-sdk-kmp",
        "module": "fhir-helper-jvm",
        "version": "1.8.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../fhir-helper-jvm/1.8.0-bump-updates-SNAPSHOT/fhir-helper-jvm-1.8.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-helper-sdk-kmp",
        "module": "fhir-helper-jvm",
        "version": "1.8.0-bump-updates-SNAPSHOT"
      }
    }
  ]
}
