{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk",
    "version": "0.1.3-bump-ios-crypto-version-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "exeuwsklwrcbra4foplllmeex4"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.3-bump-ios-crypto-version-SNAPSHOT.jar",
          "url": "data-donation-sdk-0.1.3-bump-ios-crypto-version-SNAPSHOT.jar",
          "size": 58853,
          "sha512": "e631d0c52f49ba529063331d097cda96d999c8c7aab3c9d1e42368914bffc17d629340ee3f7d5201bef68ef00977bb26e274789a8e160c5e87e76e0dfd498bb1",
          "sha256": "b202740f906a274d3a8c82ffa8d2181289046218b052cd2307ba9aaeac804955",
          "sha1": "55f241980d489bb8158c177c5907a48ce16ff451",
          "md5": "1a55b2bc3cc800c436df58f6305c3eba"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android-debug/0.1.3-bump-ios-crypto-version-SNAPSHOT/data-donation-sdk-android-debug-0.1.3-bump-ios-crypto-version-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android-debug",
        "version": "0.1.3-bump-ios-crypto-version-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android-debug/0.1.3-bump-ios-crypto-version-SNAPSHOT/data-donation-sdk-android-debug-0.1.3-bump-ios-crypto-version-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android-debug",
        "version": "0.1.3-bump-ios-crypto-version-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android/0.1.3-bump-ios-crypto-version-SNAPSHOT/data-donation-sdk-android-0.1.3-bump-ios-crypto-version-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android",
        "version": "0.1.3-bump-ios-crypto-version-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android/0.1.3-bump-ios-crypto-version-SNAPSHOT/data-donation-sdk-android-0.1.3-bump-ios-crypto-version-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android",
        "version": "0.1.3-bump-ios-crypto-version-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../data-donation-sdk-iosarm64/0.1.3-bump-ios-crypto-version-SNAPSHOT/data-donation-sdk-iosarm64-0.1.3-bump-ios-crypto-version-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-iosarm64",
        "version": "0.1.3-bump-ios-crypto-version-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../data-donation-sdk-iosx64/0.1.3-bump-ios-crypto-version-SNAPSHOT/data-donation-sdk-iosx64-0.1.3-bump-ios-crypto-version-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-iosx64",
        "version": "0.1.3-bump-ios-crypto-version-SNAPSHOT"
      }
    }
  ]
}
