{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir/0.1.0-add-full-fhir3-support-SNAPSHOT/fhir-0.1.0-add-full-fhir3-support-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir",
    "version": "0.1.0-add-full-fhir3-support-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "fhir-jvm-0.1.0-add-full-fhir3-support-SNAPSHOT.jar",
          "url": "fhir-jvm-0.1.0-add-full-fhir3-support-SNAPSHOT.jar",
          "size": 16071003,
          "sha512": "6d52e8063a7a3ee3de11cb4f71bf30b4b4aad36e32cfc048fab27570400ecff9d501081461c6f4a63d3cb114d68248007313d291e3ff1b99608fd984dc4a68cf",
          "sha256": "66d0bdeff27dd7082fb60590e49d4c7113a200558a63961635e7a0241a27c78c",
          "sha1": "f2692a90583058cbb3014e3f783d9969a63e8b88",
          "md5": "138b08639dce0fb6e314fa0067f2f0c8"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-jvm-0.1.0-add-full-fhir3-support-SNAPSHOT.jar",
          "url": "fhir-jvm-0.1.0-add-full-fhir3-support-SNAPSHOT.jar",
          "size": 16071003,
          "sha512": "6d52e8063a7a3ee3de11cb4f71bf30b4b4aad36e32cfc048fab27570400ecff9d501081461c6f4a63d3cb114d68248007313d291e3ff1b99608fd984dc4a68cf",
          "sha256": "66d0bdeff27dd7082fb60590e49d4c7113a200558a63961635e7a0241a27c78c",
          "sha1": "f2692a90583058cbb3014e3f783d9969a63e8b88",
          "md5": "138b08639dce0fb6e314fa0067f2f0c8"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../fhir-metadata/0.1.0-add-full-fhir3-support-SNAPSHOT/fhir-metadata-0.1.0-add-full-fhir3-support-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-metadata",
        "version": "0.1.0-add-full-fhir3-support-SNAPSHOT"
      }
    }
  ]
}
