{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-ktor/0.3.0-bump-updates-SNAPSHOT/test-util-ktor-0.3.0-bump-updates-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-ktor",
    "version": "0.3.0-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-util-ktor-jvm-0.3.0-bump-updates-SNAPSHOT.jar",
          "url": "test-util-ktor-jvm-0.3.0-bump-updates-SNAPSHOT.jar",
          "size": 28739,
          "sha512": "388ea7b0dd255bab1a3a862af6fe92c718ed2397ddbabeb634c872dcd62959dea3757595d1a5f8b07f56a949a8d3f3a5de314341a1b1644f96baf23bed053dba",
          "sha256": "5849d2f64ea9fe1f250bdec87a6735a66d71e8381b9d7745e29a4ef4247934f7",
          "sha1": "3a79e4604c30c5658167aaabe3e456a4ab5a29c5",
          "md5": "941df958312ae0423f3832802c188db4"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.8"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor-jvm-0.3.0-bump-updates-SNAPSHOT.jar",
          "url": "test-util-ktor-jvm-0.3.0-bump-updates-SNAPSHOT.jar",
          "size": 28739,
          "sha512": "388ea7b0dd255bab1a3a862af6fe92c718ed2397ddbabeb634c872dcd62959dea3757595d1a5f8b07f56a949a8d3f3a5de314341a1b1644f96baf23bed053dba",
          "sha256": "5849d2f64ea9fe1f250bdec87a6735a66d71e8381b9d7745e29a4ef4247934f7",
          "sha1": "3a79e4604c30c5658167aaabe3e456a4ab5a29c5",
          "md5": "941df958312ae0423f3832802c188db4"
        }
      ]
    }
  ]
}
