{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util/0.3.0-bump-updates-SNAPSHOT/test-util-0.3.0-bump-updates-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util",
    "version": "0.3.0-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-util.klib",
          "url": "test-util-iosarm64-0.3.0-bump-updates-SNAPSHOT.klib",
          "size": 17519,
          "sha512": "820737284bbf4ab160d45aba479754655983b0e7c2432ff18c68766e6640c202ce33b2b9a66af0ae82d36eb820a6354eb06e6837c0cb466e70299dfcfe83a0fb",
          "sha256": "51a0e93ec267424a33e94cbceffdbe9c3a576ca0f57208cf4d8b4caee2b4d09a",
          "sha1": "12b6f2c8e23bcfbc5c7c9e6a3fd59a327787a78a",
          "md5": "a58951b506ffce78c1d345cf1d80a6e9"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-iosarm64-0.3.0-bump-updates-SNAPSHOT-metadata.jar",
          "url": "test-util-iosarm64-0.3.0-bump-updates-SNAPSHOT-metadata.jar",
          "size": 7055,
          "sha512": "baa8b175d2180305f863d2fccaf36ec2881510e9d5fd11ca3370ef09b5de14025dd10039902ee4d0a6ef58a47c122f384e46b52b148114bf4de5c48a847163b0",
          "sha256": "5bf133da95b26c5ea1fe32a11ff48b44d36d27386503da24fc6c4db140705e9e",
          "sha1": "9c2a8f409dbebf60df7f83d17cf5b0b2be3a7b68",
          "md5": "ffa0e05b9b8cd36b89e91513a0923b07"
        }
      ]
    }
  ]
}
