{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coroutine-util/141021c/coroutine-util-141021c.module",
    "group": "care.data4life.hc-coroutine-util-sdk-kmp",
    "module": "coroutine-util",
    "version": "141021c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "ey5qsewajbc7rn4nl65ugjjb2m"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "coroutine-util-jvm-141021c.jar",
          "url": "coroutine-util-jvm-141021c.jar",
          "size": 2767,
          "sha512": "b8fca773a381e24502c55b6d49b3144c5eed24d63428e768e12486b8dbc30ff757a52cede23fd67ef39a400c4ed9f4041e2eb364cf75f3c086fa371fd36f6c1e",
          "sha256": "58502d624318b5d716059a7af82ba0c7f6eaeffd24c8837dd22232434194e2d3",
          "sha1": "d43cc20f99654733c45d632fa1ce9cc2b4365090",
          "md5": "6eb9b6de0bc91928ade22b48ec41e5e5"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "coroutine-util-jvm-141021c.jar",
          "url": "coroutine-util-jvm-141021c.jar",
          "size": 2767,
          "sha512": "b8fca773a381e24502c55b6d49b3144c5eed24d63428e768e12486b8dbc30ff757a52cede23fd67ef39a400c4ed9f4041e2eb364cf75f3c086fa371fd36f6c1e",
          "sha256": "58502d624318b5d716059a7af82ba0c7f6eaeffd24c8837dd22232434194e2d3",
          "sha1": "d43cc20f99654733c45d632fa1ce9cc2b4365090",
          "md5": "6eb9b6de0bc91928ade22b48ec41e5e5"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../coroutine-util-metadata/141021c/coroutine-util-metadata-141021c.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util-metadata",
        "version": "141021c"
      }
    }
  ]
}
