{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-gradle-scripts",
    "module": "example-kmp-library",
    "version": "0.0.1-add-coverage-scripts-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ul3lcnxngzcrbon5g3vr4jwbie"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "example-kmp-library-metadata-0.0.1-add-coverage-scripts-SNAPSHOT.jar",
          "url": "example-kmp-library-0.0.1-add-coverage-scripts-SNAPSHOT.jar",
          "size": 5810,
          "sha512": "5eedf0701cbfaf639829b53251edfa2335636cabedce1e6f30563ecade03aee23955301a3a2cfb35e03c82657686ff5648ed1f2322b3aa8c3202225891981084",
          "sha256": "6ad6c0c13ca946ace154d75d6c6afda7fd5f3d27a278c9bbe92c197f4dfd602f",
          "sha1": "593c88d5db99e366c73d21ce0703d9207c6e950a",
          "md5": "193137013283af04e472265721e5a7a9"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../example-kmp-library-android/0.0.1-add-coverage-scripts-SNAPSHOT/example-kmp-library-android-0.0.1-add-coverage-scripts-SNAPSHOT.module",
        "group": "care.data4life",
        "module": "example-kmp-library-android",
        "version": "0.0.1-add-coverage-scripts-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../example-kmp-library-android/0.0.1-add-coverage-scripts-SNAPSHOT/example-kmp-library-android-0.0.1-add-coverage-scripts-SNAPSHOT.module",
        "group": "care.data4life",
        "module": "example-kmp-library-android",
        "version": "0.0.1-add-coverage-scripts-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../example-kmp-library-android/0.0.1-add-coverage-scripts-SNAPSHOT/example-kmp-library-android-0.0.1-add-coverage-scripts-SNAPSHOT.module",
        "group": "care.data4life.hc-gradle-scripts",
        "module": "example-kmp-library-android",
        "version": "0.0.1-add-coverage-scripts-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../example-kmp-library-android/0.0.1-add-coverage-scripts-SNAPSHOT/example-kmp-library-android-0.0.1-add-coverage-scripts-SNAPSHOT.module",
        "group": "care.data4life.hc-gradle-scripts",
        "module": "example-kmp-library-android",
        "version": "0.0.1-add-coverage-scripts-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../example-kmp-library-iosarm64/0.0.1-add-coverage-scripts-SNAPSHOT/example-kmp-library-iosarm64-0.0.1-add-coverage-scripts-SNAPSHOT.module",
        "group": "care.data4life",
        "module": "example-kmp-library-iosarm64",
        "version": "0.0.1-add-coverage-scripts-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../example-kmp-library-iosx64/0.0.1-add-coverage-scripts-SNAPSHOT/example-kmp-library-iosx64-0.0.1-add-coverage-scripts-SNAPSHOT.module",
        "group": "care.data4life",
        "module": "example-kmp-library-iosx64",
        "version": "0.0.1-add-coverage-scripts-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../example-kmp-library-jvm/0.0.1-add-coverage-scripts-SNAPSHOT/example-kmp-library-jvm-0.0.1-add-coverage-scripts-SNAPSHOT.module",
        "group": "care.data4life.hc-gradle-scripts",
        "module": "example-kmp-library-jvm",
        "version": "0.0.1-add-coverage-scripts-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../example-kmp-library-jvm/0.0.1-add-coverage-scripts-SNAPSHOT/example-kmp-library-jvm-0.0.1-add-coverage-scripts-SNAPSHOT.module",
        "group": "care.data4life.hc-gradle-scripts",
        "module": "example-kmp-library-jvm",
        "version": "0.0.1-add-coverage-scripts-SNAPSHOT"
      }
    }
  ]
}
