{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.11.0-add-networking-contract-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "3ov5eze3svdddlovjj2g7vbcra"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.11.0-add-networking-contract-SNAPSHOT.jar",
          "url": "securestore-common-1.11.0-add-networking-contract-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "60130669dc8595dcb26d4c6f01df59d50a375aaf981e8560ba5ff3bbe0115495e1a0ee2a11df5a5f6f6d00dbc5568f1b217a5a01d33ef3c46ad1c7772a29323e",
          "sha256": "d2a306388ecc1090a0c9105a87a01145db70b3c99da0478f79a8a4dbc0cdcc74",
          "sha1": "38e734dba033182d55b34c0a52a6731b02657499",
          "md5": "6b99bd12a09bb5f4633a79c37d020acc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.11.0-add-networking-contract-SNAPSHOT.jar",
          "url": "securestore-common-1.11.0-add-networking-contract-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "60130669dc8595dcb26d4c6f01df59d50a375aaf981e8560ba5ff3bbe0115495e1a0ee2a11df5a5f6f6d00dbc5568f1b217a5a01d33ef3c46ad1c7772a29323e",
          "sha256": "d2a306388ecc1090a0c9105a87a01145db70b3c99da0478f79a8a4dbc0cdcc74",
          "sha1": "38e734dba033182d55b34c0a52a6731b02657499",
          "md5": "6b99bd12a09bb5f4633a79c37d020acc"
        }
      ]
    }
  ]
}
