{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.8.0-SNAPSHOT/util-1.8.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.8.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "kzppovjhezf5tfuy7qnxi7ormi"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-jvm-1.8.0-SNAPSHOT.jar",
          "url": "util-jvm-1.8.0-SNAPSHOT.jar",
          "size": 19627,
          "sha512": "60aab39af41d1d3200e5ddf942b5cd31d3ba76461993d9738704076a15c7dc71d5a8cd9e1c2b4cb8342ba33badc876cf2a050e2fc4022009aab65db5dd27c13b",
          "sha256": "c80d0a9744ea74ebc54652d3325f198179ef300a0a8e1488f9f55b8c63725095",
          "sha1": "60c1e2ea80cd876ca2ca5e97a31315f68166cc7b",
          "md5": "33b8326da7faa1773d73b95390ccafd2"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "util-jvm-1.8.0-SNAPSHOT.jar",
          "url": "util-jvm-1.8.0-SNAPSHOT.jar",
          "size": 19627,
          "sha512": "60aab39af41d1d3200e5ddf942b5cd31d3ba76461993d9738704076a15c7dc71d5a8cd9e1c2b4cb8342ba33badc876cf2a050e2fc4022009aab65db5dd27c13b",
          "sha256": "c80d0a9744ea74ebc54652d3325f198179ef300a0a8e1488f9f55b8c63725095",
          "sha1": "60c1e2ea80cd876ca2ca5e97a31315f68166cc7b",
          "md5": "33b8326da7faa1773d73b95390ccafd2"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-metadata/1.8.0-SNAPSHOT/util-metadata-1.8.0-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-metadata",
        "version": "1.8.0-SNAPSHOT"
      }
    }
  ]
}
