{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.13.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ibnopu4mrjbqveajiujxmltyam"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.13.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.13.1-SNAPSHOT.jar",
          "url": "crypto-jvm-1.13.1-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "f5c03544b8907cf927bf2e58385ae14a05b412184c68b2e40444f5c44c8503ab2831dd575ac24fc35307ad5db601fd464e407f5e3ecda1fba8275e0390e06741",
          "sha256": "026599814ec6bcef722acb3929ac9f17faeb8610a4c8de66ce21c29f57d11cf5",
          "sha1": "e5b0eee949a2785bfea914bcd6b661719e5ab2fc",
          "md5": "51a3a58e2b2bbccb9a75ed93ce48e334"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.13.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.13.1-SNAPSHOT.jar",
          "url": "crypto-jvm-1.13.1-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "f5c03544b8907cf927bf2e58385ae14a05b412184c68b2e40444f5c44c8503ab2831dd575ac24fc35307ad5db601fd464e407f5e3ecda1fba8275e0390e06741",
          "sha256": "026599814ec6bcef722acb3929ac9f17faeb8610a4c8de66ce21c29f57d11cf5",
          "sha1": "e5b0eee949a2785bfea914bcd6b661719e5ab2fc",
          "md5": "51a3a58e2b2bbccb9a75ed93ce48e334"
        }
      ]
    }
  ]
}
