{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.11.0-fix-update-record-data-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "lb2zohodwvghfkmmvcz42oxthi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.11.0-fix-update-record-data-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-fix-update-record-data-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "f2933857bb20580758938e7c0b6987b7c575014808df30476f8681c272e2e5e54b9e6d0e69d0f62548047cb5b3af1afa3ad311cb09b5d77788cd724608c6be6a",
          "sha256": "08acc358076548bc858f82f1a5f6561f8885adf293814da5fadbb2d8f2b5121a",
          "sha1": "48cd2b0247703f31fae3287f1d6c53d29120f049",
          "md5": "54571ac2b728ce24719c9208c224a7a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.11.0-fix-update-record-data-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-fix-update-record-data-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "f2933857bb20580758938e7c0b6987b7c575014808df30476f8681c272e2e5e54b9e6d0e69d0f62548047cb5b3af1afa3ad311cb09b5d77788cd724608c6be6a",
          "sha256": "08acc358076548bc858f82f1a5f6561f8885adf293814da5fadbb2d8f2b5121a",
          "sha1": "48cd2b0247703f31fae3287f1d6c53d29120f049",
          "md5": "54571ac2b728ce24719c9208c224a7a9"
        }
      ]
    }
  ]
}
