{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-securestore-sdk-kmp",
    "module": "securestore",
    "version": "1.16.0-bump-changelog-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "securestore-metadata-1.16.0-bump-changelog-SNAPSHOT.jar",
          "url": "securestore-1.16.0-bump-changelog-SNAPSHOT.jar",
          "size": 670,
          "sha512": "c521f805f2eb02c2e5e8afacd7eadd53f572d105a14ec1ac6b61cd6341f2985e3553be20ac933ddecdbb1e87cbc310cbd3515f0dfa51d1120767ab37b7a6a125",
          "sha256": "a3b1e98f8744a4597f9a957a2cc008be45c787c6353195233da7029e245d1404",
          "sha1": "dfc22945bf08732eca18746de2112b5efa8ebf4f",
          "md5": "48e23e5edd917c4011c17ee6e8ffdb5d"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../securestore-android-debug/1.16.0-bump-changelog-SNAPSHOT/securestore-android-debug-1.16.0-bump-changelog-SNAPSHOT.module",
        "group": "care.data4life.hc-securestore-sdk-kmp",
        "module": "securestore-android-debug",
        "version": "1.16.0-bump-changelog-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../securestore-android-debug/1.16.0-bump-changelog-SNAPSHOT/securestore-android-debug-1.16.0-bump-changelog-SNAPSHOT.module",
        "group": "care.data4life.hc-securestore-sdk-kmp",
        "module": "securestore-android-debug",
        "version": "1.16.0-bump-changelog-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../securestore-android/1.16.0-bump-changelog-SNAPSHOT/securestore-android-1.16.0-bump-changelog-SNAPSHOT.module",
        "group": "care.data4life.hc-securestore-sdk-kmp",
        "module": "securestore-android",
        "version": "1.16.0-bump-changelog-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../securestore-android/1.16.0-bump-changelog-SNAPSHOT/securestore-android-1.16.0-bump-changelog-SNAPSHOT.module",
        "group": "care.data4life.hc-securestore-sdk-kmp",
        "module": "securestore-android",
        "version": "1.16.0-bump-changelog-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../securestore-jvm/1.16.0-bump-changelog-SNAPSHOT/securestore-jvm-1.16.0-bump-changelog-SNAPSHOT.module",
        "group": "care.data4life.hc-securestore-sdk-kmp",
        "module": "securestore-jvm",
        "version": "1.16.0-bump-changelog-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../securestore-jvm/1.16.0-bump-changelog-SNAPSHOT/securestore-jvm-1.16.0-bump-changelog-SNAPSHOT.module",
        "group": "care.data4life.hc-securestore-sdk-kmp",
        "module": "securestore-jvm",
        "version": "1.16.0-bump-changelog-SNAPSHOT"
      }
    }
  ]
}
