{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-fhir-helper-sdk-kmp",
    "module": "fhir-helper",
    "version": "1.8.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "fhir-helper-metadata-1.8.0-SNAPSHOT.jar",
          "url": "fhir-helper-1.8.0-SNAPSHOT.jar",
          "size": 1510,
          "sha512": "54b52314e45353720c4eef0630aa77a1e9dc78650b9a8d237e5ce4a93aaca3d95da9261f6bcff985ccee24fbe29d3dcc8167f70455469d09a97bbcade4845b70",
          "sha256": "26c2d02be941aa12673146e75cf68b9abea829342dd51412dd6e19d8d0fafc4e",
          "sha1": "ca5fbca36847f8d6e8fbd054194614065824990d",
          "md5": "6aa985ef3e9a97bb71845fb66dc0cff1"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-helper-android-debug/1.8.0-SNAPSHOT/fhir-helper-android-debug-1.8.0-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-helper-sdk-kmp",
        "module": "fhir-helper-android-debug",
        "version": "1.8.0-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-helper-android-debug/1.8.0-SNAPSHOT/fhir-helper-android-debug-1.8.0-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-helper-sdk-kmp",
        "module": "fhir-helper-android-debug",
        "version": "1.8.0-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-helper-android/1.8.0-SNAPSHOT/fhir-helper-android-1.8.0-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-helper-sdk-kmp",
        "module": "fhir-helper-android",
        "version": "1.8.0-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-helper-android/1.8.0-SNAPSHOT/fhir-helper-android-1.8.0-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-helper-sdk-kmp",
        "module": "fhir-helper-android",
        "version": "1.8.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../fhir-helper-jvm/1.8.0-SNAPSHOT/fhir-helper-jvm-1.8.0-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-helper-sdk-kmp",
        "module": "fhir-helper-jvm",
        "version": "1.8.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../fhir-helper-jvm/1.8.0-SNAPSHOT/fhir-helper-jvm-1.8.0-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-helper-sdk-kmp",
        "module": "fhir-helper-jvm",
        "version": "1.8.0-SNAPSHOT"
      }
    }
  ]
}
