{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.10.0-add-secure-store-and-crypto-service-kotlin-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "vpbm6lmtdvcl7gezbc5xya2ioe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.10.0-add-secure-store-and-crypto-service-kotlin-tests-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-add-secure-store-and-crypto-service-kotlin-tests-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "23726b1ac0109255b824b408a9fc258b6624d906a257d436576f4d98638f783f34572cae21a706c00eb0bce12221a34285890b0508a15f2b96f12716e141d013",
          "sha256": "545ca70648a835c5a57a8beeb40ef76bb5c81742a7f3d4bee611beb95d29e6cd",
          "sha1": "c1ce8c8eb303879ac8921a9e855f9e2afa9786f6",
          "md5": "666103991f623dc05ce8c7ae43593a79"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.10.0-add-secure-store-and-crypto-service-kotlin-tests-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-add-secure-store-and-crypto-service-kotlin-tests-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "23726b1ac0109255b824b408a9fc258b6624d906a257d436576f4d98638f783f34572cae21a706c00eb0bce12221a34285890b0508a15f2b96f12716e141d013",
          "sha256": "545ca70648a835c5a57a8beeb40ef76bb5c81742a7f3d4bee611beb95d29e6cd",
          "sha1": "c1ce8c8eb303879ac8921a9e855f9e2afa9786f6",
          "md5": "666103991f623dc05ce8c7ae43593a79"
        }
      ]
    }
  ]
}
