{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir-helper/1.7.1-SNAPSHOT/fhir-helper-1.7.1-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-helper-sdk-kmp",
    "module": "fhir-helper",
    "version": "1.7.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "care.data4life.hc-result-sdk-kmp",
          "module": "error-jvm",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-helper-jvm-1.7.1-SNAPSHOT.jar",
          "url": "fhir-helper-jvm-1.7.1-SNAPSHOT.jar",
          "size": 116089,
          "sha512": "59de95e021a4f68fd040f583c0fba73d9f3fa55cf798ed11eb0a8c5ca3c5637e1b2b62a49a1c6028d114c91169fca4c8cb056e364d3daee3f0db687894d45a1c",
          "sha256": "43b7bf32e6f2cd842fe18c74120d0e0f39866fdcfbcae7990338139e5291e4ed",
          "sha1": "1fa21a62c638196c26da18ea0d7bbb732299e30d",
          "md5": "2c09dd28982839e678e30f8666f48cef"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "care.data4life.hc-result-sdk-kmp",
          "module": "error-jvm",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "care.data4life.hc-result-sdk-kmp",
          "module": "error",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-helper-jvm-1.7.1-SNAPSHOT.jar",
          "url": "fhir-helper-jvm-1.7.1-SNAPSHOT.jar",
          "size": 116089,
          "sha512": "59de95e021a4f68fd040f583c0fba73d9f3fa55cf798ed11eb0a8c5ca3c5637e1b2b62a49a1c6028d114c91169fca4c8cb056e364d3daee3f0db687894d45a1c",
          "sha256": "43b7bf32e6f2cd842fe18c74120d0e0f39866fdcfbcae7990338139e5291e4ed",
          "sha1": "1fa21a62c638196c26da18ea0d7bbb732299e30d",
          "md5": "2c09dd28982839e678e30f8666f48cef"
        }
      ]
    }
  ]
}
