{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.11.0-change-publishing-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "3q6sqwkuqzgqbjbhcpm4pqmfca"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-change-publishing-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.11.0-change-publishing-SNAPSHOT.jar",
          "url": "auth-jvm-1.11.0-change-publishing-SNAPSHOT.jar",
          "size": 34283,
          "sha512": "323c377c3e61f057e048f9b85983510461bb6ff9ca9a67a7598c9fdc77f36918e4a4f1e76b01162a211e224d9c7edef7244c7c83173b91f1365bf20a690b9f89",
          "sha256": "e9b93b19a1f2815ff1196f68c61f896e6f557abb44f06a5b67348968d24226f6",
          "sha1": "58ec454f208b8b09ab974415cea348608241c9d6",
          "md5": "78217a71448a2241bdf39eaf7f06fced"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.11.0-change-publishing-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-change-publishing-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.11.0-change-publishing-SNAPSHOT.jar",
          "url": "auth-jvm-1.11.0-change-publishing-SNAPSHOT.jar",
          "size": 34283,
          "sha512": "323c377c3e61f057e048f9b85983510461bb6ff9ca9a67a7598c9fdc77f36918e4a4f1e76b01162a211e224d9c7edef7244c7c83173b91f1365bf20a690b9f89",
          "sha256": "e9b93b19a1f2815ff1196f68c61f896e6f557abb44f06a5b67348968d24226f6",
          "sha1": "58ec454f208b8b09ab974415cea348608241c9d6",
          "md5": "78217a71448a2241bdf39eaf7f06fced"
        }
      ]
    }
  ]
}
