{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.8.1-SNAPSHOT/util-1.8.1-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.8.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "2q6aiy6mobbibbtl3vdzcdw4gu"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-jvm-1.8.1-SNAPSHOT.jar",
          "url": "util-jvm-1.8.1-SNAPSHOT.jar",
          "size": 19627,
          "sha512": "a2cada5638300ec44b317177585dfe27f19330289158ca6575b630ec017cf42804ad47c5b17cbdc7c3413b7a0fbad827e166c14bd652a843e027c8a4a7790bf7",
          "sha256": "e55fee9d236bf078a5bb492fc55581778be8fabdbc9fb40d05ec5cc687f191ef",
          "sha1": "fbc64c8da658218445ddea7dec3967047b800b84",
          "md5": "2c1011c5eed6f937ce0104db3ee2b67b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "util-jvm-1.8.1-SNAPSHOT.jar",
          "url": "util-jvm-1.8.1-SNAPSHOT.jar",
          "size": 19627,
          "sha512": "a2cada5638300ec44b317177585dfe27f19330289158ca6575b630ec017cf42804ad47c5b17cbdc7c3413b7a0fbad827e166c14bd652a843e027c8a4a7790bf7",
          "sha256": "e55fee9d236bf078a5bb492fc55581778be8fabdbc9fb40d05ec5cc687f191ef",
          "sha1": "fbc64c8da658218445ddea7dec3967047b800b84",
          "md5": "2c1011c5eed6f937ce0104db3ee2b67b"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-metadata/1.8.1-SNAPSHOT/util-metadata-1.8.1-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-metadata",
        "version": "1.8.1-SNAPSHOT"
      }
    }
  ]
}
