{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.8.1-SNAPSHOT/util-1.8.1-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.8.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "cst62qksjnawjlsdmfwep3t4he"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-jvm-1.8.1-SNAPSHOT.jar",
          "url": "util-jvm-1.8.1-SNAPSHOT.jar",
          "size": 19627,
          "sha512": "b814ea76f0b3e45176d6484fda528ce42a615983f8bf79560fcfc0ce8360e7852cf69b14dec58f1423d46ba9e5b765301c643470f7368d832c0834eff0897985",
          "sha256": "9494cd83ce07f810c17ce8c9aa19cd42b6efa030081e5d7f1f5b9e9a66856467",
          "sha1": "097c73eab894f409d0d99194f05a816cce338df4",
          "md5": "d00adea18306eb15b3a593e53d26fb26"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "util-jvm-1.8.1-SNAPSHOT.jar",
          "url": "util-jvm-1.8.1-SNAPSHOT.jar",
          "size": 19627,
          "sha512": "b814ea76f0b3e45176d6484fda528ce42a615983f8bf79560fcfc0ce8360e7852cf69b14dec58f1423d46ba9e5b765301c643470f7368d832c0834eff0897985",
          "sha256": "9494cd83ce07f810c17ce8c9aa19cd42b6efa030081e5d7f1f5b9e9a66856467",
          "sha1": "097c73eab894f409d0d99194f05a816cce338df4",
          "md5": "d00adea18306eb15b3a593e53d26fb26"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-metadata/1.8.1-SNAPSHOT/util-metadata-1.8.1-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-metadata",
        "version": "1.8.1-SNAPSHOT"
      }
    }
  ]
}
