{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.12.0-change-merge-fhir-and-data-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "qqfzc4u6dnghhl7da2ilc5kun4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.12.0-change-merge-fhir-and-data-SNAPSHOT.jar",
          "url": "auth-common-1.12.0-change-merge-fhir-and-data-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "0868393a1f424b7077c1d1f54018c62dac2e492c70a68e1127f74f7ab15fe50aaee1fe7a811497f0f47a66cd86c56f3089d187ba7890870f363a6110c797a376",
          "sha256": "aef1c896bca1190a89a205f10b3df0f69f1efc5531b69304f55075901ba3b8a1",
          "sha1": "ea671c4941b200c6338e8677ce5e40093731538e",
          "md5": "5e72f599cfd7ca6bca0e71ba9c45be1c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.12.0-change-merge-fhir-and-data-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.12.0-change-merge-fhir-and-data-SNAPSHOT.jar",
          "url": "auth-common-1.12.0-change-merge-fhir-and-data-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "0868393a1f424b7077c1d1f54018c62dac2e492c70a68e1127f74f7ab15fe50aaee1fe7a811497f0f47a66cd86c56f3089d187ba7890870f363a6110c797a376",
          "sha256": "aef1c896bca1190a89a205f10b3df0f69f1efc5531b69304f55075901ba3b8a1",
          "sha1": "ea671c4941b200c6338e8677ce5e40093731538e",
          "md5": "5e72f599cfd7ca6bca0e71ba9c45be1c"
        }
      ]
    }
  ]
}
