{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-coroutine-test-jvm/1.9.0-add-default-scope-SNAPSHOT/util-coroutine-test-jvm-1.9.0-add-default-scope-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-coroutine-test-jvm",
    "version": "1.9.0-add-default-scope-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "lywpjsvcsfhm7mjwnl7aytkyki"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-coroutine-test-metadata-1.9.0-add-default-scope-SNAPSHOT.jar",
          "url": "util-coroutine-test-metadata-1.9.0-add-default-scope-SNAPSHOT.jar",
          "size": 1777,
          "sha512": "a3c269b3bd6da2672ba6a5915c37fd262a081e4c2125c8cf2d4d78827523659d9d75ce3d72a1e3c1565eebb5c580f2196a4360cf9f37e37171fb78ab57bf4bb4",
          "sha256": "3ffd19e85c159ea02b93e53e860b0cdbfe88ea5f55315af3d56250a3e2b90f68",
          "sha1": "455d0b6f3b67c3fb08744c88e1b2ffda6fd003a5",
          "md5": "6a5e349f8196ba63dda8ed3c0a66e9e0"
        }
      ]
    }
  ]
}
