{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.11.0-change-api-module-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "yh7v6gktcnclfmkyqperhteof4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.11.0-change-api-module-tests-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-change-api-module-tests-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "c9c21c1f81e6dd57171fb05af3e462897540baa3b74bbc4c0198f3547cc105bed1dac74439bed3b5f5c4b0220a47bc78da3a5db1b153c90186a0f170246cb0d5",
          "sha256": "3305aa75cf568efa68e2a0b3c71c876c66ad3f46ca1f1abf02d5d0832dd6c3e0",
          "sha1": "194ab19c4dce5c6e53d963ba879f2c5e7d66fecb",
          "md5": "f5c7f4033328e2078b76455453804016"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.11.0-change-api-module-tests-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-change-api-module-tests-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "c9c21c1f81e6dd57171fb05af3e462897540baa3b74bbc4c0198f3547cc105bed1dac74439bed3b5f5c4b0220a47bc78da3a5db1b153c90186a0f170246cb0d5",
          "sha256": "3305aa75cf568efa68e2a0b3c71c876c66ad3f46ca1f1abf02d5d0832dd6c3e0",
          "sha1": "194ab19c4dce5c6e53d963ba879f2c5e7d66fecb",
          "md5": "f5c7f4033328e2078b76455453804016"
        }
      ]
    }
  ]
}
