{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-jvm",
    "version": "1.11.0-change-api-service-to-kotlin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "bu5s5zhe5becvbygzzwghyn3gi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.11.0-change-api-service-to-kotlin-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.11.0-change-api-service-to-kotlin-SNAPSHOT.jar",
          "url": "sdk-jvm-1.11.0-change-api-service-to-kotlin-SNAPSHOT.jar",
          "size": 11547,
          "sha512": "135c46a8042280f6021ce29107b7f96c0b8fb811d9aae35a482341e4235915d01966472ac7ed558bd6e923e2f3d1867fbaffd7f5905a5d71422c7a84a7d2e4df",
          "sha256": "25fa20994cd91b0d493dc8e32969301c79dad2c5e3a6743ac0a3ccaeaf859934",
          "sha1": "c69f48b15480c94e262e9bdf7b232b56b4275ca5",
          "md5": "68d62daa7e3045ec4ffe486736881587"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.11.0-change-api-service-to-kotlin-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.11.0-change-api-service-to-kotlin-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.11.0-change-api-service-to-kotlin-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.11.0-change-api-service-to-kotlin-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.11.0-change-api-service-to-kotlin-SNAPSHOT.jar",
          "url": "sdk-jvm-1.11.0-change-api-service-to-kotlin-SNAPSHOT.jar",
          "size": 11547,
          "sha512": "135c46a8042280f6021ce29107b7f96c0b8fb811d9aae35a482341e4235915d01966472ac7ed558bd6e923e2f3d1867fbaffd7f5905a5d71422c7a84a7d2e4df",
          "sha256": "25fa20994cd91b0d493dc8e32969301c79dad2c5e3a6743ac0a3ccaeaf859934",
          "sha1": "c69f48b15480c94e262e9bdf7b232b56b4275ca5",
          "md5": "68d62daa7e3045ec4ffe486736881587"
        }
      ]
    }
  ]
}
