{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.12.0-add-auth-client-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "jfappqw7pncurlg45vldq5mioy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.12.0-add-auth-client-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.12.0-add-auth-client-tests-SNAPSHOT.jar",
          "url": "crypto-jvm-1.12.0-add-auth-client-tests-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "1a32c0f2cf0da7431f675239f6f77dc87cc826616a57632b5d001c65ba3a3463c683a03069a5ad38ae59d9447c6c073a5d3c381528cb6bfc6f8d7cec04fd2a48",
          "sha256": "c662bc736ce9e3ca531739009ef3cfab63e565aec9c4518cf4ef56242e3d7922",
          "sha1": "1111eb6929c2e9e5381246a8f42028946d7c8597",
          "md5": "b9fb050d78135d7729ce2b66220b50f0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.12.0-add-auth-client-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.12.0-add-auth-client-tests-SNAPSHOT.jar",
          "url": "crypto-jvm-1.12.0-add-auth-client-tests-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "1a32c0f2cf0da7431f675239f6f77dc87cc826616a57632b5d001c65ba3a3463c683a03069a5ad38ae59d9447c6c073a5d3c381528cb6bfc6f8d7cec04fd2a48",
          "sha256": "c662bc736ce9e3ca531739009ef3cfab63e565aec9c4518cf4ef56242e3d7922",
          "sha1": "1111eb6929c2e9e5381246a8f42028946d7c8597",
          "md5": "b9fb050d78135d7729ce2b66220b50f0"
        }
      ]
    }
  ]
}
