{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-android",
    "version": "1.11.0-bump-okhttp-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "gpnkc7p7ebeeffqavho5h7k5ju"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-bump-okhttp-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.11.0-bump-okhttp-SNAPSHOT.aar",
          "url": "auth-android-1.11.0-bump-okhttp-SNAPSHOT.aar",
          "size": 45006,
          "sha512": "65cea31037dd051090baa0ae63a976189360aff54a0c0fc680c5d965ece7df653dc84b60b76fbbfb0999bd2eee7e4fcc39cfa2f90981d317beb811ca330b12f1",
          "sha256": "b56c2ade77784879cebb2f47e766a8f084d7d127950944e818553e7a63a77da7",
          "sha1": "d1e80742cb9a0fab154512517728f35df1907fd2",
          "md5": "d0a8ef9c371a913bc1da1d52108c37e4"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-bump-okhttp-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-android",
          "version": {
            "requires": "1.11.0-bump-okhttp-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.gesundheitscloud",
          "module": "AppAuth-Android",
          "version": {
            "requires": "9e3cc033ff"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.11.0-bump-okhttp-SNAPSHOT.aar",
          "url": "auth-android-1.11.0-bump-okhttp-SNAPSHOT.aar",
          "size": 45006,
          "sha512": "65cea31037dd051090baa0ae63a976189360aff54a0c0fc680c5d965ece7df653dc84b60b76fbbfb0999bd2eee7e4fcc39cfa2f90981d317beb811ca330b12f1",
          "sha256": "b56c2ade77784879cebb2f47e766a8f084d7d127950944e818553e7a63a77da7",
          "sha1": "d1e80742cb9a0fab154512517728f35df1907fd2",
          "md5": "d0a8ef9c371a913bc1da1d52108c37e4"
        }
      ]
    }
  ]
}
