{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-coroutine-util-sdk-kmp",
    "module": "coroutine-util",
    "version": "0.1.0-change-setup-to-latest-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "z7v3ek7uxrcjdbyyyvyzsrctvm"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "coroutine-util-metadata-0.1.0-change-setup-to-latest-SNAPSHOT-all.jar",
          "url": "coroutine-util-0.1.0-change-setup-to-latest-SNAPSHOT-all.jar",
          "size": 5085,
          "sha512": "42225d1c0e2b47135973d339d8ab46164b451abf567bf0284e885f366f9ddabaa5739ab38bf57ff5ff6e8e793c3468cb6cd1bc4a8381b0cf3b0b4abfda5c4f89",
          "sha256": "a195ceb1ee5358cde623429105422a249219d2b23ce1bac1f399a7a385c4deb1",
          "sha1": "8c3c6a7904a9eb61bb5ec08ed7fad21184d26915",
          "md5": "5653c7b4e10a31c208c6686cf18bedaf"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "coroutine-util-0.1.0-change-setup-to-latest-SNAPSHOT.jar",
          "url": "coroutine-util-0.1.0-change-setup-to-latest-SNAPSHOT.jar",
          "size": 2634,
          "sha512": "2b8bdeb1ebc32defb0b10d23485d8a7b54e86467e734cf65d234114cbc8e13795ca30102d152197009ea935a52a629f301ee0f9a2abaf68015cf1c104086fa27",
          "sha256": "722969117588c0e6510a0e777973c04764a128d72aacd7d84340428f11f66223",
          "sha1": "dd05c62c7cc6a4bdffac25352637bb3ddb93a8ef",
          "md5": "e4a27b3ecbac4276724fd89de04a1f0d"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../coroutine-util-android-debug/0.1.0-change-setup-to-latest-SNAPSHOT/coroutine-util-android-debug-0.1.0-change-setup-to-latest-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util-android-debug",
        "version": "0.1.0-change-setup-to-latest-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../coroutine-util-android-debug/0.1.0-change-setup-to-latest-SNAPSHOT/coroutine-util-android-debug-0.1.0-change-setup-to-latest-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util-android-debug",
        "version": "0.1.0-change-setup-to-latest-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../coroutine-util-android/0.1.0-change-setup-to-latest-SNAPSHOT/coroutine-util-android-0.1.0-change-setup-to-latest-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util-android",
        "version": "0.1.0-change-setup-to-latest-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../coroutine-util-android/0.1.0-change-setup-to-latest-SNAPSHOT/coroutine-util-android-0.1.0-change-setup-to-latest-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util-android",
        "version": "0.1.0-change-setup-to-latest-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutine-util-iosarm64/0.1.0-change-setup-to-latest-SNAPSHOT/coroutine-util-iosarm64-0.1.0-change-setup-to-latest-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util-iosarm64",
        "version": "0.1.0-change-setup-to-latest-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutine-util-iosarm64/0.1.0-change-setup-to-latest-SNAPSHOT/coroutine-util-iosarm64-0.1.0-change-setup-to-latest-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util-iosarm64",
        "version": "0.1.0-change-setup-to-latest-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutine-util-iosx64/0.1.0-change-setup-to-latest-SNAPSHOT/coroutine-util-iosx64-0.1.0-change-setup-to-latest-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util-iosx64",
        "version": "0.1.0-change-setup-to-latest-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutine-util-iosx64/0.1.0-change-setup-to-latest-SNAPSHOT/coroutine-util-iosx64-0.1.0-change-setup-to-latest-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util-iosx64",
        "version": "0.1.0-change-setup-to-latest-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../coroutine-util-jvm/0.1.0-change-setup-to-latest-SNAPSHOT/coroutine-util-jvm-0.1.0-change-setup-to-latest-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util-jvm",
        "version": "0.1.0-change-setup-to-latest-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../coroutine-util-jvm/0.1.0-change-setup-to-latest-SNAPSHOT/coroutine-util-jvm-0.1.0-change-setup-to-latest-SNAPSHOT.module",
        "group": "care.data4life.hc-coroutine-util-sdk-kmp",
        "module": "coroutine-util-jvm",
        "version": "0.1.0-change-setup-to-latest-SNAPSHOT"
      }
    }
  ]
}
