{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.3-add-credential-retrieval-SNAPSHOT/data-donation-sdk-iosx64-0.1.3-add-credential-retrieval-SNAPSHOT.module",
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.3-add-credential-retrieval-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "5s3wlis2srf6tggzs3qqswkapm"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.3-add-credential-retrieval-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.3-add-credential-retrieval-SNAPSHOT.jar",
          "size": 82639,
          "sha512": "4912feed165c8cd80620c78520d959bdf99b05c7f48210bdff297f4e1ec9e33a6134e2ed3d2d0e72e96599fd4a4cf7d9c44af0fa6e6508bd6df1bbcf620f68ed",
          "sha256": "57c2087918437086d26323ee5f629ffb8cdb39db673adad2b7cded7d860a2687",
          "sha1": "e519049319056c0e558bedf246108bac70864c3f",
          "md5": "d4e720a36cb40aae8f212a335bd4f6ef"
        }
      ]
    }
  ]
}
