{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.3-add-credential-retrieval-SNAPSHOT/data-donation-sdk-iosx64-0.1.3-add-credential-retrieval-SNAPSHOT.module",
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.3-add-credential-retrieval-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "rh6zwhvj3vc3ng57dmltsmi324"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.3-add-credential-retrieval-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.3-add-credential-retrieval-SNAPSHOT.jar",
          "size": 97923,
          "sha512": "c468b234c66d87791cf8f184da94e5c09c5c89413156b21d78ed0cfb47b69ec89d18f6e0689e6c151d7ee1c470f612e3b2c0b3981ef571e74aabf0a292a65c9d",
          "sha256": "8c765545ebd34ec9e37a02fe85b17c1a54367121e6dca032f3bab4bc6f274327",
          "sha1": "b84afd7d5eacad41ffb80a53e56597f3ef6316f8",
          "md5": "8748b185258fe49b727a3fb31c513624"
        }
      ]
    }
  ]
}
