{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-coroutine-jvm/1.9.0-change-badges-SNAPSHOT/util-coroutine-jvm-1.9.0-change-badges-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-coroutine-jvm",
    "version": "1.9.0-change-badges-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ucz6ymk7arb2deya3srkruk5r4"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-coroutine-metadata-1.9.0-change-badges-SNAPSHOT.jar",
          "url": "util-coroutine-metadata-1.9.0-change-badges-SNAPSHOT.jar",
          "size": 2237,
          "sha512": "bd7fa25d508351f44cc0a81d73d1e6b919eff13f8a337563d3c7eca03e77cc12757ba3829a598d1ebe7908a13e7999ccaaf18fe590abb10955f6a48a49da5163",
          "sha256": "84d586f8999bc9468935331ab98bbb311ac7dbccc45f7a4d22ab7086c0726e86",
          "sha1": "ad6ab64d0906bda2bb5b687385f896e1c897de4d",
          "md5": "533a670ff1741183f560e9d80c3dd4f0"
        }
      ]
    }
  ]
}
