{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-jvm/1.8.0-add-ios-min-version-SNAPSHOT/util-jvm-1.8.0-add-ios-min-version-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-jvm",
    "version": "1.8.0-add-ios-min-version-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "bqecn2liy5fi7bul5bkwignmxq"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-metadata-1.8.0-add-ios-min-version-SNAPSHOT.jar",
          "url": "util-metadata-1.8.0-add-ios-min-version-SNAPSHOT.jar",
          "size": 6309,
          "sha512": "3cc2e83edd3d614a54b5d3e60151a7a850986a82d320ea5562acc21672d825016ae2e3d73aa66abe54623216bed443bda0be04c6503a34f2b58bd99246ef09cb",
          "sha256": "cee578700966cc6a5300e0e728f812015a5bdc55774a837cb3650d8bb6533cbc",
          "sha1": "35ea20f0ec43fcd69fc23376bfd0efaa17efdead",
          "md5": "8145f38b0307a40f84a6c501c5343cf0"
        }
      ]
    }
  ]
}
