{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk",
    "version": "0.2.1-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.2.1-bump-updates-SNAPSHOT.jar",
          "url": "data-donation-sdk-0.2.1-bump-updates-SNAPSHOT.jar",
          "size": 61785,
          "sha512": "24c960d0b35c116c05cf5a8135d77c4524a55ccea6d8ca85546e2f75819e57651883277284cf9bbd959e4f84ea52fea5179870e2fa6f5cc66565c1be0736be13",
          "sha256": "22dfde268a03dea15361611a5742240c17a19ff18f90a5ffed5e1728f41378b6",
          "sha1": "261eafcb082856b1dafae00d80753407168d90bf",
          "md5": "fce48fad1a5ff9c78c1eee61e1a1b866"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android-debug/0.2.1-bump-updates-SNAPSHOT/data-donation-sdk-android-debug-0.2.1-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android-debug",
        "version": "0.2.1-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android-debug/0.2.1-bump-updates-SNAPSHOT/data-donation-sdk-android-debug-0.2.1-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android-debug",
        "version": "0.2.1-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android/0.2.1-bump-updates-SNAPSHOT/data-donation-sdk-android-0.2.1-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android",
        "version": "0.2.1-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android/0.2.1-bump-updates-SNAPSHOT/data-donation-sdk-android-0.2.1-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android",
        "version": "0.2.1-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../data-donation-sdk-iosarm64/0.2.1-bump-updates-SNAPSHOT/data-donation-sdk-iosarm64-0.2.1-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-iosarm64",
        "version": "0.2.1-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../data-donation-sdk-iosx64/0.2.1-bump-updates-SNAPSHOT/data-donation-sdk-iosx64-0.2.1-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-iosx64",
        "version": "0.2.1-bump-updates-SNAPSHOT"
      }
    }
  ]
}
