{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.13.1-bump-jacoco-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "p6unozuvgbfcpiib776eg4bqha"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.13.1-bump-jacoco-SNAPSHOT.jar",
          "url": "securestore-common-1.13.1-bump-jacoco-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "d0563cf4164fbf19cc74e577c9e32e537ac2267f81e198f41d4c15901d67472f5c6d3aef165447b909a6f5e0c5b47aa52a3ba1cc6090cd2135d65030041648b4",
          "sha256": "5b21a64002b20414e34c0ed3a928e49db63f735f6d11df3db07b8c91ade6444e",
          "sha1": "858c27b87186a6210e8931d046bdad14be07e114",
          "md5": "a383b5196512f305c831b07bb34bc548"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.13.1-bump-jacoco-SNAPSHOT.jar",
          "url": "securestore-common-1.13.1-bump-jacoco-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "d0563cf4164fbf19cc74e577c9e32e537ac2267f81e198f41d4c15901d67472f5c6d3aef165447b909a6f5e0c5b47aa52a3ba1cc6090cd2135d65030041648b4",
          "sha256": "5b21a64002b20414e34c0ed3a928e49db63f735f6d11df3db07b8c91ade6444e",
          "sha1": "858c27b87186a6210e8931d046bdad14be07e114",
          "md5": "a383b5196512f305c831b07bb34bc548"
        }
      ]
    }
  ]
}
