{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.13.1-bump-jacoco-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "7kpxdly4qjfqtmmfl4pjoatamm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.13.1-bump-jacoco-SNAPSHOT.jar",
          "url": "securestore-common-1.13.1-bump-jacoco-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "eb5faf46bdba9e511e56b7a39af5f8cd8fa22739560417e718b7637cb15a1184e93ac30740d5efbf4057b7efaa5f785f7766992750f90e0b8b818c4471029130",
          "sha256": "55020a2200565065a489c739e14eb6ee462e383a44abe19d6b76d8aa4ea181d7",
          "sha1": "ac823b4f6699ecca00f89252b8a4fb530ed38d1f",
          "md5": "7a29174adf51f24da8ea5809efb6adf8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.13.1-bump-jacoco-SNAPSHOT.jar",
          "url": "securestore-common-1.13.1-bump-jacoco-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "eb5faf46bdba9e511e56b7a39af5f8cd8fa22739560417e718b7637cb15a1184e93ac30740d5efbf4057b7efaa5f785f7766992750f90e0b8b818c4471029130",
          "sha256": "55020a2200565065a489c739e14eb6ee462e383a44abe19d6b76d8aa4ea181d7",
          "sha1": "ac823b4f6699ecca00f89252b8a4fb530ed38d1f",
          "md5": "7a29174adf51f24da8ea5809efb6adf8"
        }
      ]
    }
  ]
}
