{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.0.3-change-koin-SNAPSHOT/data-donation-sdk-iosx64-0.0.3-change-koin-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.0.3-change-koin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "dz7ctdxnqbhwfgwnehumw5amay"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.3-change-koin-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.0.3-change-koin-SNAPSHOT.jar",
          "size": 68446,
          "sha512": "2f505a2ee1fa0d319d696b903c981cb5b14420d586b68e336d227fe925765a473ba0a199689535910657e039e2eef786f6a18d5263835b37e3a03b827d6de056",
          "sha256": "342e2d48f3cb756258c1245f866c8c1a3801ae2078240c30fa5f4ffdcd4b645b",
          "sha1": "73ef71458abfc133ee19dd197163b8d5c6f0e7b7",
          "md5": "693a017d775d6281da9be2289a607fb2"
        }
      ]
    }
  ]
}
