{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.12.0-change-resource-crypto-service-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "mgpqk7z7tfagfajl6gojuhg4oa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.12.0-change-resource-crypto-service-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.12.0-change-resource-crypto-service-SNAPSHOT.jar",
          "url": "auth-jvm-1.12.0-change-resource-crypto-service-SNAPSHOT.jar",
          "size": 34318,
          "sha512": "1c4b41dd3755dc5a5f2d27098b5ac18035e2d0ecc28ff2969a08e2e10777e61fe64f16f474168c974c91854cce177b34eb40dcc250dda3b3021b0bfa09eb174b",
          "sha256": "61fd00a85d585268c3df7c355aa5c24d90788fb3c52cec36cc1e1b76074ae73a",
          "sha1": "d9dfc69b2cc6ed387344cf13a52fda09a57cd905",
          "md5": "9ea8478830360c8c7503633a6b471db6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.12.0-change-resource-crypto-service-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.12.0-change-resource-crypto-service-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.12.0-change-resource-crypto-service-SNAPSHOT.jar",
          "url": "auth-jvm-1.12.0-change-resource-crypto-service-SNAPSHOT.jar",
          "size": 34318,
          "sha512": "1c4b41dd3755dc5a5f2d27098b5ac18035e2d0ecc28ff2969a08e2e10777e61fe64f16f474168c974c91854cce177b34eb40dcc250dda3b3021b0bfa09eb174b",
          "sha256": "61fd00a85d585268c3df7c355aa5c24d90788fb3c52cec36cc1e1b76074ae73a",
          "sha1": "d9dfc69b2cc6ed387344cf13a52fda09a57cd905",
          "md5": "9ea8478830360c8c7503633a6b471db6"
        }
      ]
    }
  ]
}
