{
  "formatVersion": "1.1",
  "component": {
    "url": "../../securestore/1.13.2-SNAPSHOT/securestore-1.13.2-SNAPSHOT.module",
    "group": "care.data4life.hc-securestore-sdk-kmp",
    "module": "securestore",
    "version": "1.13.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "securestore-jvm-1.13.2-SNAPSHOT.jar",
          "url": "securestore-jvm-1.13.2-SNAPSHOT.jar",
          "size": 16659,
          "sha512": "9af49e42b2132609034db3ef3732526781cd4a50c00c911239cdc037b00bbbaec7b8c91e8488684d15fbfacd6ddfc4e33e7b7d1696c9d76436f27514ef8b62d3",
          "sha256": "c8d8c7111341972ced3a5dae6ccd0eca8e23f694911db322cb4b01fb91c62f56",
          "sha1": "929661d893f8c19e4829ee8c360837f29e18d89e",
          "md5": "c240a87848af93ecedd2434c3fb2227e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.13.2-SNAPSHOT.jar",
          "url": "securestore-jvm-1.13.2-SNAPSHOT.jar",
          "size": 16659,
          "sha512": "9af49e42b2132609034db3ef3732526781cd4a50c00c911239cdc037b00bbbaec7b8c91e8488684d15fbfacd6ddfc4e33e7b7d1696c9d76436f27514ef8b62d3",
          "sha256": "c8d8c7111341972ced3a5dae6ccd0eca8e23f694911db322cb4b01fb91c62f56",
          "sha1": "929661d893f8c19e4829ee8c360837f29e18d89e",
          "md5": "c240a87848af93ecedd2434c3fb2227e"
        }
      ]
    }
  ]
}
