{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.14.0-add-new-search-parameter-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "32tx7contzckhowvew3ufdutae"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.14.0-add-new-search-parameter-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.14.0-add-new-search-parameter-SNAPSHOT.jar",
          "url": "securestore-jvm-1.14.0-add-new-search-parameter-SNAPSHOT.jar",
          "size": 16455,
          "sha512": "23d9c6387bdc62c0feda22dfb0557d20bb90a78a28832a4462878eaeb98e83bf23c9969dbde53d559364d6d9197afbe2464f3cf775237c2775491cc65403c474",
          "sha256": "ff4554b9031cb0efba2b8e4badb23982d97278451859e3d328d8c885f0170c90",
          "sha1": "14bbc99d68f755f87c05b22011f581ec86247fe9",
          "md5": "55b381b3f9db1b428cd9dba1d9ee9a70"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.14.0-add-new-search-parameter-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.14.0-add-new-search-parameter-SNAPSHOT.jar",
          "url": "securestore-jvm-1.14.0-add-new-search-parameter-SNAPSHOT.jar",
          "size": 16455,
          "sha512": "23d9c6387bdc62c0feda22dfb0557d20bb90a78a28832a4462878eaeb98e83bf23c9969dbde53d559364d6d9197afbe2464f3cf775237c2775491cc65403c474",
          "sha256": "ff4554b9031cb0efba2b8e4badb23982d97278451859e3d328d8c885f0170c90",
          "sha1": "14bbc99d68f755f87c05b22011f581ec86247fe9",
          "md5": "55b381b3f9db1b428cd9dba1d9ee9a70"
        }
      ]
    }
  ]
}
