{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.11.0-add-envrioment-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "hojyvrcyxjexpegvtztn72b6fa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.11.0-add-envrioment-tests-SNAPSHOT.jar",
          "url": "securestore-common-1.11.0-add-envrioment-tests-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "bd0378806b28514dcd7c4385ebdbb21f741896ab94f5001e0065687365e799b426a7ddb8415b3c4ce3b91e0ef0247f49f6140e5025ca745491af03129058d84c",
          "sha256": "a21f9fce8335a014b15e90d8cf7ba81b2130356dd7698d62edfa4b1b56d993e3",
          "sha1": "f2f1c9379ac48be3f60125f3c6ca11e4aa25baca",
          "md5": "e7f9ba8f5a636888eeff194b21a67f8f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.11.0-add-envrioment-tests-SNAPSHOT.jar",
          "url": "securestore-common-1.11.0-add-envrioment-tests-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "bd0378806b28514dcd7c4385ebdbb21f741896ab94f5001e0065687365e799b426a7ddb8415b3c4ce3b91e0ef0247f49f6140e5025ca745491af03129058d84c",
          "sha256": "a21f9fce8335a014b15e90d8cf7ba81b2130356dd7698d62edfa4b1b56d993e3",
          "sha1": "f2f1c9379ac48be3f60125f3c6ca11e4aa25baca",
          "md5": "e7f9ba8f5a636888eeff194b21a67f8f"
        }
      ]
    }
  ]
}
