{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.0.3-change-dependencies-SNAPSHOT/data-donation-sdk-iosx64-0.0.3-change-dependencies-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.0.3-change-dependencies-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "3owwmr4cvraslcn5augubhtk3m"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.3-change-dependencies-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.0.3-change-dependencies-SNAPSHOT.jar",
          "size": 64163,
          "sha512": "5a373abacede38b67a57ce9ff77e0dcf0082ab53e66a30366ddbf95a4d7dd00d49bbe5a8b18762fa20c34a0fd5d6e57085d15d1a59043daaf2869616d7734881",
          "sha256": "23a4c7cddfcba39f68171f8a08328ceca290efc7a919dc09f5e198672f2d2bff",
          "sha1": "389b68bdb512bd3a5659169a97171e6828cc5a51",
          "md5": "ddc84991ca95658fefc0fcd35002e285"
        }
      ]
    }
  ]
}
