{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.0.3-change-dependencies-SNAPSHOT/data-donation-sdk-iosx64-0.0.3-change-dependencies-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.0.3-change-dependencies-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "2hp6v7nqmbbj5pwufeay6b7xrq"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.3-change-dependencies-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.0.3-change-dependencies-SNAPSHOT.jar",
          "size": 64163,
          "sha512": "c3f0089886dba5f2635e24e0fac12375324fb90d82877f81cd44539e1188dc71e7d65429e556077b89da91100dd3edb41d2814ce40d54e1e5bdad12a9420eca9",
          "sha256": "64f5681d394b7165ef214be7f9365985744a2b89fc8d8996047144a4c5f3c7c8",
          "sha1": "962d4aeae242a7418f10c32884d3fddd72c3aafc",
          "md5": "c11d32d40ca02ab62b18899aa561f593"
        }
      ]
    }
  ]
}
