{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk",
    "version": "0.0.4-add-consent-serive-error-propagation-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "tucwqzuxbrevrn2nnw2cunyvz4"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.4-add-consent-serive-error-propagation-SNAPSHOT.jar",
          "url": "data-donation-sdk-0.0.4-add-consent-serive-error-propagation-SNAPSHOT.jar",
          "size": 79917,
          "sha512": "2e174f14b23485f61265b530241e49c5b7be5a6f05fdd26b045572e1e0c8dd93272f49a29db37ede0c644632dfe32c73d4b35e85f1f738c13f11cb27891adc43",
          "sha256": "adadee4f93f4879574c9391bdb6d30c197d8807f72344a68a4301c091b55306b",
          "sha1": "940711f4a017e175748a7b615f76542e5a3ca828",
          "md5": "b43d2c4f372557cdb46c9418118ca3f8"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android-debug/0.0.4-add-consent-serive-error-propagation-SNAPSHOT/data-donation-sdk-android-debug-0.0.4-add-consent-serive-error-propagation-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android-debug",
        "version": "0.0.4-add-consent-serive-error-propagation-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android-debug/0.0.4-add-consent-serive-error-propagation-SNAPSHOT/data-donation-sdk-android-debug-0.0.4-add-consent-serive-error-propagation-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android-debug",
        "version": "0.0.4-add-consent-serive-error-propagation-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android/0.0.4-add-consent-serive-error-propagation-SNAPSHOT/data-donation-sdk-android-0.0.4-add-consent-serive-error-propagation-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android",
        "version": "0.0.4-add-consent-serive-error-propagation-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android/0.0.4-add-consent-serive-error-propagation-SNAPSHOT/data-donation-sdk-android-0.0.4-add-consent-serive-error-propagation-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android",
        "version": "0.0.4-add-consent-serive-error-propagation-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../data-donation-sdk-iosarm64/0.0.4-add-consent-serive-error-propagation-SNAPSHOT/data-donation-sdk-iosarm64-0.0.4-add-consent-serive-error-propagation-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-iosarm64",
        "version": "0.0.4-add-consent-serive-error-propagation-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../data-donation-sdk-iosx64/0.0.4-add-consent-serive-error-propagation-SNAPSHOT/data-donation-sdk-iosx64-0.0.4-add-consent-serive-error-propagation-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-iosx64",
        "version": "0.0.4-add-consent-serive-error-propagation-SNAPSHOT"
      }
    }
  ]
}
