{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.11.0-change-client-version-header-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "b3of7x3omfahdjdivrfbz4hek4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-change-client-version-header-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-change-client-version-header-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "50070f7509b557b700108b9b6a598aaec2de7bcff9ca263872d81a25482cdf79ed34a241ad1c41caebd74293ad1bcbfce842ed61d47326ee80f91f944d87979a",
          "sha256": "6ece3364cf7209743e52753c32c2b6930db41a54040a0da14448927629504d46",
          "sha1": "66c46aa3591da15eee4b58d1353631cbfd36ee9a",
          "md5": "5fce31801ad93deda40e1126952361df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-change-client-version-header-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-change-client-version-header-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-change-client-version-header-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "50070f7509b557b700108b9b6a598aaec2de7bcff9ca263872d81a25482cdf79ed34a241ad1c41caebd74293ad1bcbfce842ed61d47326ee80f91f944d87979a",
          "sha256": "6ece3364cf7209743e52753c32c2b6930db41a54040a0da14448927629504d46",
          "sha1": "66c46aa3591da15eee4b58d1353631cbfd36ee9a",
          "md5": "5fce31801ad93deda40e1126952361df"
        }
      ]
    }
  ]
}
