{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.11.0-bump-android-gradle-plugin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "qyna35etyjfxzck5l2ppswauw4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-bump-android-gradle-plugin-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.11.0-bump-android-gradle-plugin-SNAPSHOT.jar",
          "url": "crypto-jvm-1.11.0-bump-android-gradle-plugin-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "8e6ea7fa3d4ba707edade485557e1809b71d80d03915ac9d1b196686e628d2a808261054b6e19bf567b8e1ef02fd0fb9e993996d61e28b875144e44d4193bfba",
          "sha256": "63ed8f86fca2736c2c72e1ed58519571e941b4140317834157b6f7575919c1fa",
          "sha1": "150631795c67948cf7d8d78bbbf9e9d6787c26e0",
          "md5": "123f94eeca2f006b4a818a1b91b69189"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-bump-android-gradle-plugin-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.11.0-bump-android-gradle-plugin-SNAPSHOT.jar",
          "url": "crypto-jvm-1.11.0-bump-android-gradle-plugin-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "8e6ea7fa3d4ba707edade485557e1809b71d80d03915ac9d1b196686e628d2a808261054b6e19bf567b8e1ef02fd0fb9e993996d61e28b875144e44d4193bfba",
          "sha256": "63ed8f86fca2736c2c72e1ed58519571e941b4140317834157b6f7575919c1fa",
          "sha1": "150631795c67948cf7d8d78bbbf9e9d6787c26e0",
          "md5": "123f94eeca2f006b4a818a1b91b69189"
        }
      ]
    }
  ]
}
