{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.11.0-change-api-service-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "of7vey2p2nh4xherzhghmjsrey"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-change-api-service-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.11.0-change-api-service-SNAPSHOT.jar",
          "url": "crypto-jvm-1.11.0-change-api-service-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "eae4c8638a37d7dbef0555a7e68107ec072060b966a3a44f546803955ce09517a2d1c79d91bd21a9e49f0e3b6afa67f3c415b505b973d72915e247978cd88ceb",
          "sha256": "ac8685f21d04e1837e1e82ce64ac44f297095e01fc499fff6c09e21b89d79b88",
          "sha1": "11c064fbb1287df402c44bee7a3cfbf073c4f1e1",
          "md5": "ffade43831719a5f344f24a25cdd4801"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-change-api-service-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.11.0-change-api-service-SNAPSHOT.jar",
          "url": "crypto-jvm-1.11.0-change-api-service-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "eae4c8638a37d7dbef0555a7e68107ec072060b966a3a44f546803955ce09517a2d1c79d91bd21a9e49f0e3b6afa67f3c415b505b973d72915e247978cd88ceb",
          "sha256": "ac8685f21d04e1837e1e82ce64ac44f297095e01fc499fff6c09e21b89d79b88",
          "sha1": "11c064fbb1287df402c44bee7a3cfbf073c4f1e1",
          "md5": "ffade43831719a5f344f24a25cdd4801"
        }
      ]
    }
  ]
}
