{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-gradle-scripts",
    "module": "example-kmp-library",
    "version": "0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "xrqgx4ezjfhgpl3ygw5tinwg6e"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "example-kmp-library-metadata-0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT.jar",
          "url": "example-kmp-library-0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT.jar",
          "size": 6554,
          "sha512": "65be84887b936d3fc010eba31b582480e777691344c7eefca55bc9e854f289bdd0e37d9b8cc9374ba6767e17888fc19fe8492b6d33a25f44f987cec82b64b59d",
          "sha256": "05da1cdde52b71ba53beac588f007c23c49c96064b757676ece6abc1e69b7ca6",
          "sha1": "da1d6d2f3c9a392db23c228894a6dcab889cbbe7",
          "md5": "cd74beadf37f8dcd93ccabc26075afea"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../example-kmp-library-android-debug/0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT/example-kmp-library-android-debug-0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT.module",
        "group": "care.data4life.hc-gradle-scripts",
        "module": "example-kmp-library-android-debug",
        "version": "0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../example-kmp-library-android-debug/0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT/example-kmp-library-android-debug-0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT.module",
        "group": "care.data4life.hc-gradle-scripts",
        "module": "example-kmp-library-android-debug",
        "version": "0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../example-kmp-library-android/0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT/example-kmp-library-android-0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT.module",
        "group": "care.data4life.hc-gradle-scripts",
        "module": "example-kmp-library-android",
        "version": "0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../example-kmp-library-android/0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT/example-kmp-library-android-0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT.module",
        "group": "care.data4life.hc-gradle-scripts",
        "module": "example-kmp-library-android",
        "version": "0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../example-kmp-library-iosarm64/0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT/example-kmp-library-iosarm64-0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT.module",
        "group": "care.data4life.sdk.script",
        "module": "example-kmp-library-iosarm64",
        "version": "0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../example-kmp-library-iosx64/0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT/example-kmp-library-iosx64-0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT.module",
        "group": "care.data4life.sdk.script",
        "module": "example-kmp-library-iosx64",
        "version": "0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../example-kmp-library-jvm/0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT/example-kmp-library-jvm-0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT.module",
        "group": "care.data4life.hc-gradle-scripts",
        "module": "example-kmp-library-jvm",
        "version": "0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../example-kmp-library-jvm/0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT/example-kmp-library-jvm-0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT.module",
        "group": "care.data4life.hc-gradle-scripts",
        "module": "example-kmp-library-jvm",
        "version": "0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT"
      }
    }
  ]
}
