{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.2-change-kotlin-duration-usage-SNAPSHOT/data-donation-sdk-iosx64-0.1.2-change-kotlin-duration-usage-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.2-change-kotlin-duration-usage-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "5g32qonlpbab5hbejebpuiisxq"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.2-change-kotlin-duration-usage-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.2-change-kotlin-duration-usage-SNAPSHOT.jar",
          "size": 39153,
          "sha512": "14095311748c37cc8ae833df36d405f07e0cfb2aed162f26713207de4e737cce27ba5018336a5036b2dd988113ecf5935a518630f6312afaab50046a90545383",
          "sha256": "4fda0d40856c7600fa89683fe067df8371b4a75fd6476a7dfdc784053ba6ece8",
          "sha1": "12e1c22350a3f44947ead81a110ec88baff2f74c",
          "md5": "191d327e7284d6996aa40f0b08cdf979"
        }
      ]
    }
  ]
}
