{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-coroutine-jvm/1.8.1-add-coroutine-util-SNAPSHOT/util-coroutine-jvm-1.8.1-add-coroutine-util-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-coroutine-jvm",
    "version": "1.8.1-add-coroutine-util-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "3byk2twyijgtrh4bkxch45v7t4"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-coroutine-metadata-1.8.1-add-coroutine-util-SNAPSHOT.jar",
          "url": "util-coroutine-metadata-1.8.1-add-coroutine-util-SNAPSHOT.jar",
          "size": 2232,
          "sha512": "f68b47cdf016ed0760a103a0e97ee9cda7a366bd6ad197d2067f206946fb0d4c8fa44f4bc72989926462161cfff159dc9af3186c2f93c3bcb36763a901f1c896",
          "sha256": "bca74cfe968f3cd1c32e6f1a090f6256d3cc71632fcad196535227897ead9ef3",
          "sha1": "14e257d3c2c7908f407984b27349eeacc5fa7df6",
          "md5": "a7ad75e7012783cc05764727e079bd61"
        }
      ]
    }
  ]
}
