{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.13.2-bump-util-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "kbgwt4dr5jdnhcwmzjujd26kqa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.13.2-bump-util-SNAPSHOT.jar",
          "url": "crypto-common-1.13.2-bump-util-SNAPSHOT.jar",
          "size": 11957,
          "sha512": "5fef99e388a580ba3863e87be462051ee74a7d53246185502b417f9f668c67c30f878a243d2df52288a5abecf8d71f8613ac2da94056141c4a49418787e71331",
          "sha256": "7049fd94c6ccce55adae09a52c1718f9d7ac5bca66991aa57872376ae234c336",
          "sha1": "abdbd6b5b00c8c09b0b3f255dedbc4f0e46ef049",
          "md5": "e353073a31b0fc2226fa047de2fcf591"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.13.2-bump-util-SNAPSHOT.jar",
          "url": "crypto-common-1.13.2-bump-util-SNAPSHOT.jar",
          "size": 11957,
          "sha512": "5fef99e388a580ba3863e87be462051ee74a7d53246185502b417f9f668c67c30f878a243d2df52288a5abecf8d71f8613ac2da94056141c4a49418787e71331",
          "sha256": "7049fd94c6ccce55adae09a52c1718f9d7ac5bca66991aa57872376ae234c336",
          "sha1": "abdbd6b5b00c8c09b0b3f255dedbc4f0e46ef049",
          "md5": "e353073a31b0fc2226fa047de2fcf591"
        }
      ]
    }
  ]
}
