{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.0.3-missing-native-resources-SNAPSHOT/data-donation-sdk-iosx64-0.0.3-missing-native-resources-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.0.3-missing-native-resources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "2ekzr26wg5hcnbwq6wonjowrpq"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.3-missing-native-resources-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.0.3-missing-native-resources-SNAPSHOT.jar",
          "size": 63040,
          "sha512": "76789306e2a2cbe612235e42118b0f5d2673c432226321da637eb3df40b462f105e6af77e89d88387cdff47038eacf2023ccd96f0bc969cf896d9899dbb89650",
          "sha256": "461c0b42d16230167de5eba2a627ba42c20986ada25ef4596df41f0f7c618336",
          "sha1": "4939254c104497df65973dd44196ffe5400085b8",
          "md5": "196b34306be89e472927f31485e1de75"
        }
      ]
    }
  ]
}
