{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.11.0-change-client-version-header-dynamic-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "w2hj47yhy5gx7j4va6jgjjgnp4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-change-client-version-header-dynamic-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.11.0-change-client-version-header-dynamic-SNAPSHOT.jar",
          "url": "securestore-jvm-1.11.0-change-client-version-header-dynamic-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "fb23befc9de2f71ceee8e745f388ab484cb7068d4ab23c57e43dad263b97e44f34e46d11de56ed1871c1fa23bd1d204212caac4e4fac392b65a18af4f62576e4",
          "sha256": "eaf346f60dd5a30450f9fe728401ea344be2beedddc5beec790f9c0e8ff73c4c",
          "sha1": "9072eee8558d5682c79722db52205391dc41ae17",
          "md5": "7cbbe34f2990a56f332072ca34801ffb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-change-client-version-header-dynamic-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.11.0-change-client-version-header-dynamic-SNAPSHOT.jar",
          "url": "securestore-jvm-1.11.0-change-client-version-header-dynamic-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "fb23befc9de2f71ceee8e745f388ab484cb7068d4ab23c57e43dad263b97e44f34e46d11de56ed1871c1fa23bd1d204212caac4e4fac392b65a18af4f62576e4",
          "sha256": "eaf346f60dd5a30450f9fe728401ea344be2beedddc5beec790f9c0e8ff73c4c",
          "sha1": "9072eee8558d5682c79722db52205391dc41ae17",
          "md5": "7cbbe34f2990a56f332072ca34801ffb"
        }
      ]
    }
  ]
}
