{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.11.0-change-client-version-header-dynamic-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "isg4zn65ajd7fkgemsvvfsxqim"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-change-client-version-header-dynamic-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.11.0-change-client-version-header-dynamic-SNAPSHOT.jar",
          "url": "securestore-jvm-1.11.0-change-client-version-header-dynamic-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "9336da1cfe230ceea6197e4ece9b9d9409fecfd3fe071715e7348674cea9c5e5ea3e171f64cbccf6d08125620dc674f658f648321bc2dfa39fe666d53d3ef3a1",
          "sha256": "31f0a943983373e583918460c64d4d02278115dee006f1b219cceaa0ed389198",
          "sha1": "d086532028a0130703ba694016bbe39e08b7ce0c",
          "md5": "eea72851a5022baa63301225e5a8718a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-change-client-version-header-dynamic-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.11.0-change-client-version-header-dynamic-SNAPSHOT.jar",
          "url": "securestore-jvm-1.11.0-change-client-version-header-dynamic-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "9336da1cfe230ceea6197e4ece9b9d9409fecfd3fe071715e7348674cea9c5e5ea3e171f64cbccf6d08125620dc674f658f648321bc2dfa39fe666d53d3ef3a1",
          "sha256": "31f0a943983373e583918460c64d4d02278115dee006f1b219cceaa0ed389198",
          "sha1": "d086532028a0130703ba694016bbe39e08b7ce0c",
          "md5": "eea72851a5022baa63301225e5a8718a"
        }
      ]
    }
  ]
}
