{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-android",
    "version": "1.11.0-fix-update-record-data-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "b3ys5acjije5xazx2c6hgv6uyi"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-fix-update-record-data-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-android-1.11.0-fix-update-record-data-SNAPSHOT.aar",
          "url": "securestore-android-1.11.0-fix-update-record-data-SNAPSHOT.aar",
          "size": 41956,
          "sha512": "5b1964a48d90aa502142522ee0fdabeef5e673964103e46417e0706a46aa3a5238ad4f0344680764d92cb669a9cc8a7e06d80c1abaad4783b11329dbd80e54ea",
          "sha256": "3ba82ffae02f218b3f38c928759968c99a015a7d2111a2f33b40b3816ce74023",
          "sha1": "9ae0f1527332398f3457aa6b5b81b8436feecda6",
          "md5": "6b198afbcacd85d5b3373057643ec776"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-fix-update-record-data-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-android-1.11.0-fix-update-record-data-SNAPSHOT.aar",
          "url": "securestore-android-1.11.0-fix-update-record-data-SNAPSHOT.aar",
          "size": 41956,
          "sha512": "5b1964a48d90aa502142522ee0fdabeef5e673964103e46417e0706a46aa3a5238ad4f0344680764d92cb669a9cc8a7e06d80c1abaad4783b11329dbd80e54ea",
          "sha256": "3ba82ffae02f218b3f38c928759968c99a015a7d2111a2f33b40b3816ce74023",
          "sha1": "9ae0f1527332398f3457aa6b5b81b8436feecda6",
          "md5": "6b198afbcacd85d5b3373057643ec776"
        }
      ]
    }
  ]
}
