{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.12.0-change-fileservice-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "va4mzevd7zggnhjb73nob3zgnu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.12.0-change-fileservice-tests-SNAPSHOT.jar",
          "url": "auth-common-1.12.0-change-fileservice-tests-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "c7dd850fd74a2536aee191d18b9d4891da706c59f1dee87c782b87892bf2effacd1838c929fb4f7f0b1fa691bdd5c24f4e35b5a906b36dc1d012298f2c397989",
          "sha256": "d2280c0c3e244e8dfd37adc930ba808bc60179be6be5d3dfaf7df78b326898b8",
          "sha1": "ee756d18b6cc45113e9c5360f4e6d639d50e4be9",
          "md5": "6164290f383186630a37d672880b8118"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.12.0-change-fileservice-tests-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.12.0-change-fileservice-tests-SNAPSHOT.jar",
          "url": "auth-common-1.12.0-change-fileservice-tests-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "c7dd850fd74a2536aee191d18b9d4891da706c59f1dee87c782b87892bf2effacd1838c929fb4f7f0b1fa691bdd5c24f4e35b5a906b36dc1d012298f2c397989",
          "sha256": "d2280c0c3e244e8dfd37adc930ba808bc60179be6be5d3dfaf7df78b326898b8",
          "sha1": "ee756d18b6cc45113e9c5360f4e6d639d50e4be9",
          "md5": "6164290f383186630a37d672880b8118"
        }
      ]
    }
  ]
}
