{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.11.0-change-publishing-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "3q6sqwkuqzgqbjbhcpm4pqmfca"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-change-publishing-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-change-publishing-SNAPSHOT.jar",
          "size": 3404,
          "sha512": "66d354010cec4b382ab12e2b759012d3826b50cd05d3c64b472320f9e9a5007eb783e781dc0bda743f679244cb4b09dfa0d958ab99ccab03d3d1f79b24306722",
          "sha256": "2d2016a5b54ab7fa2b69a0e2453da8ae1d67efbf38962bfc9580552abbce5df8",
          "sha1": "dd83a5ba57f4604198e629a1022e6be3e3c6bec2",
          "md5": "a0fba0f27af9c8931042ab906e1b0118"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-change-publishing-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-change-publishing-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-change-publishing-SNAPSHOT.jar",
          "size": 3404,
          "sha512": "66d354010cec4b382ab12e2b759012d3826b50cd05d3c64b472320f9e9a5007eb783e781dc0bda743f679244cb4b09dfa0d958ab99ccab03d3d1f79b24306722",
          "sha256": "2d2016a5b54ab7fa2b69a0e2453da8ae1d67efbf38962bfc9580552abbce5df8",
          "sha1": "dd83a5ba57f4604198e629a1022e6be3e3c6bec2",
          "md5": "a0fba0f27af9c8931042ab906e1b0118"
        }
      ]
    }
  ]
}
