{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.12.0-change-contracts-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ch5zwb54g5h4ljpp3ca3dqjxqi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.12.0-change-contracts-SNAPSHOT.jar",
          "url": "auth-common-1.12.0-change-contracts-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "af7f84ccd3d3493da8dcac01809757f865a5180e77d3480aed280b11304f1bd9ee051bff99a23574fc207e9b51f37d5ebf4dc5c9a229b4b7c634c86efd19c7a4",
          "sha256": "0d626955ad4834cec4507e64c6cbb7a8eddc5fef5a06a15bbc6b20ce53c2270c",
          "sha1": "f03ced72eb449eb78acfc0bc8b51b888b13c6186",
          "md5": "392227a740f18cf437797cff2713a70b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.12.0-change-contracts-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.12.0-change-contracts-SNAPSHOT.jar",
          "url": "auth-common-1.12.0-change-contracts-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "af7f84ccd3d3493da8dcac01809757f865a5180e77d3480aed280b11304f1bd9ee051bff99a23574fc207e9b51f37d5ebf4dc5c9a229b4b7c634c86efd19c7a4",
          "sha256": "0d626955ad4834cec4507e64c6cbb7a8eddc5fef5a06a15bbc6b20ce53c2270c",
          "sha1": "f03ced72eb449eb78acfc0bc8b51b888b13c6186",
          "md5": "392227a740f18cf437797cff2713a70b"
        }
      ]
    }
  ]
}
