{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.3-add-time-bluring-questionaireresponse-valuedatetime-SNAPSHOT/data-donation-sdk-iosx64-0.1.3-add-time-bluring-questionaireresponse-valuedatetime-SNAPSHOT.module",
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.3-add-time-bluring-questionaireresponse-valuedatetime-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "xkjghoz5gvft7pztysa7kk3zii"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.3-add-time-bluring-questionaireresponse-valuedatetime-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.3-add-time-bluring-questionaireresponse-valuedatetime-SNAPSHOT.jar",
          "size": 66733,
          "sha512": "17e0cf12c7e4871611333fde2b59a9297396d635248b7740be1213c735f0666e7427b5cb29b4ecae2a97c122808b3748a2aae1a2cb0f3bf169eabfa6479bb7f5",
          "sha256": "85cf292f26c073c841354fbb26f8020a5fd98e8f17af89d4a12b5d161fb5773e",
          "sha1": "4098bdc78e5cdceee33124e001cea65eb265c015",
          "md5": "d42586eec626232693742a6882ca22d8"
        }
      ]
    }
  ]
}
