{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.12.0-change-merge-fhir-and-data-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "3nw3hslqt5b5hfszqqqikkelpy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.12.0-change-merge-fhir-and-data-SNAPSHOT.jar",
          "url": "crypto-common-1.12.0-change-merge-fhir-and-data-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "442d735352e817038845ccf85b03620ffa43c324f506a9a74672fa497edc4882091d381e8d914ffdd0d44ae5d89a3d1efbc9c8e1f75c3b607cf0dffb7cfc3623",
          "sha256": "e7fa22a36e508f00d6e251058a59e3bbbdc6d1f3b91ee16896ea58a1bc9927cf",
          "sha1": "d9e2e1d61d2c225c4f7bbd2b59ebdb9c1b05ad43",
          "md5": "0f39f83e844c035b556fa024ebd1e44d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.12.0-change-merge-fhir-and-data-SNAPSHOT.jar",
          "url": "crypto-common-1.12.0-change-merge-fhir-and-data-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "442d735352e817038845ccf85b03620ffa43c324f506a9a74672fa497edc4882091d381e8d914ffdd0d44ae5d89a3d1efbc9c8e1f75c3b607cf0dffb7cfc3623",
          "sha256": "e7fa22a36e508f00d6e251058a59e3bbbdc6d1f3b91ee16896ea58a1bc9927cf",
          "sha1": "d9e2e1d61d2c225c4f7bbd2b59ebdb9c1b05ad43",
          "md5": "0f39f83e844c035b556fa024ebd1e44d"
        }
      ]
    }
  ]
}
