{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-test/1.7.0-add-coroutine-test-util-SNAPSHOT/util-test-1.7.0-add-coroutine-test-util-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-test",
    "version": "1.7.0-add-coroutine-test-util-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "fv3vkdxxtvbetpqomoykzcol6u"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-test-jvm-1.7.0-add-coroutine-test-util-SNAPSHOT.jar",
          "url": "util-test-jvm-1.7.0-add-coroutine-test-util-SNAPSHOT.jar",
          "size": 5724,
          "sha512": "ffcda5b8233d0e42831a541ece686f0d12432bb64645d1084308b4c6f857097a56aee0d7e0e4c3731acc94109c750a3856fc046b7cc6d4b10aa43472ea33aeac",
          "sha256": "f1f4dadce3547d6d19ed2d9fb40c4e73a8ece922b1bfa7a65db3764e9d1ef35c",
          "sha1": "12255ce465a297114a7e7d58a3881ccd9ead1253",
          "md5": "85c6afc6bd15185fb22bda65b8822d1f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "util-test-jvm-1.7.0-add-coroutine-test-util-SNAPSHOT.jar",
          "url": "util-test-jvm-1.7.0-add-coroutine-test-util-SNAPSHOT.jar",
          "size": 5724,
          "sha512": "ffcda5b8233d0e42831a541ece686f0d12432bb64645d1084308b4c6f857097a56aee0d7e0e4c3731acc94109c750a3856fc046b7cc6d4b10aa43472ea33aeac",
          "sha256": "f1f4dadce3547d6d19ed2d9fb40c4e73a8ece922b1bfa7a65db3764e9d1ef35c",
          "sha1": "12255ce465a297114a7e7d58a3881ccd9ead1253",
          "md5": "85c6afc6bd15185fb22bda65b8822d1f"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-test-metadata/1.7.0-add-coroutine-test-util-SNAPSHOT/util-test-metadata-1.7.0-add-coroutine-test-util-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-test-metadata",
        "version": "1.7.0-add-coroutine-test-util-SNAPSHOT"
      }
    }
  ]
}
