{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-coroutine/1.9.0-add-default-scope-SNAPSHOT/util-coroutine-1.9.0-add-default-scope-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-coroutine",
    "version": "1.9.0-add-default-scope-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ub7iyfeu25gibj6q2xbe5zn4x4"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-coroutine-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "url": "util-coroutine-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "size": 12758,
          "sha512": "ad50adf16c8ad3a08af6b9d4b9b87b2a18d8d561b1f99ba148bbd1585d59f886e65c36bbec30992c03103bef8561d5e393395122ff3686e2caee3f5230063636",
          "sha256": "a92698541ff2bbcab35f971a65ba3a1f7d46c29cd0c26fb08525c1c50101664f",
          "sha1": "761f847c14d1e4ded39f307efeabb2da7d8abdbf",
          "md5": "d7203cedacaa39279aad785ea802e027"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "util-coroutine-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "url": "util-coroutine-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "size": 12758,
          "sha512": "ad50adf16c8ad3a08af6b9d4b9b87b2a18d8d561b1f99ba148bbd1585d59f886e65c36bbec30992c03103bef8561d5e393395122ff3686e2caee3f5230063636",
          "sha256": "a92698541ff2bbcab35f971a65ba3a1f7d46c29cd0c26fb08525c1c50101664f",
          "sha1": "761f847c14d1e4ded39f307efeabb2da7d8abdbf",
          "md5": "d7203cedacaa39279aad785ea802e027"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-coroutine-metadata/1.9.0-add-default-scope-SNAPSHOT/util-coroutine-metadata-1.9.0-add-default-scope-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-coroutine-metadata",
        "version": "1.9.0-add-default-scope-SNAPSHOT"
      }
    }
  ]
}
