{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-coroutine/1.9.0-add-default-scope-SNAPSHOT/util-coroutine-1.9.0-add-default-scope-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-coroutine",
    "version": "1.9.0-add-default-scope-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "3slklvdlmjbxpbmnrit5srhlme"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-coroutine-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "url": "util-coroutine-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "size": 9251,
          "sha512": "ed4d144de83f6dddf7c8c7b8b323f1aef609863ee15e4ce8864fd9d066babbe6945afab431e6c412f19bc099c91933fdb66829467cd2afa737026781d0849c18",
          "sha256": "25774e2f68eb81c62a9452cbc6b398000a9a72a2ef08cbb95fd320916a1c1c3e",
          "sha1": "90115112294919c5faf570eea694bc89f87c63e9",
          "md5": "72e68cee6021e5f192e2cf7bb560f3c5"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "util-coroutine-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "url": "util-coroutine-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "size": 9251,
          "sha512": "ed4d144de83f6dddf7c8c7b8b323f1aef609863ee15e4ce8864fd9d066babbe6945afab431e6c412f19bc099c91933fdb66829467cd2afa737026781d0849c18",
          "sha256": "25774e2f68eb81c62a9452cbc6b398000a9a72a2ef08cbb95fd320916a1c1c3e",
          "sha1": "90115112294919c5faf570eea694bc89f87c63e9",
          "md5": "72e68cee6021e5f192e2cf7bb560f3c5"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-coroutine-metadata/1.9.0-add-default-scope-SNAPSHOT/util-coroutine-metadata-1.9.0-add-default-scope-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-coroutine-metadata",
        "version": "1.9.0-add-default-scope-SNAPSHOT"
      }
    }
  ]
}
