{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-coroutine/1.9.0-add-default-scope-SNAPSHOT/util-coroutine-1.9.0-add-default-scope-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-coroutine",
    "version": "1.9.0-add-default-scope-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "xenom24cxna5hikpnifc4jf6lu"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-coroutine-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "url": "util-coroutine-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "size": 9592,
          "sha512": "57055dec101db4610f1280955169ad2c7a447996b8b61efac4488531cc6ba94b0aeca36a4e5ce865747988710f7f8556723b143ab320a1585f1925886587447f",
          "sha256": "d18ad04ecf55b95749489dfc37b902a30c06526e08f6303b8de1e4c147c53574",
          "sha1": "8b82b21fb82a7e117fe3b6e97e25931f2d4bdfd6",
          "md5": "6d91df3334d74d76e9b6fa5c3085fcaa"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "util-coroutine-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "url": "util-coroutine-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "size": 9592,
          "sha512": "57055dec101db4610f1280955169ad2c7a447996b8b61efac4488531cc6ba94b0aeca36a4e5ce865747988710f7f8556723b143ab320a1585f1925886587447f",
          "sha256": "d18ad04ecf55b95749489dfc37b902a30c06526e08f6303b8de1e4c147c53574",
          "sha1": "8b82b21fb82a7e117fe3b6e97e25931f2d4bdfd6",
          "md5": "6d91df3334d74d76e9b6fa5c3085fcaa"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-coroutine-metadata/1.9.0-add-default-scope-SNAPSHOT/util-coroutine-metadata-1.9.0-add-default-scope-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-coroutine-metadata",
        "version": "1.9.0-add-default-scope-SNAPSHOT"
      }
    }
  ]
}
