{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-coroutine/1.9.0-add-default-scope-SNAPSHOT/util-coroutine-1.9.0-add-default-scope-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-coroutine",
    "version": "1.9.0-add-default-scope-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "fncgrx3r7jc7zf3yari5cu3qpm"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-coroutine-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "url": "util-coroutine-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "size": 10603,
          "sha512": "9c56a4b877e7d7504d17e661badca82a8f6fe37bdd86574ffa6cbcbe81e02313f6d9194b5ef88a3529af855b0131b0645421942bfb88d5a70459d677860546e5",
          "sha256": "4f7ccea3758d288ffafb2c3037fa8a65456a88d0de40f362fbfe7d12b210e67d",
          "sha1": "c72334e27b334ff30c1570868213003363fd724d",
          "md5": "9b1737bfefaa1071332def6ebea18ffe"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "util-coroutine-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "url": "util-coroutine-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "size": 10603,
          "sha512": "9c56a4b877e7d7504d17e661badca82a8f6fe37bdd86574ffa6cbcbe81e02313f6d9194b5ef88a3529af855b0131b0645421942bfb88d5a70459d677860546e5",
          "sha256": "4f7ccea3758d288ffafb2c3037fa8a65456a88d0de40f362fbfe7d12b210e67d",
          "sha1": "c72334e27b334ff30c1570868213003363fd724d",
          "md5": "9b1737bfefaa1071332def6ebea18ffe"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-coroutine-metadata/1.9.0-add-default-scope-SNAPSHOT/util-coroutine-metadata-1.9.0-add-default-scope-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-coroutine-metadata",
        "version": "1.9.0-add-default-scope-SNAPSHOT"
      }
    }
  ]
}
