{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-jvm",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "4ybgtmcsrvemblmyhvy6lp6uoi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.12.0-SNAPSHOT.jar",
          "url": "sdk-jvm-1.12.0-SNAPSHOT.jar",
          "size": 11632,
          "sha512": "1cfb0562c7f750fbe7cc69438351d0cf14e6fe439d8e4cca2b03e1046f4e6524a6c89a731f8de1a82f73aa4943683ff6d0098cf898fab3a183e613f16747d021",
          "sha256": "0e398b536355d9e5b052b81ac74440b5ae0a441f4092e81f762889cbb77b85c0",
          "sha1": "a2c7fddc6f450ef17032a28d6210bfd9291326a2",
          "md5": "d3c244e25513d66497b9851a453e641e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.12.0-SNAPSHOT.jar",
          "url": "sdk-jvm-1.12.0-SNAPSHOT.jar",
          "size": 11632,
          "sha512": "1cfb0562c7f750fbe7cc69438351d0cf14e6fe439d8e4cca2b03e1046f4e6524a6c89a731f8de1a82f73aa4943683ff6d0098cf898fab3a183e613f16747d021",
          "sha256": "0e398b536355d9e5b052b81ac74440b5ae0a441f4092e81f762889cbb77b85c0",
          "sha1": "a2c7fddc6f450ef17032a28d6210bfd9291326a2",
          "md5": "d3c244e25513d66497b9851a453e641e"
        }
      ]
    }
  ]
}
