{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-gradle-scripts",
    "module": "example-kmp-library",
    "version": "0.0.1-add-coverage-doc-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "3ao4k7mm6jbczltqcs54mz5dye"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "example-kmp-library-metadata-0.0.1-add-coverage-doc-SNAPSHOT.jar",
          "url": "example-kmp-library-0.0.1-add-coverage-doc-SNAPSHOT.jar",
          "size": 6384,
          "sha512": "6e8db11913054eb819c490a64ed4d162be0a226cfd0f9e0b5ab6f237eb835794547b769d2436c44c2c3a954ef27f87d8d8198908246e26ed57e9bc011237f486",
          "sha256": "0c995bcf33f55352a222a4b9dfdf3ab0c8f52f1737038a4d38c2ed608ce38680",
          "sha1": "31e10e290e67cd75683baec724db29971cd58ff7",
          "md5": "31a8c746f06f6bbe0e64e3eaf336c57f"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../example-kmp-library-android/0.0.1-add-coverage-doc-SNAPSHOT/example-kmp-library-android-0.0.1-add-coverage-doc-SNAPSHOT.module",
        "group": "care.data4life",
        "module": "example-kmp-library-android",
        "version": "0.0.1-add-coverage-doc-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../example-kmp-library-android/0.0.1-add-coverage-doc-SNAPSHOT/example-kmp-library-android-0.0.1-add-coverage-doc-SNAPSHOT.module",
        "group": "care.data4life",
        "module": "example-kmp-library-android",
        "version": "0.0.1-add-coverage-doc-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../example-kmp-library-android/0.0.1-add-coverage-doc-SNAPSHOT/example-kmp-library-android-0.0.1-add-coverage-doc-SNAPSHOT.module",
        "group": "care.data4life.hc-gradle-scripts",
        "module": "example-kmp-library-android",
        "version": "0.0.1-add-coverage-doc-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../example-kmp-library-android/0.0.1-add-coverage-doc-SNAPSHOT/example-kmp-library-android-0.0.1-add-coverage-doc-SNAPSHOT.module",
        "group": "care.data4life.hc-gradle-scripts",
        "module": "example-kmp-library-android",
        "version": "0.0.1-add-coverage-doc-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../example-kmp-library-jvm/0.0.1-add-coverage-doc-SNAPSHOT/example-kmp-library-jvm-0.0.1-add-coverage-doc-SNAPSHOT.module",
        "group": "care.data4life.hc-gradle-scripts",
        "module": "example-kmp-library-jvm",
        "version": "0.0.1-add-coverage-doc-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../example-kmp-library-jvm/0.0.1-add-coverage-doc-SNAPSHOT/example-kmp-library-jvm-0.0.1-add-coverage-doc-SNAPSHOT.module",
        "group": "care.data4life.hc-gradle-scripts",
        "module": "example-kmp-library-jvm",
        "version": "0.0.1-add-coverage-doc-SNAPSHOT"
      }
    }
  ]
}
