{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-android",
    "version": "1.11.0-change-client-version-header-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "b3of7x3omfahdjdivrfbz4hek4"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-change-client-version-header-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.11.0-change-client-version-header-SNAPSHOT.aar",
          "url": "auth-android-1.11.0-change-client-version-header-SNAPSHOT.aar",
          "size": 45013,
          "sha512": "ea9eea55e3c1962037edb2958055cf10842b14e68e5e54d8ab9d3ad3a45ea9ef78fc6946fa8b840e08f08a9dd61caf91362b2ea405172f39b68c21242401624a",
          "sha256": "03e4d1ddd841879d2868ade6f0547b74887a60b423d37444acfc9a9fdb0eaeff",
          "sha1": "86bb05077eccbadd0475b1f329ac5223939b4373",
          "md5": "7631094ab27acec91a8c70a89774b6f9"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-change-client-version-header-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-android",
          "version": {
            "requires": "1.11.0-change-client-version-header-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.gesundheitscloud",
          "module": "AppAuth-Android",
          "version": {
            "requires": "9e3cc033ff"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.11.0-change-client-version-header-SNAPSHOT.aar",
          "url": "auth-android-1.11.0-change-client-version-header-SNAPSHOT.aar",
          "size": 45013,
          "sha512": "ea9eea55e3c1962037edb2958055cf10842b14e68e5e54d8ab9d3ad3a45ea9ef78fc6946fa8b840e08f08a9dd61caf91362b2ea405172f39b68c21242401624a",
          "sha256": "03e4d1ddd841879d2868ade6f0547b74887a60b423d37444acfc9a9fdb0eaeff",
          "sha1": "86bb05077eccbadd0475b1f329ac5223939b4373",
          "md5": "7631094ab27acec91a8c70a89774b6f9"
        }
      ]
    }
  ]
}
