{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-coroutine-jvm/0.2.0-change-setup-to-latest-SNAPSHOT/test-util-coroutine-jvm-0.2.0-change-setup-to-latest-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-coroutine-jvm",
    "version": "0.2.0-change-setup-to-latest-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "zpmu4wnpmvg7zgjd3gvyn7txai"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-util-coroutine-metadata-0.2.0-change-setup-to-latest-SNAPSHOT.jar",
          "url": "test-util-coroutine-metadata-0.2.0-change-setup-to-latest-SNAPSHOT.jar",
          "size": 1777,
          "sha512": "e832c3fe1e9a7f8ac64ba233106fdabc92b679eadd0b956007783f2972d27fffe6361cf1bce9bb5f7ca3d9544c41d5a80a3775721acf6aadd6cf1a2d95c1a17a",
          "sha256": "337c6ec9ca7c3092f2a3ac6194f8f06ed81477645458259f88d3653c366c6677",
          "sha1": "6935556f7938a2fc07c78b437828c128f9f216a2",
          "md5": "b5c62004c38b55bda11c4fc1c366a0c9"
        }
      ]
    }
  ]
}
