{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir",
    "version": "0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-metadata-0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT-all.jar",
          "url": "fhir-0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT-all.jar",
          "size": 10004,
          "sha512": "d12736b0c8add66e31602c655b4ee14679823177134a8f1bfd0f1a0fa52b1e4c4132ff4905a86169083079148e7abb5176b38559d57a1a8239511ef7a3230e29",
          "sha256": "0ea745b3c7fee22574e2d5fb13d0bd4487afb12e4ef678d01b081c04a05652ac",
          "sha1": "b45cb1ad02b717826354d91456d8981041a0342f",
          "md5": "dfbc93506959a7dd938b030cf9a08a19"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "fhir-0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT.jar",
          "url": "fhir-0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT.jar",
          "size": 11493,
          "sha512": "4c70ced8c96517120d7a4b439eb16d2274d78ef82c64c85a93d20d54d7972c88a6dfa1d21011179f07aa6fdedebfca6be39fd0a283ef34aa379fc9e108473a6b",
          "sha256": "3b35eef12a3c03b537199fa102f5ac5553f986e89df86ff3e1a0c1718b69f4af",
          "sha1": "07c4a278dd753a54978e8bcbea1e7f0aebd7a256",
          "md5": "a31e5c01a746ee7fbee403a4d12f06c8"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-android-debug/0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT/fhir-android-debug-0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-android-debug",
        "version": "0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-android-debug/0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT/fhir-android-debug-0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-android-debug",
        "version": "0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-android/0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT/fhir-android-0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-android",
        "version": "0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-android/0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT/fhir-android-0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-android",
        "version": "0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fhir-iosarm64/0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT/fhir-iosarm64-0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-iosarm64",
        "version": "0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fhir-iosarm64/0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT/fhir-iosarm64-0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-iosarm64",
        "version": "0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fhir-iosx64/0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT/fhir-iosx64-0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-iosx64",
        "version": "0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fhir-iosx64/0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT/fhir-iosx64-0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-iosx64",
        "version": "0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../fhir-jvm/0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT/fhir-jvm-0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-jvm",
        "version": "0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../fhir-jvm/0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT/fhir-jvm-0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-jvm",
        "version": "0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT"
      }
    }
  ]
}
