{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.13.1-bump-jacoco-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "p6unozuvgbfcpiib776eg4bqha"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.1-bump-jacoco-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.13.1-bump-jacoco-SNAPSHOT.jar",
          "url": "securestore-jvm-1.13.1-bump-jacoco-SNAPSHOT.jar",
          "size": 16455,
          "sha512": "0f9c036a7e33be91b564a0bc47a86a9553ae6a133b25ad9df93f4d7181a2857c5360957c97d1a116f18c9a9b4a6f5e79924de32146f206738e808e2237a51979",
          "sha256": "83080dbaea1252d39258c3f71be165d1efd24cfea38f65495d59ba4ca578438f",
          "sha1": "e03dc2d18fc9e39153c9c3c62b03a6166d5627b9",
          "md5": "310266e29c19ec3061ddfad2d40f6f72"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.1-bump-jacoco-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.13.1-bump-jacoco-SNAPSHOT.jar",
          "url": "securestore-jvm-1.13.1-bump-jacoco-SNAPSHOT.jar",
          "size": 16455,
          "sha512": "0f9c036a7e33be91b564a0bc47a86a9553ae6a133b25ad9df93f4d7181a2857c5360957c97d1a116f18c9a9b4a6f5e79924de32146f206738e808e2237a51979",
          "sha256": "83080dbaea1252d39258c3f71be165d1efd24cfea38f65495d59ba4ca578438f",
          "sha1": "e03dc2d18fc9e39153c9c3c62b03a6166d5627b9",
          "md5": "310266e29c19ec3061ddfad2d40f6f72"
        }
      ]
    }
  ]
}
