{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-ktor/0.2.0-bump-updates-SNAPSHOT/test-util-ktor-0.2.0-bump-updates-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-ktor",
    "version": "0.2.0-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor.klib",
          "url": "test-util-ktor-iosarm64-0.2.0-bump-updates-SNAPSHOT.klib",
          "size": 15022,
          "sha512": "3d291c11e9b3f75aff17236fbc9623bcbd9894939c2c5c58271ea9ed864d3af7574bd604659172cdcd68edbff2799eecc27690cc720f694a93830d4bc7a32c5a",
          "sha256": "5af24856c803b8c3f286f499368335735a5e25dfd5d16b1f24efaaedc4578a73",
          "sha1": "3db797b886e28be5f28285ea0778f3e4075736b3",
          "md5": "18d3d1b0ae22b016473070a1ba810050"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor-iosarm64-0.2.0-bump-updates-SNAPSHOT-metadata.jar",
          "url": "test-util-ktor-iosarm64-0.2.0-bump-updates-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "4699aa243c46fa9461f2b3b3a6a708f7029be8b6251b5c38accbbccdcada99d0e2d1c9d746dbfc3f9cd58ac7b2c4787db8361af7b9658e690663baf07af4a987",
          "sha256": "8f78dc6ad5ba0b1ebe3986ec9956bcfc6196ee76ea6dc7b64a65fe061ad1e90c",
          "sha1": "da73df722440113120bb175d9ed55f949feb3917",
          "md5": "bbf0fe54eb3e70cd12d3b94204e3f336"
        }
      ]
    }
  ]
}
