{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.0-SNAPSHOT/data-donation-sdk-iosx64-0.1.0-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "3t3euikyoffi3htwrjpsjo7vea"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.0-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.0-SNAPSHOT.jar",
          "size": 39147,
          "sha512": "a2c4443096bc7e63038e0196381b47f4578bf1027b6b45186f334ab080b057575877436d4c62e01365d2359f69a668aa9090cc3ef0cc4b5c1f7ab534150e2d72",
          "sha256": "23a6680b325cb736d5f718e349de5daf4f24225ff3ebfb511bf5d55566bf7804",
          "sha1": "e2ce7b687965067a5739a263b1ff12ef6b174394",
          "md5": "c35ba236d6f5e388ea705457c400a0c5"
        }
      ]
    }
  ]
}
