{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.11.0-change-api-service-to-kotlin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "fzo53vn52bfo7it2q3f2aueecq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-change-api-service-to-kotlin-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-change-api-service-to-kotlin-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "2bf1fcd7030b9e727069c42fb1d5e014a01e9ea589a26cc59551e34b133e040cc566718aaec0166cab8456e5112da52f7cd7933222ccfee4e348e6faf13ca10c",
          "sha256": "b67ce5c0b7817a5361e36d04a29ea40a55bd6521a8a5c377f7483855dac3dd47",
          "sha1": "b17706cd457deb49b4c6dcd2dcd4fbc70ab3d70a",
          "md5": "06b2928968afcd1d604ad61aac6e1f05"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-change-api-service-to-kotlin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-change-api-service-to-kotlin-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-change-api-service-to-kotlin-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "2bf1fcd7030b9e727069c42fb1d5e014a01e9ea589a26cc59551e34b133e040cc566718aaec0166cab8456e5112da52f7cd7933222ccfee4e348e6faf13ca10c",
          "sha256": "b67ce5c0b7817a5361e36d04a29ea40a55bd6521a8a5c377f7483855dac3dd47",
          "sha1": "b17706cd457deb49b4c6dcd2dcd4fbc70ab3d70a",
          "md5": "06b2928968afcd1d604ad61aac6e1f05"
        }
      ]
    }
  ]
}
