{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.13.1-change-attachment-service-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "zejt662w2jbpvdyvwh6fwgimrq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.1-change-attachment-service-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.13.1-change-attachment-service-tests-SNAPSHOT.jar",
          "url": "securestore-jvm-1.13.1-change-attachment-service-tests-SNAPSHOT.jar",
          "size": 16455,
          "sha512": "d9facdb269f0480146237fbcf128d88ab750e5740f1486cdc45ca86b0f8a21d23e5db78b355c42a6fb30eadb2a10c26c2851cc593446ba5158305184bd16f5f9",
          "sha256": "6bd42b794510590744229a35b2c0f413774ae586edb13c331eadfb31165a9ab0",
          "sha1": "b6d4a961f26c87dca69d098a53f12452865491a4",
          "md5": "382af645abf305a2fd88fc2aa5143db7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.1-change-attachment-service-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.13.1-change-attachment-service-tests-SNAPSHOT.jar",
          "url": "securestore-jvm-1.13.1-change-attachment-service-tests-SNAPSHOT.jar",
          "size": 16455,
          "sha512": "d9facdb269f0480146237fbcf128d88ab750e5740f1486cdc45ca86b0f8a21d23e5db78b355c42a6fb30eadb2a10c26c2851cc593446ba5158305184bd16f5f9",
          "sha256": "6bd42b794510590744229a35b2c0f413774ae586edb13c331eadfb31165a9ab0",
          "sha1": "b6d4a961f26c87dca69d098a53f12452865491a4",
          "md5": "382af645abf305a2fd88fc2aa5143db7"
        }
      ]
    }
  ]
}
