{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.13.1-change-attachment-service-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "d3won7mtbbgopomqomu27sdq6q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.1-change-attachment-service-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.13.1-change-attachment-service-tests-SNAPSHOT.jar",
          "url": "securestore-jvm-1.13.1-change-attachment-service-tests-SNAPSHOT.jar",
          "size": 16455,
          "sha512": "1882c3e9f8d4d65381b08422e08f3f4d32178953995a121f4bd74a1dbd8900e885a5ec82a3713f3e44b652ca1b28fe60dcaaa9b7f704d545c21762620eebab49",
          "sha256": "7953a0eb6f2514d4cbd7389babeffbf6894775cb551a4f5d74923f4abd03d176",
          "sha1": "862a9dc74fb9994049b477cf37f2f93ce01accf2",
          "md5": "52c5f5cbc0dcac8e9a1ff5a1813d5c79"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.1-change-attachment-service-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.13.1-change-attachment-service-tests-SNAPSHOT.jar",
          "url": "securestore-jvm-1.13.1-change-attachment-service-tests-SNAPSHOT.jar",
          "size": 16455,
          "sha512": "1882c3e9f8d4d65381b08422e08f3f4d32178953995a121f4bd74a1dbd8900e885a5ec82a3713f3e44b652ca1b28fe60dcaaa9b7f704d545c21762620eebab49",
          "sha256": "7953a0eb6f2514d4cbd7389babeffbf6894775cb551a4f5d74923f4abd03d176",
          "sha1": "862a9dc74fb9994049b477cf37f2f93ce01accf2",
          "md5": "52c5f5cbc0dcac8e9a1ff5a1813d5c79"
        }
      ]
    }
  ]
}
