{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.11.0-fix-update-record-data-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "2izywu4e6rgwhehoizj6gl6zdy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-fix-update-record-data-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-fix-update-record-data-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "9410244b04e661f8d3820c5e46862726747b8646d50a52c85e9faae4611dba88d5fbe6b9721f150c1a93ed49901ad325b30d8a995c18ea90e6ce3dbcec7128f1",
          "sha256": "8c0e5941a5dc42da255db9ab3464b816339013b5f661d8647c7188a00a382ccb",
          "sha1": "b4d4523220893a25208ad7d0839a34256ca7ae4a",
          "md5": "c03c3165b0712397231f2401b0b4737a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-fix-update-record-data-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-fix-update-record-data-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-fix-update-record-data-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "9410244b04e661f8d3820c5e46862726747b8646d50a52c85e9faae4611dba88d5fbe6b9721f150c1a93ed49901ad325b30d8a995c18ea90e6ce3dbcec7128f1",
          "sha256": "8c0e5941a5dc42da255db9ab3464b816339013b5f661d8647c7188a00a382ccb",
          "sha1": "b4d4523220893a25208ad7d0839a34256ca7ae4a",
          "md5": "c03c3165b0712397231f2401b0b4737a"
        }
      ]
    }
  ]
}
