{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.11.0-fix-update-record-data-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "b3ys5acjije5xazx2c6hgv6uyi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-fix-update-record-data-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-fix-update-record-data-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "db248b9314ec2ff6a430426ed5582bed73fe63639feff02e1fd0b3d0d6d42cc421dc32f1611024e4ce8fad9146035982e00239e900e560ddf8969e00a39cead5",
          "sha256": "7dbc85250144d1a55de99e5fcd26c0cc6dbeb452b3f68b38f9e32859e98d16f5",
          "sha1": "597cc2264d184610353a60a73244ef29dde7752b",
          "md5": "50e0b7e65aa1c9a76083367914a5d434"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-fix-update-record-data-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-fix-update-record-data-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-fix-update-record-data-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "db248b9314ec2ff6a430426ed5582bed73fe63639feff02e1fd0b3d0d6d42cc421dc32f1611024e4ce8fad9146035982e00239e900e560ddf8969e00a39cead5",
          "sha256": "7dbc85250144d1a55de99e5fcd26c0cc6dbeb452b3f68b38f9e32859e98d16f5",
          "sha1": "597cc2264d184610353a60a73244ef29dde7752b",
          "md5": "50e0b7e65aa1c9a76083367914a5d434"
        }
      ]
    }
  ]
}
