{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.11.0-fix-update-record-data-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "tnz6vgochzftdj2lib4llqdosm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-fix-update-record-data-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-fix-update-record-data-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "38a70153dd86d3d96dd3843739b46154267dbb2397b1c57a87bef2b0a0991734613d677168a3d0c6d0abc48e13e85ce4f45316e141e55a2b868380210c7f959e",
          "sha256": "3f49fe91b54f6e14b74e491d8cbf72ef4157b37e3149993c374f722f74f8037f",
          "sha1": "8124901693b380e69b56ec0a934b6e14a2113f9a",
          "md5": "088f024eb877e52f2f13cdb5abeeacb8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-fix-update-record-data-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-fix-update-record-data-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-fix-update-record-data-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "38a70153dd86d3d96dd3843739b46154267dbb2397b1c57a87bef2b0a0991734613d677168a3d0c6d0abc48e13e85ce4f45316e141e55a2b868380210c7f959e",
          "sha256": "3f49fe91b54f6e14b74e491d8cbf72ef4157b37e3149993c374f722f74f8037f",
          "sha1": "8124901693b380e69b56ec0a934b6e14a2113f9a",
          "md5": "088f024eb877e52f2f13cdb5abeeacb8"
        }
      ]
    }
  ]
}
