{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-jvm/1.8.1-bump-android-SNAPSHOT/util-jvm-1.8.1-bump-android-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-jvm",
    "version": "1.8.1-bump-android-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "uo7cvs46mjf53mugcs3pv62wam"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-metadata-1.8.1-bump-android-SNAPSHOT.jar",
          "url": "util-metadata-1.8.1-bump-android-SNAPSHOT.jar",
          "size": 6309,
          "sha512": "6cdc68a5e4ddabc84df5b44285bb12d963cd6fdbfb097195a3d68433abcec38d857e4754a46de8d61154fd7607f3129c6ca0fac1f4b0ae1827eaab819aa312d4",
          "sha256": "6ca2eb35d5da38071cd96961658cb4adc104ef51c9dd4a655627e3b92e4f9c57",
          "sha1": "cfd4e65fbb01a478cd9828f87a5d11b937359eae",
          "md5": "f31398787f05d53f99e6d220de228e02"
        }
      ]
    }
  ]
}
