{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-jvm/1.8.1-bump-android-SNAPSHOT/util-jvm-1.8.1-bump-android-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-jvm",
    "version": "1.8.1-bump-android-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "w4kpcm5gr5f53ixajmnyyzsrzi"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-metadata-1.8.1-bump-android-SNAPSHOT.jar",
          "url": "util-metadata-1.8.1-bump-android-SNAPSHOT.jar",
          "size": 6309,
          "sha512": "d0f7009a5d00f844e6fc57746f9fbd8f19c58de698ec438ddfce38f1f6e949dc8a14807af79e745ef973b6a9fdcf0e6bf2cd214668a59a694c23cc66d0a79d77",
          "sha256": "6c0d00e3d074cbf07a31e4a754d687907682a49774fc3007c724bf0ae3a47eb7",
          "sha1": "ae1271a15fe36f8dfc12c6ca641c1d1ec12db33e",
          "md5": "3b203c23b6a5a4c648525e6ce9ba9625"
        }
      ]
    }
  ]
}
