{
  "formatVersion": "1.1",
  "component": {
    "url": "../../error/1.11.0-SNAPSHOT/error-1.11.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "error",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "error.klib",
          "url": "error-iosarm64-1.11.0-SNAPSHOT.klib",
          "size": 7100,
          "sha512": "6a4f00dfb2e9216859511612f28936ad8d04a46f89f7a35e065c792f2aebbbed129bc6e9fa6fd75be69976280c1af7bd9f7fa7b9da6b0b7a07a1d9e5bcb18f2a",
          "sha256": "0b55087a1d26b454ca975f26d916e1a2c1683541cac36e4bb3c83814aea82ef9",
          "sha1": "ae441be4e76b509af8a51da13be61d0a4466d154",
          "md5": "b4f80a90b3d3852b8bb6054d132887c1"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "error-iosarm64-1.11.0-SNAPSHOT-metadata.jar",
          "url": "error-iosarm64-1.11.0-SNAPSHOT-metadata.jar",
          "size": 5010,
          "sha512": "831c048db658309fa0c9081a546f4b34d3890e0a2f2ba5486e7bbdf06b63bb38388561717a5d943c22c7a5a17875dc9466f07f0cd8164fffb5023e3948bd1e46",
          "sha256": "6718d288864fa46480352ba2e7b84ebb1f7e2dd7c66806873753bb2c29f45c5f",
          "sha1": "49e4900d160db4f1dbc12fb56408382356dd8d8d",
          "md5": "44a0bf73c887f954cc445a4c99187268"
        }
      ]
    }
  ]
}
