{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-coroutine/1.9.0-add-default-scope-SNAPSHOT/util-coroutine-1.9.0-add-default-scope-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-coroutine",
    "version": "1.9.0-add-default-scope-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "txlx3xcicbhwjb3difcdh5zfy4"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "util-coroutine-release.aar",
          "url": "util-coroutine-android-1.9.0-add-default-scope-SNAPSHOT.aar",
          "size": 9052,
          "sha512": "de0ce19f28e611c330d45e411e3bdd74907fb8e1c138e4454c3500c3ff3173e0300c85d029fce34ecf17bfbd7792612e8f9f2c0fd7b3debf61d5a8f49c9e1b2e",
          "sha256": "6c0e43be29f73426b967685b0560c29cafb89c70f32531cccf00c5aa8ac4679a",
          "sha1": "e15c23be369c9c31bc888c4736e3f73b16628ab9",
          "md5": "cefe066469e586f2d5bdce0f881d7ab5"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "util-coroutine-release.aar",
          "url": "util-coroutine-android-1.9.0-add-default-scope-SNAPSHOT.aar",
          "size": 9052,
          "sha512": "de0ce19f28e611c330d45e411e3bdd74907fb8e1c138e4454c3500c3ff3173e0300c85d029fce34ecf17bfbd7792612e8f9f2c0fd7b3debf61d5a8f49c9e1b2e",
          "sha256": "6c0e43be29f73426b967685b0560c29cafb89c70f32531cccf00c5aa8ac4679a",
          "sha1": "e15c23be369c9c31bc888c4736e3f73b16628ab9",
          "md5": "cefe066469e586f2d5bdce0f881d7ab5"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-coroutine-metadata/1.9.0-add-default-scope-SNAPSHOT/util-coroutine-metadata-1.9.0-add-default-scope-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-coroutine-metadata",
        "version": "1.9.0-add-default-scope-SNAPSHOT"
      }
    }
  ]
}
