{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.13.2-add-coverage-android-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "y3j7a5h4nfdddcw7tuhxprx55e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.2-add-coverage-android-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.13.2-add-coverage-android-SNAPSHOT.jar",
          "url": "securestore-jvm-1.13.2-add-coverage-android-SNAPSHOT.jar",
          "size": 16455,
          "sha512": "1c6e2b5510c380fc67ff099865b0a1442958ce630df718c7cea4c35c9da3d31011310d7a7db07aa81da1cf97ed4fa5a65a5a9d4f7bbe51458b2a12816a4b4dc3",
          "sha256": "f158383d0b01fbbd251466704fb8f0d51e7f14340d38321258b6f48e724e63e4",
          "sha1": "3463b58134fcbb4cd65fe8bd76098f9faabf1f33",
          "md5": "6e95f55ab3399c17c3a92741ee2eb9a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.2-add-coverage-android-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.13.2-add-coverage-android-SNAPSHOT.jar",
          "url": "securestore-jvm-1.13.2-add-coverage-android-SNAPSHOT.jar",
          "size": 16455,
          "sha512": "1c6e2b5510c380fc67ff099865b0a1442958ce630df718c7cea4c35c9da3d31011310d7a7db07aa81da1cf97ed4fa5a65a5a9d4f7bbe51458b2a12816a4b4dc3",
          "sha256": "f158383d0b01fbbd251466704fb8f0d51e7f14340d38321258b6f48e724e63e4",
          "sha1": "3463b58134fcbb4cd65fe8bd76098f9faabf1f33",
          "md5": "6e95f55ab3399c17c3a92741ee2eb9a5"
        }
      ]
    }
  ]
}
