{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-coroutine/1.9.0-add-default-scope-SNAPSHOT/util-coroutine-1.9.0-add-default-scope-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-coroutine",
    "version": "1.9.0-add-default-scope-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "kajwctthtndz5mesu25u6hfcwa"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "util-coroutine-debug.aar",
          "url": "util-coroutine-android-debug-1.9.0-add-default-scope-SNAPSHOT.aar",
          "size": 9409,
          "sha512": "efba15b2aeabeee726efd7c2315373b3a5b026f310ffc1667d26cec1943bc4e9bf30a713049d814c1b01211ce5454fa8b8979099c23f2bf50cb7a7c9208401d0",
          "sha256": "9bb7a719f6a0b0ce0f34bffdecd6d32ad7c74cbec94a995791401533ae2235b3",
          "sha1": "cdd14936da6a8752ed75cfc51cd4b1bbb4a79ab4",
          "md5": "7406d4c4fb0073e3cced35ebffc4ff9e"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "util-coroutine-debug.aar",
          "url": "util-coroutine-android-debug-1.9.0-add-default-scope-SNAPSHOT.aar",
          "size": 9409,
          "sha512": "efba15b2aeabeee726efd7c2315373b3a5b026f310ffc1667d26cec1943bc4e9bf30a713049d814c1b01211ce5454fa8b8979099c23f2bf50cb7a7c9208401d0",
          "sha256": "9bb7a719f6a0b0ce0f34bffdecd6d32ad7c74cbec94a995791401533ae2235b3",
          "sha1": "cdd14936da6a8752ed75cfc51cd4b1bbb4a79ab4",
          "md5": "7406d4c4fb0073e3cced35ebffc4ff9e"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-coroutine-metadata/1.9.0-add-default-scope-SNAPSHOT/util-coroutine-metadata-1.9.0-add-default-scope-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-coroutine-metadata",
        "version": "1.9.0-add-default-scope-SNAPSHOT"
      }
    }
  ]
}
