{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.11.0-add-interceptors-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "4wnhsisxrbhzhnyfitrygvw7xe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-add-interceptors-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-add-interceptors-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "ea315743a845982eb2e5029581e2305f070a623137c12c0669039323bd1ff47ea9fbfa9584efd9ebb892eea0fe0630d26207bc8a4ed35a267cd9eabcbaf8e2ae",
          "sha256": "3ec953eb79c69ef432dc4519e0c63bf6d5a9c0288dc31153637eafff03ed9678",
          "sha1": "486e2ffd96f73fbb3b16b8745ee7de6774dc0076",
          "md5": "83c3b5742abf95fbae20a2c8f17d125d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-add-interceptors-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-add-interceptors-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-add-interceptors-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "ea315743a845982eb2e5029581e2305f070a623137c12c0669039323bd1ff47ea9fbfa9584efd9ebb892eea0fe0630d26207bc8a4ed35a267cd9eabcbaf8e2ae",
          "sha256": "3ec953eb79c69ef432dc4519e0c63bf6d5a9c0288dc31153637eafff03ed9678",
          "sha1": "486e2ffd96f73fbb3b16b8745ee7de6774dc0076",
          "md5": "83c3b5742abf95fbae20a2c8f17d125d"
        }
      ]
    }
  ]
}
