{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.11.0-add-interceptors-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "x4sy7hm7ivevzne7z5vn5d7fei"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-add-interceptors-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-add-interceptors-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "a8c4ef18db629e21d743f38b3b1975080903547710b700958b0ea94bf6edb6086671210bf7df9da057f357a0fba3c0c396f8b3af43bb2ce31b041ca9f86e00e3",
          "sha256": "777133c85599cbf4311d642d95fbf95489dbc3aca1017040a04e4cbae633e3d6",
          "sha1": "66c2d3298958fe0aed4cf331da3f4de6a87f6a34",
          "md5": "a3bccfcabdcf33d1926254006980d796"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-add-interceptors-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-add-interceptors-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-add-interceptors-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "a8c4ef18db629e21d743f38b3b1975080903547710b700958b0ea94bf6edb6086671210bf7df9da057f357a0fba3c0c396f8b3af43bb2ce31b041ca9f86e00e3",
          "sha256": "777133c85599cbf4311d642d95fbf95489dbc3aca1017040a04e4cbae633e3d6",
          "sha1": "66c2d3298958fe0aed4cf331da3f4de6a87f6a34",
          "md5": "a3bccfcabdcf33d1926254006980d796"
        }
      ]
    }
  ]
}
