{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.11.0-add-interceptors-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "u6fa5pqgq5dk3n2ber5tl6kzgm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-add-interceptors-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-add-interceptors-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "327c56dec28cb1e1844816dd2e05624d9b9e2579082a300dbf94af67683d343d9eb55f6e5ca343b7a8b8669949155ea25e8ec045e0244ea3ac928cdc32f454a4",
          "sha256": "7477e1f0cbf1089da73d3d59c4cb289617ec34e0e5d43957fb2c801fc0e4c4ca",
          "sha1": "83d7ad7f207fdbac9bc40943ccb1d38f4acdb5f5",
          "md5": "c474106306cf46b9fd63f083e47fc686"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-add-interceptors-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-add-interceptors-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-add-interceptors-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "327c56dec28cb1e1844816dd2e05624d9b9e2579082a300dbf94af67683d343d9eb55f6e5ca343b7a8b8669949155ea25e8ec045e0244ea3ac928cdc32f454a4",
          "sha256": "7477e1f0cbf1089da73d3d59c4cb289617ec34e0e5d43957fb2c801fc0e4c4ca",
          "sha1": "83d7ad7f207fdbac9bc40943ccb1d38f4acdb5f5",
          "md5": "c474106306cf46b9fd63f083e47fc686"
        }
      ]
    }
  ]
}
