{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.11.0-add-interceptors-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "kecct5uhzravrnidg46gsglloi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-add-interceptors-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-add-interceptors-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "91a16f775d1c8f1572aebecb065d164ea7cf53ce29620e6ab53c3ea1a9145cfcaae0a625c840d175fbac1b4923105edb2d6f76f88862fa377c3fb89a85573edf",
          "sha256": "d7e3419ae02421e959a45a17820eb26430ece04e9ca1ea63af5e20e396411238",
          "sha1": "ddc6aabf0a02b0613c195724aa7f2c1371565735",
          "md5": "8fbaf8896f33370ac5646313a86181ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-add-interceptors-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-add-interceptors-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-add-interceptors-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "91a16f775d1c8f1572aebecb065d164ea7cf53ce29620e6ab53c3ea1a9145cfcaae0a625c840d175fbac1b4923105edb2d6f76f88862fa377c3fb89a85573edf",
          "sha256": "d7e3419ae02421e959a45a17820eb26430ece04e9ca1ea63af5e20e396411238",
          "sha1": "ddc6aabf0a02b0613c195724aa7f2c1371565735",
          "md5": "8fbaf8896f33370ac5646313a86181ea"
        }
      ]
    }
  ]
}
