{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-core",
    "version": "1.12.0-change-user-service-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "mu5b7nen4zafxg3f7dh2ahj6be"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.12.0-change-user-service-tests-SNAPSHOT.jar",
          "url": "sdk-core-1.12.0-change-user-service-tests-SNAPSHOT.jar",
          "size": 568586,
          "sha512": "490eec3d0340d805ea6b31b1a21ee0409db85f7951f1697ca524fa5232626eba497ff66fd2975c45b5d66b932cd991147d756dce99151fe749f6e34a9f6a4790",
          "sha256": "49b9a5b993c43035aa8db73e9ed2c0c64b5a670473d0c98e3fab5d217af1f2ee",
          "sha1": "5707d999ec4190c7bbf8f0ddfdbf1a8b3d174451",
          "md5": "89a2d1538d8fc99b27bd923f3b2076a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.12.0-change-user-service-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.12.0-change-user-service-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.12.0-change-user-service-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.12.0-change-user-service-tests-SNAPSHOT.jar",
          "url": "sdk-core-1.12.0-change-user-service-tests-SNAPSHOT.jar",
          "size": 568586,
          "sha512": "490eec3d0340d805ea6b31b1a21ee0409db85f7951f1697ca524fa5232626eba497ff66fd2975c45b5d66b932cd991147d756dce99151fe749f6e34a9f6a4790",
          "sha256": "49b9a5b993c43035aa8db73e9ed2c0c64b5a670473d0c98e3fab5d217af1f2ee",
          "sha1": "5707d999ec4190c7bbf8f0ddfdbf1a8b3d174451",
          "md5": "89a2d1538d8fc99b27bd923f3b2076a5"
        }
      ]
    }
  ]
}
