{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-test",
    "version": "1.8.1-add-coroutine-util-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "3byk2twyijgtrh4bkxch45v7t4"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-test-metadata-1.8.1-add-coroutine-util-SNAPSHOT.jar",
          "url": "util-test-1.8.1-add-coroutine-util-SNAPSHOT.jar",
          "size": 4877,
          "sha512": "59ed5b70a6ce8671c18d214246198d0e9027b071459172634ef9947e0c0141029aa9b795be1e8fa1b034f9a3ead26af2e519f717905625a73b7699611bef0c3d",
          "sha256": "d4bd869588a03399df2ccb60788ca0b40f373cf013a2700f048b670afd345705",
          "sha1": "c5f90dbe86e9e29f10787027a00071aa6444f890",
          "md5": "e52b35c25dc0d3b28f7a8e1fcf103df3"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../util-test-android-debug/1.8.1-add-coroutine-util-SNAPSHOT/util-test-android-debug-1.8.1-add-coroutine-util-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-test-android-debug",
        "version": "1.8.1-add-coroutine-util-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../util-test-android-debug/1.8.1-add-coroutine-util-SNAPSHOT/util-test-android-debug-1.8.1-add-coroutine-util-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-test-android-debug",
        "version": "1.8.1-add-coroutine-util-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../util-test-android/1.8.1-add-coroutine-util-SNAPSHOT/util-test-android-1.8.1-add-coroutine-util-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-test-android",
        "version": "1.8.1-add-coroutine-util-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../util-test-android/1.8.1-add-coroutine-util-SNAPSHOT/util-test-android-1.8.1-add-coroutine-util-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-test-android",
        "version": "1.8.1-add-coroutine-util-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../util-test-iosarm64/1.8.1-add-coroutine-util-SNAPSHOT/util-test-iosarm64-1.8.1-add-coroutine-util-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-test-iosarm64",
        "version": "1.8.1-add-coroutine-util-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../util-test-iosx64/1.8.1-add-coroutine-util-SNAPSHOT/util-test-iosx64-1.8.1-add-coroutine-util-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-test-iosx64",
        "version": "1.8.1-add-coroutine-util-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../util-test-jvm/1.8.1-add-coroutine-util-SNAPSHOT/util-test-jvm-1.8.1-add-coroutine-util-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-test-jvm",
        "version": "1.8.1-add-coroutine-util-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../util-test-jvm/1.8.1-add-coroutine-util-SNAPSHOT/util-test-jvm-1.8.1-add-coroutine-util-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-test-jvm",
        "version": "1.8.1-add-coroutine-util-SNAPSHOT"
      }
    }
  ]
}
