{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.0.4-change-client-parameter-injection-SNAPSHOT/data-donation-sdk-iosx64-0.0.4-change-client-parameter-injection-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.0.4-change-client-parameter-injection-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "y73ajr56ejcytnaxsq3o4ukiqa"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.4-change-client-parameter-injection-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.0.4-change-client-parameter-injection-SNAPSHOT.jar",
          "size": 46192,
          "sha512": "e91302292734413170d8895d6c1735f8b0ca305ff93a507128ea87924669220232f6e92d1e3018980e380c709aa7baa360be9bbef538e5cf89718ebbf5c52301",
          "sha256": "97795f247ba73e73b1bba37c0455d03166473eb31fd59ddfb72373e1ecb91fe9",
          "sha1": "1c8150ff91d0b5f8031e419e5ecc68b02eb59a68",
          "md5": "a09e4f71b3ebc02f5aa33bae7b44ef49"
        }
      ]
    }
  ]
}
