{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk/0.0.2-change_fetch_consent_for_custom_key-SNAPSHOT/data-donation-sdk-0.0.2-change_fetch_consent_for_custom_key-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk",
    "version": "0.0.2-change_fetch_consent_for_custom_key-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "6xx54iqb35bsrksjbw3apu6lgm"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2-native-mt"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-kmp",
          "module": "fhir",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.4.2-native-mt",
            "requires": "1.4.2-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "data-donation-sdk.klib",
          "url": "data-donation-sdk-iosarm64-0.0.2-change_fetch_consent_for_custom_key-SNAPSHOT.klib",
          "size": 7263832,
          "sha512": "4e19ec97f92676912bc98c1c673e015575808ae15df170c1a66f18129a01156f88b35a15a89763bdcd45577f6635ba7d192f5ef6a73cc0b9ea9f44885fe2ce6d",
          "sha256": "45edb3a434060a659ce391e823b7021a8e577421a47785c79a758107c09b1daa",
          "sha1": "baec57fd7fe6bf76d8c5e81125d504c9eff75b73",
          "md5": "4d3e0288414a7de9eb657a94aae964f3"
        },
        {
          "name": "data-donation-sdk-cinterop-iOSDCryptoDD.klib",
          "url": "data-donation-sdk-iosarm64-0.0.2-change_fetch_consent_for_custom_key-SNAPSHOT-cinterop-iOSDCryptoDD.klib",
          "size": 5914,
          "sha512": "1a7f4b48650002ac90e24e9b656ec7bcd0c3d073b0c6274ea36880469011e7020a0e0a0d816864de6c35fd87126777432ddd920ec634f03587fac1f680194115",
          "sha256": "7d5ada2ecccf493a69799c14be7500ad14a5b4815d30105da4a17ba6936fbabc",
          "sha1": "4e8a00ee5ef478bbd2a5e1a1666b4b065fd19d94",
          "md5": "d1ba86948c788a007bc801a16e9844d0"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../data-donation-sdk-metadata/0.0.2-change_fetch_consent_for_custom_key-SNAPSHOT/data-donation-sdk-metadata-0.0.2-change_fetch_consent_for_custom_key-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-metadata",
        "version": "0.0.2-change_fetch_consent_for_custom_key-SNAPSHOT"
      }
    }
  ]
}
