{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.2-add-redact-SNAPSHOT/data-donation-sdk-iosx64-0.1.2-add-redact-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.2-add-redact-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "bvqtn2jrxvdtjjbo34wijiepcu"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.2-add-redact-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.2-add-redact-SNAPSHOT.jar",
          "size": 35721,
          "sha512": "87f48e1cb432a73ba28545156f97391abdea6288bd813f5321e688669a5be23bfc6414eac46a31de2dd37af229f5c662cd332395d16fed5b1a3cc0dfb2294a00",
          "sha256": "5af854bfdb04c16f391af698154b0ebbd4f6df7b958abd153e146590bad840e7",
          "sha1": "cfe2351d34528eb3c7aa9306bb87b3d6c0fccf5d",
          "md5": "9853f370805725fc2faa5e229760fd16"
        }
      ]
    }
  ]
}
