{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.2-add-redact-SNAPSHOT/data-donation-sdk-iosx64-0.1.2-add-redact-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.2-add-redact-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ww6upvc62fcvxltgwszmhom6ua"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.2-add-redact-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.2-add-redact-SNAPSHOT.jar",
          "size": 35655,
          "sha512": "42c42e5958e4ed188c23370d8f3531c0065785e46d4e194f724319fa2ca33e6e5aafabd5cee1d240fe2907294e1a6df0619f9567f9adfd38d6d03808b67756ab",
          "sha256": "fc62b4ac350423bf5bff98ff1d0daef0c4fc2486d1b1d07673bed776574ea4f3",
          "sha1": "ae4056ea2591e2ea90670c96394c22124fb33e76",
          "md5": "f1260db047d43e656f165fe4caea4d2f"
        }
      ]
    }
  ]
}
