{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.2-add-redact-SNAPSHOT/data-donation-sdk-iosx64-0.1.2-add-redact-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.2-add-redact-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "4rxltgpg4ve5zm6jxykamx3ebe"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.2-add-redact-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.2-add-redact-SNAPSHOT.jar",
          "size": 35725,
          "sha512": "17580f67e5f71eda14d2971a1ee0c20b0f88e6032f87b4199f6f3325c8615701a46caaaeccdf9cb09abd6cebfc33fcb76e9b464537b6201bc47c73b771d44ba9",
          "sha256": "ae7755e5c3823cf1b196172ea7729d38a2fafdb77ed26a74e53cec85403e7523",
          "sha1": "82acc4efd969d8f9f0d489afb7da227bb8eb5ed1",
          "md5": "af4c5d605f90fcabb791cbad260954e1"
        }
      ]
    }
  ]
}
