{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util/0.4.0-SNAPSHOT/test-util-0.4.0-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util",
    "version": "0.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-util-jvm-0.4.0-SNAPSHOT.jar",
          "url": "test-util-jvm-0.4.0-SNAPSHOT.jar",
          "size": 12827,
          "sha512": "f269429ec68f1e9d0bf876eda2ed539f7ba76f9717fd42bfd2d5228f713f41c58838408418af4aae1e7b5ba7607193365cb79b34cd5733073afb13555621a314",
          "sha256": "09d4791ca7d610217fd5bab821879af9a1bacf956ca21d7a99dc5de97e84f3b7",
          "sha1": "cbd269f69978978a3de04b67fb2db596adaa4366",
          "md5": "758cefdc65f7ec0c968facf976b95c37"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-jvm-0.4.0-SNAPSHOT.jar",
          "url": "test-util-jvm-0.4.0-SNAPSHOT.jar",
          "size": 12827,
          "sha512": "f269429ec68f1e9d0bf876eda2ed539f7ba76f9717fd42bfd2d5228f713f41c58838408418af4aae1e7b5ba7607193365cb79b34cd5733073afb13555621a314",
          "sha256": "09d4791ca7d610217fd5bab821879af9a1bacf956ca21d7a99dc5de97e84f3b7",
          "sha1": "cbd269f69978978a3de04b67fb2db596adaa4366",
          "md5": "758cefdc65f7ec0c968facf976b95c37"
        }
      ]
    }
  ]
}
