{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.10.0-add-secure-store-and-crypto-service-kotlin-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "vpbm6lmtdvcl7gezbc5xya2ioe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-add-secure-store-and-crypto-service-kotlin-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-add-secure-store-and-crypto-service-kotlin-tests-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-add-secure-store-and-crypto-service-kotlin-tests-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "0f5fc7684d5ed0e123bd97c3f1fea848043b3c54a25ecd42bf988c5a90393da3309caf63ae5069a6a637dfa40cf30bf557a186cb41e415295f99f818c2cd90ef",
          "sha256": "28ba73d5b19a309359b5decbbdea3e231e56d3711d9135a853e57666a6c9f92d",
          "sha1": "70225adabdbf2749fca6f7c6bec9238d2d647231",
          "md5": "4fd662937276c36e8ab1a5ed24a97de1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-add-secure-store-and-crypto-service-kotlin-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-add-secure-store-and-crypto-service-kotlin-tests-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-add-secure-store-and-crypto-service-kotlin-tests-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "0f5fc7684d5ed0e123bd97c3f1fea848043b3c54a25ecd42bf988c5a90393da3309caf63ae5069a6a637dfa40cf30bf557a186cb41e415295f99f818c2cd90ef",
          "sha256": "28ba73d5b19a309359b5decbbdea3e231e56d3711d9135a853e57666a6c9f92d",
          "sha1": "70225adabdbf2749fca6f7c6bec9238d2d647231",
          "md5": "4fd662937276c36e8ab1a5ed24a97de1"
        }
      ]
    }
  ]
}
