{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-ingestion",
    "version": "1.13.2-add-coverage-aggregation-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "gg6bdfi34nhqnjhmywyajp6ha4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.13.2-add-coverage-aggregation-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-ingestion-1.13.2-add-coverage-aggregation-SNAPSHOT.jar",
          "url": "sdk-ingestion-1.13.2-add-coverage-aggregation-SNAPSHOT.jar",
          "size": 18346,
          "sha512": "312ca3769e4b9edfac22fc1a647c78471d60ab34654b7b6aa02bb5359367f30551f8f8f3f2a6461c8d4490d60b696c86caa8cebb16c93e87b5655ad62a9ccb43",
          "sha256": "5b3ab37554653908cf304a1696232e716d66d554be31a17c17d7b245d8783815",
          "sha1": "a5a03ae443a672f6b9d65e3361da4028f1377988",
          "md5": "535d9a4a4d1be67c3e2fb71b65344b26"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.13.2-add-coverage-aggregation-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.13.2-add-coverage-aggregation-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.13.2-add-coverage-aggregation-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-helper-sdk-kmp",
          "module": "fhir-helper-jvm",
          "version": {
            "requires": "1.4.1"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            }
          ]
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.13.2-add-coverage-aggregation-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-ingestion-1.13.2-add-coverage-aggregation-SNAPSHOT.jar",
          "url": "sdk-ingestion-1.13.2-add-coverage-aggregation-SNAPSHOT.jar",
          "size": 18346,
          "sha512": "312ca3769e4b9edfac22fc1a647c78471d60ab34654b7b6aa02bb5359367f30551f8f8f3f2a6461c8d4490d60b696c86caa8cebb16c93e87b5655ad62a9ccb43",
          "sha256": "5b3ab37554653908cf304a1696232e716d66d554be31a17c17d7b245d8783815",
          "sha1": "a5a03ae443a672f6b9d65e3361da4028f1377988",
          "md5": "535d9a4a4d1be67c3e2fb71b65344b26"
        }
      ]
    }
  ]
}
