{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-coroutine",
    "version": "0.2.0-add-platform-only-annotation-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "76q2u4kkfncxhghh2zhheq5rqu"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-util-coroutine-metadata-0.2.0-add-platform-only-annotation-SNAPSHOT.jar",
          "url": "test-util-coroutine-0.2.0-add-platform-only-annotation-SNAPSHOT.jar",
          "size": 1777,
          "sha512": "6976b5849d2977a9e245e2b0bf3389c05c2116339e15158604fa704db9c5f548fb038dac78332c9fe71cffd7690ce76685564c2168ce32d276709e36d04a5707",
          "sha256": "34b88d776588cfefde93dca47c51abfdc7465bc9b9d5076cdfaaad73142f9c1e",
          "sha1": "356753b5e36a5f0a38eea630c62e1c6f2e7930f1",
          "md5": "b5f8a0aaa6c3de7b4ae278f585f4c3e3"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-util-coroutine-android-debug/0.2.0-add-platform-only-annotation-SNAPSHOT/test-util-coroutine-android-debug-0.2.0-add-platform-only-annotation-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-android-debug",
        "version": "0.2.0-add-platform-only-annotation-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-util-coroutine-android-debug/0.2.0-add-platform-only-annotation-SNAPSHOT/test-util-coroutine-android-debug-0.2.0-add-platform-only-annotation-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-android-debug",
        "version": "0.2.0-add-platform-only-annotation-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-util-coroutine-android/0.2.0-add-platform-only-annotation-SNAPSHOT/test-util-coroutine-android-0.2.0-add-platform-only-annotation-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-android",
        "version": "0.2.0-add-platform-only-annotation-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-util-coroutine-android/0.2.0-add-platform-only-annotation-SNAPSHOT/test-util-coroutine-android-0.2.0-add-platform-only-annotation-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-android",
        "version": "0.2.0-add-platform-only-annotation-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-util-coroutine-iosarm64/0.2.0-add-platform-only-annotation-SNAPSHOT/test-util-coroutine-iosarm64-0.2.0-add-platform-only-annotation-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-iosarm64",
        "version": "0.2.0-add-platform-only-annotation-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-util-coroutine-iosx64/0.2.0-add-platform-only-annotation-SNAPSHOT/test-util-coroutine-iosx64-0.2.0-add-platform-only-annotation-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-iosx64",
        "version": "0.2.0-add-platform-only-annotation-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-util-coroutine-jvm/0.2.0-add-platform-only-annotation-SNAPSHOT/test-util-coroutine-jvm-0.2.0-add-platform-only-annotation-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-jvm",
        "version": "0.2.0-add-platform-only-annotation-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-util-coroutine-jvm/0.2.0-add-platform-only-annotation-SNAPSHOT/test-util-coroutine-jvm-0.2.0-add-platform-only-annotation-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-coroutine-jvm",
        "version": "0.2.0-add-platform-only-annotation-SNAPSHOT"
      }
    }
  ]
}
