{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-ktor/0.2.0-change-setup-to-latest-SNAPSHOT/test-util-ktor-0.2.0-change-setup-to-latest-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-ktor",
    "version": "0.2.0-change-setup-to-latest-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "bnrxbdssnrgyzp7falhrufum44"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-util-ktor-jvm-0.2.0-change-setup-to-latest-SNAPSHOT.jar",
          "url": "test-util-ktor-jvm-0.2.0-change-setup-to-latest-SNAPSHOT.jar",
          "size": 28646,
          "sha512": "17a8137af72025c13c58f830136467df0640908616cd8657982f91fdc3d95dbe5cfe71942de1b90254990146daa7174825466111f14f755858fc9aea83589dbf",
          "sha256": "844d9254b78927dca322ceb9e4282f53fe28f9cc31bc85c9556832bf650246df",
          "sha1": "48022ca92e1c92a6f840d85d1d3c2ff4e1731dc7",
          "md5": "083dfbca91c33cf293c0a305ad3e8d1f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor-jvm-0.2.0-change-setup-to-latest-SNAPSHOT.jar",
          "url": "test-util-ktor-jvm-0.2.0-change-setup-to-latest-SNAPSHOT.jar",
          "size": 28646,
          "sha512": "17a8137af72025c13c58f830136467df0640908616cd8657982f91fdc3d95dbe5cfe71942de1b90254990146daa7174825466111f14f755858fc9aea83589dbf",
          "sha256": "844d9254b78927dca322ceb9e4282f53fe28f9cc31bc85c9556832bf650246df",
          "sha1": "48022ca92e1c92a6f840d85d1d3c2ff4e1731dc7",
          "md5": "083dfbca91c33cf293c0a305ad3e8d1f"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../test-util-ktor-metadata/0.2.0-change-setup-to-latest-SNAPSHOT/test-util-ktor-metadata-0.2.0-change-setup-to-latest-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-ktor-metadata",
        "version": "0.2.0-change-setup-to-latest-SNAPSHOT"
      }
    }
  ]
}
