{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-ktor/0.2.0-change-setup-to-latest-SNAPSHOT/test-util-ktor-0.2.0-change-setup-to-latest-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-ktor",
    "version": "0.2.0-change-setup-to-latest-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "wwokqajjqncw3ieutfoohxxpma"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-util-ktor-jvm-0.2.0-change-setup-to-latest-SNAPSHOT.jar",
          "url": "test-util-ktor-jvm-0.2.0-change-setup-to-latest-SNAPSHOT.jar",
          "size": 28646,
          "sha512": "326a0954630facfce99ca81485ba9aae885acc7fd192e8db0476277d75bab0d924f84242c1fd1a62075d1f11efc4c3c49ca4f78952997bdb6e44f7a8fd34ba49",
          "sha256": "e2239e6cfccc83ca0aedaa36af98d5d9ceeda57898363bb2cc7511c30cffa4a4",
          "sha1": "88caaf71f60951ccb57caa540af14bea4fcbbe27",
          "md5": "9c35360e1d810473e08204141d2d2517"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor-jvm-0.2.0-change-setup-to-latest-SNAPSHOT.jar",
          "url": "test-util-ktor-jvm-0.2.0-change-setup-to-latest-SNAPSHOT.jar",
          "size": 28646,
          "sha512": "326a0954630facfce99ca81485ba9aae885acc7fd192e8db0476277d75bab0d924f84242c1fd1a62075d1f11efc4c3c49ca4f78952997bdb6e44f7a8fd34ba49",
          "sha256": "e2239e6cfccc83ca0aedaa36af98d5d9ceeda57898363bb2cc7511c30cffa4a4",
          "sha1": "88caaf71f60951ccb57caa540af14bea4fcbbe27",
          "md5": "9c35360e1d810473e08204141d2d2517"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../test-util-ktor-metadata/0.2.0-change-setup-to-latest-SNAPSHOT/test-util-ktor-metadata-0.2.0-change-setup-to-latest-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-ktor-metadata",
        "version": "0.2.0-change-setup-to-latest-SNAPSHOT"
      }
    }
  ]
}
