{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.13.2-add-coverage-aggregation-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "gg6bdfi34nhqnjhmywyajp6ha4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.13.2-add-coverage-aggregation-SNAPSHOT.jar",
          "url": "auth-common-1.13.2-add-coverage-aggregation-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "95b7f3a16dd656440ea72a77a00381f6deb3e645e29243c166ec215dd8973855357fa1c62e0d912da8ef270f9a1cde6b78f518b250da2f116993360e019800f6",
          "sha256": "7192847cc86f8f0861e31700923481bc6c6c772d04214e514e17e1b73c327910",
          "sha1": "2fb9fda800d70a4d6b23462740d7a8d238106640",
          "md5": "75325442993ff4be2f8e85241d463c5b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.2-add-coverage-aggregation-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.13.2-add-coverage-aggregation-SNAPSHOT.jar",
          "url": "auth-common-1.13.2-add-coverage-aggregation-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "95b7f3a16dd656440ea72a77a00381f6deb3e645e29243c166ec215dd8973855357fa1c62e0d912da8ef270f9a1cde6b78f518b250da2f116993360e019800f6",
          "sha256": "7192847cc86f8f0861e31700923481bc6c6c772d04214e514e17e1b73c327910",
          "sha1": "2fb9fda800d70a4d6b23462740d7a8d238106640",
          "md5": "75325442993ff4be2f8e85241d463c5b"
        }
      ]
    }
  ]
}
