{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.3-add-consent-document-title-SNAPSHOT/data-donation-sdk-iosx64-0.1.3-add-consent-document-title-SNAPSHOT.module",
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.3-add-consent-document-title-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "rhstq27xsjbntbuozh3wphsyra"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.3-add-consent-document-title-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.3-add-consent-document-title-SNAPSHOT.jar",
          "size": 48136,
          "sha512": "fbee203aaafd532e541520a2cdbfb8f205e9373bdf0f5edc7a8d12c650f0437538fffc1955644d225dbf2d85d96b37b22f5288cc648a1a5c0426e0f110ac5875",
          "sha256": "34b7780e6c8f096d57d98c57c68721c7aa615ea52b03edf15caa5715a1c403ba",
          "sha1": "eec6731cf46ed1ed496b93d3de9661856bbdfb20",
          "md5": "91b47e0bcb15a6b42c185a2700d8f9cd"
        }
      ]
    }
  ]
}
