{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.3-add-consent-document-title-SNAPSHOT/data-donation-sdk-iosx64-0.1.3-add-consent-document-title-SNAPSHOT.module",
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.3-add-consent-document-title-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "aqresjwbbjgejppdqsqqcplfmu"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.3-add-consent-document-title-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.3-add-consent-document-title-SNAPSHOT.jar",
          "size": 49580,
          "sha512": "5407074f176567067cd1e35cb1cc6e42ad02d9fd947822430b6544bdec6c1be9cef30aa36ff7004dbdb9d73a32d539258fb8b35d7a78db0a5a684b6dda9da6bd",
          "sha256": "38562d14445b7f419b4129af38007dfe31a20a562e2aa1bc980316425bc42ad7",
          "sha1": "3b2da0257b7d161456fdd77daaf511218c157b20",
          "md5": "0a111aaa4c3ab3e2f838281f30ccd7ad"
        }
      ]
    }
  ]
}
