{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-ktor-test/1.8.1-change-util-test-ktor-SNAPSHOT/util-ktor-test-1.8.1-change-util-test-ktor-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-ktor-test",
    "version": "1.8.1-change-util-test-ktor-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "6q75cs4rtjbsbh5sq5c2aiw2mq"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "util-ktor-test-debug.aar",
          "url": "util-ktor-test-android-debug-1.8.1-change-util-test-ktor-SNAPSHOT.aar",
          "size": 25605,
          "sha512": "6da24448c882934e8f6efa1311d507af9666cd162fbc740fa50fb41050b9177e9f8be14097e7e05cff89b8e8e9b3f3c2072ba15e057d7cb50a02cf555a7e848a",
          "sha256": "56305ebf5327b78907e41a997189b174295abdf840726fa9d37a1dddf4fef8c1",
          "sha1": "2718327202082fbc1054aebcdbce3af1d130255d",
          "md5": "45e81d5f1175e2091618498211b3294b"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "util-ktor-test-debug.aar",
          "url": "util-ktor-test-android-debug-1.8.1-change-util-test-ktor-SNAPSHOT.aar",
          "size": 25605,
          "sha512": "6da24448c882934e8f6efa1311d507af9666cd162fbc740fa50fb41050b9177e9f8be14097e7e05cff89b8e8e9b3f3c2072ba15e057d7cb50a02cf555a7e848a",
          "sha256": "56305ebf5327b78907e41a997189b174295abdf840726fa9d37a1dddf4fef8c1",
          "sha1": "2718327202082fbc1054aebcdbce3af1d130255d",
          "md5": "45e81d5f1175e2091618498211b3294b"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-ktor-test-metadata/1.8.1-change-util-test-ktor-SNAPSHOT/util-ktor-test-metadata-1.8.1-change-util-test-ktor-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-ktor-test-metadata",
        "version": "1.8.1-change-util-test-ktor-SNAPSHOT"
      }
    }
  ]
}
