{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-test/1.8.1-add-coroutine-util-SNAPSHOT/util-test-1.8.1-add-coroutine-util-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-test",
    "version": "1.8.1-add-coroutine-util-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "2f6w3ske7zabhgjecs5uee4lom"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-test-jvm-1.8.1-add-coroutine-util-SNAPSHOT.jar",
          "url": "util-test-jvm-1.8.1-add-coroutine-util-SNAPSHOT.jar",
          "size": 18190,
          "sha512": "1cb76c3cc31c4016bfc264dd93ede9381c0fad7f6cd51609e0ecfc94eb44c950a49dff864ea6b91a08f461bbb2f158a98a4d68ec9f78d2c50083ec0a376743b7",
          "sha256": "9f3f3c7465a80b78932fd264c71778284c10f3522e01fc8615c785a632961539",
          "sha1": "9cb464f1937cfd96dd6d3bd0f6733f00809bec6d",
          "md5": "b69c9dd7f94b3eff78359407a734701d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "util-test-jvm-1.8.1-add-coroutine-util-SNAPSHOT.jar",
          "url": "util-test-jvm-1.8.1-add-coroutine-util-SNAPSHOT.jar",
          "size": 18190,
          "sha512": "1cb76c3cc31c4016bfc264dd93ede9381c0fad7f6cd51609e0ecfc94eb44c950a49dff864ea6b91a08f461bbb2f158a98a4d68ec9f78d2c50083ec0a376743b7",
          "sha256": "9f3f3c7465a80b78932fd264c71778284c10f3522e01fc8615c785a632961539",
          "sha1": "9cb464f1937cfd96dd6d3bd0f6733f00809bec6d",
          "md5": "b69c9dd7f94b3eff78359407a734701d"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-test-metadata/1.8.1-add-coroutine-util-SNAPSHOT/util-test-metadata-1.8.1-add-coroutine-util-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-test-metadata",
        "version": "1.8.1-add-coroutine-util-SNAPSHOT"
      }
    }
  ]
}
