{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-test/1.8.1-add-coroutine-util-SNAPSHOT/util-test-1.8.1-add-coroutine-util-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-test",
    "version": "1.8.1-add-coroutine-util-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "3gxapi3hobc3za3qtxn6bz6taa"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-test-jvm-1.8.1-add-coroutine-util-SNAPSHOT.jar",
          "url": "util-test-jvm-1.8.1-add-coroutine-util-SNAPSHOT.jar",
          "size": 19528,
          "sha512": "f67fbe39fea151593cd62081e52c9b86784102ebc58079864b1c93149100e32ec7bb0229a67ce096d840793ec015c5ceff05c002190547d2ab0c4b9f57ae3910",
          "sha256": "25a57db083bd296c8c4ef8acd7ad0e353e601bb3e8f3b3e61f54c94dcc8f2ef0",
          "sha1": "19b9246142357c0fb5684d5722d34964859c76a8",
          "md5": "52a112c287f289abf5cc155656eff037"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "util-test-jvm-1.8.1-add-coroutine-util-SNAPSHOT.jar",
          "url": "util-test-jvm-1.8.1-add-coroutine-util-SNAPSHOT.jar",
          "size": 19528,
          "sha512": "f67fbe39fea151593cd62081e52c9b86784102ebc58079864b1c93149100e32ec7bb0229a67ce096d840793ec015c5ceff05c002190547d2ab0c4b9f57ae3910",
          "sha256": "25a57db083bd296c8c4ef8acd7ad0e353e601bb3e8f3b3e61f54c94dcc8f2ef0",
          "sha1": "19b9246142357c0fb5684d5722d34964859c76a8",
          "md5": "52a112c287f289abf5cc155656eff037"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-test-metadata/1.8.1-add-coroutine-util-SNAPSHOT/util-test-metadata-1.8.1-add-coroutine-util-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-test-metadata",
        "version": "1.8.1-add-coroutine-util-SNAPSHOT"
      }
    }
  ]
}
