{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-test/1.9.0-add-default-scope-SNAPSHOT/util-test-1.9.0-add-default-scope-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-test",
    "version": "1.9.0-add-default-scope-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "fncgrx3r7jc7zf3yari5cu3qpm"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-test-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "url": "util-test-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "size": 6558,
          "sha512": "1496ee95124bae708ab5e3cc0d220a664acc56c8ae09c97f6f469a4e38b15bd2e69e7a0f545bd947c9a2136b8d0362cf6988c00cf2284f490087a56d78cd47d3",
          "sha256": "9a3a70a058c7cf8e4eadecfdd4a4c74e18ffe4ba98c5864fa3819b26a0929b24",
          "sha1": "65521c24dee1b92a6f3537f1c20ddef0fba69d90",
          "md5": "c65d1753f5564090146ebdc7dc1776b0"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "util-test-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "url": "util-test-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "size": 6558,
          "sha512": "1496ee95124bae708ab5e3cc0d220a664acc56c8ae09c97f6f469a4e38b15bd2e69e7a0f545bd947c9a2136b8d0362cf6988c00cf2284f490087a56d78cd47d3",
          "sha256": "9a3a70a058c7cf8e4eadecfdd4a4c74e18ffe4ba98c5864fa3819b26a0929b24",
          "sha1": "65521c24dee1b92a6f3537f1c20ddef0fba69d90",
          "md5": "c65d1753f5564090146ebdc7dc1776b0"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-test-metadata/1.9.0-add-default-scope-SNAPSHOT/util-test-metadata-1.9.0-add-default-scope-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-test-metadata",
        "version": "1.9.0-add-default-scope-SNAPSHOT"
      }
    }
  ]
}
