{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-test/1.9.0-add-default-scope-SNAPSHOT/util-test-1.9.0-add-default-scope-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-test",
    "version": "1.9.0-add-default-scope-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "xenom24cxna5hikpnifc4jf6lu"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-test-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "url": "util-test-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "size": 6558,
          "sha512": "71b3eb367f428e1f20180ea3cdcdc8129ce64a3b07e5972b44798d837445ac00fcc58a2b1d06fd96f0505fe92f274aeb92a1b5bf807feccc1e283967b1092ec9",
          "sha256": "3f727cce9984af5e893524f2a447adf5d0eda5ca8a50f7ce31cbbd1dc0f5a9f5",
          "sha1": "e3285ad9ff07054ef2c95a591cad49c31e421e5e",
          "md5": "c8e05b0edf8ddcbb5817c0e3dd79a6a9"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "util-test-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "url": "util-test-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "size": 6558,
          "sha512": "71b3eb367f428e1f20180ea3cdcdc8129ce64a3b07e5972b44798d837445ac00fcc58a2b1d06fd96f0505fe92f274aeb92a1b5bf807feccc1e283967b1092ec9",
          "sha256": "3f727cce9984af5e893524f2a447adf5d0eda5ca8a50f7ce31cbbd1dc0f5a9f5",
          "sha1": "e3285ad9ff07054ef2c95a591cad49c31e421e5e",
          "md5": "c8e05b0edf8ddcbb5817c0e3dd79a6a9"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-test-metadata/1.9.0-add-default-scope-SNAPSHOT/util-test-metadata-1.9.0-add-default-scope-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-test-metadata",
        "version": "1.9.0-add-default-scope-SNAPSHOT"
      }
    }
  ]
}
