{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.11.0-add-client-factory-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ktklzn34pbfwdeknp3gip6zgia"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.11.0-add-client-factory-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-add-client-factory-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "0fc956634e371de574536c503693f9a14e71e5caee1f9248285c7437fa078df86d70a86e328003f1af2be5b425470163bbbb70cac976ee4e64f2099a5ddbedfd",
          "sha256": "8a2b97ea09a1cfffd8603bfbf37d4f137aa781f1090fa3bdcfd60ad971628f3c",
          "sha1": "827a263328f8eedea783c29baabca73c1a20b11d",
          "md5": "47f47b1a9b1baa390e65ffce8bc16cd0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.11.0-add-client-factory-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-add-client-factory-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "0fc956634e371de574536c503693f9a14e71e5caee1f9248285c7437fa078df86d70a86e328003f1af2be5b425470163bbbb70cac976ee4e64f2099a5ddbedfd",
          "sha256": "8a2b97ea09a1cfffd8603bfbf37d4f137aa781f1090fa3bdcfd60ad971628f3c",
          "sha1": "827a263328f8eedea783c29baabca73c1a20b11d",
          "md5": "47f47b1a9b1baa390e65ffce8bc16cd0"
        }
      ]
    }
  ]
}
