{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-ktor-test/1.8.1-change-util-test-ktor-SNAPSHOT/util-ktor-test-1.8.1-change-util-test-ktor-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-ktor-test",
    "version": "1.8.1-change-util-test-ktor-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "nor2jz4uybfxdlwhkbtk3rwmam"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-ktor-test-jvm-1.8.1-change-util-test-ktor-SNAPSHOT.jar",
          "url": "util-ktor-test-jvm-1.8.1-change-util-test-ktor-SNAPSHOT.jar",
          "size": 27660,
          "sha512": "85f7fd977a8da33e125946cd9d3b29b95fd2bd2142f745a2641bf0cf534a2098b58d1e439eab46399928aa1bf0238300da7c6ba2523ef65814d3468b60f9f6f8",
          "sha256": "c0a7cce7ff3114a50c9dc61e7edb5b129c17f13611370fdea6ee8868b5b6d71c",
          "sha1": "f6370b0cb7e5e36642556d10687d02e72b39057c",
          "md5": "c2ff9ee7b93fea406840ce4a65ea5b92"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "util-ktor-test-jvm-1.8.1-change-util-test-ktor-SNAPSHOT.jar",
          "url": "util-ktor-test-jvm-1.8.1-change-util-test-ktor-SNAPSHOT.jar",
          "size": 27660,
          "sha512": "85f7fd977a8da33e125946cd9d3b29b95fd2bd2142f745a2641bf0cf534a2098b58d1e439eab46399928aa1bf0238300da7c6ba2523ef65814d3468b60f9f6f8",
          "sha256": "c0a7cce7ff3114a50c9dc61e7edb5b129c17f13611370fdea6ee8868b5b6d71c",
          "sha1": "f6370b0cb7e5e36642556d10687d02e72b39057c",
          "md5": "c2ff9ee7b93fea406840ce4a65ea5b92"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-ktor-test-metadata/1.8.1-change-util-test-ktor-SNAPSHOT/util-ktor-test-metadata-1.8.1-change-util-test-ktor-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-ktor-test-metadata",
        "version": "1.8.1-change-util-test-ktor-SNAPSHOT"
      }
    }
  ]
}
