{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-ktor-test/1.8.1-change-util-test-ktor-SNAPSHOT/util-ktor-test-1.8.1-change-util-test-ktor-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-ktor-test",
    "version": "1.8.1-change-util-test-ktor-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "dksa7z23hzdlxd5ftaixfygnba"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-ktor-test-jvm-1.8.1-change-util-test-ktor-SNAPSHOT.jar",
          "url": "util-ktor-test-jvm-1.8.1-change-util-test-ktor-SNAPSHOT.jar",
          "size": 28641,
          "sha512": "347272532f0bacee00b11c202e32f944a202e7157853c52fc0efccdfa7db646cd4b7c79b8d709de0643ef89751a1142a77e92515c5739436daf350006fd9a5b0",
          "sha256": "0b46c74441407145ca518637444e7a435b3e338b4375428b95015c9f7cce31ea",
          "sha1": "8d35a2c8c767f7bfdebc22522e6b2461dcee96f1",
          "md5": "4365b45824b723cbd2851b37e3165544"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "util-ktor-test-jvm-1.8.1-change-util-test-ktor-SNAPSHOT.jar",
          "url": "util-ktor-test-jvm-1.8.1-change-util-test-ktor-SNAPSHOT.jar",
          "size": 28641,
          "sha512": "347272532f0bacee00b11c202e32f944a202e7157853c52fc0efccdfa7db646cd4b7c79b8d709de0643ef89751a1142a77e92515c5739436daf350006fd9a5b0",
          "sha256": "0b46c74441407145ca518637444e7a435b3e338b4375428b95015c9f7cce31ea",
          "sha1": "8d35a2c8c767f7bfdebc22522e6b2461dcee96f1",
          "md5": "4365b45824b723cbd2851b37e3165544"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-ktor-test-metadata/1.8.1-change-util-test-ktor-SNAPSHOT/util-ktor-test-metadata-1.8.1-change-util-test-ktor-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-ktor-test-metadata",
        "version": "1.8.1-change-util-test-ktor-SNAPSHOT"
      }
    }
  ]
}
