{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-ktor-test/1.8.1-change-util-test-ktor-SNAPSHOT/util-ktor-test-1.8.1-change-util-test-ktor-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-ktor-test",
    "version": "1.8.1-change-util-test-ktor-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "dmuj7nktljamnk4qk2vce44lka"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-ktor-test-jvm-1.8.1-change-util-test-ktor-SNAPSHOT.jar",
          "url": "util-ktor-test-jvm-1.8.1-change-util-test-ktor-SNAPSHOT.jar",
          "size": 27586,
          "sha512": "1a789ea628e8f3a96c49310a92f9131e554e9285b968bd6c9b5ee337d1d2136ddcc8e9e01652ed7d6e71a4797659612130080fdb012e2ed5299aaab3a4166a21",
          "sha256": "8790e60b33e4dd1bbe16f1865d8e239a46d29204e1cc72bc84607fb7123d1cdc",
          "sha1": "db8f418dfc7eaceabc6b5309c1353b9fef450266",
          "md5": "2e0b7ea1682aa8b89400f2c96173f739"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "util-ktor-test-jvm-1.8.1-change-util-test-ktor-SNAPSHOT.jar",
          "url": "util-ktor-test-jvm-1.8.1-change-util-test-ktor-SNAPSHOT.jar",
          "size": 27586,
          "sha512": "1a789ea628e8f3a96c49310a92f9131e554e9285b968bd6c9b5ee337d1d2136ddcc8e9e01652ed7d6e71a4797659612130080fdb012e2ed5299aaab3a4166a21",
          "sha256": "8790e60b33e4dd1bbe16f1865d8e239a46d29204e1cc72bc84607fb7123d1cdc",
          "sha1": "db8f418dfc7eaceabc6b5309c1353b9fef450266",
          "md5": "2e0b7ea1682aa8b89400f2c96173f739"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-ktor-test-metadata/1.8.1-change-util-test-ktor-SNAPSHOT/util-ktor-test-metadata-1.8.1-change-util-test-ktor-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-ktor-test-metadata",
        "version": "1.8.1-change-util-test-ktor-SNAPSHOT"
      }
    }
  ]
}
