{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.13.1-change-attachment-service-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "zaek2pfilvcjla4x434qhxwmei"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.13.1-change-attachment-service-SNAPSHOT.jar",
          "url": "securestore-common-1.13.1-change-attachment-service-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "f4357985867e4a98bf81dc3f60f85c9793e5e9ddc3ffe261d37671f1a255cb03ebb21fa86fdf64a1d4df1f8c305ff23523fca13c5bede250e78140e2e2b51e80",
          "sha256": "6fe0f9b8f1f293cdfc17cea1856eee07e28d950bb4122359f4cb8267c160c5b8",
          "sha1": "df6fd09225c85cb5617ddb21cdc5c950835c1fc9",
          "md5": "923e5f522c3f92b29284019f6f8c264e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.13.1-change-attachment-service-SNAPSHOT.jar",
          "url": "securestore-common-1.13.1-change-attachment-service-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "f4357985867e4a98bf81dc3f60f85c9793e5e9ddc3ffe261d37671f1a255cb03ebb21fa86fdf64a1d4df1f8c305ff23523fca13c5bede250e78140e2e2b51e80",
          "sha256": "6fe0f9b8f1f293cdfc17cea1856eee07e28d950bb4122359f4cb8267c160c5b8",
          "sha1": "df6fd09225c85cb5617ddb21cdc5c950835c1fc9",
          "md5": "923e5f522c3f92b29284019f6f8c264e"
        }
      ]
    }
  ]
}
