{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-coroutine/0.2.0-bump-updates-SNAPSHOT/test-util-coroutine-0.2.0-bump-updates-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-coroutine",
    "version": "0.2.0-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-util-coroutine-jvm-0.2.0-bump-updates-SNAPSHOT.jar",
          "url": "test-util-coroutine-jvm-0.2.0-bump-updates-SNAPSHOT.jar",
          "size": 6089,
          "sha512": "6f6c7316bfa35818998ca9c37c782e0403cb7b75ddded1b92b4db3b3a82b3729a8afc74ce0d5230a3e53534004f5a76542b48c9360e3a6cecb429c5a3072ca31",
          "sha256": "e0500bad009e757af17d468fe8337adff66ade55b16743e280af8f47096409d8",
          "sha1": "22f756212042a61fb87e4022299eea8cf58c18da",
          "md5": "2642bab650abfdcc7f3b3a2da3eac16e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-coroutine-jvm-0.2.0-bump-updates-SNAPSHOT.jar",
          "url": "test-util-coroutine-jvm-0.2.0-bump-updates-SNAPSHOT.jar",
          "size": 6089,
          "sha512": "6f6c7316bfa35818998ca9c37c782e0403cb7b75ddded1b92b4db3b3a82b3729a8afc74ce0d5230a3e53534004f5a76542b48c9360e3a6cecb429c5a3072ca31",
          "sha256": "e0500bad009e757af17d468fe8337adff66ade55b16743e280af8f47096409d8",
          "sha1": "22f756212042a61fb87e4022299eea8cf58c18da",
          "md5": "2642bab650abfdcc7f3b3a2da3eac16e"
        }
      ]
    }
  ]
}
