{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.11.0-change-naming-crypto-convention-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "zcotc3iso5cpfcw4ylcifjqxhy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-change-naming-crypto-convention-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.11.0-change-naming-crypto-convention-SNAPSHOT.jar",
          "url": "auth-jvm-1.11.0-change-naming-crypto-convention-SNAPSHOT.jar",
          "size": 34283,
          "sha512": "3695d39186ea24497527fb0140f7b0872c0f0b0891e8ecbfdcf628885e16a78cd1b867237231da765891c10e86f095915c47c94e502f941ae0534ea92e5e77f4",
          "sha256": "2fce44869469fe02d53a643638c5665791832262fcd174980c849172018a9119",
          "sha1": "6c680f24c3d3edc327c4d35797add3667bd23882",
          "md5": "770a3d1228bc9d1860afdf5120f86645"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.11.0-change-naming-crypto-convention-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-change-naming-crypto-convention-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.11.0-change-naming-crypto-convention-SNAPSHOT.jar",
          "url": "auth-jvm-1.11.0-change-naming-crypto-convention-SNAPSHOT.jar",
          "size": 34283,
          "sha512": "3695d39186ea24497527fb0140f7b0872c0f0b0891e8ecbfdcf628885e16a78cd1b867237231da765891c10e86f095915c47c94e502f941ae0534ea92e5e77f4",
          "sha256": "2fce44869469fe02d53a643638c5665791832262fcd174980c849172018a9119",
          "sha1": "6c680f24c3d3edc327c4d35797add3667bd23882",
          "md5": "770a3d1228bc9d1860afdf5120f86645"
        }
      ]
    }
  ]
}
