{
  "formatVersion": "1.1",
  "component": {
    "url": "../../securestore/1.13.2-change-to-latest-project-setup-SNAPSHOT/securestore-1.13.2-change-to-latest-project-setup-SNAPSHOT.module",
    "group": "care.data4life.hc-securestore-sdk-kmp",
    "module": "securestore",
    "version": "1.13.2-change-to-latest-project-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "4u4xgl6j65brtany72szlykyx4"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "securestore-jvm-1.13.2-change-to-latest-project-setup-SNAPSHOT.jar",
          "url": "securestore-jvm-1.13.2-change-to-latest-project-setup-SNAPSHOT.jar",
          "size": 16739,
          "sha512": "558bbcb1add7032f702c3d3141a89f1e9be671a727c6c6acd6262d377cc139c3b4d0e32f19c178ff9f4121d845983c64506e06be6f0f3a3502869c871a51fc30",
          "sha256": "a99e6f3fd7031ac1154b7dc1a11bf34df70d230a675d07fa5e6b3e370b45b7f5",
          "sha1": "63ebfc42b890cc2f63c2ecea79443c6540d152db",
          "md5": "83e6363a12d798d2a05745d212793017"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.13.2-change-to-latest-project-setup-SNAPSHOT.jar",
          "url": "securestore-jvm-1.13.2-change-to-latest-project-setup-SNAPSHOT.jar",
          "size": 16739,
          "sha512": "558bbcb1add7032f702c3d3141a89f1e9be671a727c6c6acd6262d377cc139c3b4d0e32f19c178ff9f4121d845983c64506e06be6f0f3a3502869c871a51fc30",
          "sha256": "a99e6f3fd7031ac1154b7dc1a11bf34df70d230a675d07fa5e6b3e370b45b7f5",
          "sha1": "63ebfc42b890cc2f63c2ecea79443c6540d152db",
          "md5": "83e6363a12d798d2a05745d212793017"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../securestore-metadata/1.13.2-change-to-latest-project-setup-SNAPSHOT/securestore-metadata-1.13.2-change-to-latest-project-setup-SNAPSHOT.module",
        "group": "care.data4life.hc-securestore-sdk-kmp",
        "module": "securestore-metadata",
        "version": "1.13.2-change-to-latest-project-setup-SNAPSHOT"
      }
    }
  ]
}
