{
  "formatVersion": "1.1",
  "component": {
    "url": "../../crypto/1.13.2-fix-project-dependency-to-util-sdk-SNAPSHOT/crypto-1.13.2-fix-project-dependency-to-util-sdk-SNAPSHOT.module",
    "group": "care.data4life.hc-crypto-sdk-kmp",
    "module": "crypto",
    "version": "1.13.2-fix-project-dependency-to-util-sdk-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "paqddhk5ljglli2s3axmpqypge"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "crypto-jvm-1.13.2-fix-project-dependency-to-util-sdk-SNAPSHOT.jar",
          "url": "crypto-jvm-1.13.2-fix-project-dependency-to-util-sdk-SNAPSHOT.jar",
          "size": 58308,
          "sha512": "c5fbcb06caca68dc360f3601e88c21017785f557a2de7daa2bc0fda9ac1690c69b7b8abaee4260d1c2b95c6bc59f45ebe31b772ab81dc93880cbb72aa2fe6cdd",
          "sha256": "82675461c3fc83e3761aa8606ef4b48ce01f3e8f10cf6561de95bb9d78a6df9c",
          "sha1": "9e7b845233b939c9baaa878c25134c93dc7c7c50",
          "md5": "254d454527b3dd6444897757cb24647e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.13.2-fix-project-dependency-to-util-sdk-SNAPSHOT.jar",
          "url": "crypto-jvm-1.13.2-fix-project-dependency-to-util-sdk-SNAPSHOT.jar",
          "size": 58308,
          "sha512": "c5fbcb06caca68dc360f3601e88c21017785f557a2de7daa2bc0fda9ac1690c69b7b8abaee4260d1c2b95c6bc59f45ebe31b772ab81dc93880cbb72aa2fe6cdd",
          "sha256": "82675461c3fc83e3761aa8606ef4b48ce01f3e8f10cf6561de95bb9d78a6df9c",
          "sha1": "9e7b845233b939c9baaa878c25134c93dc7c7c50",
          "md5": "254d454527b3dd6444897757cb24647e"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../crypto-metadata/1.13.2-fix-project-dependency-to-util-sdk-SNAPSHOT/crypto-metadata-1.13.2-fix-project-dependency-to-util-sdk-SNAPSHOT.module",
        "group": "care.data4life.hc-crypto-sdk-kmp",
        "module": "crypto-metadata",
        "version": "1.13.2-fix-project-dependency-to-util-sdk-SNAPSHOT"
      }
    }
  ]
}
