{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "sd5ljhqyjvhzhpwbh2nuxip3hu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.12.0-SNAPSHOT.jar",
          "url": "auth-jvm-1.12.0-SNAPSHOT.jar",
          "size": 34318,
          "sha512": "97d3286e3c373fd34ec96fe019701a8840b3a73436607d21c264d9ad6d4f291d756f1a6cf8e11c0c9ed906044cf3834c546456e5cf660dc110fce7aa74d41544",
          "sha256": "199a88bf16109e58f2da52612bb95bb22d8fccd80cf45c6445bf161a7e72876f",
          "sha1": "9e0d62c05d6c00c689e5a07b4bc6307688b21799",
          "md5": "a3324bb08b67a0dedff61a4182fe1654"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.12.0-SNAPSHOT.jar",
          "url": "auth-jvm-1.12.0-SNAPSHOT.jar",
          "size": 34318,
          "sha512": "97d3286e3c373fd34ec96fe019701a8840b3a73436607d21c264d9ad6d4f291d756f1a6cf8e11c0c9ed906044cf3834c546456e5cf660dc110fce7aa74d41544",
          "sha256": "199a88bf16109e58f2da52612bb95bb22d8fccd80cf45c6445bf161a7e72876f",
          "sha1": "9e0d62c05d6c00c689e5a07b4bc6307688b21799",
          "md5": "a3324bb08b67a0dedff61a4182fe1654"
        }
      ]
    }
  ]
}
