{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.11.0-change-ihc-service-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ay3rdd2vo5blzp5hhzxvy676cu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-change-ihc-service-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.11.0-change-ihc-service-SNAPSHOT.jar",
          "url": "securestore-jvm-1.11.0-change-ihc-service-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "e1d7a5fc3947a60ded98a84e53c8af91de62b88ee18a606080a97011d477cf836e8a5b9f88cc530ffad7a0de0d688fbe7fab5b32473f1a8ef095a6beadeb5fa2",
          "sha256": "caf4ac8f1243602b95429caa801b9ecb61c5f37ef5419435dac8f68f1f796d7a",
          "sha1": "ad8aa91927c2c13cb94a95655081119aedebafe8",
          "md5": "bc5953e60ff3bc5a7f0f580e20111903"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-change-ihc-service-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.11.0-change-ihc-service-SNAPSHOT.jar",
          "url": "securestore-jvm-1.11.0-change-ihc-service-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "e1d7a5fc3947a60ded98a84e53c8af91de62b88ee18a606080a97011d477cf836e8a5b9f88cc530ffad7a0de0d688fbe7fab5b32473f1a8ef095a6beadeb5fa2",
          "sha256": "caf4ac8f1243602b95429caa801b9ecb61c5f37ef5419435dac8f68f1f796d7a",
          "sha1": "ad8aa91927c2c13cb94a95655081119aedebafe8",
          "md5": "bc5953e60ff3bc5a7f0f580e20111903"
        }
      ]
    }
  ]
}
