{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.11.0-change-ihc-service-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "zakliq67cnabnibqsbgpkai6tm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-change-ihc-service-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.11.0-change-ihc-service-SNAPSHOT.jar",
          "url": "securestore-jvm-1.11.0-change-ihc-service-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "02c579b2f0ca1c8f90122cd2b239614fe850779c13590af5e3b1761433f8527ed1330fd71d1025f5947ea7d2acadbba5c7f74e72d57888118ba79540d4fb5b05",
          "sha256": "1d4a8d73d2b406d93889e342ad500d4dd917e8554c12d1f26f788c1d436d9709",
          "sha1": "fc7c390e88490a7f111d2c22d7e053d1c588a5ea",
          "md5": "b4eab36ad0a76fe84eb3bb7c1af01351"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-change-ihc-service-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.11.0-change-ihc-service-SNAPSHOT.jar",
          "url": "securestore-jvm-1.11.0-change-ihc-service-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "02c579b2f0ca1c8f90122cd2b239614fe850779c13590af5e3b1761433f8527ed1330fd71d1025f5947ea7d2acadbba5c7f74e72d57888118ba79540d4fb5b05",
          "sha256": "1d4a8d73d2b406d93889e342ad500d4dd917e8554c12d1f26f788c1d436d9709",
          "sha1": "fc7c390e88490a7f111d2c22d7e053d1c588a5ea",
          "md5": "b4eab36ad0a76fe84eb3bb7c1af01351"
        }
      ]
    }
  ]
}
