{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-ktor/0.2.0-change-to-seflcontained-SNAPSHOT/test-util-ktor-0.2.0-change-to-seflcontained-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-ktor",
    "version": "0.2.0-change-to-seflcontained-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "256glaxuurcclofuqjzn2stkga"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-util-ktor-jvm-0.2.0-change-to-seflcontained-SNAPSHOT.jar",
          "url": "test-util-ktor-jvm-0.2.0-change-to-seflcontained-SNAPSHOT.jar",
          "size": 28646,
          "sha512": "78d7ba007884c2ec36a648d40473558e5e0c0a7453eebb77085b833d66ef5a3ca3215a619bc678e62bb6bd141596f520d296cf9c94ff32f934fe30846d53e8a8",
          "sha256": "f753ad269d6378b18853706669c677aebeb45d73bbc9fe8d62d0e22f62e2ce83",
          "sha1": "9a5f4425ddc70a62f51b245f75434483153a4a5d",
          "md5": "644bb8b7e778d1a090d759af8ddc9f65"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor-jvm-0.2.0-change-to-seflcontained-SNAPSHOT.jar",
          "url": "test-util-ktor-jvm-0.2.0-change-to-seflcontained-SNAPSHOT.jar",
          "size": 28646,
          "sha512": "78d7ba007884c2ec36a648d40473558e5e0c0a7453eebb77085b833d66ef5a3ca3215a619bc678e62bb6bd141596f520d296cf9c94ff32f934fe30846d53e8a8",
          "sha256": "f753ad269d6378b18853706669c677aebeb45d73bbc9fe8d62d0e22f62e2ce83",
          "sha1": "9a5f4425ddc70a62f51b245f75434483153a4a5d",
          "md5": "644bb8b7e778d1a090d759af8ddc9f65"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../test-util-ktor-metadata/0.2.0-change-to-seflcontained-SNAPSHOT/test-util-ktor-metadata-0.2.0-change-to-seflcontained-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-ktor-metadata",
        "version": "0.2.0-change-to-seflcontained-SNAPSHOT"
      }
    }
  ]
}
