{
  "formatVersion": "1.1",
  "component": {
    "url": "../../example-kmp-library-jvm/0.0.1-bump-dependencies-SNAPSHOT/example-kmp-library-jvm-0.0.1-bump-dependencies-SNAPSHOT.module",
    "group": "care.data4life.hc-gradle-scripts",
    "module": "example-kmp-library-jvm",
    "version": "0.0.1-bump-dependencies-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "ptwhxi6lkfar5eopijovduvtee"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "example-kmp-library-metadata-0.0.1-bump-dependencies-SNAPSHOT.jar",
          "url": "example-kmp-library-metadata-0.0.1-bump-dependencies-SNAPSHOT.jar",
          "size": 5810,
          "sha512": "696fe331e2a8129d2e8b3d0a0d207cc693329eec8d432ccc6cdd7aee14df8ddfdca4ef04b1ac0b55d89be525720ac93e9cfde41c837f4d7a750a971194681c4f",
          "sha256": "063616b8a02a371df8d421606358b68ce12a2963f074fa06152a91951626f254",
          "sha1": "1c5cd6316d8a0081838dee1591985787ad563ad7",
          "md5": "4e28d1770a057b98cd086eaa52310718"
        }
      ]
    }
  ]
}
