{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.13.2-bump-util-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "kkd3tvfm2vegbemclgxo2eqsce"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.13.2-bump-util-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.13.2-bump-util-SNAPSHOT.jar",
          "url": "auth-jvm-1.13.2-bump-util-SNAPSHOT.jar",
          "size": 34319,
          "sha512": "f4459790322f776d8dc9dd15869967ef4d77419ef941b4226bbc98c3ad3c27d2fc6593e1789e97c84d36ea6f9cc9bb3d723a4505b6dd30bfbb8ac9b82a1358e3",
          "sha256": "7b621717826fc895ce2aa8289b2eb15fbf8000cfbefbd31c7327db6379a04278",
          "sha1": "9bfd0200c1ce847834578fd4815c1d3b9cbdaaae",
          "md5": "19be39e642c95ab1b8e500d3da4b4995"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.13.2-bump-util-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.13.2-bump-util-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.13.2-bump-util-SNAPSHOT.jar",
          "url": "auth-jvm-1.13.2-bump-util-SNAPSHOT.jar",
          "size": 34319,
          "sha512": "f4459790322f776d8dc9dd15869967ef4d77419ef941b4226bbc98c3ad3c27d2fc6593e1789e97c84d36ea6f9cc9bb3d723a4505b6dd30bfbb8ac9b82a1358e3",
          "sha256": "7b621717826fc895ce2aa8289b2eb15fbf8000cfbefbd31c7327db6379a04278",
          "sha1": "9bfd0200c1ce847834578fd4815c1d3b9cbdaaae",
          "md5": "19be39e642c95ab1b8e500d3da4b4995"
        }
      ]
    }
  ]
}
