{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.13.2-bump-util-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "xmyruergafad7iumov7cthehqi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.13.2-bump-util-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.13.2-bump-util-SNAPSHOT.jar",
          "url": "auth-jvm-1.13.2-bump-util-SNAPSHOT.jar",
          "size": 34319,
          "sha512": "479ba0e1e076b6a57e9c86b1196ff6862b20fd6989518040d35d2c8cff5a316b696a1dbee2d8ec3db8db0723049ee7df72572670f10f2e0c6a56c637c20a0fe7",
          "sha256": "90ee0e0754c6a967524dde619106841bf5b39aa724c9877025e1b45ba9b88315",
          "sha1": "fddca8f18c25a27fceb7e287b06dfed263c31555",
          "md5": "adb91a694423b4d1a6a8cd8c82c1d8ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.13.2-bump-util-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.8.1-bump-android-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.13.2-bump-util-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.13.2-bump-util-SNAPSHOT.jar",
          "url": "auth-jvm-1.13.2-bump-util-SNAPSHOT.jar",
          "size": 34319,
          "sha512": "479ba0e1e076b6a57e9c86b1196ff6862b20fd6989518040d35d2c8cff5a316b696a1dbee2d8ec3db8db0723049ee7df72572670f10f2e0c6a56c637c20a0fe7",
          "sha256": "90ee0e0754c6a967524dde619106841bf5b39aa724c9877025e1b45ba9b88315",
          "sha1": "fddca8f18c25a27fceb7e287b06dfed263c31555",
          "md5": "adb91a694423b4d1a6a8cd8c82c1d8ab"
        }
      ]
    }
  ]
}
