{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-fhir-sdk-java",
    "module": "fhir-java",
    "version": "1.8.0-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fhir-java-1.8.0-bump-updates-SNAPSHOT.jar",
          "url": "fhir-java-1.8.0-bump-updates-SNAPSHOT.jar",
          "size": 1012051,
          "sha512": "fd4713ec10663a8d7aac46f6c308c6f84f12674d3e61ff6785c9f92198d1d1556df680d34257c89238e7df1196df103aedc094760d335cfdbc00ae12d0ef8d76",
          "sha256": "fa708fd4cad306e8fe96000068c90dbfc9f16f1140c65bcd78d0fe732f58b9b9",
          "sha1": "ecf52429af55401e81279efec1c4cec5b724c9b1",
          "md5": "6d6801f106a0ad567c28f39a7af7ca04"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-java-1.8.0-bump-updates-SNAPSHOT.jar",
          "url": "fhir-java-1.8.0-bump-updates-SNAPSHOT.jar",
          "size": 1012051,
          "sha512": "fd4713ec10663a8d7aac46f6c308c6f84f12674d3e61ff6785c9f92198d1d1556df680d34257c89238e7df1196df103aedc094760d335cfdbc00ae12d0ef8d76",
          "sha256": "fa708fd4cad306e8fe96000068c90dbfc9f16f1140c65bcd78d0fe732f58b9b9",
          "sha1": "ecf52429af55401e81279efec1c4cec5b724c9b1",
          "md5": "6d6801f106a0ad567c28f39a7af7ca04"
        }
      ]
    }
  ]
}
