{
  "formatVersion": "1.1",
  "component": {
    "url": "../../example-kmp-library-jvm/0.0.1-add-coverage-scripts-SNAPSHOT/example-kmp-library-jvm-0.0.1-add-coverage-scripts-SNAPSHOT.module",
    "group": "care.data4life.hc-gradle-scripts",
    "module": "example-kmp-library-jvm",
    "version": "0.0.1-add-coverage-scripts-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ul3lcnxngzcrbon5g3vr4jwbie"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "example-kmp-library-metadata-0.0.1-add-coverage-scripts-SNAPSHOT.jar",
          "url": "example-kmp-library-metadata-0.0.1-add-coverage-scripts-SNAPSHOT.jar",
          "size": 5810,
          "sha512": "5eedf0701cbfaf639829b53251edfa2335636cabedce1e6f30563ecade03aee23955301a3a2cfb35e03c82657686ff5648ed1f2322b3aa8c3202225891981084",
          "sha256": "6ad6c0c13ca946ace154d75d6c6afda7fd5f3d27a278c9bbe92c197f4dfd602f",
          "sha1": "593c88d5db99e366c73d21ce0703d9207c6e950a",
          "md5": "193137013283af04e472265721e5a7a9"
        }
      ]
    }
  ]
}
