{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.11.0-change-client-version-header-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "cssre7lvf5ac3izegv3ikffu3a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-change-client-version-header-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.11.0-change-client-version-header-SNAPSHOT.jar",
          "url": "crypto-jvm-1.11.0-change-client-version-header-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "7e411e631fd20db5ecc6c0f29c1f4fa5bfc01c6f76071f11312b070d6e9a4ff9d94b599107a096c73e31636514eddfece3e68f1682bdfe55f18f8ce7ef096f91",
          "sha256": "f78bb1509f96d6e419af997264f1dd57469e2fa4c03b9e53e6d01f8fcd45ff40",
          "sha1": "607ec68eb158fe3cd7dc30c4a00d6a7c3dcddfb8",
          "md5": "82ccdb6fb87beb1ed6230b9b04793ffd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-change-client-version-header-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.11.0-change-client-version-header-SNAPSHOT.jar",
          "url": "crypto-jvm-1.11.0-change-client-version-header-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "7e411e631fd20db5ecc6c0f29c1f4fa5bfc01c6f76071f11312b070d6e9a4ff9d94b599107a096c73e31636514eddfece3e68f1682bdfe55f18f8ce7ef096f91",
          "sha256": "f78bb1509f96d6e419af997264f1dd57469e2fa4c03b9e53e6d01f8fcd45ff40",
          "sha1": "607ec68eb158fe3cd7dc30c4a00d6a7c3dcddfb8",
          "md5": "82ccdb6fb87beb1ed6230b9b04793ffd"
        }
      ]
    }
  ]
}
