{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.13.2-add-alessio-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "oj7wsp7tpbeorhl4yd76ewwiiq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.13.2-add-alessio-SNAPSHOT.jar",
          "url": "auth-common-1.13.2-add-alessio-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "70c4d6e7aa53c251f10b8c7f049c8f5090af60bc87f3b130cc151a45ddf2d674be6dfb3013849ad6deb47f4a672f723bbe2ef42472de6742f7dd4acf3b7585f7",
          "sha256": "cebad1992d0a50ced6f6b9685a7b054ca4c67c3d8386be670bf953e2f3963c10",
          "sha1": "bed2794391442d63d416b316054698de261565d5",
          "md5": "8deaf0831ce2999f849c90bcaaeea1fa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.2-add-alessio-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.13.2-add-alessio-SNAPSHOT.jar",
          "url": "auth-common-1.13.2-add-alessio-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "70c4d6e7aa53c251f10b8c7f049c8f5090af60bc87f3b130cc151a45ddf2d674be6dfb3013849ad6deb47f4a672f723bbe2ef42472de6742f7dd4acf3b7585f7",
          "sha256": "cebad1992d0a50ced6f6b9685a7b054ca4c67c3d8386be670bf953e2f3963c10",
          "sha1": "bed2794391442d63d416b316054698de261565d5",
          "md5": "8deaf0831ce2999f849c90bcaaeea1fa"
        }
      ]
    }
  ]
}
