{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-ingestion",
    "version": "1.17.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.17.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            },
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-ingestion-1.17.0-SNAPSHOT.jar",
          "url": "sdk-ingestion-1.17.0-SNAPSHOT.jar",
          "size": 19820,
          "sha512": "dfac0bd4d764ab7872a87177ea34401bca59d28a1cc8756427328633f94f3b9674f801d11aa03be0f80b9817ed961ab2dd989fd83c6b7f38627bb0adbbb51187",
          "sha256": "969a558f8cbc48bfe6bb90ff0393403dbb049e930cfca9c3d4820900021ab4f2",
          "sha1": "e0f9c270cd192a5fd9c652129292cd0149ec7c70",
          "md5": "aca3e164ec2c57d91c44a7da6caa85f0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "care.data4life.hc-auth-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.17.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "care.data4life.hc-crypto-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.16.1"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "care.data4life.hc-securestore-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.16.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.14.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "error-jvm",
          "version": {
            "requires": "1.14.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "care.data4life.hc-fhir-helper-sdk-kmp",
          "module": "fhir-helper-jvm",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            }
          ]
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.9.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.13.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.17.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            },
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-ingestion-1.17.0-SNAPSHOT.jar",
          "url": "sdk-ingestion-1.17.0-SNAPSHOT.jar",
          "size": 19820,
          "sha512": "dfac0bd4d764ab7872a87177ea34401bca59d28a1cc8756427328633f94f3b9674f801d11aa03be0f80b9817ed961ab2dd989fd83c6b7f38627bb0adbbb51187",
          "sha256": "969a558f8cbc48bfe6bb90ff0393403dbb049e930cfca9c3d4820900021ab4f2",
          "sha1": "e0f9c270cd192a5fd9c652129292cd0149ec7c70",
          "md5": "aca3e164ec2c57d91c44a7da6caa85f0"
        }
      ]
    }
  ]
}
