{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk/0.1.3-add-credential-retrieval-SNAPSHOT/data-donation-sdk-0.1.3-add-credential-retrieval-SNAPSHOT.module",
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk",
    "version": "0.1.3-add-credential-retrieval-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "5s3wlis2srf6tggzs3qqswkapm"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.6"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.1.6-a1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "1.1.6"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-kmp",
          "module": "fhir",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "care.data4life.hc-result-sdk-kmp",
          "module": "flow",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "care.data4life.hc-result-sdk-kmp",
          "module": "error",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "care.data4life.hc-coroutine-util-sdk-kmp",
          "module": "coroutine-util",
          "version": {
            "requires": "0.1.0"
          },
          "excludes": [
            {
              "group": "co.touchlab:stately-concurrency",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.4.3-native-mt",
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-ios",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "care.data4life.hc-objc-util-sdk-kmp",
          "module": "objc-util",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "data-donation-sdk.klib",
          "url": "data-donation-sdk-iosarm64-0.1.3-add-credential-retrieval-SNAPSHOT.klib",
          "size": 207034,
          "sha512": "e93400513b193908156ee6680029c4ade82d95d7844a7bc6cdcabb821362cc1979b290638b9008bde486dec27be7d2fe289401c15aa4ddee50ee5dd6b0f90e67",
          "sha256": "f4ff2faddd0377e1ebb7ac934301916862183db2136a545b185279c3d60b2b32",
          "sha1": "a51ea5474422da4e8b218565fbbea446727da00d",
          "md5": "740019c2e59e79e0b6cef60290f21cd2"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../data-donation-sdk-metadata/0.1.3-add-credential-retrieval-SNAPSHOT/data-donation-sdk-metadata-0.1.3-add-credential-retrieval-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-metadata",
        "version": "0.1.3-add-credential-retrieval-SNAPSHOT"
      }
    }
  ]
}
