{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-coroutine-jvm/1.9.0-add-default-scope-SNAPSHOT/util-coroutine-jvm-1.9.0-add-default-scope-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-coroutine-jvm",
    "version": "1.9.0-add-default-scope-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "s7ddhadks5hybjbsj72jm4rgnm"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-coroutine-metadata-1.9.0-add-default-scope-SNAPSHOT.jar",
          "url": "util-coroutine-metadata-1.9.0-add-default-scope-SNAPSHOT.jar",
          "size": 4071,
          "sha512": "c51268e465b4200de13cab720707b01e3b0096d05885366313789890cdca57428fd06c8d92105c460a6caf4b3abcfe1ffea2518b7ddd63d2293801de327e546f",
          "sha256": "a77ffd4fcc91176e0bf261c98edb2e1b4dc596a2149e47e57c5bb1a383823b6b",
          "sha1": "e87b3d9d7b73166c977c07dad6e347ec5b8776cf",
          "md5": "0ef1a3c8acc55a802b7ac9ebaeae504c"
        }
      ]
    }
  ]
}
