{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-coroutine-jvm/1.9.0-add-default-scope-SNAPSHOT/util-coroutine-jvm-1.9.0-add-default-scope-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-coroutine-jvm",
    "version": "1.9.0-add-default-scope-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "kajwctthtndz5mesu25u6hfcwa"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-coroutine-metadata-1.9.0-add-default-scope-SNAPSHOT.jar",
          "url": "util-coroutine-metadata-1.9.0-add-default-scope-SNAPSHOT.jar",
          "size": 2494,
          "sha512": "aedb6b03471e7d1908dd87e87c73de037042bd7410a5af8e34d56684c2db78b03082e8423efc3a1b2ddfa0170c17d7a393456968980aebd5d4563662dd6634a7",
          "sha256": "0831377dbaad6540303097ea1f54bf68cc1e661a717b982b832cee098d91b0ac",
          "sha1": "960ab8fcbf3b0e74a8e979b42929b9dc0c3886e8",
          "md5": "edadd101f47978023ec30f2fe7b31c19"
        }
      ]
    }
  ]
}
