{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.9.0-change-badges-SNAPSHOT/util-1.9.0-change-badges-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.9.0-change-badges-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ucz6ymk7arb2deya3srkruk5r4"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-jvm-1.9.0-change-badges-SNAPSHOT.jar",
          "url": "util-jvm-1.9.0-change-badges-SNAPSHOT.jar",
          "size": 19627,
          "sha512": "6017e26ed7006f30abad358307c0d2f768c4b3e887fafe2bffe083dbc25b26928c37abf556256da300b662df0e7d9ef8d42879167c0c507d40598c0690bbd095",
          "sha256": "7a3bb58ea639a83f8264211c0721ea5c5d45a7aa8768e3524712c5e1bb1f9764",
          "sha1": "d0e3b7e4a5bae863fe18cb7fa028e403ff41faa0",
          "md5": "360e8051fd40b40640f4ccccc6a56b33"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "util-jvm-1.9.0-change-badges-SNAPSHOT.jar",
          "url": "util-jvm-1.9.0-change-badges-SNAPSHOT.jar",
          "size": 19627,
          "sha512": "6017e26ed7006f30abad358307c0d2f768c4b3e887fafe2bffe083dbc25b26928c37abf556256da300b662df0e7d9ef8d42879167c0c507d40598c0690bbd095",
          "sha256": "7a3bb58ea639a83f8264211c0721ea5c5d45a7aa8768e3524712c5e1bb1f9764",
          "sha1": "d0e3b7e4a5bae863fe18cb7fa028e403ff41faa0",
          "md5": "360e8051fd40b40640f4ccccc6a56b33"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-metadata/1.9.0-change-badges-SNAPSHOT/util-metadata-1.9.0-change-badges-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-metadata",
        "version": "1.9.0-change-badges-SNAPSHOT"
      }
    }
  ]
}
