{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.9.0-change-badges-SNAPSHOT/util-1.9.0-change-badges-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.9.0-change-badges-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "d4h7o7s3cngfnjje4vazyi3c64"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-jvm-1.9.0-change-badges-SNAPSHOT.jar",
          "url": "util-jvm-1.9.0-change-badges-SNAPSHOT.jar",
          "size": 19627,
          "sha512": "5ceaa64fc896840d96d70d2fb95baf4e5d388290253829e600f1326f82cce1e0e054f381976d45c805ec7a7045484f77a911d121ba8e37465a06410b805121d0",
          "sha256": "1993abff9c7cf4cb882179da81d1af10fdf53e171b70676ad9ea35bc26c2a0a5",
          "sha1": "f69d93f7e8b454cb27bb58f3b4a4c1e795bdadfb",
          "md5": "ad5bf1d395cdd090b6bd0285725e8a1d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "util-jvm-1.9.0-change-badges-SNAPSHOT.jar",
          "url": "util-jvm-1.9.0-change-badges-SNAPSHOT.jar",
          "size": 19627,
          "sha512": "5ceaa64fc896840d96d70d2fb95baf4e5d388290253829e600f1326f82cce1e0e054f381976d45c805ec7a7045484f77a911d121ba8e37465a06410b805121d0",
          "sha256": "1993abff9c7cf4cb882179da81d1af10fdf53e171b70676ad9ea35bc26c2a0a5",
          "sha1": "f69d93f7e8b454cb27bb58f3b4a4c1e795bdadfb",
          "md5": "ad5bf1d395cdd090b6bd0285725e8a1d"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-metadata/1.9.0-change-badges-SNAPSHOT/util-metadata-1.9.0-change-badges-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-metadata",
        "version": "1.9.0-change-badges-SNAPSHOT"
      }
    }
  ]
}
