{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-ktor/0.2.0-SNAPSHOT/test-util-ktor-0.2.0-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-ktor",
    "version": "0.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-util-ktor-jvm-0.2.0-SNAPSHOT.jar",
          "url": "test-util-ktor-jvm-0.2.0-SNAPSHOT.jar",
          "size": 28636,
          "sha512": "ff0ea13b4131c8d3a39a7789f78df480b84358dd5c9f60837dd08c28ad9b38845c192f6e0a5c9b4128ebac6b8c158e0b0583ed3b09dbb3a2525fd87ed0259181",
          "sha256": "ed8d58df230593d8be8650113e900908f337eddb490c79252b2e1c8e3aac219c",
          "sha1": "5e60c28728470c74f18151415ffeb387b97dcd51",
          "md5": "5e71f88ad437e6bb30db3926ae54fc1b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor-jvm-0.2.0-SNAPSHOT.jar",
          "url": "test-util-ktor-jvm-0.2.0-SNAPSHOT.jar",
          "size": 28636,
          "sha512": "ff0ea13b4131c8d3a39a7789f78df480b84358dd5c9f60837dd08c28ad9b38845c192f6e0a5c9b4128ebac6b8c158e0b0583ed3b09dbb3a2525fd87ed0259181",
          "sha256": "ed8d58df230593d8be8650113e900908f337eddb490c79252b2e1c8e3aac219c",
          "sha1": "5e60c28728470c74f18151415ffeb387b97dcd51",
          "md5": "5e71f88ad437e6bb30db3926ae54fc1b"
        }
      ]
    }
  ]
}
