{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk",
    "version": "0.1.2-change-kotlin-duration-usage-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "qyhx6xudxbcqhio3tukogwlg5i"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.2-change-kotlin-duration-usage-SNAPSHOT.jar",
          "url": "data-donation-sdk-0.1.2-change-kotlin-duration-usage-SNAPSHOT.jar",
          "size": 39147,
          "sha512": "f8494df8ae76c426cd6ef132f6846617bc47113f2f0fbabfbde8cef54c5bc3841201333dd5d040f66465203132905c1acde9f43c72b67ca47a1ba8b042b70090",
          "sha256": "d733e20f880ee50253167bf41992ce76a40c2b7406eb1dde48ce0c7b207cc394",
          "sha1": "30e7ba582241d3856f4d6711e8ea183cd1675245",
          "md5": "4010a0565fb4d8a315d0cc309e6a5fed"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android-debug/0.1.2-change-kotlin-duration-usage-SNAPSHOT/data-donation-sdk-android-debug-0.1.2-change-kotlin-duration-usage-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android-debug",
        "version": "0.1.2-change-kotlin-duration-usage-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android-debug/0.1.2-change-kotlin-duration-usage-SNAPSHOT/data-donation-sdk-android-debug-0.1.2-change-kotlin-duration-usage-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android-debug",
        "version": "0.1.2-change-kotlin-duration-usage-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android/0.1.2-change-kotlin-duration-usage-SNAPSHOT/data-donation-sdk-android-0.1.2-change-kotlin-duration-usage-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android",
        "version": "0.1.2-change-kotlin-duration-usage-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android/0.1.2-change-kotlin-duration-usage-SNAPSHOT/data-donation-sdk-android-0.1.2-change-kotlin-duration-usage-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android",
        "version": "0.1.2-change-kotlin-duration-usage-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../data-donation-sdk-iosarm64/0.1.2-change-kotlin-duration-usage-SNAPSHOT/data-donation-sdk-iosarm64-0.1.2-change-kotlin-duration-usage-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-iosarm64",
        "version": "0.1.2-change-kotlin-duration-usage-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../data-donation-sdk-iosx64/0.1.2-change-kotlin-duration-usage-SNAPSHOT/data-donation-sdk-iosx64-0.1.2-change-kotlin-duration-usage-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-iosx64",
        "version": "0.1.2-change-kotlin-duration-usage-SNAPSHOT"
      }
    }
  ]
}
