{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk",
    "version": "0.1.3-add-observation-wrapper-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "gife5r4wpvdzxef7fflrlgszii"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.3-add-observation-wrapper-SNAPSHOT.jar",
          "url": "data-donation-sdk-0.1.3-add-observation-wrapper-SNAPSHOT.jar",
          "size": 121857,
          "sha512": "a07b973fd88a7bcdde86d5da7e8f7ba82fe334d68ff2973a7622710b9de98cf266686e1f2ba8fdd3a77f99d4b354012efb7b0b6111479fed7e27b5e54606edf7",
          "sha256": "61bffc48451ae1a3401a20fdd399e1ff2dd768219e795185681f58532e1d1185",
          "sha1": "a19a8b1efb1161893779eb9ef294479b5dcdca43",
          "md5": "4c50c0675b72d2165da79b490a2438de"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android-debug/0.1.3-add-observation-wrapper-SNAPSHOT/data-donation-sdk-android-debug-0.1.3-add-observation-wrapper-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android-debug",
        "version": "0.1.3-add-observation-wrapper-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android-debug/0.1.3-add-observation-wrapper-SNAPSHOT/data-donation-sdk-android-debug-0.1.3-add-observation-wrapper-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android-debug",
        "version": "0.1.3-add-observation-wrapper-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android/0.1.3-add-observation-wrapper-SNAPSHOT/data-donation-sdk-android-0.1.3-add-observation-wrapper-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android",
        "version": "0.1.3-add-observation-wrapper-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android/0.1.3-add-observation-wrapper-SNAPSHOT/data-donation-sdk-android-0.1.3-add-observation-wrapper-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android",
        "version": "0.1.3-add-observation-wrapper-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../data-donation-sdk-iosarm64/0.1.3-add-observation-wrapper-SNAPSHOT/data-donation-sdk-iosarm64-0.1.3-add-observation-wrapper-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-iosarm64",
        "version": "0.1.3-add-observation-wrapper-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../data-donation-sdk-iosx64/0.1.3-add-observation-wrapper-SNAPSHOT/data-donation-sdk-iosx64-0.1.3-add-observation-wrapper-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-iosx64",
        "version": "0.1.3-add-observation-wrapper-SNAPSHOT"
      }
    }
  ]
}
