{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.12.0-change-contracts-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ttc33ah5sbgevdt33k4rhpgi3a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.12.0-change-contracts-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.12.0-change-contracts-SNAPSHOT.jar",
          "url": "crypto-jvm-1.12.0-change-contracts-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "1b63ed5c710da8450c0d621d52ef4367070a87695d8d0161900614209f74bb9eb886d9853e07f0c3ba0dc38dd3bf20d9f331ae82083ef6636ddfa3980a2fffb4",
          "sha256": "82ba9c3712597049f2679129889c70ada5518d51b3bb39b972c4c5b017a445cf",
          "sha1": "65f3f53054115103244c4d4768c221891f6fc51a",
          "md5": "d5ffb00f67fb699afc832eb17d1dab46"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.12.0-change-contracts-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.12.0-change-contracts-SNAPSHOT.jar",
          "url": "crypto-jvm-1.12.0-change-contracts-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "1b63ed5c710da8450c0d621d52ef4367070a87695d8d0161900614209f74bb9eb886d9853e07f0c3ba0dc38dd3bf20d9f331ae82083ef6636ddfa3980a2fffb4",
          "sha256": "82ba9c3712597049f2679129889c70ada5518d51b3bb39b972c4c5b017a445cf",
          "sha1": "65f3f53054115103244c4d4768c221891f6fc51a",
          "md5": "d5ffb00f67fb699afc832eb17d1dab46"
        }
      ]
    }
  ]
}
