{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.12.0-change-contracts-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "63cmugcfene45nenctysit3pri"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.12.0-change-contracts-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.12.0-change-contracts-SNAPSHOT.jar",
          "url": "crypto-jvm-1.12.0-change-contracts-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "12c62e2f300881e518db0d7fda600ed29bec029f5baac87ada2e02784793da6d0762c53020e2130dec90491a9f1a4f6dbb6a2ca2f8d2b6dc67bf280113f1f18a",
          "sha256": "a9cc38ab178f0c6fa66a96dbb73c5573080ba209f17362dea0d4e2c783b0c423",
          "sha1": "be1eadf6ade20a8a8c3bb6ea261eea2782d39cdb",
          "md5": "80b09dea3dddf419746fbda244f7d015"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.12.0-change-contracts-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.12.0-change-contracts-SNAPSHOT.jar",
          "url": "crypto-jvm-1.12.0-change-contracts-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "12c62e2f300881e518db0d7fda600ed29bec029f5baac87ada2e02784793da6d0762c53020e2130dec90491a9f1a4f6dbb6a2ca2f8d2b6dc67bf280113f1f18a",
          "sha256": "a9cc38ab178f0c6fa66a96dbb73c5573080ba209f17362dea0d4e2c783b0c423",
          "sha1": "be1eadf6ade20a8a8c3bb6ea261eea2782d39cdb",
          "md5": "80b09dea3dddf419746fbda244f7d015"
        }
      ]
    }
  ]
}
