{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.12.0-change-contracts-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ixnyxrk4prfxrp7b4vitsfm52a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.12.0-change-contracts-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.12.0-change-contracts-SNAPSHOT.jar",
          "url": "crypto-jvm-1.12.0-change-contracts-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "6d05bc3c2daf9956032cdc9ed8a205bb4b00638973d4017f9816a8fd5a8583e27dbc97c7fad005fa5939e9918ccf5f77292cd2ea9de3f2b611fb96c6aeb863a3",
          "sha256": "9946bdcd9263aa20f6194fba026e14b18dbfc32744fee49338550510fa3955cc",
          "sha1": "f21a511b9b31c7b6d1b65681eb9e5dd8531669e7",
          "md5": "8371981d3c11cba46fd6b17de825a167"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.12.0-change-contracts-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.12.0-change-contracts-SNAPSHOT.jar",
          "url": "crypto-jvm-1.12.0-change-contracts-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "6d05bc3c2daf9956032cdc9ed8a205bb4b00638973d4017f9816a8fd5a8583e27dbc97c7fad005fa5939e9918ccf5f77292cd2ea9de3f2b611fb96c6aeb863a3",
          "sha256": "9946bdcd9263aa20f6194fba026e14b18dbfc32744fee49338550510fa3955cc",
          "sha1": "f21a511b9b31c7b6d1b65681eb9e5dd8531669e7",
          "md5": "8371981d3c11cba46fd6b17de825a167"
        }
      ]
    }
  ]
}
