{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.0-change-flow-return-SNAPSHOT/data-donation-sdk-iosx64-0.1.0-change-flow-return-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.0-change-flow-return-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "zrz466nb2rd67ljgddzgeuhuji"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.0-change-flow-return-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.0-change-flow-return-SNAPSHOT.jar",
          "size": 40753,
          "sha512": "149b017cbaaab46dd695ff20b985b0e6fd0aa1e8dd69c7e3f7d36f46acedb666f82aaccce19643d1220e74921a1d9634e720d6cf211a717872a25a33d7d56809",
          "sha256": "39cb37f0a85461dc04a012d04ff82310860ce58d7e1a379bd394b3cba2a980a8",
          "sha1": "76bcbb8d17e26124ba768c8a227d5ad2d8a51684",
          "md5": "b612311bd693d3b59cac2c39084110c7"
        }
      ]
    }
  ]
}
