{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-jvm",
    "version": "1.14.0-add-new-search-parameter-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "32tx7contzckhowvew3ufdutae"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.14.0-add-new-search-parameter-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util"
            },
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.14.0-add-new-search-parameter-SNAPSHOT.jar",
          "url": "sdk-jvm-1.14.0-add-new-search-parameter-SNAPSHOT.jar",
          "size": 11651,
          "sha512": "be0d0fc567e52eece1a6a4bf1308c8d8530d812080b6a717cade9ad9cbe53594bf523ad441d50e7ed0010be120593fbaeee08caa04598f449828e3c7248a2bd0",
          "sha256": "e53947a82523d831561c0ad197f2da5cf0a48acaac34d5fa1f0e73abc5197a64",
          "sha1": "8fc564ad47c686b6d2458f9d63369a262c425811",
          "md5": "bef17058e252b092969dc18bb3f8e2c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.14.0-add-new-search-parameter-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.14.0-add-new-search-parameter-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.14.0-add-new-search-parameter-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.14.0-add-new-search-parameter-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util"
            },
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.14.0-add-new-search-parameter-SNAPSHOT.jar",
          "url": "sdk-jvm-1.14.0-add-new-search-parameter-SNAPSHOT.jar",
          "size": 11651,
          "sha512": "be0d0fc567e52eece1a6a4bf1308c8d8530d812080b6a717cade9ad9cbe53594bf523ad441d50e7ed0010be120593fbaeee08caa04598f449828e3c7248a2bd0",
          "sha256": "e53947a82523d831561c0ad197f2da5cf0a48acaac34d5fa1f0e73abc5197a64",
          "sha1": "8fc564ad47c686b6d2458f9d63369a262c425811",
          "md5": "bef17058e252b092969dc18bb3f8e2c0"
        }
      ]
    }
  ]
}
