{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir",
    "version": "0.2.0-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-metadata-0.2.0-bump-updates-SNAPSHOT-all.jar",
          "url": "fhir-0.2.0-bump-updates-SNAPSHOT-all.jar",
          "size": 865811,
          "sha512": "f670e75ecde150bc41676b2cef3317fba3c7283688ebfcffd12edf6f13d0f7aaec9b41c04178c5d01660462ded606b877d2c6f72f405495d7ce82f38eb2f3e84",
          "sha256": "11d98b48cc395d698bba9332d1c5c1bd1811ef1f0dd0da91e919b6a4746b9459",
          "sha1": "f593bb17e7f9bd13d5a68d614f3d47b38b15ccc2",
          "md5": "3117154affdb7fc8d461fd5bce418a82"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "fhir-0.2.0-bump-updates-SNAPSHOT.jar",
          "url": "fhir-0.2.0-bump-updates-SNAPSHOT.jar",
          "size": 3216165,
          "sha512": "9519c5e50c500269865b1fe41536bc0d222ee4a77b284e84d4fc4764e4ee7754b32800c5fd6e606aaf2eb843eff36c9fe5114824a211ff0df85df1f3cbbb8aae",
          "sha256": "05dab551e0df798684abd49ab7d865cb24d907b048c79e685633ee453c712d0c",
          "sha1": "d68a11794b60174aadd27052bac0e2c2a05a55ec",
          "md5": "749f70f99305f9f82f781dc7fbed56fb"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-android-debug/0.2.0-bump-updates-SNAPSHOT/fhir-android-debug-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-android-debug",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-android-debug/0.2.0-bump-updates-SNAPSHOT/fhir-android-debug-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-android-debug",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-android/0.2.0-bump-updates-SNAPSHOT/fhir-android-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-android",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-android/0.2.0-bump-updates-SNAPSHOT/fhir-android-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-android",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fhir-iosarm64/0.2.0-bump-updates-SNAPSHOT/fhir-iosarm64-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-iosarm64",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fhir-iosarm64/0.2.0-bump-updates-SNAPSHOT/fhir-iosarm64-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-iosarm64",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fhir-iosx64/0.2.0-bump-updates-SNAPSHOT/fhir-iosx64-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-iosx64",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fhir-iosx64/0.2.0-bump-updates-SNAPSHOT/fhir-iosx64-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-iosx64",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../fhir-jvm/0.2.0-bump-updates-SNAPSHOT/fhir-jvm-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-jvm",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../fhir-jvm/0.2.0-bump-updates-SNAPSHOT/fhir-jvm-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-jvm",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    }
  ]
}
