{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.8.1-add-resource-loader-common-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "6k57mjy53vabpkdbduypzfranq"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-metadata-1.8.1-add-resource-loader-common-SNAPSHOT.jar",
          "url": "util-1.8.1-add-resource-loader-common-SNAPSHOT.jar",
          "size": 6309,
          "sha512": "785d17d08524b6ae904fe4f79ce24edfc9507c1c238da19a058da2c4c2f1159eaf48b57363392f7ace40149aa86bda96a4b8d21dffabb0ba629ef921aa4427b6",
          "sha256": "0a719ca859d9d4e25687c6525490d3bf13312ca53335653489e51231d3102ad6",
          "sha1": "08ee972c977b96c1e2ed4590b2f4002d4a28b231",
          "md5": "f369a34cb9fc4686b4a02688a8f5d6af"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../util-android-debug/1.8.1-add-resource-loader-common-SNAPSHOT/util-android-debug-1.8.1-add-resource-loader-common-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-android-debug",
        "version": "1.8.1-add-resource-loader-common-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../util-android-debug/1.8.1-add-resource-loader-common-SNAPSHOT/util-android-debug-1.8.1-add-resource-loader-common-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-android-debug",
        "version": "1.8.1-add-resource-loader-common-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../util-android/1.8.1-add-resource-loader-common-SNAPSHOT/util-android-1.8.1-add-resource-loader-common-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-android",
        "version": "1.8.1-add-resource-loader-common-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../util-android/1.8.1-add-resource-loader-common-SNAPSHOT/util-android-1.8.1-add-resource-loader-common-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-android",
        "version": "1.8.1-add-resource-loader-common-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../util-iosarm64/1.8.1-add-resource-loader-common-SNAPSHOT/util-iosarm64-1.8.1-add-resource-loader-common-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-iosarm64",
        "version": "1.8.1-add-resource-loader-common-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../util-iosx64/1.8.1-add-resource-loader-common-SNAPSHOT/util-iosx64-1.8.1-add-resource-loader-common-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-iosx64",
        "version": "1.8.1-add-resource-loader-common-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../util-jvm/1.8.1-add-resource-loader-common-SNAPSHOT/util-jvm-1.8.1-add-resource-loader-common-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-jvm",
        "version": "1.8.1-add-resource-loader-common-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../util-jvm/1.8.1-add-resource-loader-common-SNAPSHOT/util-jvm-1.8.1-add-resource-loader-common-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-jvm",
        "version": "1.8.1-add-resource-loader-common-SNAPSHOT"
      }
    }
  ]
}
