{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.12.0-change-resource-crypto-service-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "u75audiu3jaf7geury3s4ijsp4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.12.0-change-resource-crypto-service-SNAPSHOT.jar",
          "url": "securestore-common-1.12.0-change-resource-crypto-service-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "8dca22ffc62a204d8553b3238e248d3a28b24726929bd4bf4cfd010101493331b4d5fd03495294580e586b2327a4bf5b737c20bfeb32ecc6c0cedbb29d4f5af2",
          "sha256": "592e78f6ff5dadb211dadb16f3a437078899be1442d8ff8d6423dd0e4a169d4f",
          "sha1": "7b3c2772fe54694999d55c6923e580597080f4b5",
          "md5": "7938a281049e380b06f614fcbda1f63e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.12.0-change-resource-crypto-service-SNAPSHOT.jar",
          "url": "securestore-common-1.12.0-change-resource-crypto-service-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "8dca22ffc62a204d8553b3238e248d3a28b24726929bd4bf4cfd010101493331b4d5fd03495294580e586b2327a4bf5b737c20bfeb32ecc6c0cedbb29d4f5af2",
          "sha256": "592e78f6ff5dadb211dadb16f3a437078899be1442d8ff8d6423dd0e4a169d4f",
          "sha1": "7b3c2772fe54694999d55c6923e580597080f4b5",
          "md5": "7938a281049e380b06f614fcbda1f63e"
        }
      ]
    }
  ]
}
