{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.12.0-change-resource-crypto-service-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "deuhjigdszh3fitt4f5picqb6u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.12.0-change-resource-crypto-service-SNAPSHOT.jar",
          "url": "securestore-common-1.12.0-change-resource-crypto-service-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "25468e2f60f92698642918e13dfac39dbcbeb727dbb1aac3642b8e80ff2735112ded3b1ca2ba86469033c59b82c40d32546dde06c93cdf817deedb2cba554453",
          "sha256": "0139fa3900b8caa1587c65119508f4d676d7691ed9468cee9e660b19e0bae22a",
          "sha1": "9c7ba24fdba717536903d0cad5fe01a6745834cf",
          "md5": "30414f31f3e151e4e4b44cd56a641b44"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.12.0-change-resource-crypto-service-SNAPSHOT.jar",
          "url": "securestore-common-1.12.0-change-resource-crypto-service-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "25468e2f60f92698642918e13dfac39dbcbeb727dbb1aac3642b8e80ff2735112ded3b1ca2ba86469033c59b82c40d32546dde06c93cdf817deedb2cba554453",
          "sha256": "0139fa3900b8caa1587c65119508f4d676d7691ed9468cee9e660b19e0bae22a",
          "sha1": "9c7ba24fdba717536903d0cad5fe01a6745834cf",
          "md5": "30414f31f3e151e4e4b44cd56a641b44"
        }
      ]
    }
  ]
}
