{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.11.0-add-envrioment-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "hojyvrcyxjexpegvtztn72b6fa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-add-envrioment-tests-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-add-envrioment-tests-SNAPSHOT.jar",
          "size": 3404,
          "sha512": "3834a7f14823f96236150fb185946d095be8b42a5a179538b283e84a7973cf95ab31278c80732639a9dd5fc94fee283da11bfc4e39e9b6b7dda6b8cc05a9571b",
          "sha256": "a5e73a29c06e00e6ebebf4492c82ab162a34304bd3d2f6bd78a44f050161b6c8",
          "sha1": "9b21cfd198682974401a04e7da3e9fc23986ec8a",
          "md5": "ce593cc592330421212913874a829370"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-add-envrioment-tests-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-add-envrioment-tests-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-add-envrioment-tests-SNAPSHOT.jar",
          "size": 3404,
          "sha512": "3834a7f14823f96236150fb185946d095be8b42a5a179538b283e84a7973cf95ab31278c80732639a9dd5fc94fee283da11bfc4e39e9b6b7dda6b8cc05a9571b",
          "sha256": "a5e73a29c06e00e6ebebf4492c82ab162a34304bd3d2f6bd78a44f050161b6c8",
          "sha1": "9b21cfd198682974401a04e7da3e9fc23986ec8a",
          "md5": "ce593cc592330421212913874a829370"
        }
      ]
    }
  ]
}
