{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util/0.2.0-fix-labels-SNAPSHOT/test-util-0.2.0-fix-labels-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util",
    "version": "0.2.0-fix-labels-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-util-jvm-0.2.0-fix-labels-SNAPSHOT.jar",
          "url": "test-util-jvm-0.2.0-fix-labels-SNAPSHOT.jar",
          "size": 12792,
          "sha512": "49061bf56efeb76aa6fb14053ef9f0237b290548cee0413485b3e731d736bf2ca3c40e827290e9f638c8da5a6bfcc342b228d7a81e1e6ef3358acf0f6121dc7e",
          "sha256": "c3967423be874dcb70396668f0131eda34d22089dfc0a047872d2c44802ea275",
          "sha1": "dee6222ac04d5d3c9b65cb8796cd7961c7e78b29",
          "md5": "1ec88643914011edc4cb8809ce385f6e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-jvm-0.2.0-fix-labels-SNAPSHOT.jar",
          "url": "test-util-jvm-0.2.0-fix-labels-SNAPSHOT.jar",
          "size": 12792,
          "sha512": "49061bf56efeb76aa6fb14053ef9f0237b290548cee0413485b3e731d736bf2ca3c40e827290e9f638c8da5a6bfcc342b228d7a81e1e6ef3358acf0f6121dc7e",
          "sha256": "c3967423be874dcb70396668f0131eda34d22089dfc0a047872d2c44802ea275",
          "sha1": "dee6222ac04d5d3c9b65cb8796cd7961c7e78b29",
          "md5": "1ec88643914011edc4cb8809ce385f6e"
        }
      ]
    }
  ]
}
