{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk/0.0.2-change-fetch-consent-for-custom-key-SNAPSHOT/data-donation-sdk-0.0.2-change-fetch-consent-for-custom-key-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk",
    "version": "0.0.2-change-fetch-consent-for-custom-key-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "bbfbv5mrvbbjbh6r5v7yvzdklu"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2-native-mt"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-kmp",
          "module": "fhir",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.4.2-native-mt",
            "requires": "1.4.2-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "data-donation-sdk.klib",
          "url": "data-donation-sdk-iosx64-0.0.2-change-fetch-consent-for-custom-key-SNAPSHOT.klib",
          "size": 7264654,
          "sha512": "7c41ff5c400f0ee46ef5d48bdb9aa2eeed79cd114881ab66ea8e7893384e78f69fe10eb87e73b64c882d4af966a2a871c966da573ec60831b031979a4d6fb2ac",
          "sha256": "1f0a744aff63e6df7621dd040558ad914eafaf45af5bdf95407a14a83283aa13",
          "sha1": "1ec71c6831a932f11f1b0c6f7b8c0d676e4650e0",
          "md5": "de2e09ddfcc08457b73b316d23a676a2"
        },
        {
          "name": "data-donation-sdk-cinterop-iOSDCryptoDD.klib",
          "url": "data-donation-sdk-iosx64-0.0.2-change-fetch-consent-for-custom-key-SNAPSHOT-cinterop-iOSDCryptoDD.klib",
          "size": 5940,
          "sha512": "2079eac622255a8c83135a46ab5c250ab1882bfa4f47cceeec032f5aea153874c8870bab2ca39c36803db075e3798f7911f11e70e54dbdd3c62604646e210826",
          "sha256": "5e70753cd39b338b59aec2f2cf9eb260a1a2f37f8c43e94fc7d61d0034468187",
          "sha1": "55b66aad3ff6cccfc076ea2c2c40639b13b98a09",
          "md5": "d8fbdab6a68886b363afc7abd2e41511"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../data-donation-sdk-metadata/0.0.2-change-fetch-consent-for-custom-key-SNAPSHOT/data-donation-sdk-metadata-0.0.2-change-fetch-consent-for-custom-key-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-metadata",
        "version": "0.0.2-change-fetch-consent-for-custom-key-SNAPSHOT"
      }
    }
  ]
}
