{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.3-add-resource-validator-SNAPSHOT/data-donation-sdk-iosx64-0.1.3-add-resource-validator-SNAPSHOT.module",
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.3-add-resource-validator-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "kqfpcbrolfhkro4r4ehmgteppa"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.3-add-resource-validator-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.3-add-resource-validator-SNAPSHOT.jar",
          "size": 63132,
          "sha512": "5e23e5023368165e0d23948ce0489e64d31f08f4a0666bcdda536c35e20e5dcf7335be8c575143b06f49e1a3113e112fbe3bdc6b8e856a73698770874553eb5b",
          "sha256": "c53ac467647b59f062cd5ec289f4385534ee9b2045f9b53c62812ccc3fe23226",
          "sha1": "df47f5120acd77dc6c996bdfa0f4c36385e11f2f",
          "md5": "eae260f88a5df631a56c13bbd8c59480"
        }
      ]
    }
  ]
}
