{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.3-add-resource-validator-SNAPSHOT/data-donation-sdk-iosx64-0.1.3-add-resource-validator-SNAPSHOT.module",
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.3-add-resource-validator-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "g3t6qvqfyjaujbnlhqjlphtmye"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.3-add-resource-validator-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.3-add-resource-validator-SNAPSHOT.jar",
          "size": 87691,
          "sha512": "8641d5919eee25ba32344273bd9c40d7c121680ae1916dffb7c92566bd72f3fbc2a4a1c8dcaa55971ccd0560fb22c8478c6d3a96b9c2798350d6a60d258afafc",
          "sha256": "24689e98ee2d15ce4bb2790a8361c80dc3410f2f8c57a48d2d0b25b6bb45d935",
          "sha1": "b9bff172a5eadb56cff814f4c302b917529c6c0a",
          "md5": "d58256036dffbd8772241706e07e2cd6"
        }
      ]
    }
  ]
}
