{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.13.2-bump-util-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "kbgwt4dr5jdnhcwmzjujd26kqa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.2-bump-util-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.13.2-bump-util-SNAPSHOT.jar",
          "url": "securestore-jvm-1.13.2-bump-util-SNAPSHOT.jar",
          "size": 16455,
          "sha512": "fb5a38cc6715af6f90268407fd7aee581d175fa580efe3c310966a2d423f444a42759cfe342666cf5685115367762740b32af223f34f52085ec8ebb528034973",
          "sha256": "6a1dcfd01b632ceb51b3f5d1b5ceef9e0ab7e89c4646272384878cbe8bec60df",
          "sha1": "f6b19c13459c029f083bccecc01c745a40d8a190",
          "md5": "03da3b9ebb02b6c0bea25bd7aaa1e2db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.2-bump-util-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.13.2-bump-util-SNAPSHOT.jar",
          "url": "securestore-jvm-1.13.2-bump-util-SNAPSHOT.jar",
          "size": 16455,
          "sha512": "fb5a38cc6715af6f90268407fd7aee581d175fa580efe3c310966a2d423f444a42759cfe342666cf5685115367762740b32af223f34f52085ec8ebb528034973",
          "sha256": "6a1dcfd01b632ceb51b3f5d1b5ceef9e0ab7e89c4646272384878cbe8bec60df",
          "sha1": "f6b19c13459c029f083bccecc01c745a40d8a190",
          "md5": "03da3b9ebb02b6c0bea25bd7aaa1e2db"
        }
      ]
    }
  ]
}
