{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "4ybgtmcsrvemblmyhvy6lp6uoi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.12.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.12.0-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "477aaeda24f8042f88375a08b97fc8ef29d0102f9bba91c9fe53ff482092a6c697be5ceceb7b047f43d5f791f68623e8ed8a049918d6adfbfc1c2c97c57f821d",
          "sha256": "e90b4d2df9e698956017148ef1b94195cb948cc35aae3d8d352c483895f7b7cd",
          "sha1": "7d0e88d40277bc8113f85592be896526c22f535c",
          "md5": "67fe7880fc8125aab232f15348661ff8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.12.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.12.0-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "477aaeda24f8042f88375a08b97fc8ef29d0102f9bba91c9fe53ff482092a6c697be5ceceb7b047f43d5f791f68623e8ed8a049918d6adfbfc1c2c97c57f821d",
          "sha256": "e90b4d2df9e698956017148ef1b94195cb948cc35aae3d8d352c483895f7b7cd",
          "sha1": "7d0e88d40277bc8113f85592be896526c22f535c",
          "md5": "67fe7880fc8125aab232f15348661ff8"
        }
      ]
    }
  ]
}
