{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.13.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ibnopu4mrjbqveajiujxmltyam"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.13.1-SNAPSHOT.jar",
          "url": "securestore-common-1.13.1-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "3f7699d9ff4ad4211b82f2178a5c51e1d14d0a48bcae1aad6e255a393a0a9a6ba424d56f6610ce800ae8ced77e24e4f9c3adc8d98c12419e351c6ee75a532921",
          "sha256": "90af3de0ca945cc4fb257e3ba3a8f75ebd3f51d905062b9da98f4403eb6f2935",
          "sha1": "fa8fccef2f6364e6e69b88bce3e781cd8807e048",
          "md5": "6bce8ad06b2153ec2757058d85744423"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.13.1-SNAPSHOT.jar",
          "url": "securestore-common-1.13.1-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "3f7699d9ff4ad4211b82f2178a5c51e1d14d0a48bcae1aad6e255a393a0a9a6ba424d56f6610ce800ae8ced77e24e4f9c3adc8d98c12419e351c6ee75a532921",
          "sha256": "90af3de0ca945cc4fb257e3ba3a8f75ebd3f51d905062b9da98f4403eb6f2935",
          "sha1": "fa8fccef2f6364e6e69b88bce3e781cd8807e048",
          "md5": "6bce8ad06b2153ec2757058d85744423"
        }
      ]
    }
  ]
}
