{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.10.0-bump-updates-SNAPSHOT/util-1.10.0-bump-updates-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.10.0-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "util.klib",
          "url": "util-iosarm64-1.10.0-bump-updates-SNAPSHOT.klib",
          "size": 24862,
          "sha512": "dc0d82d16ae5d91e1b0dafeee6caa7744b6b0627f372288b5e5fcd4b99268493be29975883a860a08d52c7a0b249994f3717a798d0153d77c8ed3d013aef7c35",
          "sha256": "e2c4115a3e4c3b923d160fc6f59dd6d128fa19bb3bdda462b54542792ea04fc5",
          "sha1": "98c855243c966ad0276f52e0c3571577395728b2",
          "md5": "ca35cd0e7e4b827efa61e261d1c4e954"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "util-iosarm64-1.10.0-bump-updates-SNAPSHOT-metadata.jar",
          "url": "util-iosarm64-1.10.0-bump-updates-SNAPSHOT-metadata.jar",
          "size": 6110,
          "sha512": "b4aebaf011f72b8623b8d90f82bcc9fb856566b728958dd57fda4877ff4188e54262a72db4f9d1564cab0d0bad35a589fa2f6c5068ddfaf73bdb2205bd6ff10d",
          "sha256": "96f16dc17be64adab21318bb47b468ceb8a01584535db335da5cdf9657e2469b",
          "sha1": "6ae0f64814fc273c91b3424235f8915fae98f4c0",
          "md5": "cdae63e1ebcc1721390692619e46d8a6"
        }
      ]
    }
  ]
}
