{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-jvm/1.7.0-add-coroutine-test-util-SNAPSHOT/util-jvm-1.7.0-add-coroutine-test-util-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-jvm",
    "version": "1.7.0-add-coroutine-test-util-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ocl5bckqffey3a4jvhkxxfnx3e"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-metadata-1.7.0-add-coroutine-test-util-SNAPSHOT.jar",
          "url": "util-metadata-1.7.0-add-coroutine-test-util-SNAPSHOT.jar",
          "size": 6309,
          "sha512": "38e15a7fe5764016905d6987666c9cd9fd3909f75974cfd50decc37e403f0e13a245da1c92776591df50a9e864a2247a6bfa0071afb4302d62d5c09390e2d789",
          "sha256": "294a1e334b1a06b61ad288b461f121bfe206b179435b7f34de1529d9fcbfaf62",
          "sha1": "eb93d12a0407648672ff027375b38daec581d6c4",
          "md5": "0d5d4bd5d64f283a96590523295d8668"
        }
      ]
    }
  ]
}
