{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-jvm/1.7.0-add-coroutine-test-util-SNAPSHOT/util-jvm-1.7.0-add-coroutine-test-util-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-jvm",
    "version": "1.7.0-add-coroutine-test-util-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "fv3vkdxxtvbetpqomoykzcol6u"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-metadata-1.7.0-add-coroutine-test-util-SNAPSHOT.jar",
          "url": "util-metadata-1.7.0-add-coroutine-test-util-SNAPSHOT.jar",
          "size": 6309,
          "sha512": "ba4854b3c64e45f0e0163d6d3de059a4bc0f192865473c3958ecb5c6d9e21c741460ac3cbfbb80948575376bac69f2e0c5ed822a933481947e016b2182b4466a",
          "sha256": "a9baf03c9e13d326bd11b45ede277cd993da99f097fca57021e800213a45d3c3",
          "sha1": "43680c2ecf73389ccb92029fa8f1ba5d297eda3f",
          "md5": "28fb5da89f8897e4d7548bc40a4d6087"
        }
      ]
    }
  ]
}
