{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-test/1.8.1-add-resource-loader-common-SNAPSHOT/util-test-1.8.1-add-resource-loader-common-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-test",
    "version": "1.8.1-add-resource-loader-common-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "c6ioeznlrnh3rjuzujcysatwsa"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.8.1-add-resource-loader-common-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.4.3-native-mt",
            "requires": "1.4.3-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "util-test.klib",
          "url": "util-test-iosx64-1.8.1-add-resource-loader-common-SNAPSHOT.klib",
          "size": 13004,
          "sha512": "c1b8e5cf189e2f9c08f7510e1b0f9be9e0b306d335a0f36cc9ddc6e370f48df1a2d6f7a85471b7fcddc068b6912df466943021d4e37fa6acf32efec244918955",
          "sha256": "256d1c3a73c936daa4e0a3187a87738d053269907837aef3882b70c03f665ed7",
          "sha1": "ab7e4965ede06c2f0b8da7f3f6cbec36a0d28281",
          "md5": "733a3c3728bf6a96dc0c487b8190ca28"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-test-metadata/1.8.1-add-resource-loader-common-SNAPSHOT/util-test-metadata-1.8.1-add-resource-loader-common-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-test-metadata",
        "version": "1.8.1-add-resource-loader-common-SNAPSHOT"
      }
    }
  ]
}
