{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util/0.2.0-SNAPSHOT/test-util-0.2.0-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util",
    "version": "0.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-util-jvm-0.2.0-SNAPSHOT.jar",
          "url": "test-util-jvm-0.2.0-SNAPSHOT.jar",
          "size": 12792,
          "sha512": "c10912262de3d922d47576e42d8449db62a64cf44d5929daef38d40f25eaed675a2c1aae3f39e838463f6aa9851ebe32c70f83136133785a8c84169346978e0a",
          "sha256": "3bcc41258601d55b2a5426cb8fc6357753fc3d9a7476c8dfe86f34cc08356062",
          "sha1": "f50433e5b35324657eac499e3d8128cdcb9378ec",
          "md5": "4453475f61a71e7d0ab7ae83285eeaa4"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-jvm-0.2.0-SNAPSHOT.jar",
          "url": "test-util-jvm-0.2.0-SNAPSHOT.jar",
          "size": 12792,
          "sha512": "c10912262de3d922d47576e42d8449db62a64cf44d5929daef38d40f25eaed675a2c1aae3f39e838463f6aa9851ebe32c70f83136133785a8c84169346978e0a",
          "sha256": "3bcc41258601d55b2a5426cb8fc6357753fc3d9a7476c8dfe86f34cc08356062",
          "sha1": "f50433e5b35324657eac499e3d8128cdcb9378ec",
          "md5": "4453475f61a71e7d0ab7ae83285eeaa4"
        }
      ]
    }
  ]
}
