{
  "formatVersion": "1.1",
  "component": {
    "url": "../../securestore/1.13.2-change-to-latest-setup-SNAPSHOT/securestore-1.13.2-change-to-latest-setup-SNAPSHOT.module",
    "group": "care.data4life.hc-securestore-sdk-kmp",
    "module": "securestore",
    "version": "1.13.2-change-to-latest-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "tov2nwv6bzbh7pne444nbnvvda"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "securestore-jvm-1.13.2-change-to-latest-setup-SNAPSHOT.jar",
          "url": "securestore-jvm-1.13.2-change-to-latest-setup-SNAPSHOT.jar",
          "size": 16739,
          "sha512": "702f8e635fc2e3e0e8c0587bc19982ba3d58b26de50de79e0988723eb1ad4bd68f35198e78e70803b5ca1d1a937ad301c97cc16e68e817222eddf772f9dd964e",
          "sha256": "f7015e1dd91daa901bdbed510da663367e9b2c4871c2cb17813f156a4881ecb9",
          "sha1": "bd24671f193e9bd9b300a77e45cd15674e6660cb",
          "md5": "50c822e010cc9dfc4c49389aefe5a214"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.13.2-change-to-latest-setup-SNAPSHOT.jar",
          "url": "securestore-jvm-1.13.2-change-to-latest-setup-SNAPSHOT.jar",
          "size": 16739,
          "sha512": "702f8e635fc2e3e0e8c0587bc19982ba3d58b26de50de79e0988723eb1ad4bd68f35198e78e70803b5ca1d1a937ad301c97cc16e68e817222eddf772f9dd964e",
          "sha256": "f7015e1dd91daa901bdbed510da663367e9b2c4871c2cb17813f156a4881ecb9",
          "sha1": "bd24671f193e9bd9b300a77e45cd15674e6660cb",
          "md5": "50c822e010cc9dfc4c49389aefe5a214"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../securestore-metadata/1.13.2-change-to-latest-setup-SNAPSHOT/securestore-metadata-1.13.2-change-to-latest-setup-SNAPSHOT.module",
        "group": "care.data4life.hc-securestore-sdk-kmp",
        "module": "securestore-metadata",
        "version": "1.13.2-change-to-latest-setup-SNAPSHOT"
      }
    }
  ]
}
