{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk/0.0.3-fix-missing-native-resources-SNAPSHOT/data-donation-sdk-0.0.3-fix-missing-native-resources-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk",
    "version": "0.0.3-fix-missing-native-resources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "d6yqzewcrzgl3j7i6pli6i2pz4"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "data-donation-sdk-release.aar",
          "url": "data-donation-sdk-android-0.0.3-fix-missing-native-resources-SNAPSHOT.aar",
          "size": 393966,
          "sha512": "afab7de09e3e3ff54379c3c151dc71b531ac082d8cf405468d68fd034625c368526f897410898dd47c11865c1b34b9629c40e5e49a4abd10e7a525e0c476aba8",
          "sha256": "08dc665ad1c3e8eb79d3ae2e28e7e9d66960270dc278b6144b7e16645b3b2cff",
          "sha1": "ae95def12ec773912c2330d94361402c62978e01",
          "md5": "3ee3eba86efd8b6e77cbc5cc8454af4f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.2-native-mt"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.jakewharton.threetenabp",
          "module": "threetenabp",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization-jvm",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core-jvm",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2-native-mt"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-kmp",
          "module": "fhir",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "data-donation-sdk-release.aar",
          "url": "data-donation-sdk-android-0.0.3-fix-missing-native-resources-SNAPSHOT.aar",
          "size": 393966,
          "sha512": "afab7de09e3e3ff54379c3c151dc71b531ac082d8cf405468d68fd034625c368526f897410898dd47c11865c1b34b9629c40e5e49a4abd10e7a525e0c476aba8",
          "sha256": "08dc665ad1c3e8eb79d3ae2e28e7e9d66960270dc278b6144b7e16645b3b2cff",
          "sha1": "ae95def12ec773912c2330d94361402c62978e01",
          "md5": "3ee3eba86efd8b6e77cbc5cc8454af4f"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../data-donation-sdk-metadata/0.0.3-fix-missing-native-resources-SNAPSHOT/data-donation-sdk-metadata-0.0.3-fix-missing-native-resources-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-metadata",
        "version": "0.0.3-fix-missing-native-resources-SNAPSHOT"
      }
    }
  ]
}
