{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.11.0-change-client-version-header-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "jjloxvxefvfirnmz6dqhsjomta"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.11.0-change-client-version-header-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-change-client-version-header-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "e66dc650f860aa8eb29f84fa863a5731e6506a015a0648a733ca20bbd0a037691149ac4839c5bc61ae8abeef6c8a11c117566fb1ff1abbac38cd062fb4e04e2c",
          "sha256": "9b3dce2ac3100a94f543f27a203b0922a39e7e5fb72db83ccbe3be21212d19f4",
          "sha1": "0bd3a76df99dfe97cffcc230186c936f43a8f176",
          "md5": "e2565f894cddd6153866d2635e0aa8e0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.11.0-change-client-version-header-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-change-client-version-header-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "e66dc650f860aa8eb29f84fa863a5731e6506a015a0648a733ca20bbd0a037691149ac4839c5bc61ae8abeef6c8a11c117566fb1ff1abbac38cd062fb4e04e2c",
          "sha256": "9b3dce2ac3100a94f543f27a203b0922a39e7e5fb72db83ccbe3be21212d19f4",
          "sha1": "0bd3a76df99dfe97cffcc230186c936f43a8f176",
          "md5": "e2565f894cddd6153866d2635e0aa8e0"
        }
      ]
    }
  ]
}
