{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.11.0-change-client-version-header-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "m45z2ok3vfhlrkwni53av37rfq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.11.0-change-client-version-header-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-change-client-version-header-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "5b258d6d6b9c0345afd9a2dbd1a2376362880a10071d4fdc7592e071c93f402b20f93cbc7cf87b9547e65f34bb0bd7ace8c788021569045916ec2e4598a7a422",
          "sha256": "43b8466af33cd3c31fd0ba4db698946a9bd3fe112fdd38757bcb29e9729b7e1d",
          "sha1": "0ca7ed8dbd7b880b67dd4aa9ad04f760cfe1495d",
          "md5": "b31fff7c10f5556623e6e9aa579f86a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.11.0-change-client-version-header-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-change-client-version-header-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "5b258d6d6b9c0345afd9a2dbd1a2376362880a10071d4fdc7592e071c93f402b20f93cbc7cf87b9547e65f34bb0bd7ace8c788021569045916ec2e4598a7a422",
          "sha256": "43b8466af33cd3c31fd0ba4db698946a9bd3fe112fdd38757bcb29e9729b7e1d",
          "sha1": "0ca7ed8dbd7b880b67dd4aa9ad04f760cfe1495d",
          "md5": "b31fff7c10f5556623e6e9aa579f86a5"
        }
      ]
    }
  ]
}
