{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.11.0-add-certificate-pinner-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "exsjfgsemfgk7fawrxnhqaokqm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-add-certificate-pinner-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.11.0-add-certificate-pinner-SNAPSHOT.jar",
          "url": "crypto-jvm-1.11.0-add-certificate-pinner-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "1f5dea135f79d310a034a7a38c6dde39dd991c58cd9e5d32a6c11615beda15aca80cf91f69b12a498b3513153b961585acd8b1837e7127d0424e532924e7fd13",
          "sha256": "10ee2ae83668a1d4c9c931c10fd454bddb3550f421b9b5a546858e0df82cc857",
          "sha1": "174bb80f4360e6073cee6d327a87b159e29b94b3",
          "md5": "8dbf6940633fd6d58a0a997d825df211"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-add-certificate-pinner-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.11.0-add-certificate-pinner-SNAPSHOT.jar",
          "url": "crypto-jvm-1.11.0-add-certificate-pinner-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "1f5dea135f79d310a034a7a38c6dde39dd991c58cd9e5d32a6c11615beda15aca80cf91f69b12a498b3513153b961585acd8b1837e7127d0424e532924e7fd13",
          "sha256": "10ee2ae83668a1d4c9c931c10fd454bddb3550f421b9b5a546858e0df82cc857",
          "sha1": "174bb80f4360e6073cee6d327a87b159e29b94b3",
          "md5": "8dbf6940633fd6d58a0a997d825df211"
        }
      ]
    }
  ]
}
