{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.0.3-fix-missing-native-resources-SNAPSHOT/data-donation-sdk-iosx64-0.0.3-fix-missing-native-resources-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.0.3-fix-missing-native-resources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "km4d3k5aofcxbd3ioelnkrkquy"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.3-fix-missing-native-resources-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.0.3-fix-missing-native-resources-SNAPSHOT.jar",
          "size": 64163,
          "sha512": "4706a0e8ecdfd1da5a61d481952919591f6272f15b3ef7893720f40e31298fa53f00937e8d60179ec7be4989aadc40d71fbdacb7992122ce423e47a7ef59c526",
          "sha256": "eb042b2af1d84340723e4c896ba8d493428da6c59e9e53f21bacee48095fe229",
          "sha1": "776242010184ab0ea67b58bfd9ed5e818cee8905",
          "md5": "61107040e6749839d59eb9f2adfab265"
        }
      ]
    }
  ]
}
