{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.0.3-fix-missing-native-resources-SNAPSHOT/data-donation-sdk-iosx64-0.0.3-fix-missing-native-resources-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.0.3-fix-missing-native-resources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ckobuog32va5paqsiwozxgkqvu"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.3-fix-missing-native-resources-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.0.3-fix-missing-native-resources-SNAPSHOT.jar",
          "size": 64163,
          "sha512": "99e8a95942d366e63a57c603770d015d0c01b99c6bc81f956f3dc2b0620701f6a36e9864d7631709c9edb29dd17cd09cb56b2fd6c2bb87de3ffdc28799cc3982",
          "sha256": "3b16853893b29b8c10b5784729e56bbc99712500594530a0331221f51560389f",
          "sha1": "c7c997454cc828846a91bc25dc6f68eb02a7cf23",
          "md5": "b437914cca055f5dfa27a8898dce242c"
        }
      ]
    }
  ]
}
