{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.0.3-fix-missing-native-resources-SNAPSHOT/data-donation-sdk-iosx64-0.0.3-fix-missing-native-resources-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.0.3-fix-missing-native-resources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "6pxk5yppczgezdxwfr2tgwtl24"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.3-fix-missing-native-resources-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.0.3-fix-missing-native-resources-SNAPSHOT.jar",
          "size": 64163,
          "sha512": "7d201914849496705b4923cdb0bf8a4f4d5c953ecbbfb8a50e8277181183acd8556a9ccaade504f90a9ae187b5ce6e64ce4ad6966daffb5a53da587c8fe31955",
          "sha256": "d7b6cf8e265cefa8950241587920c5fffe7a1faf33f327363648f91599eb862c",
          "sha1": "66b81601d3fddaabeae96264cba16a0e0d0c575e",
          "md5": "ca0cff34ecb0fb696fc0a10043abde51"
        }
      ]
    }
  ]
}
