{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-coroutine-jvm/1.8.1-change-util-test-SNAPSHOT/util-coroutine-jvm-1.8.1-change-util-test-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-coroutine-jvm",
    "version": "1.8.1-change-util-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "wmediofzbve6fnpgoqpadtf2aq"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-coroutine-metadata-1.8.1-change-util-test-SNAPSHOT.jar",
          "url": "util-coroutine-metadata-1.8.1-change-util-test-SNAPSHOT.jar",
          "size": 2237,
          "sha512": "1623b553fb2e21698038441c6cae28a82b07cdaf70e73a62a4649b058fb004dddebb47ac3422527e58c5e1937fa8cfc4411e03acadd8015ea28205c194935af9",
          "sha256": "78c4b8e862577f64c643c004c206b1dda1cee2e13a90db4f0a3757731dbd0f08",
          "sha1": "8619622324589db0e46210638638a13989822faf",
          "md5": "d402f2ea1faa94715e8d3be00b16c3be"
        }
      ]
    }
  ]
}
