{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.11.0-bump-okhttp-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "wbwnp32vdvbofcdpbagdxxp6tu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-bump-okhttp-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.11.0-bump-okhttp-SNAPSHOT.jar",
          "url": "auth-jvm-1.11.0-bump-okhttp-SNAPSHOT.jar",
          "size": 34318,
          "sha512": "6854c21bdf6c13e9e9ed9eb7b7478ea3d98d5b75d9a3c9c02e37e613061fd50a7eee4b5214c06ff84ad5f49d59e5e1d894e1edec5c25ffa2b5725786a9f721a8",
          "sha256": "abaa0605b8da1b9bf5d086b87a112a4b7f5dccea6de9ced42ef2108256cdccd6",
          "sha1": "a909346f8a6699f60ead98cb143a4ee8a24cc45e",
          "md5": "7c353bb9c3ea73fea6526e9cbdd85a7e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.11.0-bump-okhttp-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-bump-okhttp-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.11.0-bump-okhttp-SNAPSHOT.jar",
          "url": "auth-jvm-1.11.0-bump-okhttp-SNAPSHOT.jar",
          "size": 34318,
          "sha512": "6854c21bdf6c13e9e9ed9eb7b7478ea3d98d5b75d9a3c9c02e37e613061fd50a7eee4b5214c06ff84ad5f49d59e5e1d894e1edec5c25ffa2b5725786a9f721a8",
          "sha256": "abaa0605b8da1b9bf5d086b87a112a4b7f5dccea6de9ced42ef2108256cdccd6",
          "sha1": "a909346f8a6699f60ead98cb143a4ee8a24cc45e",
          "md5": "7c353bb9c3ea73fea6526e9cbdd85a7e"
        }
      ]
    }
  ]
}
