{
  "formatVersion": "1.1",
  "component": {
    "url": "../../example-kmp-library/0.0.1-add-jacoco-coverage-SNAPSHOT/example-kmp-library-0.0.1-add-jacoco-coverage-SNAPSHOT.module",
    "group": "care.data4life.hc-gradle-scripts",
    "module": "example-kmp-library",
    "version": "0.0.1-add-jacoco-coverage-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "vl2isglfefbopnxit3626m2xjq"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "example-kmp-library-jvm-0.0.1-add-jacoco-coverage-SNAPSHOT.jar",
          "url": "example-kmp-library-jvm-0.0.1-add-jacoco-coverage-SNAPSHOT.jar",
          "size": 16602,
          "sha512": "7ab7882dd0a0149410c6e21bab4f060f03c09b9e4c39c1d3f59d6ada7a992fc4d4cb7742ebf854ae052ee16623512e5d6dab9718c5290bf3470be6c8cb8ff32c",
          "sha256": "f497f8a996ad94a5c548133425120470add6a3e8bdcf0547daeb7943b765b178",
          "sha1": "a50908a746781c2062c4998f3bbbc517ca8702fa",
          "md5": "030463420a696286fc1cd0de89cbc374"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "example-kmp-library-jvm-0.0.1-add-jacoco-coverage-SNAPSHOT.jar",
          "url": "example-kmp-library-jvm-0.0.1-add-jacoco-coverage-SNAPSHOT.jar",
          "size": 16602,
          "sha512": "7ab7882dd0a0149410c6e21bab4f060f03c09b9e4c39c1d3f59d6ada7a992fc4d4cb7742ebf854ae052ee16623512e5d6dab9718c5290bf3470be6c8cb8ff32c",
          "sha256": "f497f8a996ad94a5c548133425120470add6a3e8bdcf0547daeb7943b765b178",
          "sha1": "a50908a746781c2062c4998f3bbbc517ca8702fa",
          "md5": "030463420a696286fc1cd0de89cbc374"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../example-kmp-library-metadata/0.0.1-add-jacoco-coverage-SNAPSHOT/example-kmp-library-metadata-0.0.1-add-jacoco-coverage-SNAPSHOT.module",
        "group": "care.data4life.hc-gradle-scripts",
        "module": "example-kmp-library-metadata",
        "version": "0.0.1-add-jacoco-coverage-SNAPSHOT"
      }
    }
  ]
}
