{
  "formatVersion": "1.1",
  "component": {
    "url": "../../example-kmp-library/0.0.1-add-android-example-app-SNAPSHOT/example-kmp-library-0.0.1-add-android-example-app-SNAPSHOT.module",
    "group": "care.data4life.hc-gradle-scripts",
    "module": "example-kmp-library",
    "version": "0.0.1-add-android-example-app-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "s4tegbxlszetpn4ilovry7jhgm"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "example-kmp-library-jvm-0.0.1-add-android-example-app-SNAPSHOT.jar",
          "url": "example-kmp-library-jvm-0.0.1-add-android-example-app-SNAPSHOT.jar",
          "size": 16692,
          "sha512": "e6b9a9f688aabd1c8eaecc0c2bb5ef180ec5038ef46f2a270c647a4b11aae1338afcd5877f46e8a4275a5db2739f97167cdff5a668620de571d004ec61594d19",
          "sha256": "3bc24f31a73a1bf71b5cdae4f7fc6c04bd9e8e563750b706f0998fea574d096d",
          "sha1": "b775f6b6eb043cd77fce672e499e17f4181a725f",
          "md5": "f9d4e68a01b80e9a5eb8cd19a9cd1116"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "example-kmp-library-jvm-0.0.1-add-android-example-app-SNAPSHOT.jar",
          "url": "example-kmp-library-jvm-0.0.1-add-android-example-app-SNAPSHOT.jar",
          "size": 16692,
          "sha512": "e6b9a9f688aabd1c8eaecc0c2bb5ef180ec5038ef46f2a270c647a4b11aae1338afcd5877f46e8a4275a5db2739f97167cdff5a668620de571d004ec61594d19",
          "sha256": "3bc24f31a73a1bf71b5cdae4f7fc6c04bd9e8e563750b706f0998fea574d096d",
          "sha1": "b775f6b6eb043cd77fce672e499e17f4181a725f",
          "md5": "f9d4e68a01b80e9a5eb8cd19a9cd1116"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../example-kmp-library-metadata/0.0.1-add-android-example-app-SNAPSHOT/example-kmp-library-metadata-0.0.1-add-android-example-app-SNAPSHOT.module",
        "group": "care.data4life.hc-gradle-scripts",
        "module": "example-kmp-library-metadata",
        "version": "0.0.1-add-android-example-app-SNAPSHOT"
      }
    }
  ]
}
