{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.11.0-add-interceptors-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "x4sy7hm7ivevzne7z5vn5d7fei"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-add-interceptors-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.11.0-add-interceptors-SNAPSHOT.jar",
          "url": "auth-jvm-1.11.0-add-interceptors-SNAPSHOT.jar",
          "size": 34318,
          "sha512": "6a794cf51e65b77f735938fece1f8869ed010614dca4da0a0efe56bbdbd8178b2b4b911d984d585851bc0b60eb1a3f53c48844d6d6ef29024b8a35aaca288e15",
          "sha256": "57558efae59849f0585770195358973ced3285c440d4295ca7ab6fb7bbf06095",
          "sha1": "2fbfe9215d3b85a87fb8554e92325f551d4ffa17",
          "md5": "9d92d420f294ea1562e1dd238e434a94"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.11.0-add-interceptors-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-add-interceptors-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.11.0-add-interceptors-SNAPSHOT.jar",
          "url": "auth-jvm-1.11.0-add-interceptors-SNAPSHOT.jar",
          "size": 34318,
          "sha512": "6a794cf51e65b77f735938fece1f8869ed010614dca4da0a0efe56bbdbd8178b2b4b911d984d585851bc0b60eb1a3f53c48844d6d6ef29024b8a35aaca288e15",
          "sha256": "57558efae59849f0585770195358973ced3285c440d4295ca7ab6fb7bbf06095",
          "sha1": "2fbfe9215d3b85a87fb8554e92325f551d4ffa17",
          "md5": "9d92d420f294ea1562e1dd238e434a94"
        }
      ]
    }
  ]
}
