{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.11.0-add-interceptors-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "kecct5uhzravrnidg46gsglloi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-add-interceptors-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.11.0-add-interceptors-SNAPSHOT.jar",
          "url": "auth-jvm-1.11.0-add-interceptors-SNAPSHOT.jar",
          "size": 34318,
          "sha512": "d32cab40ad09f04c6e36b6906982a41c1421cec5519564c9128bba6035ca7cc310a97b3e2341664a94c36e4afe262369fec44dddb1ebb6f698bd2341c2262486",
          "sha256": "548cf51ade3628dce17b7c1e41a5ad0c6f553e369c5512e27c8fbfa80c8f0c05",
          "sha1": "61c5bbfb5fad8efe71a1e877727bbf4c33a3bf37",
          "md5": "cdfeacd7df85a0fda7aaba1099fde7c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.11.0-add-interceptors-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-add-interceptors-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.11.0-add-interceptors-SNAPSHOT.jar",
          "url": "auth-jvm-1.11.0-add-interceptors-SNAPSHOT.jar",
          "size": 34318,
          "sha512": "d32cab40ad09f04c6e36b6906982a41c1421cec5519564c9128bba6035ca7cc310a97b3e2341664a94c36e4afe262369fec44dddb1ebb6f698bd2341c2262486",
          "sha256": "548cf51ade3628dce17b7c1e41a5ad0c6f553e369c5512e27c8fbfa80c8f0c05",
          "sha1": "61c5bbfb5fad8efe71a1e877727bbf4c33a3bf37",
          "md5": "cdfeacd7df85a0fda7aaba1099fde7c3"
        }
      ]
    }
  ]
}
