{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-coroutine-test",
    "version": "1.8.1-change-util-test-ktor-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "6q75cs4rtjbsbh5sq5c2aiw2mq"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-coroutine-test-metadata-1.8.1-change-util-test-ktor-SNAPSHOT.jar",
          "url": "util-coroutine-test-1.8.1-change-util-test-ktor-SNAPSHOT.jar",
          "size": 1777,
          "sha512": "0cf2148db411a53cf014f1d2cf1a95fa3bc9196ac3d918ff3060b4333ca92d28ce4209f0d2c79e15cba8ef4df647b3b8e74ec8703ae7d7bbf0a35abf4e186fbe",
          "sha256": "106c4d6c9e64191abc8aea3b98269fb6a4511249d103dbacf5e4a5f10a2519af",
          "sha1": "000332200ee4c7823fcce286c73eb2202159d7dd",
          "md5": "a135cb7846e2531a58cdd6aefb033112"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../util-coroutine-test-android-debug/1.8.1-change-util-test-ktor-SNAPSHOT/util-coroutine-test-android-debug-1.8.1-change-util-test-ktor-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-coroutine-test-android-debug",
        "version": "1.8.1-change-util-test-ktor-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../util-coroutine-test-android-debug/1.8.1-change-util-test-ktor-SNAPSHOT/util-coroutine-test-android-debug-1.8.1-change-util-test-ktor-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-coroutine-test-android-debug",
        "version": "1.8.1-change-util-test-ktor-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../util-coroutine-test-android/1.8.1-change-util-test-ktor-SNAPSHOT/util-coroutine-test-android-1.8.1-change-util-test-ktor-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-coroutine-test-android",
        "version": "1.8.1-change-util-test-ktor-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../util-coroutine-test-android/1.8.1-change-util-test-ktor-SNAPSHOT/util-coroutine-test-android-1.8.1-change-util-test-ktor-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-coroutine-test-android",
        "version": "1.8.1-change-util-test-ktor-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../util-coroutine-test-iosarm64/1.8.1-change-util-test-ktor-SNAPSHOT/util-coroutine-test-iosarm64-1.8.1-change-util-test-ktor-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-coroutine-test-iosarm64",
        "version": "1.8.1-change-util-test-ktor-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../util-coroutine-test-iosx64/1.8.1-change-util-test-ktor-SNAPSHOT/util-coroutine-test-iosx64-1.8.1-change-util-test-ktor-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-coroutine-test-iosx64",
        "version": "1.8.1-change-util-test-ktor-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../util-coroutine-test-jvm/1.8.1-change-util-test-ktor-SNAPSHOT/util-coroutine-test-jvm-1.8.1-change-util-test-ktor-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-coroutine-test-jvm",
        "version": "1.8.1-change-util-test-ktor-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../util-coroutine-test-jvm/1.8.1-change-util-test-ktor-SNAPSHOT/util-coroutine-test-jvm-1.8.1-change-util-test-ktor-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-coroutine-test-jvm",
        "version": "1.8.1-change-util-test-ktor-SNAPSHOT"
      }
    }
  ]
}
