{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.3-change-latest-consent-SNAPSHOT/data-donation-sdk-iosx64-0.1.3-change-latest-consent-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.3-change-latest-consent-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "g63bg2lbhnd4reujhgsw7ywuze"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.3-change-latest-consent-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.3-change-latest-consent-SNAPSHOT.jar",
          "size": 33909,
          "sha512": "7c133fcc5846cb0447a327284b7984a6f7a0e03ea71584bf26fcaf76602391780f4fa4f17480ecaa59b3379f05be0d6ab39c584698b2dd2124e1a94447d0cffd",
          "sha256": "31fe2740dbece458d7e5244e79f5cbbed6926aa355af7e1255eeae0a56c3ca67",
          "sha1": "2ca92bbb4f347f67debf934092eb20fbdc6fd2e9",
          "md5": "82a11365554d9f579b9d433d2066c275"
        }
      ]
    }
  ]
}
