{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp.hc-sdk-kmp",
    "module": "sdk-jvm",
    "version": "1.15.1-change-documentation-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.15.1-change-documentation-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-result-sdk-kmp",
              "module": "error-android-debug"
            },
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.15.1-change-documentation-SNAPSHOT.jar",
          "url": "sdk-jvm-1.15.1-change-documentation-SNAPSHOT.jar",
          "size": 11637,
          "sha512": "09282f72ac306d964c5b47a95cb353c3322adb65f22f7de8c2e5d33bd50190f5d6e42e65fb2dc3f625defcf4c31eb73d8db069a54a49e54756bc9f5248542110",
          "sha256": "d9c092f81a5ba4838fa1306edd9dfc2ea222d8b6771250910bde34cf1ee62ef4",
          "sha1": "4ff64d55cac5d248f8e3d433ba0e1afaf8742257",
          "md5": "850d3148124d02fc58b351853f014b55"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-auth-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.14.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-result-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "care.data4life.hc-crypto-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.13.2"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-result-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "care.data4life.hc-securestore-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.13.2"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-result-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-result-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.6.3"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-result-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.5.1"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-result-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-result-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-result-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "care.data4life.hc-sdk-kmp.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.15.1-change-documentation-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-result-sdk-kmp",
              "module": "error-android-debug"
            },
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.15.1-change-documentation-SNAPSHOT.jar",
          "url": "sdk-jvm-1.15.1-change-documentation-SNAPSHOT.jar",
          "size": 11637,
          "sha512": "09282f72ac306d964c5b47a95cb353c3322adb65f22f7de8c2e5d33bd50190f5d6e42e65fb2dc3f625defcf4c31eb73d8db069a54a49e54756bc9f5248542110",
          "sha256": "d9c092f81a5ba4838fa1306edd9dfc2ea222d8b6771250910bde34cf1ee62ef4",
          "sha1": "4ff64d55cac5d248f8e3d433ba0e1afaf8742257",
          "md5": "850d3148124d02fc58b351853f014b55"
        }
      ]
    }
  ]
}
