{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-coroutine/1.8.1-add-coroutine-util-SNAPSHOT/util-coroutine-1.8.1-add-coroutine-util-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-coroutine",
    "version": "1.8.1-add-coroutine-util-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "3gxapi3hobc3za3qtxn6bz6taa"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-coroutine-jvm-1.8.1-add-coroutine-util-SNAPSHOT.jar",
          "url": "util-coroutine-jvm-1.8.1-add-coroutine-util-SNAPSHOT.jar",
          "size": 8508,
          "sha512": "9a5a14e6e87201b33c1d292d962cf6d2f843756da4fa4b80e05e4326ea86e0ad688ca0d7041dc0783da35813d2b30a7bfc3f920e92ca580e98b1687cbdddec97",
          "sha256": "dd5f06aac705c598372a3d52eb97fd0702c6c3d41669b5830fe33ba96350702e",
          "sha1": "0b61c7ecfb161d3d9631e976795dc95a96e4a11c",
          "md5": "2dd85199f9b436deabf5e6153154fe9a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "util-coroutine-jvm-1.8.1-add-coroutine-util-SNAPSHOT.jar",
          "url": "util-coroutine-jvm-1.8.1-add-coroutine-util-SNAPSHOT.jar",
          "size": 8508,
          "sha512": "9a5a14e6e87201b33c1d292d962cf6d2f843756da4fa4b80e05e4326ea86e0ad688ca0d7041dc0783da35813d2b30a7bfc3f920e92ca580e98b1687cbdddec97",
          "sha256": "dd5f06aac705c598372a3d52eb97fd0702c6c3d41669b5830fe33ba96350702e",
          "sha1": "0b61c7ecfb161d3d9631e976795dc95a96e4a11c",
          "md5": "2dd85199f9b436deabf5e6153154fe9a"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-coroutine-metadata/1.8.1-add-coroutine-util-SNAPSHOT/util-coroutine-metadata-1.8.1-add-coroutine-util-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-coroutine-metadata",
        "version": "1.8.1-add-coroutine-util-SNAPSHOT"
      }
    }
  ]
}
