{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.11.0-fix-updateRecord-checks-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "uqypsdpftrervn3osaqkitvtmm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-fix-updateRecord-checks-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.11.0-fix-updateRecord-checks-SNAPSHOT.jar",
          "url": "crypto-jvm-1.11.0-fix-updateRecord-checks-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "0894831ded99c3a4eff064ba223f2f6e2ed720f6f4ef8046bae24c1a0947ce0d0e6f394503ec4edf7f0d633dfc16cb432e03712bf74306ad5b66aa4d1f9a29f8",
          "sha256": "6aaa1b683d0801698f42a8c2ebe7acd582ab2ff847966803fa1bde9f72925fc1",
          "sha1": "3da808bd9369f2fc5f7f5c2777620b2dc80f50a7",
          "md5": "bb65d5aa28f1785219683911b34ba762"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-fix-updateRecord-checks-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.11.0-fix-updateRecord-checks-SNAPSHOT.jar",
          "url": "crypto-jvm-1.11.0-fix-updateRecord-checks-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "0894831ded99c3a4eff064ba223f2f6e2ed720f6f4ef8046bae24c1a0947ce0d0e6f394503ec4edf7f0d633dfc16cb432e03712bf74306ad5b66aa4d1f9a29f8",
          "sha256": "6aaa1b683d0801698f42a8c2ebe7acd582ab2ff847966803fa1bde9f72925fc1",
          "sha1": "3da808bd9369f2fc5f7f5c2777620b2dc80f50a7",
          "md5": "bb65d5aa28f1785219683911b34ba762"
        }
      ]
    }
  ]
}
