{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.7.0-add-coroutine-test-util-SNAPSHOT/util-1.7.0-add-coroutine-test-util-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.7.0-add-coroutine-test-util-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "lq5f7ap6czaibh3exgfmmtufqy"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-jvm-1.7.0-add-coroutine-test-util-SNAPSHOT.jar",
          "url": "util-jvm-1.7.0-add-coroutine-test-util-SNAPSHOT.jar",
          "size": 19627,
          "sha512": "5162140b97c165aaf4de1eb1d8c3163ab7351fa027f3071d6520f487d51a25cf9d8b53cd8246ba1593e45594eec8f694b27397cbd07065714ae189a49904080b",
          "sha256": "a302b59bb04dcc19ce342be70c1de9f5de464ac00793425f39315ed06a16d692",
          "sha1": "176a9472c17b201035e5faa4fdfd36dd771c7994",
          "md5": "85a7a168419d75e0e26cc906aa36b218"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "util-jvm-1.7.0-add-coroutine-test-util-SNAPSHOT.jar",
          "url": "util-jvm-1.7.0-add-coroutine-test-util-SNAPSHOT.jar",
          "size": 19627,
          "sha512": "5162140b97c165aaf4de1eb1d8c3163ab7351fa027f3071d6520f487d51a25cf9d8b53cd8246ba1593e45594eec8f694b27397cbd07065714ae189a49904080b",
          "sha256": "a302b59bb04dcc19ce342be70c1de9f5de464ac00793425f39315ed06a16d692",
          "sha1": "176a9472c17b201035e5faa4fdfd36dd771c7994",
          "md5": "85a7a168419d75e0e26cc906aa36b218"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-metadata/1.7.0-add-coroutine-test-util-SNAPSHOT/util-metadata-1.7.0-add-coroutine-test-util-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-metadata",
        "version": "1.7.0-add-coroutine-test-util-SNAPSHOT"
      }
    }
  ]
}
