{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-android",
    "version": "1.15.1-fix-group-id-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.15.1-fix-group-id-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            },
            {
              "group": "*",
              "module": "auth-jvm"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            },
            {
              "group": "*",
              "module": "securestore-jvm"
            },
            {
              "group": "*",
              "module": "crypto-jvm"
            },
            {
              "group": "org.threeten",
              "module": "threetenbp"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-jvm"
            }
          ]
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.13.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "error-android",
          "version": {
            "requires": "1.13.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-android-1.15.1-fix-group-id-SNAPSHOT.aar",
          "url": "sdk-android-1.15.1-fix-group-id-SNAPSHOT.aar",
          "size": 28357,
          "sha512": "54f898c69bc32bc0c62f3fa955c96a87fa4378b1fd63fe4dbc4d5d64a654d4d19ed1e1b99f007e82a0ca81fa90d7e033541d4ad5102892cfaa9cdafe921979d4",
          "sha256": "1e699a8d0ba6bc74587ec9b74f4621c97e5e44190c377e50dea7e9083d8845b8",
          "sha1": "bf4840420bd16a3b1bd2f8cdb3f7bf3800080edf",
          "md5": "8b05d147ede221baddb313f913aac7c7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.15.1-fix-group-id-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            },
            {
              "group": "*",
              "module": "auth-jvm"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            },
            {
              "group": "*",
              "module": "securestore-jvm"
            },
            {
              "group": "*",
              "module": "crypto-jvm"
            },
            {
              "group": "org.threeten",
              "module": "threetenbp"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-jvm"
            }
          ]
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.13.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "error-android",
          "version": {
            "requires": "1.13.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "care.data4life.hc-auth-sdk-kmp",
          "module": "auth-android",
          "version": {
            "requires": "1.15.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "care.data4life.hc-crypto-sdk-kmp",
          "module": "crypto-android",
          "version": {
            "requires": "1.15.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "care.data4life.hc-securestore-sdk-kmp",
          "module": "securestore-android",
          "version": {
            "requires": "1.15.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "com.jakewharton.threetenabp",
          "module": "threetenabp",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.3"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.3"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "net.openid",
          "module": "appauth",
          "version": {
            "requires": "0.11.1"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.71"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android-debug"
            },
            {
              "group": "care.data4life.hc-securestore-sdk-kmp",
              "module": "securestore-android-debug"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "error-android-debug"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-android-1.15.1-fix-group-id-SNAPSHOT.aar",
          "url": "sdk-android-1.15.1-fix-group-id-SNAPSHOT.aar",
          "size": 28357,
          "sha512": "54f898c69bc32bc0c62f3fa955c96a87fa4378b1fd63fe4dbc4d5d64a654d4d19ed1e1b99f007e82a0ca81fa90d7e033541d4ad5102892cfaa9cdafe921979d4",
          "sha256": "1e699a8d0ba6bc74587ec9b74f4621c97e5e44190c377e50dea7e9083d8845b8",
          "sha1": "bf4840420bd16a3b1bd2f8cdb3f7bf3800080edf",
          "md5": "8b05d147ede221baddb313f913aac7c7"
        }
      ]
    }
  ]
}
