{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.12.0-bump-fhir-java-sdk-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "mva6kdav5zc2hl2l4n3zguil34"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.12.0-bump-fhir-java-sdk-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.12.0-bump-fhir-java-sdk-SNAPSHOT.jar",
          "url": "crypto-jvm-1.12.0-bump-fhir-java-sdk-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "8a3ef622549d8e196f0373457ffb9f0e98a6bdb853a9e309907da3a42539cab35ecd6e450a06834405454c8a0fb0ddcd0903d948bb1f7c8de3449cbf4c0dd99f",
          "sha256": "d60c364a45bc51276afcb938c8cbbd1ba84257e1b258f72cd6f7fd38b6f5a5e1",
          "sha1": "fd54e308afe95c7e453bd5e1140be1af57e14a81",
          "md5": "f3ce9fab8fbb8f52509ce13d091864b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.12.0-bump-fhir-java-sdk-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.12.0-bump-fhir-java-sdk-SNAPSHOT.jar",
          "url": "crypto-jvm-1.12.0-bump-fhir-java-sdk-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "8a3ef622549d8e196f0373457ffb9f0e98a6bdb853a9e309907da3a42539cab35ecd6e450a06834405454c8a0fb0ddcd0903d948bb1f7c8de3449cbf4c0dd99f",
          "sha256": "d60c364a45bc51276afcb938c8cbbd1ba84257e1b258f72cd6f7fd38b6f5a5e1",
          "sha1": "fd54e308afe95c7e453bd5e1140be1af57e14a81",
          "md5": "f3ce9fab8fbb8f52509ce13d091864b4"
        }
      ]
    }
  ]
}
