{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.9.0-remove-migrated-features-SNAPSHOT/util-1.9.0-remove-migrated-features-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.9.0-remove-migrated-features-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "s43tid3qbfb6de5dc6unvpeeju"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-jvm-1.9.0-remove-migrated-features-SNAPSHOT.jar",
          "url": "util-jvm-1.9.0-remove-migrated-features-SNAPSHOT.jar",
          "size": 14923,
          "sha512": "20d2d96b2d6e3c7b0ba2998cdc89ff7aa46d4b642a17f4861caf6c5e705374302ec4eb44d620476c12614e154eeb846308db1824ad179ade5f1d98eb4157d3c3",
          "sha256": "ddd2cb176b6a5cb94b7ed3b4813a4359d58d19519622568f045a5f6efea060b8",
          "sha1": "05dc4c99b799eba429c4b7323a2c0facd600ae37",
          "md5": "2ef4a7a3cd912418f56a8655d3658986"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "util-jvm-1.9.0-remove-migrated-features-SNAPSHOT.jar",
          "url": "util-jvm-1.9.0-remove-migrated-features-SNAPSHOT.jar",
          "size": 14923,
          "sha512": "20d2d96b2d6e3c7b0ba2998cdc89ff7aa46d4b642a17f4861caf6c5e705374302ec4eb44d620476c12614e154eeb846308db1824ad179ade5f1d98eb4157d3c3",
          "sha256": "ddd2cb176b6a5cb94b7ed3b4813a4359d58d19519622568f045a5f6efea060b8",
          "sha1": "05dc4c99b799eba429c4b7323a2c0facd600ae37",
          "md5": "2ef4a7a3cd912418f56a8655d3658986"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-metadata/1.9.0-remove-migrated-features-SNAPSHOT/util-metadata-1.9.0-remove-migrated-features-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-metadata",
        "version": "1.9.0-remove-migrated-features-SNAPSHOT"
      }
    }
  ]
}
