{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.11.0-change-api-module-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "luqx74dezja57hfq7xdgoshhiq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-change-api-module-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.11.0-change-api-module-tests-SNAPSHOT.jar",
          "url": "crypto-jvm-1.11.0-change-api-module-tests-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "162392110bd3104904f9f2a9b7e8531dce61e0366d19ec4487bd48148cfc7434778f46e4fa7f9b3601a2694826e3c58241280b82668b95915487ceace795f305",
          "sha256": "2dbf5fa64cdb145de6946d95d295bd4e61881566ed25b8850240450c3fe93ad7",
          "sha1": "c85d435535f92ccadc89b6efbef61297f8ecdee5",
          "md5": "203e1757eb5804104b2463251e80e5a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-change-api-module-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.11.0-change-api-module-tests-SNAPSHOT.jar",
          "url": "crypto-jvm-1.11.0-change-api-module-tests-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "162392110bd3104904f9f2a9b7e8531dce61e0366d19ec4487bd48148cfc7434778f46e4fa7f9b3601a2694826e3c58241280b82668b95915487ceace795f305",
          "sha256": "2dbf5fa64cdb145de6946d95d295bd4e61881566ed25b8850240450c3fe93ad7",
          "sha1": "c85d435535f92ccadc89b6efbef61297f8ecdee5",
          "md5": "203e1757eb5804104b2463251e80e5a3"
        }
      ]
    }
  ]
}
