{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.11.0-change-api-module-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "yh7v6gktcnclfmkyqperhteof4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-change-api-module-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.11.0-change-api-module-tests-SNAPSHOT.jar",
          "url": "crypto-jvm-1.11.0-change-api-module-tests-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "11e4149b9c8db629f04133a8d7971743bbfff5f07d46455a0477edb5923bae9df10cf3a5764d74f3201513b740d5fd48e009e05c80471298a68e58cf004dcd37",
          "sha256": "955a2664785a23d3ba055970466461eaf8827b73a5d6cadfa967d4175bace0b5",
          "sha1": "35c2f1b6136099c30a922cd25db6df6c8891aa75",
          "md5": "ad0b58b0182f03f7cb6fcfa2c347bebd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-change-api-module-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.11.0-change-api-module-tests-SNAPSHOT.jar",
          "url": "crypto-jvm-1.11.0-change-api-module-tests-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "11e4149b9c8db629f04133a8d7971743bbfff5f07d46455a0477edb5923bae9df10cf3a5764d74f3201513b740d5fd48e009e05c80471298a68e58cf004dcd37",
          "sha256": "955a2664785a23d3ba055970466461eaf8827b73a5d6cadfa967d4175bace0b5",
          "sha1": "35c2f1b6136099c30a922cd25db6df6c8891aa75",
          "md5": "ad0b58b0182f03f7cb6fcfa2c347bebd"
        }
      ]
    }
  ]
}
