{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-ktor/0.3.0-SNAPSHOT/test-util-ktor-0.3.0-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-ktor",
    "version": "0.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.8"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor.klib",
          "url": "test-util-ktor-iosarm64-0.3.0-SNAPSHOT.klib",
          "size": 15772,
          "sha512": "e8cfcf34869e3bbd205bf4871362cae0f70555f3fc2a203063f6f80e29b47e7cbed06ef904c18027610a779232f65f46ad32f0c788101d1178af0133399a0497",
          "sha256": "640de9ad2f664cc8515e5992d5600f8ee9428442f762b32ad2afc7cc9c12c616",
          "sha1": "835dde8e84698a54ef79ba4aa97355da630f6e07",
          "md5": "eeab497d7bac5d84b3a32b75402288fe"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.8"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor-iosarm64-0.3.0-SNAPSHOT-metadata.jar",
          "url": "test-util-ktor-iosarm64-0.3.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "25198e726213ed870eac91d6cea4fdfcd68658f3125b696588c66c406db48c1e258b0fd3f199e605dabb51e7fefd911a7cbaf536a70bee83b89028c847afe152",
          "sha256": "63c959765df28809f7fd52e368a594cd9554d1d24e584bda15e8ad205e71f79f",
          "sha1": "ae804e1d47c4ab047208db8b0582503a4c719a92",
          "md5": "bab236b37776dab89e69c2d8ee1c735a"
        }
      ]
    }
  ]
}
