{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-ktor/0.3.0-SNAPSHOT/test-util-ktor-0.3.0-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-ktor",
    "version": "0.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor.klib",
          "url": "test-util-ktor-iosarm64-0.3.0-SNAPSHOT.klib",
          "size": 15772,
          "sha512": "e8cfcf34869e3bbd205bf4871362cae0f70555f3fc2a203063f6f80e29b47e7cbed06ef904c18027610a779232f65f46ad32f0c788101d1178af0133399a0497",
          "sha256": "640de9ad2f664cc8515e5992d5600f8ee9428442f762b32ad2afc7cc9c12c616",
          "sha1": "835dde8e84698a54ef79ba4aa97355da630f6e07",
          "md5": "eeab497d7bac5d84b3a32b75402288fe"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor-iosarm64-0.3.0-SNAPSHOT-metadata.jar",
          "url": "test-util-ktor-iosarm64-0.3.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "9693cc6d4db282404992ae4ac95cbde5b7a8ed8f6adc668969ffa957fb3eaf6d83665cb6bb00ea3d07c7f8d71790bb63f4a8328d87564a6e9bd9913cfccd90f8",
          "sha256": "7cad12b47ab70a9342bd3ebf4ebe3a3858513a4426aeb7463267e9dc9de07780",
          "sha1": "60b6c827d0293fa49ea10cafafe75f2f0029f3d3",
          "md5": "bcbae233f35d10478fba64ac811126eb"
        }
      ]
    }
  ]
}
