{
  "formatVersion": "1.1",
  "component": {
    "url": "../../example-kmp-library/0.0.1-bump-dependencies-SNAPSHOT/example-kmp-library-0.0.1-bump-dependencies-SNAPSHOT.module",
    "group": "care.data4life.hc-gradle-scripts",
    "module": "example-kmp-library",
    "version": "0.0.1-bump-dependencies-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "j2m2qp4mqna3jckewsjlmjvla4"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "example-kmp-library-jvm-0.0.1-bump-dependencies-SNAPSHOT.jar",
          "url": "example-kmp-library-jvm-0.0.1-bump-dependencies-SNAPSHOT.jar",
          "size": 14516,
          "sha512": "0b6e6d1a68678e0d4a6edb8cfbf17134b60e4b13eaf0a21b017f05564db22933d88f81039309bd1dca999bac598d56eccb73fa6edd07708e68ea86c46a2a2177",
          "sha256": "41c950dd002a7c2e16aae33341298081092622d7c9686c4f867ad5b3207ecb7e",
          "sha1": "5bed27fad768228a00017857d625a9a8ce8e542c",
          "md5": "5318ef913f3133f802b4f336ac8da0a0"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "example-kmp-library-jvm-0.0.1-bump-dependencies-SNAPSHOT.jar",
          "url": "example-kmp-library-jvm-0.0.1-bump-dependencies-SNAPSHOT.jar",
          "size": 14516,
          "sha512": "0b6e6d1a68678e0d4a6edb8cfbf17134b60e4b13eaf0a21b017f05564db22933d88f81039309bd1dca999bac598d56eccb73fa6edd07708e68ea86c46a2a2177",
          "sha256": "41c950dd002a7c2e16aae33341298081092622d7c9686c4f867ad5b3207ecb7e",
          "sha1": "5bed27fad768228a00017857d625a9a8ce8e542c",
          "md5": "5318ef913f3133f802b4f336ac8da0a0"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../example-kmp-library-metadata/0.0.1-bump-dependencies-SNAPSHOT/example-kmp-library-metadata-0.0.1-bump-dependencies-SNAPSHOT.module",
        "group": "care.data4life.hc-gradle-scripts",
        "module": "example-kmp-library-metadata",
        "version": "0.0.1-bump-dependencies-SNAPSHOT"
      }
    }
  ]
}
