{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk/0.1.3-add-program-SNAPSHOT/data-donation-sdk-0.1.3-add-program-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk",
    "version": "0.1.3-add-program-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "3yrxi2v2pzgsjarxbgfspj2hsm"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.6"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.1.6-a1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "1.1.6"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "care.data4life.hc-result-sdk-kmp",
          "module": "flow",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "care.data4life.hc-result-sdk-kmp",
          "module": "error",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "care.data4life.hc-coroutine-util-sdk-kmp",
          "module": "coroutine-util",
          "version": {
            "requires": "0.1.0"
          },
          "excludes": [
            {
              "group": "co.touchlab:stately-concurrency",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.4.3-native-mt",
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-ios",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "care.data4life.hc-objc-util-sdk-kmp",
          "module": "objc-util",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "data-donation-sdk.klib",
          "url": "data-donation-sdk-iosx64-0.1.3-add-program-SNAPSHOT.klib",
          "size": 130394,
          "sha512": "e0784ed93f6aa4c198c9be480fadd6dcfcdffa72218b1a57c3a27c68325e4bfa8af45711e72f281af527f002b36162065369b7c5d7aeb5e8861598c0781203e2",
          "sha256": "47cf8ef5019d2abf6996e66f49056196051755347a8b045a9cb093c9ad280486",
          "sha1": "e0626cf56ce022d25d49288b8ecad8fa71a5f39d",
          "md5": "f80edf769690890ee0e3899d64561484"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../data-donation-sdk-metadata/0.1.3-add-program-SNAPSHOT/data-donation-sdk-metadata-0.1.3-add-program-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-metadata",
        "version": "0.1.3-add-program-SNAPSHOT"
      }
    }
  ]
}
