{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-ktor",
    "version": "0.2.0-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor-metadata-0.2.0-bump-updates-SNAPSHOT-all.jar",
          "url": "test-util-ktor-0.2.0-bump-updates-SNAPSHOT-all.jar",
          "size": 5649,
          "sha512": "37ef78f83c843d87805eb734f9c74fec295cfcf0c46bcea2d25b3cd7bea44018620a18c2502c8b769a1c546f52b13f32126f0a07c40563557addd627f98e0e1a",
          "sha256": "8c9198ee4a27508fbb6167a37f7f570c21c13065949828d58f9157413b6cebf3",
          "sha1": "dba84c60d81ac6f5a2a751303ebbbbaf3a7122c8",
          "md5": "39c5ec6a979001584aebc6f9f5204e0a"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-util-ktor-0.2.0-bump-updates-SNAPSHOT.jar",
          "url": "test-util-ktor-0.2.0-bump-updates-SNAPSHOT.jar",
          "size": 3184,
          "sha512": "51ff6f110c066e9d3330fc1eff9e3632b65e0c13fd4c95603e7c992d4054f840158325c1d3589b777ffafb29f5f613f38c65603ca5ea48fac280a6c41913a2ef",
          "sha256": "4f922596cbe4eac83e2c0a60087f2fd156a1c740b27837452040aff064fbf01c",
          "sha1": "9e7d8c0d1c97900c47a5bf969ac2396662ffef8c",
          "md5": "2f29b81461c7aaebef50d58bb7e99fdd"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-util-ktor-android-debug/0.2.0-bump-updates-SNAPSHOT/test-util-ktor-android-debug-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-ktor-android-debug",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-util-ktor-android-debug/0.2.0-bump-updates-SNAPSHOT/test-util-ktor-android-debug-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-ktor-android-debug",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-util-ktor-android/0.2.0-bump-updates-SNAPSHOT/test-util-ktor-android-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-ktor-android",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-util-ktor-android/0.2.0-bump-updates-SNAPSHOT/test-util-ktor-android-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-ktor-android",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-util-ktor-iosarm64/0.2.0-bump-updates-SNAPSHOT/test-util-ktor-iosarm64-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-ktor-iosarm64",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-util-ktor-iosarm64/0.2.0-bump-updates-SNAPSHOT/test-util-ktor-iosarm64-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-ktor-iosarm64",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-util-ktor-iosx64/0.2.0-bump-updates-SNAPSHOT/test-util-ktor-iosx64-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-ktor-iosx64",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-util-ktor-iosx64/0.2.0-bump-updates-SNAPSHOT/test-util-ktor-iosx64-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-ktor-iosx64",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-util-ktor-jvm/0.2.0-bump-updates-SNAPSHOT/test-util-ktor-jvm-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-ktor-jvm",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-util-ktor-jvm/0.2.0-bump-updates-SNAPSHOT/test-util-ktor-jvm-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-ktor-jvm",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    }
  ]
}
