{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-ktor",
    "version": "0.2.0-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor-metadata-0.2.0-bump-updates-SNAPSHOT-all.jar",
          "url": "test-util-ktor-0.2.0-bump-updates-SNAPSHOT-all.jar",
          "size": 5649,
          "sha512": "ed438130a3e2db1dfdf5433ed0f2c006107fe12f7ab9a1166776563925cb709e1909f9e933afe65886f98fcfdbeb229b4a039de8e81f541456098a306ffa8f3f",
          "sha256": "6ecf1f287701af2057567991affec3a0b47785cd0e4c84a56c1d78cf4995fd41",
          "sha1": "2c611df0fe4c9c4308dfab968e0585f47abdcb4d",
          "md5": "7aaf12eda1973be678d80294e2be85f1"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-util-ktor-0.2.0-bump-updates-SNAPSHOT.jar",
          "url": "test-util-ktor-0.2.0-bump-updates-SNAPSHOT.jar",
          "size": 3184,
          "sha512": "6cacece254e583e9740da9bceed7cf668497463b868f37f4250ebeebacb60b7732a0f9e54365670727fd219452cdc3d867d905420ea07bf90e8521a99453cb08",
          "sha256": "91cc2f22cf05c5b23f8c1cafe19fff2193a6122ab47c86a7dbf3b609a6d5fabf",
          "sha1": "0c9a419a2df98869d39495152c49e9b4e0459602",
          "md5": "5c475ffa8db3b55c91bd0af7b09e5aa3"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-util-ktor-android-debug/0.2.0-bump-updates-SNAPSHOT/test-util-ktor-android-debug-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-ktor-android-debug",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-util-ktor-android-debug/0.2.0-bump-updates-SNAPSHOT/test-util-ktor-android-debug-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-ktor-android-debug",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-util-ktor-android/0.2.0-bump-updates-SNAPSHOT/test-util-ktor-android-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-ktor-android",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-util-ktor-android/0.2.0-bump-updates-SNAPSHOT/test-util-ktor-android-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-ktor-android",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-util-ktor-iosarm64/0.2.0-bump-updates-SNAPSHOT/test-util-ktor-iosarm64-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-ktor-iosarm64",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-util-ktor-iosarm64/0.2.0-bump-updates-SNAPSHOT/test-util-ktor-iosarm64-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-ktor-iosarm64",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-util-ktor-iosx64/0.2.0-bump-updates-SNAPSHOT/test-util-ktor-iosx64-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-ktor-iosx64",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-util-ktor-iosx64/0.2.0-bump-updates-SNAPSHOT/test-util-ktor-iosx64-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-ktor-iosx64",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-util-ktor-jvm/0.2.0-bump-updates-SNAPSHOT/test-util-ktor-jvm-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-ktor-jvm",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-util-ktor-jvm/0.2.0-bump-updates-SNAPSHOT/test-util-ktor-jvm-0.2.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-ktor-jvm",
        "version": "0.2.0-bump-updates-SNAPSHOT"
      }
    }
  ]
}
