{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir-stu3/0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT/fhir-stu3-0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir-stu3",
    "version": "0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-kmp",
          "module": "fhir",
          "version": {
            "requires": "0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-stu3.klib",
          "url": "fhir-stu3-iosarm64-0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT.klib",
          "size": 3985942,
          "sha512": "24334577b146d3da7505b17480a6afcb9717c917964133a765a09e463a9100ef31a86aab34dfd7f763781690c4ade056ade4395f6c6e4f144fb6da821471d23f",
          "sha256": "0098815522c19037c8b6b9e0ff4babdcef79617f223df78bb4e5c8a290490fac",
          "sha1": "583555e9c383b6ab24799245cc4fca0a646a20f5",
          "md5": "af0ef84a53e084a2808ebde319f42610"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-kmp",
          "module": "fhir",
          "version": {
            "requires": "0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-stu3-iosarm64-0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT-metadata.jar",
          "url": "fhir-stu3-iosarm64-0.2.0-change-fhir-sdk-to-separate-modules-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "aa1693540759e03d2b847986084edec90df2e21e2c6eaa1543687fc3302e21fc772dbc568a2fab5074578d1934c5ba1c8585cc359b432ca6d5a7f27a0637e497",
          "sha256": "3ed8aff80b6b02103cc4e2b2159e48747407798f5c057ff08f666a20117c90f1",
          "sha1": "95adc9446333eab1d3c5fbe05304ce4f55abbcdb",
          "md5": "85c228716a2c722dedd54656e666fed1"
        }
      ]
    }
  ]
}
