{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir-jvm/0.1.0-add-spotless-SNAPSHOT/fhir-jvm-0.1.0-add-spotless-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir-jvm",
    "version": "0.1.0-add-spotless-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "nonq5wpy5jdltbfa3sogegfyju"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "fhir-metadata-0.1.0-add-spotless-SNAPSHOT.jar",
          "url": "fhir-metadata-0.1.0-add-spotless-SNAPSHOT.jar",
          "size": 522472,
          "sha512": "774cd0edc76e1b392a6c87a0b3f0775b1d3d9dc1675bdb8fd63532218b8497ed7ef43d006a429faf78123a56e413002043f74896683291ac88dadf6b40870e34",
          "sha256": "d03d00b298089cdfb3877f411a41b36130b00de02af2d3a40c46c33383f9cb89",
          "sha1": "b0bc4fa20ceaff9c22103c772cb276a6ee0606cc",
          "md5": "25c6ebef426ab649f737be6ce90d09cb"
        }
      ]
    }
  ]
}
