{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-coroutine-test-jvm/1.9.0-change-setup-SNAPSHOT/util-coroutine-test-jvm-1.9.0-change-setup-SNAPSHOT.module",
    "group": "care.data4life.hc-coroutine-util-sdk-kmp",
    "module": "util-coroutine-test-jvm",
    "version": "1.9.0-change-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "yorverysjbczhdukaj2axvo7um"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-coroutine-test-metadata-1.9.0-change-setup-SNAPSHOT.jar",
          "url": "util-coroutine-test-metadata-1.9.0-change-setup-SNAPSHOT.jar",
          "size": 1777,
          "sha512": "487b5f975f4305e439486c513ddd12b67fa3a9f537cc4dbe5067c6a885c0be706616b817b29040d35ef1364e528bbdc6ccd65a3d974bcbe2454287f822d0a451",
          "sha256": "728c1065cfad29357f3e1ed25d8d513c8900d7f1588180b0eb457ab7c8a0278e",
          "sha1": "3108f9f4ac216b16f305cf29a7eb7d52e044789c",
          "md5": "802d7c68beb795c139d763407777367d"
        }
      ]
    }
  ]
}
