{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir",
    "version": "0.1.0-add-full-fhir4-support-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "fhir-metadata-0.1.0-add-full-fhir4-support-SNAPSHOT.jar",
          "url": "fhir-0.1.0-add-full-fhir4-support-SNAPSHOT.jar",
          "size": 2395579,
          "sha512": "76c6d21834c1f6cdac677cb44be2782625106c4577fb56e9df238a7573446595bff1abd37f5de49d993ac2ee0e7d95a31722fc1d5662f7309ec76b26ec207883",
          "sha256": "f192e039639be805ce1bece6c62e9feaf374e9eedd02ea9dd3c800118bf43f7d",
          "sha1": "5ac36685f39f5aeff6bec77525388a5debb6ce70",
          "md5": "b90eb43fd9527cb4dc71f341690c4048"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-android/0.1.0-add-full-fhir4-support-SNAPSHOT/fhir-android-0.1.0-add-full-fhir4-support-SNAPSHOT.module",
        "group": "care.data4life",
        "module": "fhir-android",
        "version": "0.1.0-add-full-fhir4-support-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-android/0.1.0-add-full-fhir4-support-SNAPSHOT/fhir-android-0.1.0-add-full-fhir4-support-SNAPSHOT.module",
        "group": "care.data4life",
        "module": "fhir-android",
        "version": "0.1.0-add-full-fhir4-support-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-android/0.1.0-add-full-fhir4-support-SNAPSHOT/fhir-android-0.1.0-add-full-fhir4-support-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-android",
        "version": "0.1.0-add-full-fhir4-support-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-android/0.1.0-add-full-fhir4-support-SNAPSHOT/fhir-android-0.1.0-add-full-fhir4-support-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-android",
        "version": "0.1.0-add-full-fhir4-support-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fhir-iosarm64/0.1.0-add-full-fhir4-support-SNAPSHOT/fhir-iosarm64-0.1.0-add-full-fhir4-support-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-iosarm64",
        "version": "0.1.0-add-full-fhir4-support-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fhir-iosx64/0.1.0-add-full-fhir4-support-SNAPSHOT/fhir-iosx64-0.1.0-add-full-fhir4-support-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-iosx64",
        "version": "0.1.0-add-full-fhir4-support-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../fhir-jvm/0.1.0-add-full-fhir4-support-SNAPSHOT/fhir-jvm-0.1.0-add-full-fhir4-support-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-jvm",
        "version": "0.1.0-add-full-fhir4-support-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../fhir-jvm/0.1.0-add-full-fhir4-support-SNAPSHOT/fhir-jvm-0.1.0-add-full-fhir4-support-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-jvm",
        "version": "0.1.0-add-full-fhir4-support-SNAPSHOT"
      }
    }
  ]
}
