{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.0.5-change-README-SNAPSHOT/data-donation-sdk-iosx64-0.0.5-change-README-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.0.5-change-README-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ldw7gjguc5hgzciod7y5qdzgge"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.5-change-README-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.0.5-change-README-SNAPSHOT.jar",
          "size": 40185,
          "sha512": "2dc253029126d5a920c213281ea01b238eb7926558198c0138f7dee2e4e76b65a389c523f6e0ac7d5890d06a43b36d47e2299eba0f5a2b0a0b663e2f6b995cba",
          "sha256": "4372c03fd2514de65982a4ec89fdf99431b3462e8bb2eacdf531f3d644267fb3",
          "sha1": "15d0dd58964589d014ddc6899989391b68ba5765",
          "md5": "275fd3b77bc1515ad18ebf02b39c3104"
        }
      ]
    }
  ]
}
