{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir-stu3/0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT/fhir-stu3-0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir-stu3",
    "version": "0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-kmp",
          "module": "fhir",
          "version": {
            "requires": "0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-stu3-release.aar",
          "url": "fhir-stu3-android-0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT.aar",
          "size": 6013056,
          "sha512": "0a0ce47d3279344fde457c650099183c525389cf8d28522e19da3fcad872ea85836f726b140e24a93956593f82c686448f7906b04d3ea77f4450a268d313c322",
          "sha256": "c23793adc1076b053939283084bc728e7f822a53ebecc74599438f3b31791596",
          "sha1": "0f6b08cb2a79df3442fda6d8d59c9ad03b2f1aba",
          "md5": "d5ddcf211b4c28c44126dd1ee84b5656"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-kmp",
          "module": "fhir",
          "version": {
            "requires": "0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-stu3-release.aar",
          "url": "fhir-stu3-android-0.2.0-add-fhir-r4-d4l-app-minimized-version-SNAPSHOT.aar",
          "size": 6013056,
          "sha512": "0a0ce47d3279344fde457c650099183c525389cf8d28522e19da3fcad872ea85836f726b140e24a93956593f82c686448f7906b04d3ea77f4450a268d313c322",
          "sha256": "c23793adc1076b053939283084bc728e7f822a53ebecc74599438f3b31791596",
          "sha1": "0f6b08cb2a79df3442fda6d8d59c9ad03b2f1aba",
          "md5": "d5ddcf211b4c28c44126dd1ee84b5656"
        }
      ]
    }
  ]
}
