{
  "formatVersion": "1.1",
  "component": {
    "url": "../../example-kmp-library-jvm/0.0.1-change-example-lib-SNAPSHOT/example-kmp-library-jvm-0.0.1-change-example-lib-SNAPSHOT.module",
    "group": "care.data4life.hc-gradle-scripts",
    "module": "example-kmp-library-jvm",
    "version": "0.0.1-change-example-lib-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "bh6wplazi5eofdypmy2xgngtzq"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "example-kmp-library-metadata-0.0.1-change-example-lib-SNAPSHOT.jar",
          "url": "example-kmp-library-metadata-0.0.1-change-example-lib-SNAPSHOT.jar",
          "size": 6554,
          "sha512": "1e8baecc8b7d015a9a3640e6e9121b42fb9e2c29402e60ce90eb430b594a250ef24c09bcc7a40354cf0657220b4fa50c7143156f4adde6d3864e963c17a62e5d",
          "sha256": "b6b2eff27f6adc9dc01e2fa88def3a8f13e2e963f0f20905d2e2aa155c8966d2",
          "sha1": "61b4ce0817cb3b3ddef63bd7362253a34c3856ea",
          "md5": "b9475eb1feb912f96da43b95f7a91c42"
        }
      ]
    }
  ]
}
