{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk",
    "version": "0.1.3-add-questionnaireresponseitemlist-wrapper-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "uivmltbt5za4xni7ztsnwfocjm"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.3-add-questionnaireresponseitemlist-wrapper-SNAPSHOT.jar",
          "url": "data-donation-sdk-0.1.3-add-questionnaireresponseitemlist-wrapper-SNAPSHOT.jar",
          "size": 107493,
          "sha512": "22da4345dc75d07f48e9c22aa8e03ff038039c38b8dc062973b3f85f26e218616f2ceb6731b1a913240d5eb7f579f5aa6a17274c490006e9e3eafbd006d7168b",
          "sha256": "ecefa3efad95b3f6f85085f1d6a67963a205b84e7396c17e9fe0bdb4505d5b04",
          "sha1": "d0aa213b990f4fbcf872d48fd0b5f6a8a79dac03",
          "md5": "3b590cb37fa95f92fb4e7faeb4d7beb9"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android-debug/0.1.3-add-questionnaireresponseitemlist-wrapper-SNAPSHOT/data-donation-sdk-android-debug-0.1.3-add-questionnaireresponseitemlist-wrapper-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android-debug",
        "version": "0.1.3-add-questionnaireresponseitemlist-wrapper-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android-debug/0.1.3-add-questionnaireresponseitemlist-wrapper-SNAPSHOT/data-donation-sdk-android-debug-0.1.3-add-questionnaireresponseitemlist-wrapper-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android-debug",
        "version": "0.1.3-add-questionnaireresponseitemlist-wrapper-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android/0.1.3-add-questionnaireresponseitemlist-wrapper-SNAPSHOT/data-donation-sdk-android-0.1.3-add-questionnaireresponseitemlist-wrapper-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android",
        "version": "0.1.3-add-questionnaireresponseitemlist-wrapper-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android/0.1.3-add-questionnaireresponseitemlist-wrapper-SNAPSHOT/data-donation-sdk-android-0.1.3-add-questionnaireresponseitemlist-wrapper-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android",
        "version": "0.1.3-add-questionnaireresponseitemlist-wrapper-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../data-donation-sdk-iosarm64/0.1.3-add-questionnaireresponseitemlist-wrapper-SNAPSHOT/data-donation-sdk-iosarm64-0.1.3-add-questionnaireresponseitemlist-wrapper-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-iosarm64",
        "version": "0.1.3-add-questionnaireresponseitemlist-wrapper-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../data-donation-sdk-iosx64/0.1.3-add-questionnaireresponseitemlist-wrapper-SNAPSHOT/data-donation-sdk-iosx64-0.1.3-add-questionnaireresponseitemlist-wrapper-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-iosx64",
        "version": "0.1.3-add-questionnaireresponseitemlist-wrapper-SNAPSHOT"
      }
    }
  ]
}
