{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-ktor/0.2.0-fix-labels-SNAPSHOT/test-util-ktor-0.2.0-fix-labels-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-ktor",
    "version": "0.2.0-fix-labels-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor.klib",
          "url": "test-util-ktor-iosx64-0.2.0-fix-labels-SNAPSHOT.klib",
          "size": 15005,
          "sha512": "4b5cfe5d52c304e429c0af886859d33d13ab5a8b50bfa5921c2e9d92a3b353612cfa2d411606c949f7e82fa3eb1bea05d720b1179cb296ca3615b3ff1062ca66",
          "sha256": "507585872a0c1411c255a7c77a9dc38ac1625144f52a284e87511baa71faecfd",
          "sha1": "e4dcd4d54d7ef9dd4717f8b88dc20c18cc65c321",
          "md5": "b345758e1955e374cb891010e338cff0"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor-iosx64-0.2.0-fix-labels-SNAPSHOT-metadata.jar",
          "url": "test-util-ktor-iosx64-0.2.0-fix-labels-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "a6d605316b28cd3c559fa58e991532ebaf835df83e419833d3ba7216dc9402293d3af6cab66889aad63f8ecc6466c1e8c8eebdb869c57d0710121acd3e40d109",
          "sha256": "20fbff2b8dbf2e578cce604a727c74b18735fd051fb085fd1196bb2ebc0ad587",
          "sha1": "6d6491ea10d691dc7d4f1ee7010a20d035cdbf66",
          "md5": "6a9bbde9a3a4e034917fd540506bd21c"
        }
      ]
    }
  ]
}
