{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-ingestion",
    "version": "1.11.0-add-envrioment-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "hojyvrcyxjexpegvtztn72b6fa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.11.0-add-envrioment-tests-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-ingestion-1.11.0-add-envrioment-tests-SNAPSHOT.jar",
          "url": "sdk-ingestion-1.11.0-add-envrioment-tests-SNAPSHOT.jar",
          "size": 18179,
          "sha512": "a2ee8c5e34090894765e344d581460a150d5ad1d4516a913c6a9b1305eeb9402c764af7e0336d0bb861c017399e5d2e7a535c5bd4d51170dd6f09725dabea1fe",
          "sha256": "eaf076e25ee6f1a0029588c89585d26064a104c5017dd5c3d8c2f922e562b641",
          "sha1": "fb39fd3b05384a473ed8aaccca70849fbec68712",
          "md5": "95cc8fb7b4e87cc89b8028d8f6cfb664"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.11.0-add-envrioment-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.11.0-add-envrioment-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.11.0-add-envrioment-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-helper-sdk-kmp",
          "module": "fhir-helper-jvm",
          "version": {
            "requires": "1.4.1"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            }
          ]
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.11.0-add-envrioment-tests-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-ingestion-1.11.0-add-envrioment-tests-SNAPSHOT.jar",
          "url": "sdk-ingestion-1.11.0-add-envrioment-tests-SNAPSHOT.jar",
          "size": 18179,
          "sha512": "a2ee8c5e34090894765e344d581460a150d5ad1d4516a913c6a9b1305eeb9402c764af7e0336d0bb861c017399e5d2e7a535c5bd4d51170dd6f09725dabea1fe",
          "sha256": "eaf076e25ee6f1a0029588c89585d26064a104c5017dd5c3d8c2f922e562b641",
          "sha1": "fb39fd3b05384a473ed8aaccca70849fbec68712",
          "md5": "95cc8fb7b4e87cc89b8028d8f6cfb664"
        }
      ]
    }
  ]
}
