{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.10.0-add-secure-store-and-crypto-service-kotlin-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "vpbm6lmtdvcl7gezbc5xya2ioe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-add-secure-store-and-crypto-service-kotlin-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-add-secure-store-and-crypto-service-kotlin-tests-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-add-secure-store-and-crypto-service-kotlin-tests-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "42f27a1de24fc5b2dec3cef3824dd1f4ba3a405b2c65c2969909de21120dcb558116e3fb37ae4075329045eff69c523f27131287c60a7a7826b74f1deb7132fb",
          "sha256": "8d607ed8c1dab1fc8e27437e4aa88496c35458e71b2a5398bc7888230f063d09",
          "sha1": "517b2b5f791ff47ae837314752044daee9d53790",
          "md5": "4b42d84d3e940a9c0ede6cf22e3a0e2e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-add-secure-store-and-crypto-service-kotlin-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-add-secure-store-and-crypto-service-kotlin-tests-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-add-secure-store-and-crypto-service-kotlin-tests-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "42f27a1de24fc5b2dec3cef3824dd1f4ba3a405b2c65c2969909de21120dcb558116e3fb37ae4075329045eff69c523f27131287c60a7a7826b74f1deb7132fb",
          "sha256": "8d607ed8c1dab1fc8e27437e4aa88496c35458e71b2a5398bc7888230f063d09",
          "sha1": "517b2b5f791ff47ae837314752044daee9d53790",
          "md5": "4b42d84d3e940a9c0ede6cf22e3a0e2e"
        }
      ]
    }
  ]
}
