{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.13.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ibnopu4mrjbqveajiujxmltyam"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.13.1-SNAPSHOT.jar",
          "url": "auth-common-1.13.1-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "ebbce3d3839e9e3a12beca05364a1174b856ef2d1924bbc2919906dc8280fd0ce47ad721552179cbdad52a01a20cac4578af44854c9913649ad6c526021d03da",
          "sha256": "04944541b163de5c3c2ac2fed0852613cfb7b69eb9ac03632251515989d5d920",
          "sha1": "82c7e419204078010291a89591cc51f9712d06c1",
          "md5": "d2da02c7e9741f9d22510350a5731448"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.13.1-SNAPSHOT.jar",
          "url": "auth-common-1.13.1-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "ebbce3d3839e9e3a12beca05364a1174b856ef2d1924bbc2919906dc8280fd0ce47ad721552179cbdad52a01a20cac4578af44854c9913649ad6c526021d03da",
          "sha256": "04944541b163de5c3c2ac2fed0852613cfb7b69eb9ac03632251515989d5d920",
          "sha1": "82c7e419204078010291a89591cc51f9712d06c1",
          "md5": "d2da02c7e9741f9d22510350a5731448"
        }
      ]
    }
  ]
}
