{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-fhir-sdk-java",
    "module": "fhir-java",
    "version": "1.7.0-bump-danger-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fhir-java-1.7.0-bump-danger-SNAPSHOT.jar",
          "url": "fhir-java-1.7.0-bump-danger-SNAPSHOT.jar",
          "size": 1012051,
          "sha512": "732241cc2b577d8a9f024c56b296045521d67226a45e73fbcdb859ed2f8ef75982006e2dc7e2dfb00782ceb7177e380c9de76c24ca924b3015bc81079c9574be",
          "sha256": "9834ddac9662770a909af4cdea98f025a8b99f825cd0281a172fe94fc6353ce4",
          "sha1": "8f3155b691ded41a98f6bc07b33ca559e112d770",
          "md5": "5bb0f76b2ae747182211afd1a7eb8ed6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-java-1.7.0-bump-danger-SNAPSHOT.jar",
          "url": "fhir-java-1.7.0-bump-danger-SNAPSHOT.jar",
          "size": 1012051,
          "sha512": "732241cc2b577d8a9f024c56b296045521d67226a45e73fbcdb859ed2f8ef75982006e2dc7e2dfb00782ceb7177e380c9de76c24ca924b3015bc81079c9574be",
          "sha256": "9834ddac9662770a909af4cdea98f025a8b99f825cd0281a172fe94fc6353ce4",
          "sha1": "8f3155b691ded41a98f6bc07b33ca559e112d770",
          "md5": "5bb0f76b2ae747182211afd1a7eb8ed6"
        }
      ]
    }
  ]
}
