{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.12.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "sd5ljhqyjvhzhpwbh2nuxip3hu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.12.0-SNAPSHOT.jar",
          "url": "auth-common-1.12.0-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "877a9a1b27149a5c747e15f0c80b89443425c06290351ca6de54f8dd72d24fffb254b4bb0980ceb1a16623a9c5f6d4427038a5409e048c5d587fc9c4a8b03d19",
          "sha256": "6480414dbb03bd04ff98328d861e3c34ba3f70d5b526c222f1b6adfd2877ffb6",
          "sha1": "a83dc6675038c19ea00ad27b3847035a163c4bd4",
          "md5": "1a1106d3fe7e9392d483ca159a5e3da0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.12.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.12.0-SNAPSHOT.jar",
          "url": "auth-common-1.12.0-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "877a9a1b27149a5c747e15f0c80b89443425c06290351ca6de54f8dd72d24fffb254b4bb0980ceb1a16623a9c5f6d4427038a5409e048c5d587fc9c4a8b03d19",
          "sha256": "6480414dbb03bd04ff98328d861e3c34ba3f70d5b526c222f1b6adfd2877ffb6",
          "sha1": "a83dc6675038c19ea00ad27b3847035a163c4bd4",
          "md5": "1a1106d3fe7e9392d483ca159a5e3da0"
        }
      ]
    }
  ]
}
