{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.13.1-change-attachment-service-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "zaek2pfilvcjla4x434qhxwmei"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.13.1-change-attachment-service-SNAPSHOT.jar",
          "url": "auth-common-1.13.1-change-attachment-service-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "d584d853b159d4ffaabe614cc4bc3a2089c37766ecb3f31c7b5d2c5f53f3f3e2d6eba46661a7c5e53642131a2ccb12494090a5f2377f1b3a63940667ba6b3491",
          "sha256": "bffaee1264659375ffb4bf120ff155043e32729ca13b0f48a3964cc7c800d4be",
          "sha1": "81c04c7ca066aefec0f54cc428414b60c2e2ed54",
          "md5": "ae1959d0c9d068f14d064f0c7d27dae4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.13.1-change-attachment-service-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.13.1-change-attachment-service-SNAPSHOT.jar",
          "url": "auth-common-1.13.1-change-attachment-service-SNAPSHOT.jar",
          "size": 3578,
          "sha512": "d584d853b159d4ffaabe614cc4bc3a2089c37766ecb3f31c7b5d2c5f53f3f3e2d6eba46661a7c5e53642131a2ccb12494090a5f2377f1b3a63940667ba6b3491",
          "sha256": "bffaee1264659375ffb4bf120ff155043e32729ca13b0f48a3964cc7c800d4be",
          "sha1": "81c04c7ca066aefec0f54cc428414b60c2e2ed54",
          "md5": "ae1959d0c9d068f14d064f0c7d27dae4"
        }
      ]
    }
  ]
}
