{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.7.0-add-ios-base64-SNAPSHOT/util-1.7.0-add-ios-base64-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.7.0-add-ios-base64-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "4m6ymnyyvrcwpnt6poerhadmiq"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "util.klib",
          "url": "util-iosx64-1.7.0-add-ios-base64-SNAPSHOT.klib",
          "size": 22698,
          "sha512": "1fbd7a2ee85e3307e2ca74ca8c5e88dc5986d56ae37d5de176e4d1bad4c9a5cf2d9b0ad51c8170f25d30745a9ffe667dc5f662e040f32951315b704d48e381be",
          "sha256": "e4d04c25b92591055d6a9151de4d5229643fd4294fd5dfc681527890c26eb726",
          "sha1": "c4b8a239161a57f3298412b245045b10d8308c05",
          "md5": "4f287f0f6c03f452faed1c1f8427e2a7"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-metadata/1.7.0-add-ios-base64-SNAPSHOT/util-metadata-1.7.0-add-ios-base64-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-metadata",
        "version": "1.7.0-add-ios-base64-SNAPSHOT"
      }
    }
  ]
}
