{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.10.0-add-proguard-annotation-SNAPSHOT/util-1.10.0-add-proguard-annotation-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.10.0-add-proguard-annotation-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "d6e3j5zvtzbqvkipz7z247api4"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "util.klib",
          "url": "util-iosarm64-1.10.0-add-proguard-annotation-SNAPSHOT.klib",
          "size": 24490,
          "sha512": "4221a0652743aeae39885d320914ea0839685612b67e919b8304402835133c5659bd43b656ec270fc307449714f259c0a3d2fbae49b21893f234d73cca66999d",
          "sha256": "f6de8341f24728370333ccabc53f0c180aa0814624cde77bba96f49916fee717",
          "sha1": "f806edd1e03c49cd71c13ba1142d285c8f3e8dbe",
          "md5": "12180b5826e9948c05689685c7c37ff3"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "util-iosarm64-1.10.0-add-proguard-annotation-SNAPSHOT-metadata.jar",
          "url": "util-iosarm64-1.10.0-add-proguard-annotation-SNAPSHOT-metadata.jar",
          "size": 6092,
          "sha512": "4c6c9577ed35049e94d13b52a8c513df8bf051e4213e57a147d73a167551ab74b88175eb7203cf88564079a69563050b35ec6122b19bc5edc23842af60b79746",
          "sha256": "cc78c3980504960c47eb539cdf5f6fb57ed58c27552977068d698bf2c78ed09b",
          "sha1": "bba2d87792df25d151a929a6138bb28c63e63d1f",
          "md5": "75708b423e5a31c5e8c8f8d2aa338bc2"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util/1.10.0-add-proguard-annotation-SNAPSHOT/util-1.10.0-add-proguard-annotation-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util",
        "version": "1.10.0-add-proguard-annotation-SNAPSHOT"
      }
    },
    {
      "name": "commonMainMetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util/1.10.0-add-proguard-annotation-SNAPSHOT/util-1.10.0-add-proguard-annotation-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util",
        "version": "1.10.0-add-proguard-annotation-SNAPSHOT"
      }
    }
  ]
}
