{
  "formatVersion": "1.1",
  "component": {
    "url": "../../example-kmp-library/0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT/example-kmp-library-0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT.module",
    "group": "care.data4life.hc-gradle-scripts",
    "module": "example-kmp-library",
    "version": "0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "myzzcbkzmjfvhnpmfbt4zanugm"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "example-kmp-library-jvm-0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT.jar",
          "url": "example-kmp-library-jvm-0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT.jar",
          "size": 16692,
          "sha512": "adc39f1ff70b441b79984c8f9b809bf17a7f1afbe4a26434d6704f76e5aa8f0d8828822d70ec1e66c90a200cd5730aa060ca8bb7f84fd99d746e552b99c78c2f",
          "sha256": "3e8656edcd74ac5d91422bccb0fb5ff6330a79a9e9b7bf58f49102a0f8a69d31",
          "sha1": "84f1d8598322eacc4679430bbea29e6b9580146a",
          "md5": "ae13b80c085ff0b99f1148e312d42579"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "example-kmp-library-jvm-0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT.jar",
          "url": "example-kmp-library-jvm-0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT.jar",
          "size": 16692,
          "sha512": "adc39f1ff70b441b79984c8f9b809bf17a7f1afbe4a26434d6704f76e5aa8f0d8828822d70ec1e66c90a200cd5730aa060ca8bb7f84fd99d746e552b99c78c2f",
          "sha256": "3e8656edcd74ac5d91422bccb0fb5ff6330a79a9e9b7bf58f49102a0f8a69d31",
          "sha1": "84f1d8598322eacc4679430bbea29e6b9580146a",
          "md5": "ae13b80c085ff0b99f1148e312d42579"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../example-kmp-library-metadata/0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT/example-kmp-library-metadata-0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT.module",
        "group": "care.data4life.hc-gradle-scripts",
        "module": "example-kmp-library-metadata",
        "version": "0.0.1-change-project-setup-to-latest-iteration-SNAPSHOT"
      }
    }
  ]
}
