{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk/0.1.3-add-time-bluring-research-subject-SNAPSHOT/data-donation-sdk-0.1.3-add-time-bluring-research-subject-SNAPSHOT.module",
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk",
    "version": "0.1.3-add-time-bluring-research-subject-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "uny4urmm6rghhjyrpqngqcowau"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.6"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.1.6-a1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "1.1.6"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-kmp",
          "module": "fhir",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "care.data4life.hc-result-sdk-kmp",
          "module": "flow",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "care.data4life.hc-result-sdk-kmp",
          "module": "error",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "care.data4life.hc-coroutine-util-sdk-kmp",
          "module": "coroutine-util",
          "version": {
            "requires": "0.1.0"
          },
          "excludes": [
            {
              "group": "co.touchlab:stately-concurrency",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.4.3-native-mt",
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-ios",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "care.data4life.hc-objc-util-sdk-kmp",
          "module": "objc-util",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "data-donation-sdk.klib",
          "url": "data-donation-sdk-iosarm64-0.1.3-add-time-bluring-research-subject-SNAPSHOT.klib",
          "size": 162408,
          "sha512": "55384cf4ad9bb98feb2a7d2dc24d8ed66bcb546aba456763dab6f03f4bc84f0b4b779e1f916d66f7fb2db852d4208596c6edb99c55f532d827582d4e9c91c4bf",
          "sha256": "5fd4a15efe395a0cc5cfddf1c4c3f130ba6ea03377395b0c15daad00195dac64",
          "sha1": "df4f64d4d1cb32e47cc3f406d01e363582914ff7",
          "md5": "f8d77b1c59e603c4f731c4953f092562"
        },
        {
          "name": "data-donation-sdk-cinterop-DataDonationCryptoObjC.klib",
          "url": "data-donation-sdk-iosarm64-0.1.3-add-time-bluring-research-subject-SNAPSHOT-cinterop-DataDonationCryptoObjC.klib",
          "size": 12562,
          "sha512": "062eff186973bddaa1aa1c5d33a42c3f6b1296a67a5647a0ef24a1216729033c1d72e5bfe5e51d95a799b6f641e0fdc1d73cc9b8546b9cae031e0878c589c5c8",
          "sha256": "a9782707479e027b2aa07daf2ad58175c3e0d0568c0fdf08bc13dedad6a29bda",
          "sha1": "02e61391329277f3de4c4da06cf3f71be89cea8e",
          "md5": "6210a86c9c2875a47a302186f85c1b8e"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../data-donation-sdk-metadata/0.1.3-add-time-bluring-research-subject-SNAPSHOT/data-donation-sdk-metadata-0.1.3-add-time-bluring-research-subject-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-metadata",
        "version": "0.1.3-add-time-bluring-research-subject-SNAPSHOT"
      }
    }
  ]
}
