{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.12.0-change-fileservice-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "y5kcuo7t35f3njk4jjinivy77m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.12.0-change-fileservice-tests-SNAPSHOT.jar",
          "url": "securestore-common-1.12.0-change-fileservice-tests-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "4fd87aa7a6e8624f7115a71f2559c22bdec695675f0650f694d4b656af32d9f42b22acc3633269722ee9e4279111b2e8a0bd4708d6834c18b2e130d46aa7bebf",
          "sha256": "b1e2b9ea1f349f95fd09d9b5a17566dd774f836fc58623b334acfd7cd08d42ea",
          "sha1": "061f9eddc8074e974bac8da54f4da26b6cc477ff",
          "md5": "d80ffe0829562bc7e92d9f06f0099483"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.12.0-change-fileservice-tests-SNAPSHOT.jar",
          "url": "securestore-common-1.12.0-change-fileservice-tests-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "4fd87aa7a6e8624f7115a71f2559c22bdec695675f0650f694d4b656af32d9f42b22acc3633269722ee9e4279111b2e8a0bd4708d6834c18b2e130d46aa7bebf",
          "sha256": "b1e2b9ea1f349f95fd09d9b5a17566dd774f836fc58623b334acfd7cd08d42ea",
          "sha1": "061f9eddc8074e974bac8da54f4da26b6cc477ff",
          "md5": "d80ffe0829562bc7e92d9f06f0099483"
        }
      ]
    }
  ]
}
