{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.12.0-change-fileservice-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "va4mzevd7zggnhjb73nob3zgnu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.12.0-change-fileservice-tests-SNAPSHOT.jar",
          "url": "securestore-common-1.12.0-change-fileservice-tests-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "9fa10fc76ef233ca8885a1db141b8752ac0787bd3f67f97278daffe00a256cb6f4bed4906f95fb32b62ea82afc4891de0c0319ff02109900a490fe75ff52c4a1",
          "sha256": "221c4d8a291ab1bb7d188ee87b5debdc7b2c83ebcd533e5b80dcbc1cbd53663a",
          "sha1": "470de207325e285ef5a264910fb94a3384332734",
          "md5": "870422b7c38399fa8c7ae4d886518047"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.12.0-change-fileservice-tests-SNAPSHOT.jar",
          "url": "securestore-common-1.12.0-change-fileservice-tests-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "9fa10fc76ef233ca8885a1db141b8752ac0787bd3f67f97278daffe00a256cb6f4bed4906f95fb32b62ea82afc4891de0c0319ff02109900a490fe75ff52c4a1",
          "sha256": "221c4d8a291ab1bb7d188ee87b5debdc7b2c83ebcd533e5b80dcbc1cbd53663a",
          "sha1": "470de207325e285ef5a264910fb94a3384332734",
          "md5": "870422b7c38399fa8c7ae4d886518047"
        }
      ]
    }
  ]
}
