{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.13.2-add-coverage-aggregation-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "gg6bdfi34nhqnjhmywyajp6ha4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.13.2-add-coverage-aggregation-SNAPSHOT.jar",
          "url": "crypto-common-1.13.2-add-coverage-aggregation-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "faa9a0dc4a86318e795a6e142e663cf872bca23bd913c094ac4459c0b07e205485af2146d993f7777c9f2fc0fabdc2ad50eec16ee6f83359ad7b75ca2fa6df0a",
          "sha256": "82546e9f02e45b3d293608d4f0b58a01493d753ea320609f88c557fa2d325d2a",
          "sha1": "67b960be7cb451d090ce782e2e2ea85bc9fa4566",
          "md5": "e08b6a71c7d455f388984a2601165a57"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.13.2-add-coverage-aggregation-SNAPSHOT.jar",
          "url": "crypto-common-1.13.2-add-coverage-aggregation-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "faa9a0dc4a86318e795a6e142e663cf872bca23bd913c094ac4459c0b07e205485af2146d993f7777c9f2fc0fabdc2ad50eec16ee6f83359ad7b75ca2fa6df0a",
          "sha256": "82546e9f02e45b3d293608d4f0b58a01493d753ea320609f88c557fa2d325d2a",
          "sha1": "67b960be7cb451d090ce782e2e2ea85bc9fa4566",
          "md5": "e08b6a71c7d455f388984a2601165a57"
        }
      ]
    }
  ]
}
