{
  "formatVersion": "1.1",
  "component": {
    "url": "../../objc-util/0.1.0-bump-kotlin-SNAPSHOT/objc-util-0.1.0-bump-kotlin-SNAPSHOT.module",
    "group": "care.data4life.hc-objc-util-sdk-kmp",
    "module": "objc-util",
    "version": "0.1.0-bump-kotlin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "objc-util.klib",
          "url": "objc-util-iosarm64-0.1.0-bump-kotlin-SNAPSHOT.klib",
          "size": 8900,
          "sha512": "a378cc690f4a70147cc2fba88d320ae78ddef5a52fc052df495ec2e4e4a4af7dc5248a1da44abfd501841864055003addf0ccaede62ac84131638b462fb94c81",
          "sha256": "632d6a5b32ac7072e3768c3694f4c36cad46bed506a02c2a0652c77cd2a62637",
          "sha1": "57ad6b32232eff5e9d970ce592cb41c91e314d23",
          "md5": "6e049c86649ee63b9999f919da94af76"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "objc-util-iosarm64-0.1.0-bump-kotlin-SNAPSHOT-metadata.jar",
          "url": "objc-util-iosarm64-0.1.0-bump-kotlin-SNAPSHOT-metadata.jar",
          "size": 5763,
          "sha512": "72b66d3cf9efdf1c33d9a2a1198e1217a629e482a0673898bf47c10c0256b75c55d8128283b54fc204fc1533d3257da05c47f8f3c1a66a152f661e025c0e3390",
          "sha256": "abc217f035619e81b8e2e2c5684c65a45528cc5e3111bb050ab16aac2ffb95b7",
          "sha1": "c6711ca8acbecf3dc51c9e20f608a89f638525f5",
          "md5": "3c59ea47e58757c15b9ed91348819944"
        }
      ]
    }
  ]
}
