{
  "formatVersion": "1.1",
  "component": {
    "url": "../../objc-util/0.1.0-bump-kotlin-SNAPSHOT/objc-util-0.1.0-bump-kotlin-SNAPSHOT.module",
    "group": "care.data4life.hc-objc-util-sdk-kmp",
    "module": "objc-util",
    "version": "0.1.0-bump-kotlin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "t3wjjjek35flrkl2vkgzp4m2tm"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "objc-util.klib",
          "url": "objc-util-iosarm64-0.1.0-bump-kotlin-SNAPSHOT.klib",
          "size": 8731,
          "sha512": "f7c220a771e3310538a0e6267ab05e463a1f45e255ff473c5b014d429cb096f43d6124e8e49b436ff073328e6238686c24976477d4963ad67ac15478814d791f",
          "sha256": "c54811b7d274bcf90c50d0802453455523f24d347b27e36a6def8018d9a15b07",
          "sha1": "3a16aa867e28688e6169531d43c4b605516b58ee",
          "md5": "56e146ea2933e093ab93d9fdd14d65ce"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "objc-util-iosarm64-0.1.0-bump-kotlin-SNAPSHOT-metadata.jar",
          "url": "objc-util-iosarm64-0.1.0-bump-kotlin-SNAPSHOT-metadata.jar",
          "size": 5812,
          "sha512": "b3e96fc7abd98029a406f166b03ea18b38f26d54d92b2174bacf554e686f3923416a7175d36a9544761a32ff77f121697ec7f43c47a7e9b7270dbf0f3ca75b51",
          "sha256": "6e233aed132a3b4f5806739d1acd2b26b4be1e2f5b152b7ddb190c2bfd8f011c",
          "sha1": "72fe346a222ca4cda0165cb95fcb4a50464aa7e3",
          "md5": "5d16d1e83fb95601102eb46f0f6ba7f1"
        }
      ]
    }
  ]
}
