{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util/0.1.0-bump-robolectric-SNAPSHOT/test-util-0.1.0-bump-robolectric-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util",
    "version": "0.1.0-bump-robolectric-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "zwzryyjrszf5vhynbmmehnrtpe"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-util-jvm-0.1.0-bump-robolectric-SNAPSHOT.jar",
          "url": "test-util-jvm-0.1.0-bump-robolectric-SNAPSHOT.jar",
          "size": 11761,
          "sha512": "432fbcd4c319cbc9ecc14df64b33d57afd783cb772b6b7ca87af1d80f3a94ab80cd18154d44a72362b666bb8c2f930683434ba7c5e35b4faed02dd085bf66e35",
          "sha256": "4c48d56659de4d44e3c926c21ca29f95d71c1a79ff35a6aa5438dfa32a8a038a",
          "sha1": "f604e25dd4a7c9297d7b989682769d0518a4e5e2",
          "md5": "be31721c169557916d1abd407c36df88"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-jvm-0.1.0-bump-robolectric-SNAPSHOT.jar",
          "url": "test-util-jvm-0.1.0-bump-robolectric-SNAPSHOT.jar",
          "size": 11761,
          "sha512": "432fbcd4c319cbc9ecc14df64b33d57afd783cb772b6b7ca87af1d80f3a94ab80cd18154d44a72362b666bb8c2f930683434ba7c5e35b4faed02dd085bf66e35",
          "sha256": "4c48d56659de4d44e3c926c21ca29f95d71c1a79ff35a6aa5438dfa32a8a038a",
          "sha1": "f604e25dd4a7c9297d7b989682769d0518a4e5e2",
          "md5": "be31721c169557916d1abd407c36df88"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../test-util-metadata/0.1.0-bump-robolectric-SNAPSHOT/test-util-metadata-0.1.0-bump-robolectric-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-metadata",
        "version": "0.1.0-bump-robolectric-SNAPSHOT"
      }
    }
  ]
}
