{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-coroutine/0.3.0-bump-desugar-SNAPSHOT/test-util-coroutine-0.3.0-bump-desugar-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-coroutine",
    "version": "0.3.0-bump-desugar-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.1-native-mt",
            "requires": "1.5.1-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-coroutine.klib",
          "url": "test-util-coroutine-iosarm64-0.3.0-bump-desugar-SNAPSHOT.klib",
          "size": 7850,
          "sha512": "549f8c880c9463e90f607b569ee8e8dbfdc1ce433b866fcc8a0925b0b7b5ca94f8297a61641e5fb213ed8fe0afbb6a6a03153bd3e616555025215dabb716648f",
          "sha256": "230250861427fa6950eb115b04e02bd331a5410d3a8aa5909548652b2e4dc7db",
          "sha1": "8b7b3f3c7c7d03130e7ff074a27cf80974d05ac3",
          "md5": "d4297d9e0d2905ffa7acfe73bd64b1d7"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.1-native-mt",
            "requires": "1.5.1-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-coroutine-iosarm64-0.3.0-bump-desugar-SNAPSHOT-metadata.jar",
          "url": "test-util-coroutine-iosarm64-0.3.0-bump-desugar-SNAPSHOT-metadata.jar",
          "size": 6284,
          "sha512": "df27db3dead303b3f9ab7d5cecedf1d92a821ddc0770384a37288c694f1c37cd3d926774ed31843bf5e2ae398b7df39aef889a715d5ee0a98d57a25f1002ee96",
          "sha256": "dcbcc59c573e0b7d7c436b6d280f77a753f4c38f10a8108f3864cbf23d0d2dc6",
          "sha1": "63b4063ffc4f8292e70c41672ece30d77cb3d2a7",
          "md5": "6286614fb6192da2e51126b6d5318bff"
        }
      ]
    }
  ]
}
