{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-ktor/0.1.0-add-robolectric-common-SNAPSHOT/test-util-ktor-0.1.0-add-robolectric-common-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-ktor",
    "version": "0.1.0-add-robolectric-common-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "xng2ulgvgnf63azrlwhohh4lzi"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-util-ktor-jvm-0.1.0-add-robolectric-common-SNAPSHOT.jar",
          "url": "test-util-ktor-jvm-0.1.0-add-robolectric-common-SNAPSHOT.jar",
          "size": 28646,
          "sha512": "8ee8275f669089084a0cb30ac7be9d8bddf516e2da141dd3e1b5f6bd9cd4fabf9807d88a31836a98032d5533a65f100da73bfaf212f601fb5deb46bf18afd3cc",
          "sha256": "8a7797056ce9776185f511c012b127a81f7b895ecac999bca29fa47979f201ef",
          "sha1": "4359903c674da1fd67413b00ef2a90a636b6095c",
          "md5": "c39fad5e52c68a127930658d4598f5cd"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor-jvm-0.1.0-add-robolectric-common-SNAPSHOT.jar",
          "url": "test-util-ktor-jvm-0.1.0-add-robolectric-common-SNAPSHOT.jar",
          "size": 28646,
          "sha512": "8ee8275f669089084a0cb30ac7be9d8bddf516e2da141dd3e1b5f6bd9cd4fabf9807d88a31836a98032d5533a65f100da73bfaf212f601fb5deb46bf18afd3cc",
          "sha256": "8a7797056ce9776185f511c012b127a81f7b895ecac999bca29fa47979f201ef",
          "sha1": "4359903c674da1fd67413b00ef2a90a636b6095c",
          "md5": "c39fad5e52c68a127930658d4598f5cd"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../test-util-ktor-metadata/0.1.0-add-robolectric-common-SNAPSHOT/test-util-ktor-metadata-0.1.0-add-robolectric-common-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-ktor-metadata",
        "version": "0.1.0-add-robolectric-common-SNAPSHOT"
      }
    }
  ]
}
