{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.0.4-add-flow-SNAPSHOT/data-donation-sdk-iosx64-0.0.4-add-flow-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.0.4-add-flow-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "3timc6nnebcytnxrp2zehbvipe"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.4-add-flow-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.0.4-add-flow-SNAPSHOT.jar",
          "size": 50020,
          "sha512": "1512097d6779c90fcf8b6d489be2ee0caf6e667eff2af6addd0f6b8f9c2993dab2d872d1f18b4ae1859e0afa314fc9b558f6c89e2a801ed281e2f99f2664bf2c",
          "sha256": "a5be1c8d880077c6ee9a6662d521568ba862ee7c9df8532346f081a42ff62870",
          "sha1": "48acdaa07bc6be35e2a9676fb439119b39d71b4e",
          "md5": "d70808a1da05d43bda94edfb6aed4873"
        }
      ]
    }
  ]
}
