{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk",
    "version": "0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "dmq5ma3psncuhmk7443ptu67pe"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT.jar",
          "url": "data-donation-sdk-0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT.jar",
          "size": 40175,
          "sha512": "aa7d3dfd13e30282d0bbdc781d456ee7d49a6d771e76a602bf85a16d172738f9deeb32e4a50aab72fa4472db2f008d8b5e14271a043c688f9db65a4ebdc3fcb7",
          "sha256": "d7a7452ae1aa6ad65d51f9ce1912943e6cf8ecfb9324cfb9e72222c5b2ece2de",
          "sha1": "c1d8d23a145d43ed186a31a811ea19451d26be3a",
          "md5": "e53e461f7aaa5f118b082db826ec3367"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android-debug/0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT/data-donation-sdk-android-debug-0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android-debug",
        "version": "0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android-debug/0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT/data-donation-sdk-android-debug-0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android-debug",
        "version": "0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android/0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT/data-donation-sdk-android-0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android",
        "version": "0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android/0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT/data-donation-sdk-android-0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android",
        "version": "0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../data-donation-sdk-iosarm64/0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT/data-donation-sdk-iosarm64-0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-iosarm64",
        "version": "0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../data-donation-sdk-iosx64/0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT/data-donation-sdk-iosx64-0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-iosx64",
        "version": "0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT"
      }
    }
  ]
}
