{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk",
    "version": "0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "2g6mhnbva5dj7ontvcncyf2vsu"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT.jar",
          "url": "data-donation-sdk-0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT.jar",
          "size": 40175,
          "sha512": "0b139b96092ca1f27cb710d14679b77f99128568273af9788dbe0efddaf8d86ac33a8136e991e4d8b57813c33579811994e0fd60eead99812206610d7cbb9808",
          "sha256": "a8d3e6021f1e532eff1af657cb2b83ce6e13462e6de6377ca9f7bbf8dcfe18c9",
          "sha1": "8e85402b487ebbb940194f2caaf8ae0d31de3ac8",
          "md5": "7f4eb18a5d13989ea6a52e81713b73d0"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android-debug/0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT/data-donation-sdk-android-debug-0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android-debug",
        "version": "0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android-debug/0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT/data-donation-sdk-android-debug-0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android-debug",
        "version": "0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android/0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT/data-donation-sdk-android-0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android",
        "version": "0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../data-donation-sdk-android/0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT/data-donation-sdk-android-0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-android",
        "version": "0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../data-donation-sdk-iosarm64/0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT/data-donation-sdk-iosarm64-0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-iosarm64",
        "version": "0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../data-donation-sdk-iosx64/0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT/data-donation-sdk-iosx64-0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-iosx64",
        "version": "0.1.0-fix-ci-branch-trigger-from-0.1-SNAPSHOT"
      }
    }
  ]
}
