{
  "formatVersion": "1.1",
  "component": {
    "url": "../../error/1.11.0-remove-test-utils-SNAPSHOT/error-1.11.0-remove-test-utils-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "error",
    "version": "1.11.0-remove-test-utils-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "error.klib",
          "url": "error-iosx64-1.11.0-remove-test-utils-SNAPSHOT.klib",
          "size": 7084,
          "sha512": "08a3df0a32bd3750cae0c2faf444a6242522c5c2a79314304ced4895b2924a5800930caa12628542d66d27d02842ff13d02943b3cae8412afce3b52f547dd57b",
          "sha256": "e1b9021eea4f9658e0881ba9775e6783a99eb7d0edae177c5a94c35492a33656",
          "sha1": "1dd27f6eec5ff37b2c463f05e739add985153bff",
          "md5": "288c19a6148f5b0dfcc7c09598346aef"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "error-iosx64-1.11.0-remove-test-utils-SNAPSHOT-metadata.jar",
          "url": "error-iosx64-1.11.0-remove-test-utils-SNAPSHOT-metadata.jar",
          "size": 5010,
          "sha512": "486886fa49d23864612914732c2923a5680b4de7ec33cc05e6a90dbe66c154f08496ccddded71130fb6e5b2ef317305f2e2c75c1c30fd487bfcbccfb2dcd6a1e",
          "sha256": "33d40f707b5fd1c5f278272c44a41d15fe3cf08b67b1e974d7fe707ed800ce0b",
          "sha1": "53289d23fc1dce5dbd5daa66693a470f4b6c4ecf",
          "md5": "eb15acba2ce17186790fd14eaa87b2d7"
        }
      ]
    }
  ]
}
