{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-core",
    "version": "1.11.0-change-client-version-header-dynamic-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ltm5y33dkbba5jvupfrdkbs24y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.11.0-change-client-version-header-dynamic-SNAPSHOT.jar",
          "url": "sdk-core-1.11.0-change-client-version-header-dynamic-SNAPSHOT.jar",
          "size": 540413,
          "sha512": "4754613dc06132b84fb7ca007048aa8275c9e20d35e1a17f79cc1683bf61891bf867633dc73390c9d9a6dd9091f757eb151f8e6ffda4bf1f9172bff56c32717f",
          "sha256": "cf30c4ba81b54502100401a1e2e17fbdcedfe4cc6bf03929578cf9dfd36ac0d3",
          "sha1": "ffc89633367f4f40a47bc7ed58a61264133e0065",
          "md5": "23eae30306f01b2155f7296d0f1d6b9e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.11.0-change-client-version-header-dynamic-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.11.0-change-client-version-header-dynamic-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.11.0-change-client-version-header-dynamic-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.11.0-change-client-version-header-dynamic-SNAPSHOT.jar",
          "url": "sdk-core-1.11.0-change-client-version-header-dynamic-SNAPSHOT.jar",
          "size": 540413,
          "sha512": "4754613dc06132b84fb7ca007048aa8275c9e20d35e1a17f79cc1683bf61891bf867633dc73390c9d9a6dd9091f757eb151f8e6ffda4bf1f9172bff56c32717f",
          "sha256": "cf30c4ba81b54502100401a1e2e17fbdcedfe4cc6bf03929578cf9dfd36ac0d3",
          "sha1": "ffc89633367f4f40a47bc7ed58a61264133e0065",
          "md5": "23eae30306f01b2155f7296d0f1d6b9e"
        }
      ]
    }
  ]
}
