{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-core",
    "version": "1.12.0-change-resource-crypto-service-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "mgpqk7z7tfagfajl6gojuhg4oa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.12.0-change-resource-crypto-service-SNAPSHOT.jar",
          "url": "sdk-core-1.12.0-change-resource-crypto-service-SNAPSHOT.jar",
          "size": 568569,
          "sha512": "85b5593ca9a14dd4cf649e53abd83aaef09b8d41988a24f11200adfdedf2d0bce8c7c54b1fc3eb6c8269102e0b9edf207e2c162970dbf603306aec9832f675b9",
          "sha256": "3b4d56fcd1bfb2d2789bbf60a37f8c825a0af8ecd5715315bf833ab336948b16",
          "sha1": "4db26f4e203cc0ddf83c87aa2483527cc95afeaf",
          "md5": "55f0eb9883c25f38f2aa8b41ff992169"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.12.0-change-resource-crypto-service-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.12.0-change-resource-crypto-service-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.12.0-change-resource-crypto-service-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.12.0-change-resource-crypto-service-SNAPSHOT.jar",
          "url": "sdk-core-1.12.0-change-resource-crypto-service-SNAPSHOT.jar",
          "size": 568569,
          "sha512": "85b5593ca9a14dd4cf649e53abd83aaef09b8d41988a24f11200adfdedf2d0bce8c7c54b1fc3eb6c8269102e0b9edf207e2c162970dbf603306aec9832f675b9",
          "sha256": "3b4d56fcd1bfb2d2789bbf60a37f8c825a0af8ecd5715315bf833ab336948b16",
          "sha1": "4db26f4e203cc0ddf83c87aa2483527cc95afeaf",
          "md5": "55f0eb9883c25f38f2aa8b41ff992169"
        }
      ]
    }
  ]
}
