{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-ktor/0.3.0-bump-desugar-SNAPSHOT/test-util-ktor-0.3.0-bump-desugar-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-ktor",
    "version": "0.3.0-bump-desugar-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor.klib",
          "url": "test-util-ktor-iosx64-0.3.0-bump-desugar-SNAPSHOT.klib",
          "size": 15005,
          "sha512": "4b5cfe5d52c304e429c0af886859d33d13ab5a8b50bfa5921c2e9d92a3b353612cfa2d411606c949f7e82fa3eb1bea05d720b1179cb296ca3615b3ff1062ca66",
          "sha256": "507585872a0c1411c255a7c77a9dc38ac1625144f52a284e87511baa71faecfd",
          "sha1": "e4dcd4d54d7ef9dd4717f8b88dc20c18cc65c321",
          "md5": "b345758e1955e374cb891010e338cff0"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor-iosx64-0.3.0-bump-desugar-SNAPSHOT-metadata.jar",
          "url": "test-util-ktor-iosx64-0.3.0-bump-desugar-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "226358ca6f309c2c4377eb5f1fde58e3c3ff17c7c07b5d97aa3c86cb1410c21e4efa488a07dda904895224b017be98a508b3f0ab88ace782e8678c4fb135e88e",
          "sha256": "ce80d14b75edaddd9fee20a7ca2804252a9c066b7e945ad7877096cbda4b63bd",
          "sha1": "94908842c1b781a677603fc13304b0d0fdfe5408",
          "md5": "d2bcc6f2235edc1bd053026ee192596d"
        }
      ]
    }
  ]
}
