{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-ktor/0.3.0-bump-desugar-SNAPSHOT/test-util-ktor-0.3.0-bump-desugar-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-ktor",
    "version": "0.3.0-bump-desugar-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor.klib",
          "url": "test-util-ktor-iosx64-0.3.0-bump-desugar-SNAPSHOT.klib",
          "size": 15005,
          "sha512": "4b5cfe5d52c304e429c0af886859d33d13ab5a8b50bfa5921c2e9d92a3b353612cfa2d411606c949f7e82fa3eb1bea05d720b1179cb296ca3615b3ff1062ca66",
          "sha256": "507585872a0c1411c255a7c77a9dc38ac1625144f52a284e87511baa71faecfd",
          "sha1": "e4dcd4d54d7ef9dd4717f8b88dc20c18cc65c321",
          "md5": "b345758e1955e374cb891010e338cff0"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-ktor-iosx64-0.3.0-bump-desugar-SNAPSHOT-metadata.jar",
          "url": "test-util-ktor-iosx64-0.3.0-bump-desugar-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "72d6856ad754827291ba084d37d0254439bd8256413ce4ff37bfde7896c97a918e828c9468d851ae102666bb2995c5de96df598b158f425931795d6b842259f3",
          "sha256": "be3f03a4d52c096b4f5b582cca4664d03ef8404c9423d836786cc7f0a7a45707",
          "sha1": "49e698911dc0594e21bdc83960d4085fa8d16540",
          "md5": "131fddec6d12ba3e3a27eb8e83f2524f"
        }
      ]
    }
  ]
}
