{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk/0.1.3-add-crypto-service-android-SNAPSHOT/data-donation-sdk-0.1.3-add-crypto-service-android-SNAPSHOT.module",
    "group": "care.data4life.hc-data-donation-sdk-kmp",
    "module": "data-donation-sdk",
    "version": "0.1.3-add-crypto-service-android-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "lgtzb6m2czgdjiet2jphymlffm"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.6"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.1.6-a1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "1.1.6"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "care.data4life.datadonation",
          "module": "data-donation-crypto",
          "version": {
            "requires": "0.1.3-add-crypto-service-android-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-kmp",
          "module": "fhir",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "care.data4life.hc-result-sdk-kmp",
          "module": "flow",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "care.data4life.hc-result-sdk-kmp",
          "module": "error",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "care.data4life.hc-coroutine-util-sdk-kmp",
          "module": "coroutine-util",
          "version": {
            "requires": "0.1.0"
          },
          "excludes": [
            {
              "group": "co.touchlab:stately-concurrency",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.4.3-native-mt",
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-ios",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "care.data4life.hc-objc-util-sdk-kmp",
          "module": "objc-util",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "data-donation-sdk.klib",
          "url": "data-donation-sdk-iosarm64-0.1.3-add-crypto-service-android-SNAPSHOT.klib",
          "size": 186024,
          "sha512": "f26aeeb35656cdf207edd97f8988c475616b12674ba3c89cab7f542f1793a6da416503864f1b8e356bdbb37ba20a1f3bca4fbf4340552ef632e35fbcc6c110bd",
          "sha256": "e6b386693339fe75fc9cbc23721291be2d23afb2a0ca140a4a16d0eac2981e0b",
          "sha1": "57afa7843d95f95c6fb0ea6e0ed268d9135f37d7",
          "md5": "860883747e9908deccfaa836283f4b07"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../data-donation-sdk-metadata/0.1.3-add-crypto-service-android-SNAPSHOT/data-donation-sdk-metadata-0.1.3-add-crypto-service-android-SNAPSHOT.module",
        "group": "care.data4life.hc-data-donation-sdk-kmp",
        "module": "data-donation-sdk-metadata",
        "version": "0.1.3-add-crypto-service-android-SNAPSHOT"
      }
    }
  ]
}
