{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.7.0-bump-updates-SNAPSHOT/util-1.7.0-bump-updates-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.7.0-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "v4eln3vqjng4fpqcwqnjvqwjlm"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-jvm-1.7.0-bump-updates-SNAPSHOT.jar",
          "url": "util-jvm-1.7.0-bump-updates-SNAPSHOT.jar",
          "size": 20085,
          "sha512": "943917294dcc3e0f7a200728d97ee68c0c0f0d61b392c439d476c85818f451f2542a2dadf2924a2380b98a03464613e28940caa3c03ee4cdae645a4ce25c8463",
          "sha256": "2b9516032218ddae08501feccfc826f1da4940cda77b0e765b8b4a82247f5adb",
          "sha1": "cc12cdd8f5af878e258b3b029944ea3363ab24d7",
          "md5": "62ba56b6b8a901c1abca8c45499d5088"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "util-jvm-1.7.0-bump-updates-SNAPSHOT.jar",
          "url": "util-jvm-1.7.0-bump-updates-SNAPSHOT.jar",
          "size": 20085,
          "sha512": "943917294dcc3e0f7a200728d97ee68c0c0f0d61b392c439d476c85818f451f2542a2dadf2924a2380b98a03464613e28940caa3c03ee4cdae645a4ce25c8463",
          "sha256": "2b9516032218ddae08501feccfc826f1da4940cda77b0e765b8b4a82247f5adb",
          "sha1": "cc12cdd8f5af878e258b3b029944ea3363ab24d7",
          "md5": "62ba56b6b8a901c1abca8c45499d5088"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-metadata/1.7.0-bump-updates-SNAPSHOT/util-metadata-1.7.0-bump-updates-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-metadata",
        "version": "1.7.0-bump-updates-SNAPSHOT"
      }
    }
  ]
}
