{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.0.3-change-fetch-consent-documents-SNAPSHOT/data-donation-sdk-iosx64-0.0.3-change-fetch-consent-documents-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.0.3-change-fetch-consent-documents-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "mhdxusnqbzgiloe7nb2dbcdzpm"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.3-change-fetch-consent-documents-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.0.3-change-fetch-consent-documents-SNAPSHOT.jar",
          "size": 66249,
          "sha512": "f35413ac25599e96994bec5603ad642cb9bee27234c92d834c473b9a4bf2984d21f23c25f32d7fcdde3f4f8bf954160e63ead3ad32a02d7dc376cab5637e6764",
          "sha256": "1f55afc9207e4c0cc1bef066552f5dcf6867218f6307820f821166f93eb4b4ec",
          "sha1": "19c5a49bda372b8b65e8b282aacf6c16a0fbd19b",
          "md5": "a5d137373932bd87c9a6edd93c78d749"
        }
      ]
    }
  ]
}
