{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.13.1-change-attachment-service-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "d3won7mtbbgopomqomu27sdq6q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.13.1-change-attachment-service-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.13.1-change-attachment-service-tests-SNAPSHOT.jar",
          "url": "crypto-jvm-1.13.1-change-attachment-service-tests-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "33e15e108daab1bf7df60b04960ba0668995b24e02b3fd867138826abb2d1072025155434190a5ac3562e4207f0e51e357a496ccf96687fd69776ebd26051220",
          "sha256": "f0e2aabe519896b23cb9c224d10c58aac94d8f0479dcc44b2fd85a42e7333dbc",
          "sha1": "d0aba3e92103ba7715d19bbe65f800228e45e067",
          "md5": "3d0bff25e9fdd3024c0c6a2e622e82e4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.13.1-change-attachment-service-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.13.1-change-attachment-service-tests-SNAPSHOT.jar",
          "url": "crypto-jvm-1.13.1-change-attachment-service-tests-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "33e15e108daab1bf7df60b04960ba0668995b24e02b3fd867138826abb2d1072025155434190a5ac3562e4207f0e51e357a496ccf96687fd69776ebd26051220",
          "sha256": "f0e2aabe519896b23cb9c224d10c58aac94d8f0479dcc44b2fd85a42e7333dbc",
          "sha1": "d0aba3e92103ba7715d19bbe65f800228e45e067",
          "md5": "3d0bff25e9fdd3024c0c6a2e622e82e4"
        }
      ]
    }
  ]
}
