{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util-coroutine/0.4.1-change-docs-SNAPSHOT/test-util-coroutine-0.4.1-change-docs-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util-coroutine",
    "version": "0.4.1-change-docs-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.6.0-native-mt",
            "requires": "1.6.0-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-coroutine.klib",
          "url": "test-util-coroutine-iosarm64-0.4.1-change-docs-SNAPSHOT.klib",
          "size": 8272,
          "sha512": "4c3c4a90602d30707b1eb3165a58fdf92a0ec63bbcdcbda20826d498049ad65d1696b02722ea05ca9b73ac70fbbc275042669ccdcb9b650cc395bc4cfb289fb3",
          "sha256": "a2b518d7a6d40a40e6f1e86c9f094ede222be6f1b9d7d640988e0f471f0b1029",
          "sha1": "361236d351c6a2be889f858eafc5c692bfe5821d",
          "md5": "16df4621e58ddbf50aa30316055997b3"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.6.0-native-mt",
            "requires": "1.6.0-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-coroutine-iosarm64-0.4.1-change-docs-SNAPSHOT-metadata.jar",
          "url": "test-util-coroutine-iosarm64-0.4.1-change-docs-SNAPSHOT-metadata.jar",
          "size": 6287,
          "sha512": "dfd70e731d3c38dcb9d14cab2b1dc92c971b5969bbd5b10b84d9a6b720f96c15d814f470f383ce7f44674f0f4e5107ebf1ecabfb6446aaba4ac74d5c13811da3",
          "sha256": "c09d924a6748fa721b177da50f96397e269ac36b31a82025b521e921fcc90447",
          "sha1": "70da9a43f60d020f17d1eed6add424f1e87023fc",
          "md5": "01684565bb537dcc0f40af1ade0492ce"
        }
      ]
    }
  ]
}
