{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.11.0-change-client-version-header-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "jjloxvxefvfirnmz6dqhsjomta"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-change-client-version-header-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.11.0-change-client-version-header-SNAPSHOT.jar",
          "url": "securestore-jvm-1.11.0-change-client-version-header-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "6c3c74fa2d6e71a0f3ba04b3965236c8308fd07abeac5a4b404acfb51f6d5e4571afbbed273831884fc468a6a01b4449822206833db9632c8229460e4e07fbfc",
          "sha256": "3feae801b118b7e2ab139191d0645883a127f0cb8f550a39242cc6ed811d476c",
          "sha1": "cccd2f8bd34ebcacf9613c1756ec4016ba11bd06",
          "md5": "16061c2c8fee78afece1704261812a72"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-change-client-version-header-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.11.0-change-client-version-header-SNAPSHOT.jar",
          "url": "securestore-jvm-1.11.0-change-client-version-header-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "6c3c74fa2d6e71a0f3ba04b3965236c8308fd07abeac5a4b404acfb51f6d5e4571afbbed273831884fc468a6a01b4449822206833db9632c8229460e4e07fbfc",
          "sha256": "3feae801b118b7e2ab139191d0645883a127f0cb8f550a39242cc6ed811d476c",
          "sha1": "cccd2f8bd34ebcacf9613c1756ec4016ba11bd06",
          "md5": "16061c2c8fee78afece1704261812a72"
        }
      ]
    }
  ]
}
