{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk/0.0.4-add-repo-tests-SNAPSHOT/data-donation-sdk-0.0.4-add-repo-tests-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk",
    "version": "0.0.4-add-repo-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ah33rwa7gvfmxbyakv5o2bxkuq"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-kmp",
          "module": "fhir",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.7.0-add-coroutine-test-util-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.4.3-native-mt",
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-ios",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "data-donation-sdk.klib",
          "url": "data-donation-sdk-iosarm64-0.0.4-add-repo-tests-SNAPSHOT.klib",
          "size": 217165,
          "sha512": "86af4f0a12a965970b06b970a6b879ded7d407dafbde502b6ac0c1d86d69ebc375715f8f03ce903f5037a732d5fa8f2c042163e658f5fae45e513017e1e5b7df",
          "sha256": "5d4a9175920ef83dae6693780d1c0a27a2651c14fecc194223b36f6487ebe178",
          "sha1": "4bb553f4b4494ac8d464531d81be25117aa52749",
          "md5": "7689175fb205949c4e76082d4d4e1de7"
        },
        {
          "name": "data-donation-sdk-cinterop-iOSCryptoDD.klib",
          "url": "data-donation-sdk-iosarm64-0.0.4-add-repo-tests-SNAPSHOT-cinterop-iOSCryptoDD.klib",
          "size": 4269864,
          "sha512": "862b78669869e136187991cd89806e22d70271b695218e4afafc961668a04b352fd59bf0f2041d323d81a1e578e70460800c1fcd0c5b91975683c8e2eb96152e",
          "sha256": "e1e8361c4b3cfb0f3f773c2c63eec342d23b34e6d152dda30fd7896adc814b4a",
          "sha1": "94b0d1e8fbe5268a4daa7c7c2c506c00c6a127a8",
          "md5": "570a861fee91f0abb0347e82b5c2c2a8"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../data-donation-sdk-metadata/0.0.4-add-repo-tests-SNAPSHOT/data-donation-sdk-metadata-0.0.4-add-repo-tests-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-metadata",
        "version": "0.0.4-add-repo-tests-SNAPSHOT"
      }
    }
  ]
}
