{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.1.0-fix-ci-branch-trigger-SNAPSHOT/data-donation-sdk-iosx64-0.1.0-fix-ci-branch-trigger-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.1.0-fix-ci-branch-trigger-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "flaynguw35huxgeuuuvn5vrjhe"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.1.0-fix-ci-branch-trigger-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.1.0-fix-ci-branch-trigger-SNAPSHOT.jar",
          "size": 39250,
          "sha512": "a747f0c9f581e2c58b59770f1d4d3e81c8c258537f34664c7542bab9620e58f659aa49e7570515c62822edac1296eda92e83dd142152c95cff8649761731406e",
          "sha256": "bafc6de4dbb2f5e15dfc146cf282d9ec69fb4e65a3bd7ac8ea6a07a869d57593",
          "sha1": "aa9028ff75a376e62fc9eb479342d9b9cfc527ff",
          "md5": "e70da5d486b784f89e70685c0001fa7a"
        }
      ]
    }
  ]
}
