{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.9.0-add-default-scope-SNAPSHOT/util-1.9.0-add-default-scope-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.9.0-add-default-scope-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "xenom24cxna5hikpnifc4jf6lu"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "url": "util-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "size": 19627,
          "sha512": "53dbc0f9acff91326ed4e880aa6581ea745777153987d81fb6b7974208a3c81ed47c3ffac0dc26b9177c7c702688f8236c25f15269c887e00852902ee2a26268",
          "sha256": "52671ec0730922515ad34adbc232225a3999cc4135f9d6b338cec26762b1a3cc",
          "sha1": "2f0c262de5de0d05562e53e5b90a18e4d8990d95",
          "md5": "37bf7c4d1a0d99eb7eb4ec72cd095194"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "util-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "url": "util-jvm-1.9.0-add-default-scope-SNAPSHOT.jar",
          "size": 19627,
          "sha512": "53dbc0f9acff91326ed4e880aa6581ea745777153987d81fb6b7974208a3c81ed47c3ffac0dc26b9177c7c702688f8236c25f15269c887e00852902ee2a26268",
          "sha256": "52671ec0730922515ad34adbc232225a3999cc4135f9d6b338cec26762b1a3cc",
          "sha1": "2f0c262de5de0d05562e53e5b90a18e4d8990d95",
          "md5": "37bf7c4d1a0d99eb7eb4ec72cd095194"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-metadata/1.9.0-add-default-scope-SNAPSHOT/util-metadata-1.9.0-add-default-scope-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-metadata",
        "version": "1.9.0-add-default-scope-SNAPSHOT"
      }
    }
  ]
}
