{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk-iosx64/0.0.4-add-consent-serive-error-propagation-SNAPSHOT/data-donation-sdk-iosx64-0.0.4-add-consent-serive-error-propagation-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk-iosx64",
    "version": "0.0.4-add-consent-serive-error-propagation-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "altyzxrlrff23erdi2xt7g2rca"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "data-donation-sdk-metadata-0.0.4-add-consent-serive-error-propagation-SNAPSHOT.jar",
          "url": "data-donation-sdk-metadata-0.0.4-add-consent-serive-error-propagation-SNAPSHOT.jar",
          "size": 77247,
          "sha512": "e58c159d948f46395c8361dfa33bc0f33fb37eda57d732a23d610d91d049f4c365fc3d309a30e72cbddf39b4c7566c91e0fc1a00fd0e73db8a6d833e7a8f5149",
          "sha256": "d32e6338c056a0b20461277e5471bf81241b3e853ebf1a8c9ec887f2b1723e23",
          "sha1": "4947a30b7db6c9acc5f9861b1a546925d6583696",
          "md5": "1eb1a1aa6cb2f951861aa1e9b8df4dca"
        }
      ]
    }
  ]
}
