{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.11.0-bump-android-gradle-plugin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "qyna35etyjfxzck5l2ppswauw4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-bump-android-gradle-plugin-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.11.0-bump-android-gradle-plugin-SNAPSHOT.jar",
          "url": "securestore-jvm-1.11.0-bump-android-gradle-plugin-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "f2536edec0accd7fcdb4f5f29d7afeff8196a3cddc4208b4413f99564ee34db841d6507ed44789ddd6a2635bde4b4f5da23db39b6515ea243c637f336e456974",
          "sha256": "cc3156f46460bb7b079cefc401c043b1a08c04013e3161c5cd5f9265e9ef71b5",
          "sha1": "a6c561a22b43689931fb7bed964c9ddec7e53979",
          "md5": "bfbf5e66ced056bf3ec332e89de45d12"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-bump-android-gradle-plugin-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.11.0-bump-android-gradle-plugin-SNAPSHOT.jar",
          "url": "securestore-jvm-1.11.0-bump-android-gradle-plugin-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "f2536edec0accd7fcdb4f5f29d7afeff8196a3cddc4208b4413f99564ee34db841d6507ed44789ddd6a2635bde4b4f5da23db39b6515ea243c637f336e456974",
          "sha256": "cc3156f46460bb7b079cefc401c043b1a08c04013e3161c5cd5f9265e9ef71b5",
          "sha1": "a6c561a22b43689931fb7bed964c9ddec7e53979",
          "md5": "bfbf5e66ced056bf3ec332e89de45d12"
        }
      ]
    }
  ]
}
