{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk/0.1.0-add-swift-package-SNAPSHOT/data-donation-sdk-0.1.0-add-swift-package-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk",
    "version": "0.1.0-add-swift-package-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ylvltvsn7ncahm2cb2wkq4evb4"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.1.6-a1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-kmp",
          "module": "fhir",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-coroutine",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.4.3-native-mt",
            "requires": "1.4.3-native-mt"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-ios",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "data-donation-sdk.klib",
          "url": "data-donation-sdk-iosx64-0.1.0-add-swift-package-SNAPSHOT.klib",
          "size": 113760,
          "sha512": "f444767aa1912ed206f869815335884eb98ac2e305233f65d31ad5f8e71ba576b06188778e1515c6381bac8901be5645f5f1f593cabb8a54921ec05013b51529",
          "sha256": "fe2af2f43746db7856e5d570d7e6b1df2d264ba5ff531dd0d3e13e5aa24b24c2",
          "sha1": "527f7feb8cbb44ae4ac2cd5d97cc7065d26eb89d",
          "md5": "8348096c891a4475261c4fefbdeb34fe"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../data-donation-sdk-metadata/0.1.0-add-swift-package-SNAPSHOT/data-donation-sdk-metadata-0.1.0-add-swift-package-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-metadata",
        "version": "0.1.0-add-swift-package-SNAPSHOT"
      }
    }
  ]
}
