{
  "formatVersion": "1.1",
  "component": {
    "url": "../../example-kmp-library-jvm/0.0.1-add-android-example-app-SNAPSHOT/example-kmp-library-jvm-0.0.1-add-android-example-app-SNAPSHOT.module",
    "group": "care.data4life.hc-gradle-scripts",
    "module": "example-kmp-library-jvm",
    "version": "0.0.1-add-android-example-app-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "eqmjegv6h5byza6ybagpb4tvvu"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "example-kmp-library-metadata-0.0.1-add-android-example-app-SNAPSHOT.jar",
          "url": "example-kmp-library-metadata-0.0.1-add-android-example-app-SNAPSHOT.jar",
          "size": 6554,
          "sha512": "7b596d8bdf0801d9fd079f1c3399769ca4ac0cfe914bdcd621c0d0cb43d930620c8ad7f88b80156088e5a5bddb7573f8be1fb02d6337d5253be68cc45098cb79",
          "sha256": "7cae8146c8d757cac5609b732484f664bd9235e4e8b947691ddc3ed58f2c86ef",
          "sha1": "8f0c20b3994c55950904533576fa01ad34ceb26a",
          "md5": "b8f353ff37475c81c68a56b3fd9aa548"
        }
      ]
    }
  ]
}
