{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.12.0-add-count-for-arbitrary-data-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ror2q6jnh5abxhltj4f2tfwpdi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.12.0-add-count-for-arbitrary-data-SNAPSHOT.jar",
          "url": "crypto-common-1.12.0-add-count-for-arbitrary-data-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "4ce494860306725a96197e07e30f63efb040bc0a9ebbcba5613afb6e91b5789f90a2ffdb05d9bab26985ca8fc1d88fe536d85e785641377748ba377ff3e000fa",
          "sha256": "a303d7aad16b147f30382c2f7244daba22a29149e7bbaf8cb49d3c90ec09815a",
          "sha1": "0a4dd996a3be58e1a6cb71774c71b70039dd82e3",
          "md5": "ee2948da88b02c560346df3cfc015763"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.12.0-add-count-for-arbitrary-data-SNAPSHOT.jar",
          "url": "crypto-common-1.12.0-add-count-for-arbitrary-data-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "4ce494860306725a96197e07e30f63efb040bc0a9ebbcba5613afb6e91b5789f90a2ffdb05d9bab26985ca8fc1d88fe536d85e785641377748ba377ff3e000fa",
          "sha256": "a303d7aad16b147f30382c2f7244daba22a29149e7bbaf8cb49d3c90ec09815a",
          "sha1": "0a4dd996a3be58e1a6cb71774c71b70039dd82e3",
          "md5": "ee2948da88b02c560346df3cfc015763"
        }
      ]
    }
  ]
}
