{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-jvm",
    "version": "1.14.0-add-ios-legacy-encoding-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "m5km4hqtizetrcc3pe3mnrwswu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.14.0-add-ios-legacy-encoding-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util"
            },
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.14.0-add-ios-legacy-encoding-SNAPSHOT.jar",
          "url": "sdk-jvm-1.14.0-add-ios-legacy-encoding-SNAPSHOT.jar",
          "size": 11647,
          "sha512": "6e5eb84b60afec39234fde9e71806f30dee316e332ca432f006ac10a7aeb9d7ae604d9973e1e875bd488df3b7b8f5ac87f7e4ba09e06ef3228c41b768b6caaa6",
          "sha256": "c21e8e2d4b38cefda9f3d5d7695ff31353065a111c2f15910116c46cf04b44df",
          "sha1": "35f29bc63b4a1be5d8b218d8c9aab8da698be24a",
          "md5": "ada6a0b0d692da23a99b777df8d6ff1f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.14.0-add-ios-legacy-encoding-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.14.0-add-ios-legacy-encoding-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.14.0-add-ios-legacy-encoding-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.14.0-add-ios-legacy-encoding-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util"
            },
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.14.0-add-ios-legacy-encoding-SNAPSHOT.jar",
          "url": "sdk-jvm-1.14.0-add-ios-legacy-encoding-SNAPSHOT.jar",
          "size": 11647,
          "sha512": "6e5eb84b60afec39234fde9e71806f30dee316e332ca432f006ac10a7aeb9d7ae604d9973e1e875bd488df3b7b8f5ac87f7e4ba09e06ef3228c41b768b6caaa6",
          "sha256": "c21e8e2d4b38cefda9f3d5d7695ff31353065a111c2f15910116c46cf04b44df",
          "sha1": "35f29bc63b4a1be5d8b218d8c9aab8da698be24a",
          "md5": "ada6a0b0d692da23a99b777df8d6ff1f"
        }
      ]
    }
  ]
}
