{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-util/0.2.0-change-to-seflcontained-SNAPSHOT/test-util-0.2.0-change-to-seflcontained-SNAPSHOT.module",
    "group": "care.data4life.hc-test-util-sdk-kmp",
    "module": "test-util",
    "version": "0.2.0-change-to-seflcontained-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "256glaxuurcclofuqjzn2stkga"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-util-jvm-0.2.0-change-to-seflcontained-SNAPSHOT.jar",
          "url": "test-util-jvm-0.2.0-change-to-seflcontained-SNAPSHOT.jar",
          "size": 12808,
          "sha512": "30a18488c1da041273a33c2bd9cc8017c19d68b578ef9c80f84cb6a2e7a1e138c25db0ba3c081679fc4d022f506aad0ffc5e7a657fff9ff2575ff0ec7755c787",
          "sha256": "0076ec8f4e2260b55d29739479a169ba510d902f325c736e279f1b2353db3851",
          "sha1": "f0385cc6432e886093f589e9f45ba2e75ba2d159",
          "md5": "a92cf9c3b0a16b4250dd36badb0922b6"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "test-util-jvm-0.2.0-change-to-seflcontained-SNAPSHOT.jar",
          "url": "test-util-jvm-0.2.0-change-to-seflcontained-SNAPSHOT.jar",
          "size": 12808,
          "sha512": "30a18488c1da041273a33c2bd9cc8017c19d68b578ef9c80f84cb6a2e7a1e138c25db0ba3c081679fc4d022f506aad0ffc5e7a657fff9ff2575ff0ec7755c787",
          "sha256": "0076ec8f4e2260b55d29739479a169ba510d902f325c736e279f1b2353db3851",
          "sha1": "f0385cc6432e886093f589e9f45ba2e75ba2d159",
          "md5": "a92cf9c3b0a16b4250dd36badb0922b6"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../test-util-metadata/0.2.0-change-to-seflcontained-SNAPSHOT/test-util-metadata-0.2.0-change-to-seflcontained-SNAPSHOT.module",
        "group": "care.data4life.hc-test-util-sdk-kmp",
        "module": "test-util-metadata",
        "version": "0.2.0-change-to-seflcontained-SNAPSHOT"
      }
    }
  ]
}
